-- Generated by scripts/build-player-guide-seed.mts from reviewed Brazilian Portuguese team guides.
-- No notifications, fake player accounts, or edits to existing community content.
CREATE TABLE IF NOT EXISTS player_guides (
  locale text NOT NULL, key text NOT NULL, thread_id bigint NOT NULL UNIQUE REFERENCES threads(id),
  PRIMARY KEY (locale, key)
);

DO $guide$
DECLARE tid bigint; aid bigint;
BEGIN
 IF NOT EXISTS (SELECT 1 FROM player_guides WHERE locale = 'pt-BR' AND key = 'first-board') THEN
  SELECT id INTO STRICT aid FROM members WHERE email = 'releases@outbrick.site' AND role = 'team';
  INSERT INTO threads (category_id, author_id, title, slug, language, pinned, last_poster_id)
  VALUES ((SELECT id FROM categories WHERE slug = 'help'), aid, 'Primeiros passos: seu primeiro tabuleiro', 'player-guide-first-board-pt-BR', 'pt-BR', false, aid) RETURNING id INTO tid;
  INSERT INTO player_guides VALUES ('pt-BR', 'first-board', tid);
  INSERT INTO posts (thread_id, author_id, number, body_md, body_html) VALUES (tid, aid, 1, 'Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado

Um quebra-cabeça tranquilo de combinar três, com 2.000 fases, 167 vilarejos feitos de blocos e nove amigos em 3D. Troque blocos vizinhos, combine três ou mais e cumpra os objetivos de cada fase. Sem cronômetro; todas as fases funcionam offline.

1. Abra sua fase atual pela Jornada. Leia os objetivos e os movimentos restantes antes de escolher uma peça.
2. Toque em uma peça e depois em uma vizinha, ou deslize em direção a ela. Procure uma linha de pelo menos três peças ou uma combinação especial.
3. Espere a cascata terminar e confira os objetivos restantes. Uma troca que não forma combinação volta ao lugar e não gasta movimento.
4. Peça uma dica se precisar. Quando todos os objetivos forem cumpridos, o tabuleiro termina e os movimentos restantes aumentam sua pontuação.

Troque blocos vizinhos para formar uma linha de três ou mais. As cascatas contornam obstáculos e trazem novos blocos. Saídas coloridas, salas lacradas, portais e canais de tinta dão a cada fase seu próprio desafio.

Complete os objetivos mostrados na fase. Ela termina assim que forem cumpridos, e as jogadas restantes viram blasters de linha que aumentam sua pontuação. Fases Difíceis, Superdifíceis e Chefes variam o desafio ao longo da Jornada.

A fase mostra as jogadas restantes; não há relógio nem contagem regressiva. Ao atingir o limite, cinco jogadas extras custam 300 moedas, depois 500 e então 900 na mesma tentativa, ou podem ser obtidas com um vídeo com recompensa. Sair ou concluir a fase reinicia essa sequência de preços.

## Continue lendo

[Biblioteca de guias do OutBrick](/community/guide-placeholder/index)

- [Peças especiais, objetivos e estrelas](/community/guide-placeholder/specials-and-stars)
- [Como se orientar na Jornada](/community/guide-placeholder/journey)
- [Jogue com o VoiceOver](/community/guide-placeholder/voiceover)
- [Acessibilidade e ajustes confortáveis](/community/guide-placeholder/settings)
- [Vidas, movimentos, desfazer e vídeos opcionais](/community/guide-placeholder/lives-moves-undos)
- [Peça ajuda e relate uma barreira de acessibilidade](/community/guide-placeholder/asking-for-help)
- [Qual versão do jogo estou usando?](/community/guide-placeholder/versions)', '<p>Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado</p>
<p>Um quebra-cabeça tranquilo de combinar três, com 2.000 fases, 167 vilarejos feitos de blocos e nove amigos em 3D. Troque blocos vizinhos, combine três ou mais e cumpra os objetivos de cada fase. Sem cronômetro; todas as fases funcionam offline.</p>
<ol><li>Abra sua fase atual pela Jornada. Leia os objetivos e os movimentos restantes antes de escolher uma peça.</li><li>Toque em uma peça e depois em uma vizinha, ou deslize em direção a ela. Procure uma linha de pelo menos três peças ou uma combinação especial.</li><li>Espere a cascata terminar e confira os objetivos restantes. Uma troca que não forma combinação volta ao lugar e não gasta movimento.</li><li>Peça uma dica se precisar. Quando todos os objetivos forem cumpridos, o tabuleiro termina e os movimentos restantes aumentam sua pontuação.</li></ol>
<p>Troque blocos vizinhos para formar uma linha de três ou mais. As cascatas contornam obstáculos e trazem novos blocos. Saídas coloridas, salas lacradas, portais e canais de tinta dão a cada fase seu próprio desafio.</p>
<p>Complete os objetivos mostrados na fase. Ela termina assim que forem cumpridos, e as jogadas restantes viram blasters de linha que aumentam sua pontuação. Fases Difíceis, Superdifíceis e Chefes variam o desafio ao longo da Jornada.</p>
<p>A fase mostra as jogadas restantes; não há relógio nem contagem regressiva. Ao atingir o limite, cinco jogadas extras custam 300 moedas, depois 500 e então 900 na mesma tentativa, ou podem ser obtidas com um vídeo com recompensa. Sair ou concluir a fase reinicia essa sequência de preços.</p>
<h3>Continue lendo</h3>
<p><a href="/community/guide-placeholder/index" rel="ugc nofollow noopener">Biblioteca de guias do OutBrick</a></p>
<ul><li><a href="/community/guide-placeholder/specials-and-stars" rel="ugc nofollow noopener">Peças especiais, objetivos e estrelas</a></li><li><a href="/community/guide-placeholder/journey" rel="ugc nofollow noopener">Como se orientar na Jornada</a></li><li><a href="/community/guide-placeholder/voiceover" rel="ugc nofollow noopener">Jogue com o VoiceOver</a></li><li><a href="/community/guide-placeholder/settings" rel="ugc nofollow noopener">Acessibilidade e ajustes confortáveis</a></li><li><a href="/community/guide-placeholder/lives-moves-undos" rel="ugc nofollow noopener">Vidas, movimentos, desfazer e vídeos opcionais</a></li><li><a href="/community/guide-placeholder/asking-for-help" rel="ugc nofollow noopener">Peça ajuda e relate uma barreira de acessibilidade</a></li><li><a href="/community/guide-placeholder/versions" rel="ugc nofollow noopener">Qual versão do jogo estou usando?</a></li></ul>');
 END IF;
END $guide$;

DO $guide$
DECLARE tid bigint; aid bigint;
BEGIN
 IF NOT EXISTS (SELECT 1 FROM player_guides WHERE locale = 'pt-BR' AND key = 'specials-and-stars') THEN
  SELECT id INTO STRICT aid FROM members WHERE email = 'releases@outbrick.site' AND role = 'team';
  INSERT INTO threads (category_id, author_id, title, slug, language, pinned, last_poster_id)
  VALUES ((SELECT id FROM categories WHERE slug = 'help'), aid, 'Peças especiais, objetivos e estrelas', 'player-guide-specials-and-stars-pt-BR', 'pt-BR', false, aid) RETURNING id INTO tid;
  INSERT INTO player_guides VALUES ('pt-BR', 'specials-and-stars', tid);
  INSERT INTO posts (thread_id, author_id, number, body_md, body_html) VALUES (tid, aid, 1, 'Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado

Quatro blocos em linha criam um blaster de linha; um L ou T cria uma bomba; um quadrado cria um dardo teleguiado; cinco em linha criam uma bomba de cor. Toque em um especial ou combine dois para limpar uma área maior.

Complete os objetivos mostrados na fase. Ela termina assim que forem cumpridos, e as jogadas restantes viram blasters de linha que aumentam sua pontuação. Fases Difíceis, Superdifíceis e Chefes variam o desafio ao longo da Jornada.

O jogo atual para iOS concede estrelas de acordo com as faixas de pontuação da fase. Combinações, especiais, cascatas e jogadas restantes contribuem para a pontuação. A demonstração no navegador mantém a antiga regra de estrelas baseada no objetivo de jogadas.

## Continue lendo

[Biblioteca de guias do OutBrick](/community/guide-placeholder/index)

- [Primeiros passos: seu primeiro tabuleiro](/community/guide-placeholder/first-board)
- [Como se orientar na Jornada](/community/guide-placeholder/journey)
- [Jogue com o VoiceOver](/community/guide-placeholder/voiceover)
- [Acessibilidade e ajustes confortáveis](/community/guide-placeholder/settings)
- [Vidas, movimentos, desfazer e vídeos opcionais](/community/guide-placeholder/lives-moves-undos)
- [Peça ajuda e relate uma barreira de acessibilidade](/community/guide-placeholder/asking-for-help)
- [Qual versão do jogo estou usando?](/community/guide-placeholder/versions)', '<p>Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado</p>
<p>Quatro blocos em linha criam um blaster de linha; um L ou T cria uma bomba; um quadrado cria um dardo teleguiado; cinco em linha criam uma bomba de cor. Toque em um especial ou combine dois para limpar uma área maior.</p>
<p>Complete os objetivos mostrados na fase. Ela termina assim que forem cumpridos, e as jogadas restantes viram blasters de linha que aumentam sua pontuação. Fases Difíceis, Superdifíceis e Chefes variam o desafio ao longo da Jornada.</p>
<p>O jogo atual para iOS concede estrelas de acordo com as faixas de pontuação da fase. Combinações, especiais, cascatas e jogadas restantes contribuem para a pontuação. A demonstração no navegador mantém a antiga regra de estrelas baseada no objetivo de jogadas.</p>
<h3>Continue lendo</h3>
<p><a href="/community/guide-placeholder/index" rel="ugc nofollow noopener">Biblioteca de guias do OutBrick</a></p>
<ul><li><a href="/community/guide-placeholder/first-board" rel="ugc nofollow noopener">Primeiros passos: seu primeiro tabuleiro</a></li><li><a href="/community/guide-placeholder/journey" rel="ugc nofollow noopener">Como se orientar na Jornada</a></li><li><a href="/community/guide-placeholder/voiceover" rel="ugc nofollow noopener">Jogue com o VoiceOver</a></li><li><a href="/community/guide-placeholder/settings" rel="ugc nofollow noopener">Acessibilidade e ajustes confortáveis</a></li><li><a href="/community/guide-placeholder/lives-moves-undos" rel="ugc nofollow noopener">Vidas, movimentos, desfazer e vídeos opcionais</a></li><li><a href="/community/guide-placeholder/asking-for-help" rel="ugc nofollow noopener">Peça ajuda e relate uma barreira de acessibilidade</a></li><li><a href="/community/guide-placeholder/versions" rel="ugc nofollow noopener">Qual versão do jogo estou usando?</a></li></ul>');
 END IF;
END $guide$;

DO $guide$
DECLARE tid bigint; aid bigint;
BEGIN
 IF NOT EXISTS (SELECT 1 FROM player_guides WHERE locale = 'pt-BR' AND key = 'journey') THEN
  SELECT id INTO STRICT aid FROM members WHERE email = 'releases@outbrick.site' AND role = 'team';
  INSERT INTO threads (category_id, author_id, title, slug, language, pinned, last_poster_id)
  VALUES ((SELECT id FROM categories WHERE slug = 'help'), aid, 'Como se orientar na Jornada', 'player-guide-journey-pt-BR', 'pt-BR', false, aid) RETURNING id INTO tid;
  INSERT INTO player_guides VALUES ('pt-BR', 'journey', tid);
  INSERT INTO posts (thread_id, author_id, number, body_md, body_html) VALUES (tid, aid, 1, 'Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado

A Jornada tem 2.000 fases em 167 vilarejos. Um vilarejo completo tem doze tabuleiros; o último tem oito. O mapa é uma avenida móvel construída com blocos, formada por lugares diferentes e nove amigos. Encontre sua fase atual, abra-a, leia os objetivos e conclua-a para seguir. Tabuleiros já liberados permitem praticar e melhorar as estrelas. Vilarejo e capítulo são coisas diferentes: são doze tabuleiros por vilarejo e vinte por capítulo. Com VoiceOver, use a ação “Onde estou?” na Jornada para ouvir sua posição e o próximo objetivo, ou “Ir para minha próxima fase” para levar o foco até lá. Na Jornada, toque duas vezes com dois dedos para ouvir o guia; em um tabuleiro, o mesmo gesto pede uma dica.

A Siri responde sobre vidas, tempo de recuperação, o Bloco do Dia e as estrelas dos vilarejos. Widgets, Atividades ao Vivo, Spotlight, Atalhos e filtros de Foco conectam o jogo aos recursos da Apple; os recursos compatíveis do Apple Intelligence dependem do dispositivo e do sistema. O iCloud mantém seu progresso nos seus dispositivos.

## Continue lendo

[Biblioteca de guias do OutBrick](/community/guide-placeholder/index)

- [Primeiros passos: seu primeiro tabuleiro](/community/guide-placeholder/first-board)
- [Peças especiais, objetivos e estrelas](/community/guide-placeholder/specials-and-stars)
- [Jogue com o VoiceOver](/community/guide-placeholder/voiceover)
- [Acessibilidade e ajustes confortáveis](/community/guide-placeholder/settings)
- [Vidas, movimentos, desfazer e vídeos opcionais](/community/guide-placeholder/lives-moves-undos)
- [Peça ajuda e relate uma barreira de acessibilidade](/community/guide-placeholder/asking-for-help)
- [Qual versão do jogo estou usando?](/community/guide-placeholder/versions)', '<p>Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado</p>
<p>A Jornada tem 2.000 fases em 167 vilarejos. Um vilarejo completo tem doze tabuleiros; o último tem oito. O mapa é uma avenida móvel construída com blocos, formada por lugares diferentes e nove amigos. Encontre sua fase atual, abra-a, leia os objetivos e conclua-a para seguir. Tabuleiros já liberados permitem praticar e melhorar as estrelas. Vilarejo e capítulo são coisas diferentes: são doze tabuleiros por vilarejo e vinte por capítulo. Com VoiceOver, use a ação “Onde estou?” na Jornada para ouvir sua posição e o próximo objetivo, ou “Ir para minha próxima fase” para levar o foco até lá. Na Jornada, toque duas vezes com dois dedos para ouvir o guia; em um tabuleiro, o mesmo gesto pede uma dica.</p>
<p>A Siri responde sobre vidas, tempo de recuperação, o Bloco do Dia e as estrelas dos vilarejos. Widgets, Atividades ao Vivo, Spotlight, Atalhos e filtros de Foco conectam o jogo aos recursos da Apple; os recursos compatíveis do Apple Intelligence dependem do dispositivo e do sistema. O iCloud mantém seu progresso nos seus dispositivos.</p>
<h3>Continue lendo</h3>
<p><a href="/community/guide-placeholder/index" rel="ugc nofollow noopener">Biblioteca de guias do OutBrick</a></p>
<ul><li><a href="/community/guide-placeholder/first-board" rel="ugc nofollow noopener">Primeiros passos: seu primeiro tabuleiro</a></li><li><a href="/community/guide-placeholder/specials-and-stars" rel="ugc nofollow noopener">Peças especiais, objetivos e estrelas</a></li><li><a href="/community/guide-placeholder/voiceover" rel="ugc nofollow noopener">Jogue com o VoiceOver</a></li><li><a href="/community/guide-placeholder/settings" rel="ugc nofollow noopener">Acessibilidade e ajustes confortáveis</a></li><li><a href="/community/guide-placeholder/lives-moves-undos" rel="ugc nofollow noopener">Vidas, movimentos, desfazer e vídeos opcionais</a></li><li><a href="/community/guide-placeholder/asking-for-help" rel="ugc nofollow noopener">Peça ajuda e relate uma barreira de acessibilidade</a></li><li><a href="/community/guide-placeholder/versions" rel="ugc nofollow noopener">Qual versão do jogo estou usando?</a></li></ul>');
 END IF;
END $guide$;

DO $guide$
DECLARE tid bigint; aid bigint;
BEGIN
 IF NOT EXISTS (SELECT 1 FROM player_guides WHERE locale = 'pt-BR' AND key = 'voiceover') THEN
  SELECT id INTO STRICT aid FROM members WHERE email = 'releases@outbrick.site' AND role = 'team';
  INSERT INTO threads (category_id, author_id, title, slug, language, pinned, last_poster_id)
  VALUES ((SELECT id FROM categories WHERE slug = 'accessibility'), aid, 'Jogue com o VoiceOver', 'player-guide-voiceover-pt-BR', 'pt-BR', false, aid) RETURNING id INTO tid;
  INSERT INTO player_guides VALUES ('pt-BR', 'voiceover', tid);
  INSERT INTO posts (thread_id, author_id, number, body_md, body_html) VALUES (tid, aid, 1, 'Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado

1. Ative o VoiceOver nos ajustes de Acessibilidade do iPhone e abra o jogo. Explore o tabuleiro pelo toque ou deslizando entre os elementos.
2. Ouça o tipo, a cor e o estado da peça. Use as ações disponíveis para escolher a direção da troca ou ativar uma peça especial.
3. Ouça o resultado antes de fazer outro movimento. Experimente os rotores de Especiais, Objetivos, Bloqueios e Portões.
4. Um toque duplo com dois dedos no tabuleiro pede uma dica. O gesto de esfregar com dois dedos abre a pausa sem abandonar sua tentativa; fora do tabuleiro, ele fecha a tela atual.
5. Se quiser outra pista sonora, experimente a ação opcional de som da fileira. Ajuste o nível de detalhes dos anúncios se a fala ficar carregada. Se algo não estiver claro, informe a fase e o anúncio exato em Acessibilidade.

O VoiceOver anuncia o resultado de cada jogada imediatamente e mantém o foco no bloco movido. As dicas indicam o bloco e o sentido da troca. Um toque duplo com dois dedos pede uma dica; o gesto de esfregar com dois dedos fecha a tela. Os rotores encontram especiais, objetivos, obstáculos e saídas; sons opcionais por linha ajudam a identificar as cores.

Abra Ajustes e toque na aba Acessibilidade. Experimente uma opção de cada vez em um tabuleiro conhecido: símbolos para daltonismo, alto contraste, velocidade das animações, nível de detalhes das falas, bandeja para canhotos e confirmação de trocas ao manter pressionado. Os símbolos oferecem pistas além da cor. Ajuste a velocidade e os detalhes para acompanhar melhor as mudanças. A confirmação ao manter pressionado dá tempo para conferir a direção antes de trocar. Os ajustes do jogo também controlam música, efeitos sonoros e háptica. Os personagens continuam com animações e balões de texto, sem vozes; os anúncios do VoiceOver permanecem. VoiceOver e Reduzir Movimento do iPhone são ajustes separados.

## Continue lendo

[Biblioteca de guias do OutBrick](/community/guide-placeholder/index)

- [Primeiros passos: seu primeiro tabuleiro](/community/guide-placeholder/first-board)
- [Peças especiais, objetivos e estrelas](/community/guide-placeholder/specials-and-stars)
- [Como se orientar na Jornada](/community/guide-placeholder/journey)
- [Acessibilidade e ajustes confortáveis](/community/guide-placeholder/settings)
- [Vidas, movimentos, desfazer e vídeos opcionais](/community/guide-placeholder/lives-moves-undos)
- [Peça ajuda e relate uma barreira de acessibilidade](/community/guide-placeholder/asking-for-help)
- [Qual versão do jogo estou usando?](/community/guide-placeholder/versions)', '<p>Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado</p>
<ol><li>Ative o VoiceOver nos ajustes de Acessibilidade do iPhone e abra o jogo. Explore o tabuleiro pelo toque ou deslizando entre os elementos.</li><li>Ouça o tipo, a cor e o estado da peça. Use as ações disponíveis para escolher a direção da troca ou ativar uma peça especial.</li><li>Ouça o resultado antes de fazer outro movimento. Experimente os rotores de Especiais, Objetivos, Bloqueios e Portões.</li><li>Um toque duplo com dois dedos no tabuleiro pede uma dica. O gesto de esfregar com dois dedos abre a pausa sem abandonar sua tentativa; fora do tabuleiro, ele fecha a tela atual.</li><li>Se quiser outra pista sonora, experimente a ação opcional de som da fileira. Ajuste o nível de detalhes dos anúncios se a fala ficar carregada. Se algo não estiver claro, informe a fase e o anúncio exato em Acessibilidade.</li></ol>
<p>O VoiceOver anuncia o resultado de cada jogada imediatamente e mantém o foco no bloco movido. As dicas indicam o bloco e o sentido da troca. Um toque duplo com dois dedos pede uma dica; o gesto de esfregar com dois dedos fecha a tela. Os rotores encontram especiais, objetivos, obstáculos e saídas; sons opcionais por linha ajudam a identificar as cores.</p>
<p>Abra Ajustes e toque na aba Acessibilidade. Experimente uma opção de cada vez em um tabuleiro conhecido: símbolos para daltonismo, alto contraste, velocidade das animações, nível de detalhes das falas, bandeja para canhotos e confirmação de trocas ao manter pressionado. Os símbolos oferecem pistas além da cor. Ajuste a velocidade e os detalhes para acompanhar melhor as mudanças. A confirmação ao manter pressionado dá tempo para conferir a direção antes de trocar. Os ajustes do jogo também controlam música, efeitos sonoros e háptica. Os personagens continuam com animações e balões de texto, sem vozes; os anúncios do VoiceOver permanecem. VoiceOver e Reduzir Movimento do iPhone são ajustes separados.</p>
<h3>Continue lendo</h3>
<p><a href="/community/guide-placeholder/index" rel="ugc nofollow noopener">Biblioteca de guias do OutBrick</a></p>
<ul><li><a href="/community/guide-placeholder/first-board" rel="ugc nofollow noopener">Primeiros passos: seu primeiro tabuleiro</a></li><li><a href="/community/guide-placeholder/specials-and-stars" rel="ugc nofollow noopener">Peças especiais, objetivos e estrelas</a></li><li><a href="/community/guide-placeholder/journey" rel="ugc nofollow noopener">Como se orientar na Jornada</a></li><li><a href="/community/guide-placeholder/settings" rel="ugc nofollow noopener">Acessibilidade e ajustes confortáveis</a></li><li><a href="/community/guide-placeholder/lives-moves-undos" rel="ugc nofollow noopener">Vidas, movimentos, desfazer e vídeos opcionais</a></li><li><a href="/community/guide-placeholder/asking-for-help" rel="ugc nofollow noopener">Peça ajuda e relate uma barreira de acessibilidade</a></li><li><a href="/community/guide-placeholder/versions" rel="ugc nofollow noopener">Qual versão do jogo estou usando?</a></li></ul>');
 END IF;
END $guide$;

DO $guide$
DECLARE tid bigint; aid bigint;
BEGIN
 IF NOT EXISTS (SELECT 1 FROM player_guides WHERE locale = 'pt-BR' AND key = 'settings') THEN
  SELECT id INTO STRICT aid FROM members WHERE email = 'releases@outbrick.site' AND role = 'team';
  INSERT INTO threads (category_id, author_id, title, slug, language, pinned, last_poster_id)
  VALUES ((SELECT id FROM categories WHERE slug = 'accessibility'), aid, 'Acessibilidade e ajustes confortáveis', 'player-guide-settings-pt-BR', 'pt-BR', false, aid) RETURNING id INTO tid;
  INSERT INTO player_guides VALUES ('pt-BR', 'settings', tid);
  INSERT INTO posts (thread_id, author_id, number, body_md, body_html) VALUES (tid, aid, 1, 'Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado

Abra Ajustes e toque na aba Acessibilidade. Experimente uma opção de cada vez em um tabuleiro conhecido: símbolos para daltonismo, alto contraste, velocidade das animações, nível de detalhes das falas, bandeja para canhotos e confirmação de trocas ao manter pressionado. Os símbolos oferecem pistas além da cor. Ajuste a velocidade e os detalhes para acompanhar melhor as mudanças. A confirmação ao manter pressionado dá tempo para conferir a direção antes de trocar. Os ajustes do jogo também controlam música, efeitos sonoros e háptica. Os personagens continuam com animações e balões de texto, sem vozes; os anúncios do VoiceOver permanecem. VoiceOver e Reduzir Movimento do iPhone são ajustes separados.

O VoiceOver anuncia o resultado de cada jogada imediatamente e mantém o foco no bloco movido. As dicas indicam o bloco e o sentido da troca. Um toque duplo com dois dedos pede uma dica; o gesto de esfregar com dois dedos fecha a tela. Os rotores encontram especiais, objetivos, obstáculos e saídas; sons opcionais por linha ajudam a identificar as cores.

## Continue lendo

[Biblioteca de guias do OutBrick](/community/guide-placeholder/index)

- [Primeiros passos: seu primeiro tabuleiro](/community/guide-placeholder/first-board)
- [Peças especiais, objetivos e estrelas](/community/guide-placeholder/specials-and-stars)
- [Como se orientar na Jornada](/community/guide-placeholder/journey)
- [Jogue com o VoiceOver](/community/guide-placeholder/voiceover)
- [Vidas, movimentos, desfazer e vídeos opcionais](/community/guide-placeholder/lives-moves-undos)
- [Peça ajuda e relate uma barreira de acessibilidade](/community/guide-placeholder/asking-for-help)
- [Qual versão do jogo estou usando?](/community/guide-placeholder/versions)', '<p>Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado</p>
<p>Abra Ajustes e toque na aba Acessibilidade. Experimente uma opção de cada vez em um tabuleiro conhecido: símbolos para daltonismo, alto contraste, velocidade das animações, nível de detalhes das falas, bandeja para canhotos e confirmação de trocas ao manter pressionado. Os símbolos oferecem pistas além da cor. Ajuste a velocidade e os detalhes para acompanhar melhor as mudanças. A confirmação ao manter pressionado dá tempo para conferir a direção antes de trocar. Os ajustes do jogo também controlam música, efeitos sonoros e háptica. Os personagens continuam com animações e balões de texto, sem vozes; os anúncios do VoiceOver permanecem. VoiceOver e Reduzir Movimento do iPhone são ajustes separados.</p>
<p>O VoiceOver anuncia o resultado de cada jogada imediatamente e mantém o foco no bloco movido. As dicas indicam o bloco e o sentido da troca. Um toque duplo com dois dedos pede uma dica; o gesto de esfregar com dois dedos fecha a tela. Os rotores encontram especiais, objetivos, obstáculos e saídas; sons opcionais por linha ajudam a identificar as cores.</p>
<h3>Continue lendo</h3>
<p><a href="/community/guide-placeholder/index" rel="ugc nofollow noopener">Biblioteca de guias do OutBrick</a></p>
<ul><li><a href="/community/guide-placeholder/first-board" rel="ugc nofollow noopener">Primeiros passos: seu primeiro tabuleiro</a></li><li><a href="/community/guide-placeholder/specials-and-stars" rel="ugc nofollow noopener">Peças especiais, objetivos e estrelas</a></li><li><a href="/community/guide-placeholder/journey" rel="ugc nofollow noopener">Como se orientar na Jornada</a></li><li><a href="/community/guide-placeholder/voiceover" rel="ugc nofollow noopener">Jogue com o VoiceOver</a></li><li><a href="/community/guide-placeholder/lives-moves-undos" rel="ugc nofollow noopener">Vidas, movimentos, desfazer e vídeos opcionais</a></li><li><a href="/community/guide-placeholder/asking-for-help" rel="ugc nofollow noopener">Peça ajuda e relate uma barreira de acessibilidade</a></li><li><a href="/community/guide-placeholder/versions" rel="ugc nofollow noopener">Qual versão do jogo estou usando?</a></li></ul>');
 END IF;
END $guide$;

DO $guide$
DECLARE tid bigint; aid bigint;
BEGIN
 IF NOT EXISTS (SELECT 1 FROM player_guides WHERE locale = 'pt-BR' AND key = 'lives-moves-undos') THEN
  SELECT id INTO STRICT aid FROM members WHERE email = 'releases@outbrick.site' AND role = 'team';
  INSERT INTO threads (category_id, author_id, title, slug, language, pinned, last_poster_id)
  VALUES ((SELECT id FROM categories WHERE slug = 'help'), aid, 'Vidas, movimentos, desfazer e vídeos opcionais', 'player-guide-lives-moves-undos-pt-BR', 'pt-BR', false, aid) RETURNING id INTO tid;
  INSERT INTO player_guides VALUES ('pt-BR', 'lives-moves-undos', tid);
  INSERT INTO posts (thread_id, author_id, number, body_md, body_html) VALUES (tid, aid, 1, 'Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado

Abrir uma fase exige uma vida, mas não consome nenhuma. Concluir também não consome. Uma vida é usada quando você recusa continuar sem jogadas, sai depois de fazer uma jogada ou reinicia depois de jogar. São cinco vidas, oito com o Brick Pass; uma se recupera a cada trinta minutos.

A fase mostra as jogadas restantes; não há relógio nem contagem regressiva. Ao atingir o limite, cinco jogadas extras custam 300 moedas, depois 500 e então 900 na mesma tentativa, ou podem ser obtidas com um vídeo com recompensa. Sair ou concluir a fase reinicia essa sequência de preços.

A primeira ação de desfazer de cada tabuleiro é grátis. As seguintes usam um tanque com cinco, que recupera uma ação a cada vinte e cinco minutos; um vídeo com recompensa concede duas. Confira a quantidade exibida antes de desfazer novamente. A ação ilimitada de desfazer existe somente na demonstração clássica de blocos no navegador.

Limites diários: 8 vídeos para vidas, 8 para desfazer, 6 para jogadas extras, 4 para a dica gratuita ao ficar sem jogadas, 4 para dobrar as moedas da vitória, 1 para a Brick Wheel, 2 para o balão-surpresa e 6 para o Brick Cinema. Sem banners nem anúncios intersticiais. O vídeo só começa se você escolher; recusar não custa nada.

## Continue lendo

[Biblioteca de guias do OutBrick](/community/guide-placeholder/index)

- [Primeiros passos: seu primeiro tabuleiro](/community/guide-placeholder/first-board)
- [Peças especiais, objetivos e estrelas](/community/guide-placeholder/specials-and-stars)
- [Como se orientar na Jornada](/community/guide-placeholder/journey)
- [Jogue com o VoiceOver](/community/guide-placeholder/voiceover)
- [Acessibilidade e ajustes confortáveis](/community/guide-placeholder/settings)
- [Peça ajuda e relate uma barreira de acessibilidade](/community/guide-placeholder/asking-for-help)
- [Qual versão do jogo estou usando?](/community/guide-placeholder/versions)', '<p>Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado</p>
<p>Abrir uma fase exige uma vida, mas não consome nenhuma. Concluir também não consome. Uma vida é usada quando você recusa continuar sem jogadas, sai depois de fazer uma jogada ou reinicia depois de jogar. São cinco vidas, oito com o Brick Pass; uma se recupera a cada trinta minutos.</p>
<p>A fase mostra as jogadas restantes; não há relógio nem contagem regressiva. Ao atingir o limite, cinco jogadas extras custam 300 moedas, depois 500 e então 900 na mesma tentativa, ou podem ser obtidas com um vídeo com recompensa. Sair ou concluir a fase reinicia essa sequência de preços.</p>
<p>A primeira ação de desfazer de cada tabuleiro é grátis. As seguintes usam um tanque com cinco, que recupera uma ação a cada vinte e cinco minutos; um vídeo com recompensa concede duas. Confira a quantidade exibida antes de desfazer novamente. A ação ilimitada de desfazer existe somente na demonstração clássica de blocos no navegador.</p>
<p>Limites diários: 8 vídeos para vidas, 8 para desfazer, 6 para jogadas extras, 4 para a dica gratuita ao ficar sem jogadas, 4 para dobrar as moedas da vitória, 1 para a Brick Wheel, 2 para o balão-surpresa e 6 para o Brick Cinema. Sem banners nem anúncios intersticiais. O vídeo só começa se você escolher; recusar não custa nada.</p>
<h3>Continue lendo</h3>
<p><a href="/community/guide-placeholder/index" rel="ugc nofollow noopener">Biblioteca de guias do OutBrick</a></p>
<ul><li><a href="/community/guide-placeholder/first-board" rel="ugc nofollow noopener">Primeiros passos: seu primeiro tabuleiro</a></li><li><a href="/community/guide-placeholder/specials-and-stars" rel="ugc nofollow noopener">Peças especiais, objetivos e estrelas</a></li><li><a href="/community/guide-placeholder/journey" rel="ugc nofollow noopener">Como se orientar na Jornada</a></li><li><a href="/community/guide-placeholder/voiceover" rel="ugc nofollow noopener">Jogue com o VoiceOver</a></li><li><a href="/community/guide-placeholder/settings" rel="ugc nofollow noopener">Acessibilidade e ajustes confortáveis</a></li><li><a href="/community/guide-placeholder/asking-for-help" rel="ugc nofollow noopener">Peça ajuda e relate uma barreira de acessibilidade</a></li><li><a href="/community/guide-placeholder/versions" rel="ugc nofollow noopener">Qual versão do jogo estou usando?</a></li></ul>');
 END IF;
END $guide$;

DO $guide$
DECLARE tid bigint; aid bigint;
BEGIN
 IF NOT EXISTS (SELECT 1 FROM player_guides WHERE locale = 'pt-BR' AND key = 'asking-for-help') THEN
  SELECT id INTO STRICT aid FROM members WHERE email = 'releases@outbrick.site' AND role = 'team';
  INSERT INTO threads (category_id, author_id, title, slug, language, pinned, last_poster_id)
  VALUES ((SELECT id FROM categories WHERE slug = 'help'), aid, 'Peça ajuda e relate uma barreira de acessibilidade', 'player-guide-asking-for-help-pt-BR', 'pt-BR', false, aid) RETURNING id INTO tid;
  INSERT INTO player_guides VALUES ('pt-BR', 'asking-for-help', tid);
  INSERT INTO posts (thread_id, author_id, number, body_md, body_html) VALUES (tid, aid, 1, 'Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado

Você pode ler sem ter uma conta. Entre com Apple, Google ou um link enviado por e-mail para fazer uma pergunta, responder ou votar. Se escolher Ocultar Meu E-mail, a Apple pode fornecer um endereço privado de retransmissão; entre pelo mesmo método para voltar à conta. Ao relatar um erro, inclua a versão e a compilação do jogo, dispositivo, versão do iOS, fase, etapas, resultado esperado e o que aconteceu. Para acessibilidade, informe se usou VoiceOver, Controle por Voz, Controle Assistivo ou outro ajuste, além do anúncio ou controle que causou dificuldade. Envie uma captura somente se ajudar e esconda dados da conta. Nunca publique senha, código de acesso ou comprovante de compra. Use Ajuda para dúvidas de jogo, Bugs para problemas reproduzíveis e Acessibilidade para barreiras de uso. Acompanhe a conversa e confira suas preferências de notificação por e-mail.

A Comunidade OutBrick está aberta: peça ajuda, relate um erro, sugira uma ideia e vote no que vem a seguir. A leitura é livre; entre com e-mail, Google ou Apple para participar.

## Continue lendo

[Biblioteca de guias do OutBrick](/community/guide-placeholder/index)

- [Primeiros passos: seu primeiro tabuleiro](/community/guide-placeholder/first-board)
- [Peças especiais, objetivos e estrelas](/community/guide-placeholder/specials-and-stars)
- [Como se orientar na Jornada](/community/guide-placeholder/journey)
- [Jogue com o VoiceOver](/community/guide-placeholder/voiceover)
- [Acessibilidade e ajustes confortáveis](/community/guide-placeholder/settings)
- [Vidas, movimentos, desfazer e vídeos opcionais](/community/guide-placeholder/lives-moves-undos)
- [Qual versão do jogo estou usando?](/community/guide-placeholder/versions)', '<p>Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado</p>
<p>Você pode ler sem ter uma conta. Entre com Apple, Google ou um link enviado por e-mail para fazer uma pergunta, responder ou votar. Se escolher Ocultar Meu E-mail, a Apple pode fornecer um endereço privado de retransmissão; entre pelo mesmo método para voltar à conta. Ao relatar um erro, inclua a versão e a compilação do jogo, dispositivo, versão do iOS, fase, etapas, resultado esperado e o que aconteceu. Para acessibilidade, informe se usou VoiceOver, Controle por Voz, Controle Assistivo ou outro ajuste, além do anúncio ou controle que causou dificuldade. Envie uma captura somente se ajudar e esconda dados da conta. Nunca publique senha, código de acesso ou comprovante de compra. Use Ajuda para dúvidas de jogo, Bugs para problemas reproduzíveis e Acessibilidade para barreiras de uso. Acompanhe a conversa e confira suas preferências de notificação por e-mail.</p>
<p>A Comunidade OutBrick está aberta: peça ajuda, relate um erro, sugira uma ideia e vote no que vem a seguir. A leitura é livre; entre com e-mail, Google ou Apple para participar.</p>
<h3>Continue lendo</h3>
<p><a href="/community/guide-placeholder/index" rel="ugc nofollow noopener">Biblioteca de guias do OutBrick</a></p>
<ul><li><a href="/community/guide-placeholder/first-board" rel="ugc nofollow noopener">Primeiros passos: seu primeiro tabuleiro</a></li><li><a href="/community/guide-placeholder/specials-and-stars" rel="ugc nofollow noopener">Peças especiais, objetivos e estrelas</a></li><li><a href="/community/guide-placeholder/journey" rel="ugc nofollow noopener">Como se orientar na Jornada</a></li><li><a href="/community/guide-placeholder/voiceover" rel="ugc nofollow noopener">Jogue com o VoiceOver</a></li><li><a href="/community/guide-placeholder/settings" rel="ugc nofollow noopener">Acessibilidade e ajustes confortáveis</a></li><li><a href="/community/guide-placeholder/lives-moves-undos" rel="ugc nofollow noopener">Vidas, movimentos, desfazer e vídeos opcionais</a></li><li><a href="/community/guide-placeholder/versions" rel="ugc nofollow noopener">Qual versão do jogo estou usando?</a></li></ul>');
 END IF;
END $guide$;

DO $guide$
DECLARE tid bigint; aid bigint;
BEGIN
 IF NOT EXISTS (SELECT 1 FROM player_guides WHERE locale = 'pt-BR' AND key = 'versions') THEN
  SELECT id INTO STRICT aid FROM members WHERE email = 'releases@outbrick.site' AND role = 'team';
  INSERT INTO threads (category_id, author_id, title, slug, language, pinned, last_poster_id)
  VALUES ((SELECT id FROM categories WHERE slug = 'help'), aid, 'Qual versão do jogo estou usando?', 'player-guide-versions-pt-BR', 'pt-BR', false, aid) RETURNING id INTO tid;
  INSERT INTO player_guides VALUES ('pt-BR', 'versions', tid);
  INSERT INTO posts (thread_id, author_id, number, body_md, body_html) VALUES (tid, aid, 1, 'Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado

Um quebra-cabeça tranquilo de combinar três, com 2.000 fases, 167 vilarejos feitos de blocos e nove amigos em 3D. Troque blocos vizinhos, combine três ou mais e cumpra os objetivos de cada fase. Sem cronômetro; todas as fases funcionam offline.

Em desenvolvimento · Slide & Match para a versão 5.1

A próxima atualização para iOS está em teste. Ela reúne deslizes para espaços livres, saídas por portas da mesma cor e trocas entre vizinhos, com doze tipos de fase por vilarejo, blocos maiores e ações de deslizar pelo VoiceOver. Os botões Comunidade e Relatar um erro nos Ajustes e controles renovados também estão em desenvolvimento. Essa versão ainda não está na App Store; a auditoria final das fases e as verificações de lançamento continuam.

Experimente no navegador o clássico jogo de deslizar blocos

Esta demonstração no navegador mantém o antigo quebra-cabeça de deslizar blocos do OutBrick: leve cada bloco até a saída da mesma cor. É um jogo web separado, com desfazer ilimitado. O app atual para iOS usa combinações, cascatas, objetivos e estrelas por pontuação; a demonstração não é uma prévia da versão 5.1.

## Continue lendo

[Biblioteca de guias do OutBrick](/community/guide-placeholder/index)

- [Primeiros passos: seu primeiro tabuleiro](/community/guide-placeholder/first-board)
- [Peças especiais, objetivos e estrelas](/community/guide-placeholder/specials-and-stars)
- [Como se orientar na Jornada](/community/guide-placeholder/journey)
- [Jogue com o VoiceOver](/community/guide-placeholder/voiceover)
- [Acessibilidade e ajustes confortáveis](/community/guide-placeholder/settings)
- [Vidas, movimentos, desfazer e vídeos opcionais](/community/guide-placeholder/lives-moves-undos)
- [Peça ajuda e relate uma barreira de acessibilidade](/community/guide-placeholder/asking-for-help)', '<p>Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado</p>
<p>Um quebra-cabeça tranquilo de combinar três, com 2.000 fases, 167 vilarejos feitos de blocos e nove amigos em 3D. Troque blocos vizinhos, combine três ou mais e cumpra os objetivos de cada fase. Sem cronômetro; todas as fases funcionam offline.</p>
<p>Em desenvolvimento · Slide &amp; Match para a versão 5.1</p>
<p>A próxima atualização para iOS está em teste. Ela reúne deslizes para espaços livres, saídas por portas da mesma cor e trocas entre vizinhos, com doze tipos de fase por vilarejo, blocos maiores e ações de deslizar pelo VoiceOver. Os botões Comunidade e Relatar um erro nos Ajustes e controles renovados também estão em desenvolvimento. Essa versão ainda não está na App Store; a auditoria final das fases e as verificações de lançamento continuam.</p>
<p>Experimente no navegador o clássico jogo de deslizar blocos</p>
<p>Esta demonstração no navegador mantém o antigo quebra-cabeça de deslizar blocos do OutBrick: leve cada bloco até a saída da mesma cor. É um jogo web separado, com desfazer ilimitado. O app atual para iOS usa combinações, cascatas, objetivos e estrelas por pontuação; a demonstração não é uma prévia da versão 5.1.</p>
<h3>Continue lendo</h3>
<p><a href="/community/guide-placeholder/index" rel="ugc nofollow noopener">Biblioteca de guias do OutBrick</a></p>
<ul><li><a href="/community/guide-placeholder/first-board" rel="ugc nofollow noopener">Primeiros passos: seu primeiro tabuleiro</a></li><li><a href="/community/guide-placeholder/specials-and-stars" rel="ugc nofollow noopener">Peças especiais, objetivos e estrelas</a></li><li><a href="/community/guide-placeholder/journey" rel="ugc nofollow noopener">Como se orientar na Jornada</a></li><li><a href="/community/guide-placeholder/voiceover" rel="ugc nofollow noopener">Jogue com o VoiceOver</a></li><li><a href="/community/guide-placeholder/settings" rel="ugc nofollow noopener">Acessibilidade e ajustes confortáveis</a></li><li><a href="/community/guide-placeholder/lives-moves-undos" rel="ugc nofollow noopener">Vidas, movimentos, desfazer e vídeos opcionais</a></li><li><a href="/community/guide-placeholder/asking-for-help" rel="ugc nofollow noopener">Peça ajuda e relate uma barreira de acessibilidade</a></li></ul>');
 END IF;
END $guide$;

DO $guide$
DECLARE tid bigint; aid bigint;
BEGIN
 IF NOT EXISTS (SELECT 1 FROM player_guides WHERE locale = 'pt-BR' AND key = 'index') THEN
  SELECT id INTO STRICT aid FROM members WHERE email = 'releases@outbrick.site' AND role = 'team';
  INSERT INTO threads (category_id, author_id, title, slug, language, pinned, last_poster_id)
  VALUES ((SELECT id FROM categories WHERE slug = 'help'), aid, 'Biblioteca de guias do OutBrick', 'player-guide-index-pt-BR', 'pt-BR', true, aid) RETURNING id INTO tid;
  INSERT INTO player_guides VALUES ('pt-BR', 'index', tid);
  INSERT INTO posts (thread_id, author_id, number, body_md, body_html) VALUES (tid, aid, 1, 'Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado

Comece por aqui para aprender a jogar, explorar a Jornada e usar VoiceOver e os recursos de acessibilidade. Estes guias descrevem o iOS 5.0.1; a prévia da versão 5.1 está identificada à parte.

- [Primeiros passos: seu primeiro tabuleiro](/community/guide-placeholder/first-board)
- [Peças especiais, objetivos e estrelas](/community/guide-placeholder/specials-and-stars)
- [Como se orientar na Jornada](/community/guide-placeholder/journey)
- [Jogue com o VoiceOver](/community/guide-placeholder/voiceover)
- [Acessibilidade e ajustes confortáveis](/community/guide-placeholder/settings)
- [Vidas, movimentos, desfazer e vídeos opcionais](/community/guide-placeholder/lives-moves-undos)
- [Peça ajuda e relate uma barreira de acessibilidade](/community/guide-placeholder/asking-for-help)
- [Qual versão do jogo estou usando?](/community/guide-placeholder/versions)', '<p>Revisado em 7 de outubro de 2026 · iOS 5.0.1 lançado</p>
<p>Comece por aqui para aprender a jogar, explorar a Jornada e usar VoiceOver e os recursos de acessibilidade. Estes guias descrevem o iOS 5.0.1; a prévia da versão 5.1 está identificada à parte.</p>
<ul><li><a href="/community/guide-placeholder/first-board" rel="ugc nofollow noopener">Primeiros passos: seu primeiro tabuleiro</a></li><li><a href="/community/guide-placeholder/specials-and-stars" rel="ugc nofollow noopener">Peças especiais, objetivos e estrelas</a></li><li><a href="/community/guide-placeholder/journey" rel="ugc nofollow noopener">Como se orientar na Jornada</a></li><li><a href="/community/guide-placeholder/voiceover" rel="ugc nofollow noopener">Jogue com o VoiceOver</a></li><li><a href="/community/guide-placeholder/settings" rel="ugc nofollow noopener">Acessibilidade e ajustes confortáveis</a></li><li><a href="/community/guide-placeholder/lives-moves-undos" rel="ugc nofollow noopener">Vidas, movimentos, desfazer e vídeos opcionais</a></li><li><a href="/community/guide-placeholder/asking-for-help" rel="ugc nofollow noopener">Peça ajuda e relate uma barreira de acessibilidade</a></li><li><a href="/community/guide-placeholder/versions" rel="ugc nofollow noopener">Qual versão do jogo estou usando?</a></li></ul>');
 END IF;
END $guide$;

DO $links$
DECLARE target record;
BEGIN
 FOR target IN SELECT g.key, t.id, t.slug FROM player_guides g JOIN threads t ON t.id = g.thread_id WHERE g.locale = 'pt-BR' LOOP
  UPDATE posts SET body_md = replace(body_md, '/community/guide-placeholder/' || target.key, '/pt-BR/community/t/' || target.id || '/' || target.slug),
   body_html = replace(body_html, '/community/guide-placeholder/' || target.key, '/pt-BR/community/t/' || target.id || '/' || target.slug)
  WHERE number = 1 AND thread_id IN (SELECT thread_id FROM player_guides WHERE locale = 'pt-BR');
 END LOOP;
END $links$;
