import type { BlogArticle } from '../blog.ts';
import { appStoreUrl } from '../app-store-url.ts';

export const batch10: BlogArticle[] = [{
  slug: 'puzzle-walkthrough-board-mismatch',
  title: 'Why a puzzle walkthrough does not match your board',
  dek: 'Before copying another move, check the game, version, mode and starting layout. Learn why a level number alone cannot identify a puzzle solution.',
  category: 'OutBrick practice', categoryColor: 'green',
  publishedAt: 'September 30, 2026', updatedAt: 'September 30, 2026', readingTime: '8 min read',
  authorId: 'outbrick-editorial', image: '/blog/puzzle-walkthrough-board-mismatch.webp',
  imageAlt: 'An OutBrick game capture inside a phone with colourful bricks and two brick friends against a navy grid',
  tags: ['puzzle games', 'problem solving', 'sliding puzzles', 'outbrick practice', 'puzzle hints'],
  intro: 'The video says level 48. Your game says level 48. Yet its first move sends a blue brick into an empty lane that is occupied on your screen. You replay the opening, try the move again and wonder what you missed. Before spending another attempt, compare the two boards. A level number is a label inside a particular game and release; it is not a complete description of a puzzle. This guide offers a practical way to identify a mismatched walkthrough, find the first point of disagreement and recover a useful idea without pretending the demonstrated sequence must work.',
  keyTakeaways: [
    'Match the exact game, mode, version and complete starting layout before relying on a move sequence.',
    'OutBrick’s published release history includes changed layouts and reordered boards, so an older level label can lead to a different puzzle.',
    'When a sequence fails, stop at the first mismatch. Keep a relevant planning idea, or request help for your actual board.',
  ],
  sections: [
    { id: 'identify-the-right-game', title: 'First, make sure you are watching the same game', paragraphs: [
      'Start with the full app name and developer, rather than a search result’s thumbnail. Many mobile puzzles use blocks, colour-matched exits and similar words in their titles. A video labelled “block sort level 48” might belong to another app altogether. Open the game’s store page from its own settings or compare its developer with the listing. Similar artwork is a reason to look more carefully, not evidence of identical rules.',
      'Next, check what the player is controlling. Does a block travel as far as it can, move a single square, or follow a dragged path? Is a character pushing boxes? Does a colour need to reach a gate, occupy a target, or complete a line? In OutBrick’s current Slide & Match rule, a brick stops where you let go, leaves through a gate matching its colour or swaps with a neighbour, and three or more of a colour in a line clear. On its classic boards, still playable in the browser, a brick glides until something stops it; our [guide to solving sliding-block puzzles](/blog/how-to-solve-sliding-block-puzzles) explains that classic movement model.',
      'Hearn and Demaine (2005) studied formal movement problems with different constraints, including sliding blocks and Sokoban. Their theoretical results concern generalised problem families, not the difficulty of your particular app. The useful distinction here is narrower: legal movement and the goal belong in a puzzle’s identity. A sequence for a push-only game cannot be assumed to work in a glide-and-stop game.',
      'Write a short identification line before searching again: app name, developer, mode and level. Add the platform and visible app version if you can find them. This is our troubleshooting recommendation, not a checklist tested by that paper. It helps a guide author or another player understand which puzzle you mean without guessing from a cropped screenshot.',
    ], sourceIds: ['hearn-2005'] },
    { id: 'check-version-mode-and-date', title: 'A familiar number can hide a changed board', paragraphs: [
      'A walkthrough’s publication date is useful context, but it is not the same as the app version used to record it. A creator might upload an older recording, or update a title without replacing the video. Look for a version in the description, comments or visible settings. If none is given, treat that detail as unknown. Do not assume the guide is wrong, or that your installation has a fault, simply because the dates differ.',
      'OutBrick provides a concrete reason to check. The studio’s [version 4.2 release notes](/whats-new#4-2) report that 1,301 of the 2,000 boards received new layouts. That is a historical change, not a claim that 4.2 is the newest version. The current [App Store listing and version history](https://apps.apple.com/us/app/outbrick-block-sort-puzzle/id6807997465), checked on 30 September 2026, show 4.5 and report further rebuilding and reordering of boards (Hamdi, n.d.). An old recording’s number may therefore be insufficient to identify today’s arrangement.',
      'Check the mode as well. A main progression board, a browser sample and a dated daily puzzle should not be treated as interchangeable simply because they share colours. OutBrick’s [daily browser board](/daily) rotates a fixed pool according to the UTC date. If you are comparing a daily-board recording, keep its date with the screenshot. This describes the website’s current implementation, not a promise that native daily features behave identically.',
      'Those observations do not establish per-player randomisation, experiments or hidden personal difficulty settings. A visible mismatch cannot tell you which of those explanations exists. Use the documented explanation where one applies, and leave unsupported explanations open. Our article on [verifying the board collection](/blog/verifying-2000-sliding-block-boards) addresses solvability; a solvable board and a matching walkthrough are separate questions.',
    ] },
    { id: 'compare-the-complete-starting-state', title: 'Compare the complete starting state', paragraphs: [
      'Pause the walkthrough before its first move and compare it with your board before you have moved anything. If restarting would cost progress or an attempt, check the game’s own rules first rather than resetting automatically. A screenshot of your current state is still useful; label it “after three moves” instead of presenting it as the opening. A guide cannot reproduce an opening sequence from a different intermediate position.',
      'Check the outline, then the goals, then the pieces. Are the dimensions and blocked cells the same? Are the coloured gates on the same edges? Does each brick have the same shape, orientation and location? Compare keys, locks and other obstacles wherever present. Finally, compare empty space. An empty square is part of the arrangement, because it may determine a route or a stopping point.',
      'Ito et al. (2023), analysing formal ball- and water-sorting models, treat ordered contents, bin capacity and empty bins as parts of an instance. Their result is about those stack-based models, not OutBrick. It offers a useful parallel: a puzzle is more specific than its visible palette. Two tube puzzles with the same colours can have different legal next pours when their ordered contents or spare capacity differ. For a sliding puzzle, inspect the spatial state under its own rules instead.',
      'Use stable labels when asking someone to compare images. Describe “the horizontal blue brick near the lower-left gate” rather than “that blue one”, or agree that rows run from the top and columns from the left. Larkin and Simon (1987) analysed how representations can change search and inference demands even when the information is equivalent. Applying that idea here, keep both boards visible and use the same location labels so you can inspect differences instead of holding one image in memory.',
    ], sourceIds: ['ito-2023', 'larkin-1987'] },
    { id: 'stop-at-the-first-divergence', title: 'Stop where the sequence first diverges', paragraphs: [
      'If the opening layouts match, replay one demonstrated action at a time. Compare the result immediately, including where the moved brick stops and what remains on the board. The first discrepancy is more informative than the tenth. Continuing after it produces a new arrangement, so later directions can fail for reasons introduced by the earlier mismatch.',
      'For example, a recording might move a red brick down until a blue brick stops it. On your board, the blue brick has already left through its gate. The red brick now travels further, so “move red down” no longer produces the demonstrated state. The instruction is superficially the same; its supporting condition is gone. This is an illustrative example of the gliding rule, not a diagnosis of a particular published level.',
      'Separate a refused move from an unexpected result. If a move is refused, recheck the brick, direction and obstacle or gate involved. If it succeeds but stops elsewhere, compare the stopping condition. If the layout matches and the action still behaves differently, record that narrow observation for support. Avoid declaring the board impossible merely because a video cannot be followed.',
      'A useful message includes the app version if known, mode, level or date, two screenshots and the earliest differing action. Crop unrelated personal information from images. Say whether you want a small hint or a full sequence; our [spoiler-free hint guide](/blog/puzzle-hints-without-spoilers) gives examples of both requests. The [support page](/support) is a sensible first stop before sending a report through the existing contact route.',
    ] },
    { id: 'keep-the-idea-not-the-sequence', title: 'Keep the planning idea, then decide what help you want', paragraphs: [
      'A mismatched guide may still show a useful relationship: move a stopper into place before sending a long brick across a lane, or clear an obstructing route before releasing the brick that uses it. Ask what each move achieves and which conditions it requires. If those conditions are absent on your board, do not force the move. A planning idea needs a fresh check against the actual state.',
      'Chi et al. (1989) examined students studying worked mechanics examples through talk-aloud protocols. More successful students generated explanations connecting actions with underlying principles and monitored their understanding. This was a physics-learning study, not a test of puzzle walkthroughs. Our modest application is to explain a demonstrated move’s purpose before borrowing it, rather than assume that copying its direction will reproduce its effect.',
      'There is also no requirement to extract a lesson from every video. If you wanted a direct solution and the board differs, look for a matching example or ask for help with the exact screenshot. If you wanted to preserve the discovery, close the sequence and request only the relevant region or dependency. Neither preference makes you a better or worse player. Help should answer the question you actually asked.',
      `You can practise checking movement conditions on [OutBrick’s browser boards](/play), where the displayed controls let you reset or undo your experiment. To explore the installed game, [download OutBrick on the App Store](${appStoreUrl('journal-walkthrough-mismatch')}) and check its current requirements and purchase information. The app includes lives and optional rewarded advertising; the website sample is not proof of every native feature.`,
      'Product reference: Hamdi, M. (n.d.). OutBrick: Block Sort Puzzle [Mobile app]. App Store. Retrieved September 30, 2026, from the linked listing above. Research references below support the distinctions used in this guide; none evaluated OutBrick or validated this troubleshooting checklist.',
    ], sourceIds: ['chi-1989'] },
  ],
  references: [
    { id: 'chi-1989', label: 'Chi et al. (1989)', citation: 'Chi, M. T. H., Bassok, M., Lewis, M. W., Reimann, P., & Glaser, R. (1989). Self-explanations: How students study and use examples in learning to solve problems. Cognitive Science, 13(2), 145–182.', url: 'https://doi.org/10.1207/s15516709cog1302_1', italicParts: ['Cognitive Science', '13'] },
    { id: 'hearn-2005', label: 'Hearn & Demaine (2005)', citation: 'Hearn, R. A., & Demaine, E. D. (2005). PSPACE-completeness of sliding-block puzzles and other problems through the nondeterministic constraint logic model of computation. Theoretical Computer Science, 343(1–2), 72–96.', url: 'https://doi.org/10.1016/j.tcs.2005.05.008', italicParts: ['Theoretical Computer Science', '343'] },
    { id: 'ito-2023', label: 'Ito et al. (2023)', citation: 'Ito, T., Kawahara, J., Minato, S.-i., Otachi, Y., Saitoh, T., Suzuki, A., Uehara, R., Uno, T., Yamanaka, K., & Yoshinaka, R. (2023). Sorting balls and water: Equivalence and computational complexity. Theoretical Computer Science, 978, Article 114158.', url: 'https://doi.org/10.1016/j.tcs.2023.114158', italicParts: ['Theoretical Computer Science', '978'] },
    { id: 'larkin-1987', label: 'Larkin & Simon (1987)', citation: 'Larkin, J. H., & Simon, H. A. (1987). Why a diagram is (sometimes) worth ten thousand words. Cognitive Science, 11(1), 65–100.', url: 'https://doi.org/10.1111/j.1551-6708.1987.tb00863.x', italicParts: ['Cognitive Science', '11'] },
  ],
  relatedSlugs: ['puzzle-hints-without-spoilers', 'verifying-2000-sliding-block-boards', 'how-to-read-a-puzzle-before-moving'],
  pullQuote: 'A level number is a label inside a particular game and release; it is not a complete description of a puzzle.',
  faqs: [
    { question: 'Why does a puzzle walkthrough show a different board at the same level?', answer: 'First check that it is the same app, mode and starting state. A release can also change layouts or reorder boards; OutBrick’s published history documents such changes, but a mismatch alone does not establish randomisation or a fault.' },
    { question: 'Should I keep following a walkthrough after one move differs?', answer: 'Pause at the first differing result and compare the two states. Later directions may depend on a stopping point or empty space that is no longer present on your board.' },
    { question: 'Does a mismatched walkthrough mean my OutBrick board is impossible?', answer: 'No. A guide for another layout does not establish whether your board can be solved; OutBrick’s published board-verification claims concern solvability, not whether a particular external video matches your version.' },
    { question: 'What should I include when asking for help with a board?', answer: 'Give the app name, mode, level or daily date, version if known, a clear screenshot and the earliest action that differs from the guide. State whether you want a small hint or the full solution, and remove unrelated personal information from images.' },
  ],
}];
