import type { BlogArticle, BlogReference } from '../blog.ts';
import { appStoreUrl } from '../app-store-url.ts';

// Source-based comparisons. Listing claims checked 30 September 2026; no hands-on rankings.
const r: Record<string, BlogReference> = {
  ryan: { id: 'ryan-2006', label: 'Ryan et al. (2006)', citation: 'Ryan, R. M., Rigby, C. S., & Przybylski, A. (2006). The motivational pull of video games: A self-determination theory approach. Motivation and Emotion, 30(4), 344–360.', url: 'https://doi.org/10.1007/s11031-006-9051-8', italicParts: ['Motivation and Emotion', '30'] },
  klimmt: { id: 'klimmt-2007', label: 'Klimmt et al. (2007)', citation: 'Klimmt, C., Hartmann, T., & Frey, A. (2007). Effectance and control as determinants of video game enjoyment. CyberPsychology & Behavior, 10(6), 845–848.', url: 'https://doi.org/10.1089/cpb.2007.9942', italicParts: ['CyberPsychology & Behavior', '10'] },
  iacovides: { id: 'iacovides-2015', label: 'Iacovides et al. (2015)', citation: 'Iacovides, I., Cox, A. L., McAndrew, P., Aczel, J., & Scanlon, E. (2015). Game-play breakdowns and breakthroughs: Exploring the relationship between action, understanding, and involvement. Human–Computer Interaction, 30(3–4), 202–231.', url: 'https://doi.org/10.1080/07370024.2014.987347', italicParts: ['Human–Computer Interaction', '30'] },
  abuhamdeh: { id: 'abuhamdeh-2012', label: 'Abuhamdeh & Csikszentmihalyi (2012)', citation: 'Abuhamdeh, S., & Csikszentmihalyi, M. (2012). The importance of challenge for the enjoyment of intrinsically motivated, goal-directed activities. Personality and Social Psychology Bulletin, 38(3), 317–330.', url: 'https://doi.org/10.1177/0146167211427147', italicParts: ['Personality and Social Psychology Bulletin', '38'] },
  isaksen: { id: 'isaksen-2017', label: 'Isaksen et al. (2017)', citation: 'Isaksen, A., Wallace, D., Finkelstein, A., & Nealen, A. (2017). Simulating strategy and dexterity for puzzle games. In 2017 IEEE Conference on Computational Intelligence and Games (CIG) (pp. 142–149). IEEE.', url: 'https://doi.org/10.1109/CIG.2017.8080427', italicParts: ['2017 IEEE Conference on Computational Intelligence and Games (CIG)'] },
  ran: { id: 'ran-2025', label: 'Ran et al. (2025)', citation: 'Ran, Z., Li, X., Xiao, Q., Fan, X., Li, F. M., Wang, Y., & Lu, Z. (2025). How users who are blind or low vision play mobile games: Perceptions, challenges, and strategies. In Proceedings of the 2025 CHI Conference on Human Factors in Computing Systems (pp. 1–18). Association for Computing Machinery.', url: 'https://doi.org/10.1145/3706598.3714205', italicParts: ['Proceedings of the 2025 CHI Conference on Human Factors in Computing Systems'] },
  goncalves: { id: 'goncalves-2023', label: 'Gonçalves et al. (2023)', citation: 'Gonçalves, D., Piçarra, M., Pais, P., Guerreiro, J., & Rodrigues, A. (2023). “My Zelda Cane”: Strategies used by blind players to play visual-centric digital games. In Proceedings of the 2023 CHI Conference on Human Factors in Computing Systems (Article 289, pp. 1–15). Association for Computing Machinery.', url: 'https://doi.org/10.1145/3544548.3580702', italicParts: ['Proceedings of the 2023 CHI Conference on Human Factors in Computing Systems'] },
  mazur: { id: 'mazur-2025', label: 'Mazur et al. (2025)', citation: 'Mazur, S., Hovis, J. K., & Ramaswamy, S. (2025). Difficulties that gamers with color vision deficiencies experience when playing digital games. Journal of the Optical Society of America A, 42(5), B365–B378.', url: 'https://doi.org/10.1364/JOSAA.544903', italicParts: ['Journal of the Optical Society of America A', '42'] },
  napoli: { id: 'napoli-2018', label: 'Napoli & Chiasson (2018)', citation: 'Napoli, D., & Chiasson, S. (2018). Exploring the impact of colour-blindness on computer game performance. In Extended Abstracts of the 2018 CHI Conference on Human Factors in Computing Systems (pp. 1–6). Association for Computing Machinery.', url: 'https://doi.org/10.1145/3170427.3188555', italicParts: ['Extended Abstracts of the 2018 CHI Conference on Human Factors in Computing Systems'] },
};
const outbrick = 'https://apps.apple.com/us/app/outbrick-block-sort-puzzle/id6807997465';
const blockOut = 'https://apps.apple.com/us/app/block-out-color-sort-puzzle/id6752672568';
const colourJam = 'https://apps.apple.com/us/app/color-block-jam/id6504332779';
const buster = 'https://apps.apple.com/us/app/block-buster-no-timer/id6745272388';
const productRefs = {
  outbrick: `Hamdi, M. (n.d.). OutBrick: Block Sort Puzzle [Mobile app]. App Store. Retrieved September 30, 2026, from [the OutBrick listing](${outbrick}).`,
  blockOut: `Grand Games A.Ş. (n.d.). Block Out! - Color Sort Puzzle [Mobile app]. App Store. Retrieved September 30, 2026, from [the Block Out listing](${blockOut}).`,
  jam: `Rollic Games. (n.d.). Color Block Jam [Mobile app]. App Store. Retrieved September 30, 2026, from [the Color Block Jam listing](${colourJam}).`,
  buster: `Lion Studios Plus. (n.d.). Block Buster - No Timer [Mobile app]. App Store. Retrieved September 30, 2026, from [the Block Buster listing](${buster}).`,
};
export const batch6: BlogArticle[] = [
  {
    slug: 'outbrick-vs-block-out-puzzle',
    title: 'OutBrick vs Block Out Puzzle: which game fits you?',
    dek: 'Compare OutBrick and Grand Games’ Block Out using official listings: mechanics, offline play, accessibility and costs, with an honest fit guide.',
    category: 'OutBrick practice', categoryColor: 'green',
    publishedAt: 'September 30, 2026', updatedAt: 'September 30, 2026', readingTime: '7 min read', authorId: 'outbrick-editorial',
    image: '/blog/outbrick-vs-block-out-puzzle.webp', imageAlt: 'OutBrick game art showing a phone, colourful bricks and two brick characters against a navy grid',
    tags: ['block sort puzzles', 'puzzle games', 'game design', 'accessibility', 'offline play'],
    intro: 'A red block sits beside a red door, but another block is in the way. The puzzle is not recognising the match; it is deciding what must move first. That shared idea makes OutBrick and Grand Games’ Block Out! - Color Sort Puzzle natural games to compare. The useful question is which version of that problem you want to spend time with. This guide compares their published descriptions, checked on 30 September 2026. We make OutBrick, and have a reason to recommend it. We also have a responsibility to distinguish documented features from preferences and unknowns. This is a source-based buying guide, not a report of hands-on testing.',
    keyTakeaways: [
      'Both games centre on moving coloured blocks to matching exits; Block Out specifically advertises moving elevators and block generators.',
      'Both advertise offline play. OutBrick additionally publishes explicit accessibility declarations; missing competitor declarations do not prove missing features.',
      'Choose by the kind of challenge and support you need. Neither a free download nor an untimed mode means unlimited lives or no purchases.',
    ],
    sections: [
      { id: 'shared-loop-different-priorities', title: 'The shared loop, and the differences worth comparing', paragraphs: [
        `Grand Games describes [Block Out! - Color Sort Puzzle](${blockOut}) as a matching-door sliding game with changing layouts, moving elevators and block generators. Those are concrete reasons to investigate it if you like an evolving board with dynamic obstacles. Its description also encourages fast movement. We do not turn that wording into a claim about every level’s precise timer or rules (Grand Games A.Ş., n.d.).`,
        `The [OutBrick listing](${outbrick}) describes a sliding colour-sort puzzle and 2,000 solver-checked boards. Since version 5.1, OutBrick plays Slide & Match: a swiped brick stops where you let go, goes home through the gate of its colour or swaps with a neighbour, and three of a colour in a line clear. In its classic boards, still playable in the browser, a brick glides until a blocker stops it, which makes positioning another brick part of the plan: the obstacle can become a useful brake. For a practical introduction, use our [sliding-block puzzle guide](/blog/how-to-solve-sliding-block-puzzles) rather than assuming all games with similar screenshots share identical movement (Hamdi, n.d.).`,
        'A comparison should separate the board’s demands from how difficult you personally find them. We apply that distinction here without scoring these two apps. An elevator mechanic may be exactly the novelty one player wants and an unwelcome interruption for another. A solver check establishes that a solution exists under particular rules; it does not establish that every person will enjoy discovering it.',
        'Start with a specific preference: do you want to read a stable arrangement, react to changing obstacles, or alternate between those experiences? That question is more informative than asking which game is harder. A harder game can be a better fit if it challenges the skill you came to practise, while an easier game can still be uncomfortable if its interface or pacing gets in your way.',
      ] },
      { id: 'choose-your-kind-of-challenge', title: 'Choose the challenge you actually want', paragraphs: [
        'Research gives a reason to take preference seriously. Across four studies, Ryan et al. (2006) associated perceived competence and autonomy in games with enjoyment and preferences. That does not tell us which of these apps is more enjoyable. It does suggest a useful test: can you understand what the game asks, and can you choose how to approach it? The same board can feel inviting when you have time to think and tiresome when you are trying to answer a message.',
        'Challenge itself is not a defect. Abuhamdeh and Csikszentmihalyi (2012), studying Internet chess and everyday activities, found that the relationship between challenge and enjoyment depended on motivation and the type of activity. Those findings do not show that clocks are harmful or that slower games are better. They support a conditional recommendation: favour planning if planning is what you enjoy, and favour action if acting quickly is part of the pleasure.',
        'OutBrick’s current App Store release notes say version 4.2 withdrew Rush throughout the game. Its boards retain move limits, so untimed play still asks you to plan carefully. If avoiding a countdown is your priority, read our [no-timer block-sort comparison](/blog/no-timer-block-sort-puzzles-iphone) (Hamdi, n.d.). If dynamic obstacles are your priority, Block Out’s explicitly advertised elevators and generators make it a reasonable candidate to try.',
        'A good first session answers a modest question: would I like another board of this kind? Do not force a verdict after a single frustrating attempt. Learning a movement rule and preferring that rule are different decisions. Equally, there is no obligation to persevere just because a game has an attractive map, a long level list or a large audience.',
      ], sourceIds: ['ryan-2006', 'abuhamdeh-2012'] },
      { id: 'feedback-and-earned-progress', title: 'Look for feedback that makes progress understandable', paragraphs: [
        'Imagine moving a blue brick to create a stopping point for a red one. If the game clearly shows where the blue brick stops, the red brick’s next route becomes legible. If the movement surprises you, your next job is learning that rule. This is a useful observation to make in either app. We have not measured their responsiveness, compared input latency or counted accidental moves.',
        'Klimmt et al. (2007) studied enjoyment and perceived influence in an online experiment with 500 participants. Perceived influence mattered, while the relationship with control was more complex than a simple “more is better” rule. For a player choosing a puzzle, the practical implication is to watch whether your actions have understandable consequences. It is an editorial application of their finding, not evidence that one of these games has better controls.',
        'Iacovides et al. (2015) used multiple case studies to explore how action, understanding and involvement interact during play. Breakthroughs in understanding and feeling responsible for progress were important in those accounts. That helps explain why an earned clear can feel different from merely getting past a level with an unfamiliar booster. It does not prove a benefit to intelligence, nor does it require avoiding help.',
        'Try stating what your last attempt taught you: “I need that space empty before moving the long brick.” If you can say it, a failed attempt has given you information. Our article on [reading a puzzle before the first move](/blog/how-to-read-a-puzzle-before-moving) develops that habit. If you cannot tell why a move was refused, look for a tutorial or help screen before treating the problem as your own mistake.',
      ], sourceIds: ['klimmt-2007', 'iacovides-2015'] },
      { id: 'offline-accessibility-and-costs', title: 'Offline play, accessibility and the price of a session', paragraphs: [
        'Both official listings advertise offline play (Grand Games A.Ş., n.d.; Hamdi, n.d.). That removes offline availability as a unique reason to pick OutBrick over Block Out. It also leaves a practical question for either app: which services still require a connection? Download and open the game before travelling, and check the board you intend to play. An offline-board claim is not a promise that adverts, purchases or synchronisation work without the internet.',
        'OutBrick’s listing explicitly declares VoiceOver, Differentiate Without Color Alone, Reduced Motion and Dark Interface support (Hamdi, n.d.). These are developer declarations, not an independent accessibility audit. Block Out had not indicated accessibility support in its listing when checked. That is an information gap, not proof of incompatibility. Our [accessibility comparison for colour-sort players](/blog/color-block-jam-accessible-alternative) explains what to test when those features are essential.',
        'Both are free to download with in-app purchases, and advertising is disclosed. OutBrick also has lives and optional rewarded video. Read a purchase’s current description before deciding what it removes or unlocks; this guide does not promise permanent ad removal or unlimited retries. A listed feature should earn your interest, not bypass your spending decision.',
        'Set a simple first-session budget: no spending while you learn the rule. Notice whether you are content to stop when the free session ends. If you are comparing games for a child or another family member, assess those interruptions together. The fairest recommendation includes the cost of continuing, not just the price of installing.',
      ] },
      { id: 'our-conditional-recommendation', title: 'Our recommendation: start with the fit, then download', paragraphs: [
        'OutBrick is worth considering if you want its Slide & Match planning rule, solver-checked board collection and explicitly documented accessibility features. Block Out deserves consideration if its advertised elevators, generators and dynamic layouts are what excite you. Neither conclusion is a universal ranking. We have not verified that a competitor lacks a feature simply because its listing does not mention it.',
        'You can sample OutBrick’s classic movement idea on [a playable browser board](/play). The browser keeps the older glide-and-stop rule, so it is a useful introduction to the matching-gate idea, not a full substitute for the installed app: it cannot validate every native mode, purchase or accessibility feature. If you enjoy setting up a route rather than dragging a block straight to its destination, you have a concrete reason to explore further.',
        `Ready to try that approach? [Download OutBrick on the Apple App Store](${appStoreUrl('journal-block-out')}) and review the current device requirements and purchase details there. If accessibility is your deciding factor, visit our [accessibility information](/accessibility) first and use the checklist on your own device. A successful download is the beginning of checking fit, not proof that the app meets every need.`,
        'Keep the decision reversible. It is reasonable to enjoy different puzzle games at different times, or to keep one for fast sessions and another for deliberate planning. The best comparison ends with a clearer preference, not an obligation to agree with the studio publishing it.',
      ] },
      { id: 'product-sources', title: 'Product sources and comparison scope', paragraphs: [
        'Product statements above use the US App Store pages retrieved on 30 September 2026. Features, availability and purchase terms can change. Research references below explain the comparison criteria; none tested or endorsed these apps.', productRefs.blockOut, productRefs.outbrick,
      ] },
    ],
    references: [r.abuhamdeh!, r.iacovides!, r.klimmt!, r.ryan!],
    relatedSlugs: ['no-timer-block-sort-puzzles-iphone', 'color-block-jam-accessible-alternative', 'how-to-solve-sliding-block-puzzles'],
    pullQuote: 'A comparison should separate the board’s demands from how difficult you personally find them.',
    faqs: [
      { question: 'Is OutBrick the same game as Block Out Puzzle?', answer: 'No. OutBrick is by Mourad Hamdi, while Block Out! - Color Sort Puzzle is by Grand Games A.Ş. They share a matching-gate sliding idea, but their published mechanics and feature descriptions differ.' },
      { question: 'Can OutBrick and Block Out be played offline?', answer: 'Both official App Store descriptions advertise offline play. This does not establish that online services such as purchases, advertising or progress synchronisation work without a connection.' },
      { question: 'Which game is better for colour-blind players?', answer: 'OutBrick explicitly declares Differentiate Without Color Alone support. Block Out’s lack of an accessibility declaration is not evidence that support is absent, so evaluate the installed games against your needs.' },
      { question: 'Is OutBrick completely free of timers and purchases?', answer: 'Its current release notes say version 4.2 removed all timing, but the app still has move limits, lives and in-app purchases. Untimed play does not mean unlimited retries or no purchase offers.' },
    ],
  },
  {
    slug: 'no-timer-block-sort-puzzles-iphone',
    title: 'No-timer block-sort puzzles for iPhone: a fit guide',
    dek: 'Compare OutBrick, Block Buster - No Timer and Color Block Jam by their published constraints. Learn what untimed play does and does not promise.',
    category: 'Player habits', categoryColor: 'blue',
    publishedAt: 'September 30, 2026', updatedAt: 'September 30, 2026', readingTime: '7 min read', authorId: 'outbrick-editorial',
    image: '/blog/no-timer-block-sort-puzzles-iphone.webp', imageAlt: 'A phone displaying OutBrick game art with brick characters and floating colourful bricks on a navy background',
    tags: ['block sort puzzles', 'puzzle games', 'player habits', 'difficulty design', 'offline play'],
    intro: 'You have seen the move you want to make, but would like another moment to check what happens afterwards. A countdown makes that moment expensive. A move budget lets you keep thinking, then charges you when you act. That difference is the real reason to search for a no-timer block-sort puzzle on iPhone. It is not a search for a game with no challenge. Here we compare the published promises of OutBrick, Block Buster - No Timer and Color Block Jam, and offer a way to choose without confusing untimed play with unlimited moves, lives or free purchases. The listings were checked on 30 September 2026; this is not hands-on performance testing.',
    keyTakeaways: [
      'A countdown limits thinking time; a move budget limits actions. Neither is automatically easier or more enjoyable for every player.',
      'Block Buster explicitly markets no-timer play. OutBrick’s current version 4.2 release notes also say timing was removed throughout the game.',
      'Check offline access, restart costs and purchase terms separately. A no-timer promise does not establish unlimited lives or an ad-free experience.',
    ],
    sections: [
      { id: 'what-no-timer-actually-means', title: 'What “no timer” actually tells you', paragraphs: [
        'An untimed board allows a pause between decisions without consuming a displayed countdown. It can still penalise the wrong move, cap the number of actions, limit retries or offer paid help. Those are separate constraints. If you search by a single phrase, you can find the right pacing and still dislike the way a game handles failure.',
        'Picture a corridor blocked by two pieces. You need to move one aside, slide the other out, then restore a stopping point. Under a move budget, the question is whether that sequence spends too many actions. Under a countdown, the question also includes how quickly you can identify and execute it. The same spatial arrangement can therefore support two different experiences.',
        'Isaksen et al. (2017) modelled strategy and dexterity separately in simulations of Tetris and Puzzle Bobble. Their work gives a useful vocabulary for separating a plan from its execution. It is computational design research, not a human trial demonstrating that untimed games are healthier or improve reasoning. We use it here to clarify the choice, not to assign scientific scores to apps.',
        'Write down the constraint you want removed. “I want time to inspect the board” is more actionable than “I want something relaxing.” You may also want generous retries, a readable interface or no connection requirement, but each needs its own check. Our [guide to what makes a puzzle feel calm](/blog/relaxing-puzzle-games-what-makes-one-calm) considers those other ingredients.',
      ], sourceIds: ['isaksen-2017'] },
      { id: 'three-official-listings', title: 'Three games, three published starting points', paragraphs: [
        `[Block Buster - No Timer](${buster}), by Lion Studios Plus, makes the no-timer promise explicit in its title. Its description also advertises offline-friendly play, boosters and a dark mode. It is a relevant alternative when time to think is your first requirement; OutBrick is not the only game in this area worth considering (Lion Studios Plus, n.d.).`,
        `[OutBrick](${outbrick}) offers matching-gate sliding boards, move constraints and a solver-checked collection. Its current version 4.2 release notes say Rush was withdrawn throughout the game and the per-board move limit remains. That is a published promise of untimed play, alongside constraints on actions and retries (Hamdi, n.d.).`,
        `[Color Block Jam](${colourJam}), by Rollic Games, describes moving blocks to matching doors and planning before time runs out. That makes it a useful timed reference for this decision. If carrying out a plan quickly is part of the fun, its published description may sound more appealing than a no-timer promise. We are not claiming that every screen or level follows one identical constraint (Rollic Games, n.d.).`,
        'These descriptions are starting points, not an exhaustive feature matrix. We have not tested every level, version, device or interruption scenario. Before deciding that an app matches your search, inspect the actual board header and failure conditions. A mode name or screenshot alone cannot tell you the full cost of a restart.',
      ] },
      { id: 'time-to-understand', title: 'Why time to understand can matter more than easy levels', paragraphs: [
        'A common frustration is being asked to move before you understand what the movement will do. In a sliding puzzle, you may need to discover whether a piece stops at an empty square, against another piece or only at an edge. Removing the countdown gives you room to investigate that question. It does not solve the puzzle for you.',
        'Iacovides et al. (2015) explored breakdowns and breakthroughs through multiple game-play case studies. Their findings connect involvement with developing understanding and feeling responsible for progress. This is qualitative evidence about experience, not proof that any one pacing system causes better learning. It does give a reason to value the moment when “I do not know what happened” becomes “I know what to try.”',
        'For a move-limited board, use the thinking time to name the purpose of an action. “This puts a brake behind the long brick” is a plan; “perhaps this will help” is an experiment. Both can be useful. The distinction lets you decide whether to spend a move on testing a rule or on executing a route. Our [guide to reading a board before moving](/blog/how-to-read-a-puzzle-before-moving) offers a fuller method.',
        'A countdown can also be enjoyable once the rule is familiar. Repeating a known sequence efficiently is a different pleasure from discovering it slowly. Do not mistake a personal preference for a verdict on game design. If you want both experiences, a game with optional modes can make sense; check whether the mode you want is available when and where you intend to use it.',
      ], sourceIds: ['iacovides-2015'] },
      { id: 'challenge-with-room-to-choose', title: 'Keep the challenge; choose the pressure', paragraphs: [
        '“Untimed” often gets treated as a synonym for “easy”, but a difficult spatial plan can remain difficult for an entire evening. You can have unlimited thinking time and still need to see a dependency you missed. Conversely, a simple plan can become demanding when you must execute it rapidly. The relevant preference is the source of the demand.',
        'Abuhamdeh and Csikszentmihalyi (2012) found that enjoyment’s relationship with challenge depended on motivation and activity type across studies involving Internet chess and experience sampling. That is a useful counterweight to the idea that pressure is always bad. Their work did not compare these mobile games, and cannot establish a universal ideal level of challenge.',
        'Ryan et al. (2006) associated perceived autonomy and competence with enjoyment and preferences across four studies of games. For this choice, ask whether the rules let you pursue the experience you came for. If you want to inspect a board slowly, a compulsory countdown may work against that intention. If you want to test fast execution, removing the clock may remove something you value.',
        'Consider a small personal trial: play a few boards without buying help, then note what made you want to continue or stop. Was it the puzzle itself, the speed requirement, an unclear rule, or the interruption after a failed attempt? This is a practical observation exercise, not a clinical assessment. One session can clarify a preference without proving anything about long-term wellbeing.',
      ], sourceIds: ['abuhamdeh-2012', 'ryan-2006'] },
      { id: 'pre-download-checklist', title: 'A pre-download checklist for unhurried play', paragraphs: [
        'First, verify the clock. Is the board untimed by default, or does the app ask you to select a mode? Can you pause and return? We have not tested backgrounding or resume behaviour, so do not infer it from a no-timer label. A board without a countdown can still be inconvenient if a session does not survive the interruptions you actually encounter.',
        'Second, verify what a mistake costs. Look for move limits, lives, restarts and the terms of any booster. All three listings disclose in-app purchases. OutBrick also has lives and optional rewarded adverts (Hamdi, n.d.). This article does not promise unlimited retries, uninterrupted access or free help. Decide whether you are content to wait or stop before an offer appears.',
        'Third, check the environment. OutBrick and Block Buster advertise offline play, but that does not guarantee every connected feature works offline (Hamdi, n.d.; Lion Studios Plus, n.d.). Download before travelling and consult our [offline iPhone puzzle guide](/blog/offline-puzzle-games-iphone). If colour recognition, motion or speech output is essential, read our [accessibility information](/accessibility) and test on your own device.',
        `Finally, sample the mechanic. [Play an OutBrick board in your browser](/play) to see the classic glide-and-stop rule (the App Store game now adds swaps and matches), then [download OutBrick on the Apple App Store](${appStoreUrl('journal-no-timer')}) if that kind of planning appeals to you. Native modes and accessibility require separate checks in the installed app. For someone whose first priority is an explicit no-timer product promise, Block Buster deserves a place on the shortlist too.`,
        'The most useful result is a game whose constraints you understand before committing time or money. You can prefer untimed planning today and a faster challenge tomorrow. Make that choice deliberately, with the current listing and the actual board in front of you.',
      ] },
      { id: 'listing-references', title: 'Product sources and scope', paragraphs: [
        'The following dynamic US App Store pages were retrieved on 30 September 2026. This comparison describes published promises rather than independent tests. The scholarly references below inform the decision criteria and do not endorse any named game.', productRefs.buster, productRefs.outbrick, productRefs.jam,
      ] },
    ],
    references: [r.abuhamdeh!, r.iacovides!, r.isaksen!, r.ryan!],
    relatedSlugs: ['outbrick-vs-block-out-puzzle', 'relaxing-puzzle-games-what-makes-one-calm', 'offline-puzzle-games-iphone'],
    pullQuote: 'The relevant preference is the source of the demand.',
    faqs: [
      { question: 'Which block-sort game explicitly advertises no timer?', answer: 'Lion Studios Plus’ Block Buster - No Timer makes that promise in its official App Store title. Check the current installed version and its other constraints before deciding it fits your sessions.' },
      { question: 'Does no timer mean unlimited moves or lives?', answer: 'No. Thinking time, move budgets and retries are separate constraints. Read the board rules and any purchase terms rather than inferring them from the absence of a countdown.' },
      { question: 'Is OutBrick entirely timer-free?', answer: 'According to its current version 4.2 App Store release notes, Rush was withdrawn and nothing in the game is timed. Move limits, lives and purchases remain separate constraints.' },
      { question: 'Why include Color Block Jam in an untimed-game guide?', answer: 'Its official description mentions planning before time runs out, making it a useful timed comparison. Players who enjoy quick execution may prefer that kind of challenge.' },
    ],
  },
  {
    slug: 'color-block-jam-accessible-alternative',
    title: 'A Color Block Jam alternative with VoiceOver support',
    dek: 'Considering OutBrick as a Color Block Jam alternative? Compare documented VoiceOver, colour-glyph and motion support, then use a practical checklist.',
    category: 'Inclusive design', categoryColor: 'teal',
    publishedAt: 'September 30, 2026', updatedAt: 'September 30, 2026', readingTime: '7 min read', authorId: 'outbrick-editorial',
    image: '/blog/color-block-jam-accessible-alternative.webp', imageAlt: 'OutBrick game art arranged around a phone with two brick characters and colourful blocks on a navy grid',
    tags: ['accessibility', 'voiceover', 'colour blindness', 'block sort puzzles', 'inclusive design'],
    intro: 'If you cannot reliably distinguish two gates, a colour-sort puzzle asks you to solve the interface before you solve the board. If you use VoiceOver, a visible route is only useful when the game also communicates the pieces and lets you act on them. Looking for a Color Block Jam alternative can therefore be a very specific search: you want the matching-door idea with clearer evidence that your way of playing is supported. OutBrick is a candidate because its App Store page explicitly declares VoiceOver, Differentiate Without Color Alone, Reduced Motion and Dark Interface. Those declarations are a useful starting point. They are not an independent audit or a guarantee for every player.',
    keyTakeaways: [
      'OutBrick publishes seven accessibility support declarations, including VoiceOver, redundant colour cues and reduced motion. Color Block Jam and Block Out had not indicated support when their listings were checked.',
      'An absent declaration means support is undocumented there, not that a competitor necessarily lacks it. Test the tasks you need on your own device.',
      'Check board navigation, identifying gates, executing moves and recovering from mistakes separately; a readable menu alone is not enough.',
    ],
    sections: [
      { id: 'what-the-listings-establish', title: 'What the listings establish, and what they leave open', paragraphs: [
        `[Color Block Jam](${colourJam}), by Rollic Games, describes sliding coloured blocks to matching doors and planning before time runs out. [Block Out! - Color Sort Puzzle](${blockOut}), by Grand Games, describes a related loop with moving elevators and block generators. They are relevant alternatives in the same broad family, rather than games we dismiss on the basis of a missing label (Rollic Games, n.d.; Grand Games A.Ş., n.d.).`,
        `The [OutBrick listing](${outbrick}) explicitly declares VoiceOver, Differentiate Without Color Alone, Reduced Motion and Dark Interface support (Hamdi, n.d.). Its colour-glyph approach pairs a distinct visible symbol with each brick and corresponding gate. That is a concrete feature to consider if colour alone is not reliable for you. Its sliding rule still needs to suit your preferences; accessibility information does not settle the question of which puzzle you enjoy.`,
        'At the time of checking, the two competitor pages had not indicated accessibility features. We cannot conclude from that wording that VoiceOver, redundant colour cues or motion options are absent. The defensible comparison is between published declarations. An undocumented feature could exist, and a declared feature can still behave differently across tasks, devices or versions.',
        'Apple describes accessibility labels as developer-provided information about common tasks, with device-specific scope (Apple, n.d.). Treat them as a way to narrow a search, then inspect the game you intend to use. We make OutBrick, but have not conducted an independent side-by-side accessibility test of these three apps. This guide offers a verification method rather than a comparative accessibility score.',
      ] },
      { id: 'voiceover-board-tasks', title: 'VoiceOver: test the board, not just the menu', paragraphs: [
        'A screen reader announcing a Play button tells you how to enter a game. It does not tell you whether you can read the board, locate a matching gate, select the intended piece and complete a move independently. Those are separate tasks. Begin with a simple board, so an unfamiliar puzzle does not obscure an interface problem.',
        'Ran et al. (2025) interviewed 32 experienced mobile players who were blind or had low vision. Their accounts describe varied motivations, barriers and strategies shaped by accessibility. This is evidence about the experience of those participants, not an evaluation of OutBrick or its competitors. It supports a practical question: which parts of playing can you do independently, and where does the interface ask you to seek help?',
        'Before completing the tutorial, check whether you can identify the selected brick, understand its available movement and locate its destination. Then deliberately try a move that cannot succeed. Does the game communicate that refusal in a way you can perceive? A clear explanation matters as much as a successful action, because it keeps the next decision from becoming guesswork.',
        'Our [guide to screen-reader games on iPhone](/blog/screen-reader-games-iphone) explains the broader context. For this particular download decision, keep a short task list: enter the board, inspect the pieces, act, detect the result, restart and leave. If one task is unclear, our [support page](/support) provides a route to ask about the current app. Describe the device, version and action that fails rather than assuming a broad label answers every detail.',
      ], sourceIds: ['ran-2025'] },
      { id: 'colour-glyphs-and-contrast', title: 'Colour glyphs: matching should have more than one clue', paragraphs: [
        'A glyph on a block and the same glyph on its gate give you a second matching clue. That can help when two colours look similar. It is not the same as making every element equally readable: small symbols, low contrast, clutter or changing backgrounds can still make a cue hard to use. Look at the actual board size on your device, not only the enlarged store screenshots.',
        'Mazur et al. (2025) surveyed 241 gamers with colour vision deficiencies. Eighty-eight per cent reported at least some gameplay difficulty, with colour matching and identifying objects by colour among the prominent problems. This was a self-selected survey, not an estimate of how often all gamers have colour vision deficiency. It does show why matching-gate tasks deserve attention beyond a general claim that an app is colourful.',
        'Napoli and Chiasson (2018) provide a useful caution. Their small simulation study, with ten analysed participants and fixed-order conditions, did not find significant performance differences, although participants perceived greater difficulty and used pattern cues. Scores alone therefore should not stand in for the whole experience. The study does not prove that any particular symbol system solves the problem for every player.',
        'Try matching a brick and gate using their symbols before using their hue. Can you distinguish the glyphs at your normal viewing distance, and do they remain useful when pieces overlap or sit near the edge? Our [article on colour blindness in games](/blog/colour-blindness-in-games) supplies more background. W3C’s advice to provide information beyond colour is a useful design principle here, although web guidance is not proof of native-app conformance (World Wide Web Consortium, 2025).',
      ], sourceIds: ['mazur-2025', 'napoli-2018'] },
      { id: 'motion-agency-and-recovery', title: 'Motion, agency and recovering from a mistake', paragraphs: [
        'OutBrick’s listing declares Reduced Motion and Dark Interface support (Hamdi, n.d.). These are distinct features. Dark styling does not guarantee sufficient contrast, and reduced animation does not guarantee every player will find the experience comfortable. Check how the board communicates an accepted move, a blocked move and a clear when your preferred settings are active.',
        'Gonçalves et al. (2023) analysed more than 70 hours of blind creators’ gameplay to document strategies for visual-centric games. The work describes tradeoffs involving accessibility, agency and engagement. It does not represent every blind player or rank the apps discussed here. A relevant question is whether an adaptation lets you make meaningful decisions yourself, rather than merely watch someone else complete them.',
        'For a puzzle, recovery is part of that agency. If you move the wrong brick, can you recognise the new state and decide what to do next? If you restart, can you find the control? Check any cost before using help. OutBrick has lives, optional rewarded advertising and in-app purchases; the accessibility declarations do not remove those systems. We do not describe it as unlimited, ad-free or free of purchase prompts.',
        'Pacing belongs on the same checklist. OutBrick’s current version 4.2 release notes say all timing was removed, while Color Block Jam’s description mentions time running out. If time to inspect spoken information is essential, that documented pacing difference is worth considering (Hamdi, n.d.; Rollic Games, n.d.). Our [guide to no-timer block-sort choices](/blog/no-timer-block-sort-puzzles-iphone) separates thinking time from move limits and retries.',
      ], sourceIds: ['goncalves-2023'] },
      { id: 'choose-and-verify', title: 'Choose a candidate, then verify your essential tasks', paragraphs: [
        'OutBrick is a reasonable candidate if you want a matching-gate puzzle whose developer explicitly documents speech output, redundant colour cues and reduced motion. That is a preference-based recommendation grounded in its listing, not a promise of flawless access. If you already enjoy Color Block Jam or Block Out, ask their developers about the features you need; a missing declaration is not a reason to invent a negative verdict.',
        'Prioritise your essential tasks before any purchase. Make a small checklist you can repeat after an update: navigate to a board, identify a brick and gate, execute a move, understand its result, recover and exit. Add a check for shop and advert controls if you plan to use them. A feature that works on the board should not be assumed to cover every surrounding screen.',
        `Read our [OutBrick accessibility information](/accessibility), then [download OutBrick on the Apple App Store](${appStoreUrl('journal-accessibility')}) if its documented features match your needs. Review current compatibility there and test the native app on the device you will use. The [browser board](/play) can introduce the classic movement idea, but it cannot certify the installed app’s VoiceOver or motion behaviour.`,
        'You do not need to justify a preference for larger cues, slower inspection or more predictable feedback. Those are practical requirements for enjoyable play. The value of a comparison is making those requirements visible, so you can choose with better information and give a developer a specific account of anything that still gets in the way.',
      ] },
      { id: 'official-reference-list', title: 'Official product and guidance references', paragraphs: [
        'Listings were retrieved on 30 September 2026. The research references below explain relevant barriers and strategies; none independently tested these apps.', productRefs.outbrick, productRefs.jam, productRefs.blockOut,
        'Apple. (n.d.). Overview of Accessibility Nutrition Labels. Apple Developer. Retrieved September 30, 2026, from [Apple’s accessibility label guidance](https://developer.apple.com/help/app-store-connect/manage-app-accessibility/overview-of-accessibility-nutrition-labels/).',
        'World Wide Web Consortium. (2025, September 16). Understanding Success Criterion 1.4.1: Use of color. [W3C’s explanation of colour and redundant information](https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html).',
      ] },
    ],
    references: [r.goncalves!, r.mazur!, r.napoli!, r.ran!],
    relatedSlugs: ['screen-reader-games-iphone', 'colour-blindness-in-games', 'outbrick-vs-block-out-puzzle'],
    pullQuote: 'For a puzzle, recovery is part of that agency.',
    faqs: [
      { question: 'Does OutBrick support VoiceOver?', answer: 'Its developer explicitly declares VoiceOver support on the App Store. Check the board and surrounding tasks on your own device; a declaration is not an independent audit.' },
      { question: 'Does Color Block Jam lack accessibility features?', answer: 'Its App Store page had not indicated accessibility support when checked on 30 September 2026. That does not establish that features are absent; ask the developer or test the tasks you need.' },
      { question: 'How do colour glyphs help with block-sort puzzles?', answer: 'Matching symbols on a brick and gate provide another clue beyond their colour. Their size, contrast and clarity still need to suit the player and device.' },
      { question: 'Does an accessibility label mean Apple certified the game?', answer: 'No. Apple describes the labels as developer-provided accessibility information. They help with discovery but do not replace checking your essential tasks in the installed game.' },
    ],
  },
];
