import type { BlogArticle, BlogReference } from '../blog.ts';
import { appStoreUrl } from '../app-store-url.ts';

const r: Record<string, BlogReference> = {
  ryan: { id: 'ryan-2006', label: 'Ryan et al. (2006)', citation: 'Ryan, R. M., Rigby, C. S., & Przybylski, A. (2006). The motivational pull of video games: A self-determination theory approach. Motivation and Emotion, 30(4), 344–360.', url: 'https://doi.org/10.1007/s11031-006-9051-8', italicParts: ['Motivation and Emotion', '30'] },
  challenge: { id: 'abuhamdeh-2012', label: 'Abuhamdeh & Csikszentmihalyi (2012)', citation: 'Abuhamdeh, S., & Csikszentmihalyi, M. (2012). The importance of challenge for the enjoyment of intrinsically motivated, goal-directed activities. Personality and Social Psychology Bulletin, 38(3), 317–330.', url: 'https://doi.org/10.1177/0146167211427147', italicParts: ['Personality and Social Psychology Bulletin', '38'] },
  isaksen: { id: 'isaksen-2017', label: 'Isaksen et al. (2017)', citation: 'Isaksen, A., Wallace, D., Finkelstein, A., & Nealen, A. (2017). Simulating strategy and dexterity for puzzle games. In 2017 IEEE Conference on Computational Intelligence and Games (CIG) (pp. 142–149). IEEE.', url: 'https://doi.org/10.1109/CIG.2017.8080427', italicParts: ['2017 IEEE Conference on Computational Intelligence and Games (CIG)'] },
  iacovides: { id: 'iacovides-2015', label: 'Iacovides et al. (2015)', citation: 'Iacovides, I., Cox, A. L., McAndrew, P., Aczel, J., & Scanlon, E. (2015). Game-play breakdowns and breakthroughs: Exploring the relationship between action, understanding, and involvement. Human–Computer Interaction, 30(3–4), 202–231.', url: 'https://doi.org/10.1080/07370024.2014.987347', italicParts: ['Human–Computer Interaction', '30'] },
  sokoban: { id: 'junghanns-2001', label: 'Junghanns & Schaeffer (2001)', citation: 'Junghanns, A., & Schaeffer, J. (2001). Sokoban: Enhancing general single-agent search methods using domain knowledge. Artificial Intelligence, 129(1–2), 219–251.', url: 'https://doi.org/10.1016/S0004-3702(01)00109-6', italicParts: ['Artificial Intelligence', '129'] },
  hearn: { id: 'hearn-2005', label: 'Hearn & Demaine (2005)', citation: 'Hearn, R. A., & Demaine, E. D. (2005). PSPACE-completeness of sliding-block puzzles and other problems through the nondeterministic constraint logic model of computation. Theoretical Computer Science, 343(1–2), 72–96.', url: 'https://doi.org/10.1016/j.tcs.2005.05.008', italicParts: ['Theoretical Computer Science', '343'] },
  kotovsky: { id: 'kotovsky-1985', label: 'Kotovsky et al. (1985)', citation: 'Kotovsky, K., Hayes, J. R., & Simon, H. A. (1985). Why are some problems hard? Evidence from Tower of Hanoi. Cognitive Psychology, 17(2), 248–294.', url: 'https://doi.org/10.1016/0010-0285(85)90009-X', italicParts: ['Cognitive Psychology', '17'] },
  shute: { id: 'shute-2008', label: 'Shute (2008)', citation: 'Shute, V. J. (2008). Focus on formative feedback. Review of Educational Research, 78(1), 153–189.', url: 'https://doi.org/10.3102/0034654307313795', italicParts: ['Review of Educational Research', '78'] },
  assistance: { id: 'koedinger-2007', label: 'Koedinger & Aleven (2007)', citation: 'Koedinger, K. R., & Aleven, V. (2007). Exploring the assistance dilemma in experiments with cognitive tutors. Educational Psychology Review, 19(3), 239–264.', url: 'https://doi.org/10.1007/s10648-007-9049-0', italicParts: ['Educational Psychology Review', '19'] },
  help: { id: 'aleven-2016', label: 'Aleven et al. (2016)', citation: 'Aleven, V., Roll, I., McLaren, B. M., & Koedinger, K. R. (2016). Help helps, but only so much: Research on help seeking with intelligent tutoring systems. International Journal of Artificial Intelligence in Education, 26(1), 205–223.', url: 'https://doi.org/10.1007/s40593-015-0089-1', italicParts: ['International Journal of Artificial Intelligence in Education', '26'] },
};
const arcadeAnnouncement = 'https://www.apple.com/newsroom/2026/08/apple-arcade-levels-up-with-block-blast-plus-and-art-of-fauna-cozy-puzzles-plus/';

export const batch8: BlogArticle[] = [
  {
    slug: 'block-blast-plus-vs-outbrick',
    title: 'Block Blast!+ vs OutBrick: two kinds of block puzzle',
    dek: 'Compare Block Blast!+ and OutBrick by their actual mechanics: placing shapes to clear lines, sliding bricks to exits, and choosing how to pay.',
    category: 'Game craft', categoryColor: 'purple',
    publishedAt: 'September 30, 2026', updatedAt: 'September 30, 2026', readingTime: '8 min read', authorId: 'outbrick-editorial',
    image: '/blog/block-blast-plus-vs-outbrick.webp', imageAlt: 'Colourful OutBrick bricks and characters arranged around a phone on a dark geometric background',
    tags: ['puzzle games', 'block sort puzzles', 'game design', 'player habits', 'mobile games'],
    intro: 'A grid full of colourful blocks can hide two very different puzzles. In one, you choose where a new shape belongs. In another, every piece already has a place and your job is to find its way out. Block Blast!+ and OutBrick make that distinction useful: both reward reading space, but they ask different questions about it. If you searched for a game like Block Blast, the most helpful answer is not a list of similar screenshots. It is an explanation of what you will actually do. This is a source-based mechanics guide, checked on 30 September 2026, written by the team behind OutBrick. We have not run a hands-on comparison or measured which game players prefer.',
    keyTakeaways: [
      'Block Blast!+ centres on placing shapes and clearing complete rows or columns; OutBrick centres on sliding existing bricks through matching gates.',
      'Block Blast!+ is the Apple Arcade edition. Do not apply its subscription, advertising or purchase conditions to the separately listed standard Block Blast! app.',
      'Choose placement if you enjoy fitting and preserving space; choose sliding if you enjoy routes, stopping points and the order of moves.',
    ],
    sections: [
      { id: 'placing-versus-routing', title: 'The first difference is the verb', paragraphs: [
        'Apple describes Block Blast!+ as a game of fitting blocks on a grid, completing rows and columns and building combinations (Apple, 2026). Its core question is “Where should this shape go?” An empty patch is an opportunity to place something. A line near completion is a possible way to recover space. You are reading the footprint of a shape against the spaces still available.',
        'OutBrick’s question is “What must move before this brick can leave?” You select a brick already on the board and slide it. It glides until something stops it, and its destination is the gate of its own colour. An empty patch may be a route, but it may also let a brick travel farther than you wanted. More free space is not automatically the better position.',
        'Consider a long straight lane. In a placement puzzle, keeping that lane open might preserve room for a long shape. In a gliding puzzle, an open lane could carry a brick past the turning point it needs. Another brick may have to sit in the lane as a temporary brake. The same visual feature has a different strategic meaning because the movement rule changes what you can do with it.',
        'Our [sliding-block puzzle introduction](/blog/how-to-solve-sliding-block-puzzles) explains that movement rule in more detail. For a wider view of placement, falling pieces and routing, see [what makes games like Tetris last](/blog/games-like-tetris). Neither mechanic is a more advanced version of the other. They are different ways of making limited space interesting.',
      ] },
      { id: 'two-ways-to-plan', title: 'Two ways to think about the next move', paragraphs: [
        'In a placement puzzle, inspect the offered shape, its possible landing spaces and the board that remains afterwards. A position can be legal and still be inconvenient: it may leave an awkward small gap or consume the only space that fits another shape. Finishing a line can be attractive because it changes the amount and shape of available space. This describes a general placement problem, not an optimal strategy for every Block Blast mode.',
        'In OutBrick, inspect the selected brick’s whole travel path and final stopping point. Moving a blocker out of the way may open a gate route, but moving it too early may remove the stopping surface another brick needs. A useful plan therefore describes dependencies: blue must stop here before red can align with its exit. The board asks you to rearrange a system, rather than simply choose an empty destination.',
        'Isaksen et al. (2017) separated strategic choice from execution demands in simulations of Tetris and Puzzle Bobble variants. Their work shows why a single difficulty label can conceal different requirements. It did not study Block Blast!+ or OutBrick. We use that distinction as a comparison tool: ask both whether you enjoy deciding on a move and whether you enjoy carrying it out.',
        'That matters if you like thoughtful puzzles but dislike a particular input style. Dragging a shape to a location and giving an existing brick a direction are separate interactions. Screenshots will not settle which feels clearer to you. Try a simple example, read the instructions and observe what a refused move means before treating an unfamiliar control as evidence that the puzzle is too hard.',
      ], sourceIds: ['isaksen-2017'] },
      { id: 'satisfaction-without-ranking', title: 'What kind of satisfaction are you looking for?', paragraphs: [
        'Some players want the repeated satisfaction of a line disappearing. Others want a final board clear whose route they gradually uncover. You may enjoy both at different times. This distinction is about the shape of an enjoyable session, not a judgement that scoring is shallow or that finite boards are intellectually superior.',
        'Ryan et al. (2006) examined gaming motivation across four studies and linked perceived competence and autonomy with enjoyment and preferences. Those findings do not rank these apps. They give a useful personal question: does this game let you understand what happened and make choices that feel like yours? A familiar mechanic can provide that feeling quickly; a new one may need a few boards before it becomes legible.',
        'Abuhamdeh and Csikszentmihalyi (2012) studied challenge in Internet chess and everyday activities. Challenge related to enjoyment differently depending on motivation and activity type. Their result is a reason to avoid declaring the gentlest or hardest puzzle the universal winner. If you want to build a score, preserving space may be compelling. If you want to untangle a bounded arrangement, a matching-gate board may fit better.',
        'Give yourself a concrete test. After a short session, name one decision you enjoyed: reserving a space, completing a combination, constructing a stopping point or finding an exit order. “I liked that decision” tells you more than “I ought to like this popular game”. You can also decide that neither is right for the moment and keep looking.',
      ], sourceIds: ['ryan-2006', 'abuhamdeh-2012'] },
      { id: 'arcade-and-standalone', title: 'Check the edition before comparing the costs', paragraphs: [
        'Apple announced that Block Blast!+ would join Apple Arcade on 3 September 2026, describing the Arcade edition as free of advertising and in-app purchases (Apple, 2026). That statement belongs to Block Blast!+. The standard Block Blast! app is a separate listing; a plus sign is not cosmetic when it identifies a different distribution model. Check which edition a recommendation, screenshot or review actually discusses.',
        'Arcade access depends on a subscription and its current terms. OutBrick is a standalone App Store download with in-app purchases and optional rewarded advertising. It also has lives and move limits. Do not turn “free to download” into a promise that all access, retries or extras are free, and do not assume a subscription puzzle’s conditions describe a standalone one.',
        'If you already subscribe to Arcade, inspect the current Block Blast!+ listing to see whether it suits your device and preferences. If you do not, consider the wider catalogue and subscription terms before buying access for one game. For OutBrick, our [fair-play explanation](/#fair) outlines its lives, undo and optional advertising arrangements. A comparison is useful when it makes those choices understandable.',
        'OutBrick removed Rush in version 4.2; its current puzzle rule uses a move limit rather than a countdown. That does not establish the exact pacing of every Block Blast edition or mode. Read the current description of the edition you intend to install instead of inferring a clock from its name, score display or colourful presentation.',
      ] },
      { id: 'a-small-fit-test', title: 'A small test is better than a sweeping verdict', paragraphs: [
        'First, explain the rule back to yourself. For placement: put a shape into a legal space and work towards a complete line. For OutBrick: give a brick a direction, predict where it stops and work towards its matching exit. Then play slowly enough to notice whether each action confirms that explanation. A comparison should help you enter the right puzzle, not persuade you to tolerate the wrong one.',
        'Iacovides et al. (2015) used multiple case studies, including observation and interviews, to examine learning and involvement in games. Their accounts connected breakthroughs in understanding with involvement, especially when players felt responsible for progress. These are qualitative findings from other games. They support paying attention to your understanding without promising that one brief trial reveals a universal preference.',
        'You can [try an OutBrick board in the browser](/play) to inspect the glide-to-stop idea. That demonstration is a way to sample the mechanic; it does not reproduce every feature, cost or accessibility behaviour of the installed app. If you enjoy it, [view OutBrick on the App Store](' + appStoreUrl('journal-block-blast-comparison') + ') and check current device requirements and purchase information before downloading.',
        'The useful outcome may be a very ordinary sentence: “I like fitting new shapes more than rerouting old ones”, or the reverse. That is enough. Block puzzles share a visual vocabulary, but their verbs decide the experience. Choose the verb you want to keep doing.',
      ], sourceIds: ['iacovides-2015'] },
      { id: 'official-source', title: 'Official product source', paragraphs: [
        `Apple. (2026, August 11). Apple Arcade’s lineup of hit puzzle games gets even bigger with the addition of Block Blast!+ and Art of Fauna: Cozy Puzzles+. Apple Newsroom. [Official Arcade announcement](${arcadeAnnouncement}). The studies below provide design and motivation context; none tested either game in this comparison.`,
      ] },
    ],
    references: [r.challenge!, r.iacovides!, r.isaksen!, r.ryan!],
    relatedSlugs: ['games-like-tetris', 'how-to-solve-sliding-block-puzzles', 'no-timer-block-sort-puzzles-iphone'],
    pullQuote: 'More free space is not automatically the better position.',
    faqs: [
      { question: 'Is OutBrick the same kind of puzzle as Block Blast!+?', answer: 'They use different core mechanics. Block Blast!+ asks you to place shapes to complete rows and columns; OutBrick asks you to slide existing bricks through matching gates.' },
      { question: 'Is Block Blast!+ the same app as standard Block Blast!?', answer: 'Block Blast!+ is the Apple Arcade edition, with subscription access and the advertising and purchase conditions described by Apple. Check the separate standard app listing rather than assuming those conditions apply to it.' },
      { question: 'Which is better for planning?', answer: 'Both can involve planning, but around different constraints. Placement asks how a shape affects remaining space, while OutBrick asks how movement order and stopping points affect routes.' },
      { question: 'Can I try OutBrick without installing it?', answer: 'The [browser board](/play) lets you try the glide-to-stop mechanic. Check the App Store listing separately for the installed app’s compatibility, features and costs.' },
    ],
  },
  {
    slug: 'sokoban-vs-sliding-block-puzzles',
    title: 'Sokoban vs sliding-block puzzles: push, glide, plan',
    dek: 'Learn how Sokoban pushing differs from glide-to-stop block puzzles, with practical examples of corners, access routes and temporary stopping points.',
    category: 'Game craft', categoryColor: 'purple',
    publishedAt: 'September 30, 2026', updatedAt: 'September 30, 2026', readingTime: '8 min read', authorId: 'outbrick-editorial',
    image: '/blog/sokoban-vs-sliding-block-puzzles.webp', imageAlt: 'OutBrick phone and colourful bricks against a dark background with geometric pathways',
    tags: ['puzzle games', 'sliding block puzzles', 'game design', 'problem solving', 'block sort puzzles'],
    intro: 'A crate is one square from its goal. Moving it looks obvious, until you notice that the person who must push it cannot get behind it. A coloured brick is beside its exit. Moving that looks obvious too, until an open lane sends it beyond the place you intended. Sokoban and gliding-block puzzles share an interest in space and order, but the obstacle you are planning around is different. This guide compares classic Sokoban rules with OutBrick’s glide-to-stop rule. It is a mechanics explanation, not a difficulty ranking, and its examples are invented teaching positions rather than solutions to named levels.',
    keyTakeaways: [
      'Classic Sokoban moves crates through pushes by a character who must reach the correct side; OutBrick lets you select a brick and send it gliding until stopped.',
      'A Sokoban corner can trap a crate permanently. In gliding puzzles, removing a blocker can remove the stopping point needed for a later route.',
      'Useful habits overlap, but a strategy only transfers when the movement and goal rules support it. Read those rules before importing a familiar plan.',
    ],
    sections: [
      { id: 'what-a-move-means', title: 'What does one move actually mean?', paragraphs: [
        'Classic Sokoban places a character, crates, walls and storage goals on a grid. The character walks into empty space and pushes a crate when the square beyond it is empty. It cannot pull a crate, push a chain of crates or walk through walls. Completion means placing the crates on the goals. Individual implementations can add variants, so this description concerns the classic rule set, not every app using the name.',
        'The character’s position is part of the puzzle. A crate with empty space to its right cannot necessarily be pushed right: the character must also reach its left side. Thinking only about the crate’s destination misses half the move. A short walking route that gets behind a crate may be essential even when it does not move any cargo towards a goal.',
        'In OutBrick, you directly select a brick and give it a direction. It glides until something stops it, and each brick leaves through its matching-colour gate. There is no warehouse worker whose walking route you must preserve. Your attention shifts to the brick’s trajectory, available stops and relationship to other bricks. Keys, locks and crates appear on later boards, but that does not make its core movement identical to Sokoban.',
        '“Sliding-block puzzle” is a broad category. Some sliding games allow small increments or restrict a piece to one axis; others use gliding rules. Our [history of sliding-block puzzles](/blog/history-of-sliding-block-puzzles) gives that wider context. Always identify the movement rule of the particular game before deciding that you already know how to solve it.',
      ] },
      { id: 'the-corner-and-the-brake', title: 'A corner in one puzzle, a brake in another', paragraphs: [
        'Imagine a Sokoban crate next to the bottom wall, with a wall immediately to its left. If it is pushed left into that corner and the corner is not a goal, it cannot get out under classic rules. To move it right, the character would need to stand inside the left wall. To move it up, the character would need to stand below the bottom wall. The crate is trapped even if the rest of the warehouse is spacious.',
        'Junghanns and Schaeffer (2001) studied Sokoban as a demanding single-agent search problem. Their solver work describes the importance of domain knowledge, including detecting deadlocks and reducing unproductive search. This is computer-search research, not an experiment showing how people should train. It supplies an important distinction: a legal move can lead to a position from which the goal is unreachable.',
        'Now imagine a gliding brick that must stop in a central column before travelling towards a gate. A second brick sits one square beyond the desired stop and acts as a brake. Moving that second brick away may appear to tidy the board, but it allows the first brick to glide past the alignment. The obstacle was doing a job. This illustrative position depends on a glide-to-stop rule and should not be generalised to every sliding puzzle.',
        'Neither example says you should never move into a corner or never clear a lane. A goal in the corner can make the Sokoban push correct; a different stopping surface can make the gliding lane safe. The question is what remains possible after the move. A tidy-looking board and a solvable board are not the same thing.',
      ], sourceIds: ['junghanns-2001'] },
      { id: 'routes-have-two-ends', title: 'Preserve access as well as destinations', paragraphs: [
        'Consider a Sokoban corridor connecting two rooms. Pushing a crate into its entrance may bring the crate closer to a storage square while cutting off the character’s route to the other room. You might later need to approach that crate from the far side, but have lost the only way to get there. Before a push, ask where the character can walk afterwards and which side of each remaining crate will still be reachable.',
        'OutBrick’s comparable question concerns transit and stops. If a blue brick must cross a lane before a red brick exits, clearing red first may remove a useful brake or change the available route. Conversely, leaving red in place forever may block blue’s path. The dependency is temporary: keep the piece while it is useful, then remove it when its job is finished.',
        'Write a plan in relationships rather than a long string of directions. In Sokoban: “Keep the doorway open until I can get behind the upper crate.” In a gliding puzzle: “Keep this brick as a stop until the other one is aligned.” Those descriptions make the reason for a move visible. If the board changes, you can check whether the reason still applies instead of trying to remember a vanished sequence.',
        'For more on reading dependencies, see our [guide to inspecting a board before moving](/blog/how-to-read-a-puzzle-before-moving). You do not need a perfect plan for the entire board. It is often enough to identify one access route that must survive and one useful position that should not be disturbed yet.',
      ] },
      { id: 'what-transfers-and-what-does-not', title: 'What transfers when you switch puzzles?', paragraphs: [
        'Checking the consequences of a move is useful in both families. So is recognising that a piece may need to move away from its destination before it can reach it. What transfers less reliably is a specific movement expectation. A Sokoban player may assume they can nudge a brick one square; a gliding player may forget that a warehouse character needs room behind a crate.',
        'Iacovides et al. (2015) examined action, understanding and involvement through multiple case studies of play. Their qualitative accounts describe breakthroughs in understanding as an important part of involvement. They do not establish a measured transfer effect between Sokoban and OutBrick. Our practical application is to treat a surprising move as a possible rule misunderstanding before blaming your planning ability.',
        'Hearn and Demaine (2005) analysed the formal computational complexity of sliding-block puzzles and other constrained problems. Their proof concerns mathematical problem families, not the difficulty of a particular consumer level. It reinforces a useful boundary for this comparison: the permitted moves define the problem. Two boards that look similar can require different reasoning when one movement rule changes; their paper does not rank Sokoban against OutBrick.',
        'Try a simple board when changing puzzle families. Predict one legal action and its exact result, perform it and compare. Repeat with a blocked action if the game allows safe exploration. This small rule check is an editorial suggestion rather than a tested training programme, but it can prevent a familiar-looking board from quietly borrowing the wrong rules in your head.',
      ], sourceIds: ['iacovides-2015', 'hearn-2005'] },
      { id: 'choose-your-favourite-constraint', title: 'Choose the constraint you enjoy thinking about', paragraphs: [
        'Sokoban is a strong candidate when you enjoy planning around a character’s access and the consequences of irreversible pushes. Gliding puzzles are worth trying when you enjoy constructing stops and rerouting pieces directly. Neither preference needs a claim that one genre improves your brain more. These mechanics can be enjoyable on their own terms.',
        'Kotovsky et al. (1985) investigated why different presentations of formally equivalent Tower of Hanoi problems produced different difficulty. Their work concerns those experimental problems, not these two puzzle genres. It is a reason to distinguish the structure of a task from the ease of understanding its rules: an unfamiliar presentation can make a problem feel harder without adding more pieces. Difficulty and personal fit remain different questions.',
        'You can [play an OutBrick demonstration](/play) to see how a gliding rule changes a lane. Read our [colour-sort puzzle tips](/blog/colour-sort-puzzle-tips) when you want to connect that movement with matching gates. If the mechanic appeals, [see OutBrick on the App Store](' + appStoreUrl('journal-sokoban-comparison') + ') for current compatibility and purchase information. The app has move limits, lives and optional rewarded advertising; an untimed puzzle is not unlimited access.',
        'For either family, take one useful question to your next board: “What must remain available after this move?” In Sokoban the answer may be a square the character needs to stand on. In OutBrick it may be a stopping surface. Seeing that difference turns a vague similarity between colourful blocks into a much clearer choice about what you want to play.',
      ], sourceIds: ['kotovsky-1985'] },
      { id: 'classic-rules-source', title: 'Classic rules and evidence boundaries', paragraphs: [
        'Sokoban.jp. (n.d.). Rules. [Classic Sokoban rules](https://sokoban.jp/rule.html). Retrieved September 30, 2026. The examples above are original illustrations of those rules and OutBrick’s movement rule. The research below provides context about search, involvement and motivation; it does not independently evaluate OutBrick.',
      ] },
    ],
    references: [r.hearn!, r.iacovides!, r.sokoban!, r.kotovsky!],
    relatedSlugs: ['history-of-sliding-block-puzzles', 'how-to-read-a-puzzle-before-moving', 'colour-sort-puzzle-tips'],
    pullQuote: 'A tidy-looking board and a solvable board are not the same thing.',
    faqs: [
      { question: 'Can you pull a crate in classic Sokoban?', answer: 'No. Classic Sokoban allows the character to push a crate into an empty square, but not pull it or push a chain of crates; variants may introduce different rules.' },
      { question: 'Why is a corner dangerous in Sokoban?', answer: 'A crate pushed into a non-goal corner can become immovable because the character cannot reach the sides needed to push it away. Check both the crate’s destination and the character’s future access.' },
      { question: 'Does OutBrick move one square at a time like Sokoban?', answer: 'OutBrick bricks glide in the selected direction until something stops them. Planning therefore includes stopping points and matching-colour exits, rather than a character’s pushing position.' },
      { question: 'Will Sokoban skills automatically make OutBrick easy?', answer: 'Some habits, such as checking move order and preserving routes, may be useful. The movement rules differ, so familiar tactics need to be checked against the new game rather than assumed to transfer.' },
    ],
  },
  {
    slug: 'puzzle-hints-without-spoilers',
    title: 'Puzzle hints without spoilers: how to help a friend',
    dek: 'Ask for and give useful puzzle hints without revealing the whole answer: agree on boundaries, share one clue at a time and keep the solver in charge.',
    category: 'Social play', categoryColor: 'pink',
    publishedAt: 'September 30, 2026', updatedAt: 'September 30, 2026', readingTime: '8 min read', authorId: 'outbrick-editorial',
    image: '/blog/puzzle-hints-without-spoilers.webp', imageAlt: 'Two OutBrick characters beside colourful puzzle bricks and a phone on a dark geometric background',
    tags: ['social play', 'puzzle games', 'problem solving', 'player habits', 'family play'],
    intro: 'You recognise the next move before your friend does. Your hand rises towards their phone. A helpful sentence is ready: “Just move that one.” Then you remember that being stuck is partly why they are playing. A puzzle hint can open a useful possibility, but it can also take away the decision someone hoped to make. The practical skill is agreeing on how much help belongs in this moment. This guide offers a graduated way to ask for and give clues, whether you are sharing a daily puzzle, watching a family member play or replying to a screenshot in a group chat. The examples are original; the research provides context from feedback, tutoring and game experience, not a tested hint system for OutBrick.',
    keyTakeaways: [
      'Ask permission before giving a hint, and agree whether the player wants a question, a small clue, a next move or a full solution.',
      'Give one bounded clue, then stop. A chain of unsolicited follow-up clues can reveal the answer just as completely as a walkthrough.',
      'Keep help specific and respectful, label public spoilers clearly, and let the solver decide when they want more information.',
    ],
    sections: [
      { id: 'agree-on-the-help', title: 'Agree on the help before giving it', paragraphs: [
        '“Do you want a hint?” is a good beginning, but it leaves the size of that hint undefined. One person may mean “point out what I have missed”. Another may mean “tell me the next move so I can continue”. Follow permission with a simple choice: a question about the board, a clue about one area, a direct move or the full answer. These are different requests, and none is morally better than another.',
        'For the person asking, a useful message is: “I want a small clue, not the move. I have tried clearing the right-hand lane, but I cannot align the blue brick.” That identifies the problem and the spoiler boundary. If you want a walkthrough, say so. The helper should not make you perform a ritual of struggling first or turn leisure into an examination.',
        'Koedinger and Aleven (2007) reviewed experiments with Cognitive Tutors and described the unresolved balance between providing information and withholding it to support learning. Their assistance dilemma concerns instructional environments, not etiquette in a puzzle chat. It offers a useful analogy: more information is not automatically the right information, and withholding everything is not automatically helpful either.',
        'Permission can change. A player who asked for one gentle clue may later decide they want the exact move. Someone who wanted company may decide to solve alone. Check again at a natural pause rather than assuming the first agreement gives you control of the session. The friend holding the puzzle still chooses what kind of afternoon they are having.',
      ], sourceIds: ['koedinger-2007'] },
      { id: 'a-ladder-of-clues', title: 'Use a ladder of clues, one rung at a time', paragraphs: [
        'Imagine a gliding-block board where a red brick needs a stopping point before it can line up with its gate. Start with an observation question: “Where will red stop if that lane is empty?” This reveals no move sequence. It asks the player to check a rule and notice a consequence. If they already understand that, do not repeat the same clue louder; ask whether they want the next level.',
        'A directional clue might be: “One of the other bricks could act as a brake.” A narrower clue might identify the relevant area: “Look at the piece above the crossing.” An explicit hint would name a move. A complete solution would provide the ordered sequence from the stated position. This is a proposed conversation ladder, not a guarantee that each clue is equally mild on every board.',
        'A clue’s spoiler size depends on the puzzle. Saying “use the green brick” can reveal almost everything on a tiny board and very little on a large one. For that reason, describe the kind of information before sending it: “I can name the piece if you want.” The player can then decide without first seeing the information they hoped to avoid.',
        'After one clue, stop writing and let the person think. Do not add “and then”, “obviously” or a string of arrows while they are still considering it. Our [guide to reading a board before moving](/blog/how-to-read-a-puzzle-before-moving) gives questions you can borrow without supplying a solution. The aim is a useful next observation, not proof that the helper is clever.',
      ] },
      { id: 'be-specific-without-judging', title: 'Be specific about the puzzle, gentle about the person', paragraphs: [
        '“Think harder” is neither a clue nor a useful diagnosis. “You are looking at the wrong thing” may be accurate but leaves the player wondering what the right thing is. A better comment identifies a consequence they can inspect: “If you move that blocker now, what will stop the long brick?” It directs attention without turning a board position into a judgement of ability.',
        'Shute (2008) reviewed formative feedback and described the importance of supportive, specific information, while emphasising that its effectiveness depends on the learner and task. It is a broad educational review, not evidence that a particular phrase improves puzzle performance. We apply its practical distinction between information about the task and evaluation of the person: explain the constraint instead of assigning a label such as careless or slow.',
        'Useful feedback can confirm a sound idea too. “Yes, preserving that doorway makes sense; the issue is the stopping point afterwards” tells the player which part of their reasoning survives. It avoids replacing the whole plan when only one assumption needs attention. If you do not know the answer, say so and explore together rather than presenting a guess as a verified solution.',
        'Avoid grabbing the device, moving a piece without asking or narrating every thought over someone’s shoulder. Those habits remove the time in which the player could connect the clue to the board. Our [friendly competition guide](/blog/friendly-competition-with-friends) makes a related point about agreeing on the experience you share. Helping is a social arrangement as well as an information exchange.',
      ], sourceIds: ['shute-2008'] },
      { id: 'give-the-solver-space', title: 'Give the solver room to use the hint', paragraphs: [
        'A person can read a clue and still need time to see why it matters. Ask them to describe what they are considering if they want company, but do not demand a correct explanation before allowing the next clue. “I think blue needs to stay put” may be enough to restart their own exploration. Sometimes the useful outcome is understanding the dead end, even before finding the exit.',
        'Aleven et al. (2016) reviewed help seeking with intelligent tutoring systems. They reported that classroom feedback on help seeking led students to use help more deliberately, including after that feedback ended, but did not produce better domain learning outcomes. That boundary matters: sensible help use and improved performance are separate claims. We cannot promise that graduated clues will make someone a stronger puzzle solver.',
        'Iacovides et al. (2015) used multiple case studies to examine understanding and involvement in games. Their accounts highlighted the importance of players feeling responsible for progress. This supports an editorial reason to leave decisions with the player, but it does not establish that revealing a move ruins enjoyment. For someone who wants the full answer, receiving it may be exactly what keeps the session pleasant.',
        'If the clue did not help, check whether you are looking at the same board state. A screenshot taken before several moves can make a correct hint irrelevant. Identify the current position, the game or level and any changed rule before sending a sequence. You can also return to a fresh [daily OutBrick board](/daily) and practise giving only observation questions, with permission, as a shared activity.',
      ], sourceIds: ['aleven-2016', 'iacovides-2015'] },
      { id: 'public-spoilers-and-clean-finishes', title: 'Keep public spoilers behind a clear boundary', paragraphs: [
        'In a group chat, the person asking is not the only possible reader. Put the puzzle name and date before any answer, then use the service’s spoiler controls if it has them. If it does not, keep the solution out of the public preview and ask whether a private reply is wanted. Avoid sending an unlabelled solved-board image: a picture can reveal the answer before anyone reads the warning beneath it.',
        'Use a plain label such as “small hint: stopping points” or “full solution follows”. Do not put the revealing move in the title, notification text or first line above the warning. Make clear whether your sequence begins from the original board or a position the player shared. That small detail can prevent a useful answer becoming confusing instructions for everyone else.',
        'When the puzzle is finished, ask whether the player wants to discuss how the clue worked. They may enjoy reconstructing the turning point, or prefer to move on. If you accidentally spoil more than intended, acknowledge it briefly and change the approach next time. There is no need to defend the spoiler by arguing that the solution was obvious.',
        'You can practise the glide-to-stop rule together on our [browser boards](/play), or [download OutBrick from the App Store](' + appStoreUrl('journal-hint-etiquette') + ') after checking the current listing. For a game question or unclear behaviour, the [support page](/support) provides the existing contact route. A friend is allowed to want company, a nudge or an answer. Good hint etiquette makes that choice easy to express and easy to respect.',
      ] },
    ],
    references: [r.help!, r.iacovides!, r.assistance!, r.shute!],
    relatedSlugs: ['friendly-competition-with-friends', 'how-to-read-a-puzzle-before-moving', 'daily-puzzle-shared-ritual'],
    pullQuote: 'The aim is a useful next observation, not proof that the helper is clever.',
    faqs: [
      { question: 'How can I ask for a puzzle hint without getting spoiled?', answer: 'State the size of help you want and what you have already tried, such as “one observation question, not the next move”. Ask the helper to wait before giving a more explicit clue.' },
      { question: 'What should I do before giving someone a hint?', answer: 'Ask permission, then agree whether they want a question, a small clue, a direct move or a complete solution. Give one bounded response and let them decide whether they want more.' },
      { question: 'Is using a hint cheating?', answer: 'In solo leisure play, you can choose how much help you want. If you are taking part in a contest or shared challenge, agree on its rules beforehand and describe any help honestly.' },
      { question: 'How do I share a daily-puzzle solution safely?', answer: 'Name the puzzle and date, label the answer as a spoiler and use spoiler controls where available. Keep revealing moves and solved images out of titles, previews and unprotected opening lines.' },
    ],
  },
];
