-- Add Brazilian Portuguese to community account, thread, translation, and FAQ locales.
-- Existing rows remain unchanged; only the accepted locale sets are widened.
ALTER TABLE members DROP CONSTRAINT members_locale_check;
ALTER TABLE members ADD CONSTRAINT members_locale_check
  CHECK (locale IN ('en','fr','de','es','ja','pt-BR'));

ALTER TABLE threads DROP CONSTRAINT threads_language_check;
ALTER TABLE threads ADD CONSTRAINT threads_language_check
  CHECK (language IN ('en','fr','de','es','ja','pt-BR'));

ALTER TABLE post_translations DROP CONSTRAINT post_translations_locale_check;
ALTER TABLE post_translations ADD CONSTRAINT post_translations_locale_check
  CHECK (locale IN ('en','fr','de','es','ja','pt-BR'));

ALTER TABLE faq_entries DROP CONSTRAINT faq_entries_locale_check;
ALTER TABLE faq_entries ADD CONSTRAINT faq_entries_locale_check
  CHECK (locale IN ('en','fr','de','es','ja','pt-BR'));

-- Brazilian Portuguese translation of every public support FAQ (positions 0–10).
-- Game facts reflect the current iOS product copy, including score-based stars and daily caps.
INSERT INTO faq_entries (locale, topic, question, answer_md, answer_html, position) VALUES
  ('pt-BR', 'undos', 'O primeiro desfazer em cada fase é mesmo grátis?', 'Sim. O primeiro desfazer de cada fase é grátis, não consome sua reserva e não tem limite. Depois disso, você usa uma reserva de cinco desfazeres, que recupera um a cada 25 minutos, ou pode comprar cinco por 250 moedas, ou ganhar dois assistindo a um vídeo recompensado.', '<p>Sim. O primeiro desfazer de cada fase é grátis, não consome sua reserva e não tem limite. Depois disso, você usa uma reserva de cinco desfazeres, que recupera um a cada 25 minutos, ou pode comprar cinco por 250 moedas, ou ganhar dois assistindo a um vídeo recompensado.</p>', 0),
  ('pt-BR', 'lives', 'Quantas vidas tenho e quando uma delas é usada?', 'Você tem cinco vidas, ou oito enquanto tiver o Brick Pass, e recupera uma a cada 30 minutos. Uma vida só é usada quando você fica sem movimentos e escolhe Tentar novamente, ou quando sai de uma fase em que já fez algum movimento.', '<p>Você tem cinco vidas, ou oito enquanto tiver o Brick Pass, e recupera uma a cada 30 minutos. Uma vida só é usada quando você fica sem movimentos e escolhe Tentar novamente, ou quando sai de uma fase em que já fez algum movimento.</p>', 1),
  ('pt-BR', 'ads', 'O OutBrick exibe anúncios?', 'Somente vídeos recompensados, e apenas quando você toca no botão para pedir uma recompensa. Não há banners, anúncios em tela cheia nem anúncios ao abrir o app. Remover anúncios é uma compra única de US$ 4,99.', '<p>Somente vídeos recompensados, e apenas quando você toca no botão para pedir uma recompensa. Não há banners, anúncios em tela cheia nem anúncios ao abrir o app. Remover anúncios é uma compra única de US$ 4,99.</p>', 2),
  ('pt-BR', 'moves', 'Há um cronômetro?', 'Não. Cada fase tem um limite de movimentos, exibido ao lado do contador desde o primeiro toque, mas não há relógio nem contagem regressiva. Ao chegar ao limite, você pode escolher cinco movimentos extras em troca de moedas ou de um vídeo antes que qualquer outra coisa aconteça.', '<p>Não. Cada fase tem um limite de movimentos, exibido ao lado do contador desde o primeiro toque, mas não há relógio nem contagem regressiva. Ao chegar ao limite, você pode escolher cinco movimentos extras em troca de moedas ou de um vídeo antes que qualquer outra coisa aconteça.</p>', 3),
  ('pt-BR', 'purchases', 'Como restauro uma compra?', 'Abra a Loja e escolha Restaurar compras. A Apple processa a transação pela sua Conta Apple.', '<p>Abra a Loja e escolha Restaurar compras. A Apple processa a transação pela sua Conta Apple.</p>', 4),
  ('pt-BR', 'stars', 'O que significam as três estrelas?', 'No jogo para iOS, as estrelas são determinadas pelas metas de pontuação da fase. Combinações, peças especiais, cascatas e o bônus de movimentos restantes contribuem para a pontuação. A demonstração no navegador ainda usa a regra anterior, baseada na meta de movimentos.', '<p>No jogo para iOS, as estrelas são determinadas pelas metas de pontuação da fase. Combinações, peças especiais, cascatas e o bônus de movimentos restantes contribuem para a pontuação. A demonstração no navegador ainda usa a regra anterior, baseada na meta de movimentos.</p>', 5),
  ('pt-BR', 'moves', 'Quanto custam os movimentos extras?', 'Cinco movimentos extras custam 300 moedas, depois 500 e depois 900 durante a mesma tentativa, ou podem ser obtidos com um vídeo recompensado. O preço volta a 300 quando você sai da fase ou a conclui.', '<p>Cinco movimentos extras custam 300 moedas, depois 500 e depois 900 durante a mesma tentativa, ou podem ser obtidos com um vídeo recompensado. O preço volta a 300 quando você sai da fase ou a conclui.</p>', 6),
  ('pt-BR', 'ads', 'Quantos vídeos recompensados posso assistir por dia?', 'No máximo 31 no total, distribuídos entre as seis recompensas, cada uma com seu próprio limite diário. Recusar um vídeo nunca altera a recompensa, a fase nem o preço.', '<p>No máximo 31 no total, distribuídos entre as seis recompensas, cada uma com seu próprio limite diário. Recusar um vídeo nunca altera a recompensa, a fase nem o preço.</p>', 7),
  ('pt-BR', 'accessibility', 'Como ativo ou desativo os símbolos para daltonismo?', 'O modo para daltonismo vem ativado por padrão, então cada bloco e portão tem um símbolo legível. Você pode desativá-lo ou ativá-lo novamente em Ajustes.', '<p>O modo para daltonismo vem ativado por padrão, então cada bloco e portão tem um símbolo legível. Você pode desativá-lo ou ativá-lo novamente em Ajustes.</p>', 8),
  ('pt-BR', 'privacy', 'Como altero minhas preferências de anúncios?', 'No Espaço Econômico Europeu, no Reino Unido e na Suíça, acesse Ajustes e depois Preferências de anúncios para abrir novamente o formulário de consentimento quando quiser. A permissão de rastreamento do iOS fica em Ajustes, Privacidade e Segurança, Rastreamento. Não autorizar não muda nada no jogo.', '<p>No Espaço Econômico Europeu, no Reino Unido e na Suíça, acesse Ajustes e depois Preferências de anúncios para abrir novamente o formulário de consentimento quando quiser. A permissão de rastreamento do iOS fica em Ajustes, Privacidade e Segurança, Rastreamento. Não autorizar não muda nada no jogo.</p>', 9),
  ('pt-BR', 'contact', 'Como entro em contato com o suporte do OutBrick?', 'Use o formulário de contato e informe o número da fase, o modelo do dispositivo, a versão do iOS e o que aconteceu. Nunca precisamos do seu login do Game Center nem de dados de pagamento.', '<p>Use o formulário de contato e informe o número da fase, o modelo do dispositivo, a versão do iOS e o que aconteceu. Nunca precisamos do seu login do Game Center nem de dados de pagamento.</p>', 10);
