-- Align released iOS facts with the support site in all five languages.

UPDATE faq_entries SET answer_md = 'The board shows moves remaining; there is no clock or countdown. At the limit, five extra moves cost 300 coins, then 500, then 900 within the same attempt, or a rewarded video. Leaving or clearing resets the coin ladder.', answer_html = '<p>The board shows moves remaining; there is no clock or countdown. At the limit, five extra moves cost 300 coins, then 500, then 900 within the same attempt, or a rewarded video. Leaving or clearing resets the coin ladder.</p>', updated_at = now() WHERE locale = 'en' AND position = 3;
UPDATE faq_entries SET answer_md = 'The current iOS game awards stars from the board’s score thresholds. Matches, specials, cascades and the leftover-move finish contribute to the score. The browser demo keeps its earlier move-target star rule.', answer_html = '<p>The current iOS game awards stars from the board’s score thresholds. Matches, specials, cascades and the leftover-move finish contribute to the score. The browser demo keeps its earlier move-target star rule.</p>', updated_at = now() WHERE locale = 'en' AND position = 5;
UPDATE faq_entries SET answer_md = 'Daily caps: lives 8, undos 8, extra moves 6, a free Hint at the out-of-moves wall 4, doubled clear coins 4, Brick Wheel 1, the gift balloon 2 and Brick Cinema 6. No banners or interstitials. A video starts only when you choose it; declining costs nothing.', answer_html = '<p>Daily caps: lives 8, undos 8, extra moves 6, a free Hint at the out-of-moves wall 4, doubled clear coins 4, Brick Wheel 1, the gift balloon 2 and Brick Cinema 6. No banners or interstitials. A video starts only when you choose it; declining costs nothing.</p>', updated_at = now() WHERE locale = 'en' AND position = 7;
UPDATE faq_entries SET answer_md = 'Le plateau affiche les coups restants, sans chrono. À la limite, cinq coups supplémentaires coûtent 300 pièces, puis 500, puis 900 dans la même tentative, ou une vidéo récompensée. Quitter ou terminer le plateau remet le tarif à zéro.', answer_html = '<p>Le plateau affiche les coups restants, sans chrono. À la limite, cinq coups supplémentaires coûtent 300 pièces, puis 500, puis 900 dans la même tentative, ou une vidéo récompensée. Quitter ou terminer le plateau remet le tarif à zéro.</p>', updated_at = now() WHERE locale = 'fr' AND position = 3;
UPDATE faq_entries SET answer_md = 'Sur iOS, les étoiles dépendent des seuils de score du plateau. Alignements, spéciaux, cascades et coups restants contribuent au score. La démo web conserve son ancienne règle d’étoiles selon les coups.', answer_html = '<p>Sur iOS, les étoiles dépendent des seuils de score du plateau. Alignements, spéciaux, cascades et coups restants contribuent au score. La démo web conserve son ancienne règle d’étoiles selon les coups.</p>', updated_at = now() WHERE locale = 'fr' AND position = 5;
UPDATE faq_entries SET answer_md = 'Plafonds quotidiens : vies 8, annulations 8, coups supplémentaires 6, indice gratuit à la limite des coups 4, pièces de victoire doublées 4, Brick Wheel 1, ballon cadeau 2 et Brick Cinema 6. Ni bannières ni publicités imposées. Une vidéo ne démarre que si vous la choisissez ; refuser ne coûte rien.', answer_html = '<p>Plafonds quotidiens : vies 8, annulations 8, coups supplémentaires 6, indice gratuit à la limite des coups 4, pièces de victoire doublées 4, Brick Wheel 1, ballon cadeau 2 et Brick Cinema 6. Ni bannières ni publicités imposées. Une vidéo ne démarre que si vous la choisissez ; refuser ne coûte rien.</p>', updated_at = now() WHERE locale = 'fr' AND position = 7;
UPDATE faq_entries SET answer_md = 'Das Feld zeigt die übrigen Züge; es gibt keinen Timer. Am Limit kosten fünf Extrazüge 300, dann 500, dann 900 Münzen im selben Versuch oder ein Belohnungsvideo. Verlassen oder Lösen setzt die Preisleiter zurück.', answer_html = '<p>Das Feld zeigt die übrigen Züge; es gibt keinen Timer. Am Limit kosten fünf Extrazüge 300, dann 500, dann 900 Münzen im selben Versuch oder ein Belohnungsvideo. Verlassen oder Lösen setzt die Preisleiter zurück.</p>', updated_at = now() WHERE locale = 'de' AND position = 3;
UPDATE faq_entries SET answer_md = 'In der aktuellen iOS-App richten sich Sterne nach den Punktschwellen des Feldes. Kombinationen, Spezialsteine, Kaskaden und übrige Züge tragen dazu bei. Die Webdemo behält ihre frühere Zugvorgabenregel.', answer_html = '<p>In der aktuellen iOS-App richten sich Sterne nach den Punktschwellen des Feldes. Kombinationen, Spezialsteine, Kaskaden und übrige Züge tragen dazu bei. Die Webdemo behält ihre frühere Zugvorgabenregel.</p>', updated_at = now() WHERE locale = 'de' AND position = 5;
UPDATE faq_entries SET answer_md = 'Tageslimits: Leben 8, Rückgängig 8, Extrazüge 6, kostenloser Hinweis am Zuglimit 4, doppelte Münzen 4, Brick Wheel 1, Geschenkballon 2 und Brick Cinema 6. Keine Banner oder Zwischenwerbung. Videos starten nur auf Wunsch; Ablehnen kostet nichts.', answer_html = '<p>Tageslimits: Leben 8, Rückgängig 8, Extrazüge 6, kostenloser Hinweis am Zuglimit 4, doppelte Münzen 4, Brick Wheel 1, Geschenkballon 2 und Brick Cinema 6. Keine Banner oder Zwischenwerbung. Videos starten nur auf Wunsch; Ablehnen kostet nichts.</p>', updated_at = now() WHERE locale = 'de' AND position = 7;
UPDATE faq_entries SET answer_md = 'El tablero muestra movimientos restantes, sin temporizador. Al agotarlos, cinco más cuestan 300 monedas, luego 500 y luego 900 dentro del mismo intento, o un vídeo con recompensa. Salir o completar reinicia la escala.', answer_html = '<p>El tablero muestra movimientos restantes, sin temporizador. Al agotarlos, cinco más cuestan 300 monedas, luego 500 y luego 900 dentro del mismo intento, o un vídeo con recompensa. Salir o completar reinicia la escala.</p>', updated_at = now() WHERE locale = 'es' AND position = 3;
UPDATE faq_entries SET answer_md = 'En iOS, las estrellas dependen de los umbrales de puntuación del tablero. Combinaciones, especiales, cascadas y movimientos restantes contribuyen al total. La demo web conserva su antigua regla por movimientos.', answer_html = '<p>En iOS, las estrellas dependen de los umbrales de puntuación del tablero. Combinaciones, especiales, cascadas y movimientos restantes contribuyen al total. La demo web conserva su antigua regla por movimientos.</p>', updated_at = now() WHERE locale = 'es' AND position = 5;
UPDATE faq_entries SET answer_md = 'Límites diarios: vidas 8, deshacer 8, movimientos extra 6, pista gratis al agotar movimientos 4, monedas duplicadas 4, Brick Wheel 1, globo de regalo 2 y Brick Cinema 6. Sin banners ni anuncios intermedios. Un vídeo solo empieza si lo eliges; rechazarlo no cuesta nada.', answer_html = '<p>Límites diarios: vidas 8, deshacer 8, movimientos extra 6, pista gratis al agotar movimientos 4, monedas duplicadas 4, Brick Wheel 1, globo de regalo 2 y Brick Cinema 6. Sin banners ni anuncios intermedios. Un vídeo solo empieza si lo eliges; rechazarlo no cuesta nada.</p>', updated_at = now() WHERE locale = 'es' AND position = 7;
UPDATE faq_entries SET answer_md = '盤面には残り手数を表示し、時計やタイマーはありません。手数切れでは5手追加が同じ挑戦中に300、500、900コインと上がるか、報酬動画を選べます。退出やクリアで価格はリセットされます。', answer_html = '<p>盤面には残り手数を表示し、時計やタイマーはありません。手数切れでは5手追加が同じ挑戦中に300、500、900コインと上がるか、報酬動画を選べます。退出やクリアで価格はリセットされます。</p>', updated_at = now() WHERE locale = 'ja' AND position = 3;
UPDATE faq_entries SET answer_md = '現在のiOSゲームでは盤面のスコア基準で星を獲得します。マッチ、特殊ブロック、連鎖、残り手数のフィニッシュがスコアに加わります。ウェブデモは以前の手数目標による星のルールを残しています。', answer_html = '<p>現在のiOSゲームでは盤面のスコア基準で星を獲得します。マッチ、特殊ブロック、連鎖、残り手数のフィニッシュがスコアに加わります。ウェブデモは以前の手数目標による星のルールを残しています。</p>', updated_at = now() WHERE locale = 'ja' AND position = 5;
UPDATE faq_entries SET answer_md = '1日の上限：ライフ8、取り消し8、追加手数6、手数切れ画面の無料ヒント4、クリア時のコイン倍増4、Brick Wheel 1、ギフト風船2、Brick Cinema 6。バナーや強制広告はありません。選んだときだけ再生し、断っても不利益はありません。', answer_html = '<p>1日の上限：ライフ8、取り消し8、追加手数6、手数切れ画面の無料ヒント4、クリア時のコイン倍増4、Brick Wheel 1、ギフト風船2、Brick Cinema 6。バナーや強制広告はありません。選んだときだけ再生し、断っても不利益はありません。</p>', updated_at = now() WHERE locale = 'ja' AND position = 7;
