import type { ExtraGuideTranslation } from '../../i18n/blog';

/** Brazilian Portuguese translations of the first nine remaining base journal articles. */
export const remainingPtBRA: Record<string, ExtraGuideTranslation> = {
  'designing-for-real-life-play': {
    title: 'Criar um jogo para a vida que as pessoas realmente têm',
    dek: 'Por que perguntar se o jogo cabe na vida é melhor do que tentar aumentar as horas jogadas.',
    imageAlt: 'Uma partida curta de quebra-cabeça no celular, ao lado de uma xícara de chá e uma janela iluminada',
    tags: ['design de jogos', 'jogos para celular', 'jogo saudável', 'pesquisa'],
    intro: 'Um jogo pode ser ótimo e ainda assim não combinar com a rotina de alguém. A pergunta de design mais útil não é “Como fazer as pessoas continuarem jogando?”, mas “Esta experiência combina com a forma como elas querem passar o tempo?”.',
    keyTakeaways: ['Estudos amplos alertam que as horas jogadas, sozinhas, não medem por completo o bem-estar de quem joga.', 'A compatibilidade depende de quando, por que e como a pessoa joga, não apenas do relógio.', 'Um jogo que acolhe pausas deve facilitar parar, voltar e entender onde a pessoa estava.'],
    sections: {
      'hours-are-not-the-whole-story': { title: 'As horas não contam a história toda', paragraphs: ['Dois estudos recentes do Oxford Internet Institute mostram uma distinção útil. Um acompanhou registros objetivos de jogo de dezenas de milhares de adultos e encontrou poucas evidências de que o tempo de jogo, por si só, causasse mudanças no bem-estar. Outro estudou 703 adultos que jogavam Nintendo casualmente, somando mais de 140 mil horas, e observou que o valor percebido — o quanto o jogo cabia na vida das pessoas — informava mais do que o tempo bruto.', 'Isso não quer dizer que o contexto possa ser ignorado. O relógio é apenas uma medida grosseira. A mesma quantidade de minutos pode representar descanso, conexão social, fuga ou uma obrigação indesejada, dependendo da pessoa e do dia.'] },
      'fit-is-a-design-material': { title: 'A compatibilidade com a rotina também se projeta', paragraphs: ['Em um quebra-cabeça para celular, essa compatibilidade aparece em pequenas decisões. A primeira tela se explica sozinha? Dá para terminar uma fase sem uma interrupção surpresa? Voltar depois de uma semana é acolhedor ou parece uma prova? O progresso fica salvo de um jeito que reduz o esforço de lembrar onde a pessoa parou?', 'OutBrick oferece um objetivo por tabuleiro, progresso sincronizado entre aparelhos pelo iCloud e widgets na tela inicial que mostram onde você está. A experiência foi pensada para ser entendida rapidamente e continuar clara quando um minuto livre dá lugar a uma tarde corrida, sem exigir que você reconstrua tudo na memória.'], bullets: ['A partida tem um ponto natural para parar', 'O caminho de volta fica visível, sem pressão', 'O progresso continua claro depois de uma pausa', 'O jogo não exige uma sequência diária para o dia valer'] },
      'research-the-quality-of-play': { title: 'Estudar a qualidade de cada partida', paragraphs: ['Um artigo da Nature Scientific Data criou um conjunto longitudinal intensivo de dados sobre PowerWash Simulator, combinando medidas repetidas de bem-estar com milhões de eventos do jogo. Sua contribuição é metodológica: pesquisadores podem aprender mais ao observar o que as pessoas fazem e sentem ao longo do tempo, em vez de depender apenas de estimativas retrospectivas das horas jogadas.', 'Essa abordagem também muda o que um estúdio deveria observar. Um sinal saudável não é simplesmente o aumento no número de partidas. Pode ser alguém encontrando uma dificuldade confortável, voltando porque uma mecânica faz sentido ou parando depois de uma conclusão satisfatória. As métricas devem ajudar a equipe a perceber esses padrões, sem reduzi-los a uma única classificação.'] },
      'a-small-design-promise': { title: 'Um pequeno compromisso de design', paragraphs: ['A promessa de OutBrick é simples: oferecer um tabuleiro que vale a pena pensar e depois devolver seu tempo. Nada interrompe uma fase, e nenhum vídeo começa sem que você toque no botão para pedi-lo. O primeiro desfazer de cada tabuleiro é grátis e não acaba. Também não é preciso manter o aplicativo aberto para o jogo continuar interessante: uma vida volta a cada trinta minutos, você esteja olhando ou não.', 'Queremos que as pessoas voltem. A diferença está no motivo do convite: um tabuleiro com uma ideia clara, nove amigos de bloquinhos que reagem quando você termina e a satisfação tranquila de enxergar um caminho que, trinta segundos antes, ainda não estava visível.'] },
    },
    pullQuote: 'Oferecer um tabuleiro que vale a pena pensar e depois devolver o tempo de quem joga.',
    faqs: [{ question: 'OutBrick acompanha meu tempo de jogo?', answer: 'Seu progresso fica no seu aparelho e na sua própria conta do iCloud, e o aplicativo não inclui SDK de análise. O provedor de vídeos premiados coleta os dados descritos na [política de privacidade](/privacy). Este artigo fala de métodos de pesquisa, não faz promessas sobre todos os jogos.' }, { question: 'O que significa o jogo caber na vida?', answer: 'É a percepção da própria pessoa de que o tempo de jogo combina com o restante da vida. Isso é diferente de simplesmente somar horas.' }],
  },
  'angry-birds-success-lessons': {
    title: 'Angry Birds: o longo caminho até o sucesso', dek: 'A história contada pela Rovio lembra que jogos icônicos costumam ser a parte visível de uma trajetória bem mais longa.', imageAlt: 'Blocos vermelhos abstratos de lançamento apontados para uma pilha divertida de tijolos verdes de brinquedo', tags: ['Angry Birds', 'jogos para celular', 'sucesso nos jogos', 'iteração'],
    intro: 'Histórias de sucesso muitas vezes parecem um raio caindo do céu. A história corporativa da Rovio conta algo mais útil: dezenas de tentativas, uma oportunidade clara nos celulares e uma equipe que continuou criando até estar pronta quando surgiu a ideia certa.',
    keyTakeaways: ['A Rovio descreve Angry Birds como seu 52º jogo, depois de 51 projetos e de chegar perto da falência.', 'A lição é aprender com cada experimento pequeno, não publicar sem parar até a sorte aparecer.', 'Um sucesso pode se transformar em um universo, mas primeiro a interação principal precisa funcionar.'],
    sections: {
      'the-52nd-game': { title: 'O 52º jogo faz diferença', paragraphs: ['Segundo a história da Rovio, o primeiro Angry Birds foi seu 52º jogo. A empresa já havia desenvolvido dezenas de títulos para as primeiras plataformas móveis e descreve uma equipe perto da falência, precisando de um grande sucesso. Angry Birds foi criado em oito meses e seus downloads cresceram rapidamente nas semanas seguintes.', 'É uma história de sucesso, não uma receita. A fonte é a própria história da empresa, portanto a linguagem tem caráter promocional e deve ser lida junto com outras evidências. A lição prática é mais limitada: o avanço visível foi apoiado por muita iteração anterior, que raramente vira manchete.'] },
      'make-the-core-readable': { title: 'Deixar a mecânica principal clara', paragraphs: ['Em Angry Birds, lançar, mirar e acertar eram ações fáceis de entender. A interação era divertida, mas oferecia um modelo mental claro: puxar, soltar e observar a estrutura reagir. Essa clareza ajuda a explicar como uma mecânica simples sustentou tantas fases e chegou a tantos tipos de jogadores.', 'OutBrick também respeita os primeiros segundos. Deslize um bloco e ele continuará até encontrar um obstáculo. Tire todos os blocos pela porta da mesma cor e o tabuleiro estará concluído. A regra se aprende em cerca de cinco segundos. Depois, cabe ao jogo oferecer pistas suficientes para você usá-la com criatividade.'] },
      'a-franchise-is-a-conversation': { title: 'Uma franquia é uma conversa', paragraphs: ['O relatório anual de 2019 da Rovio descreve uma estratégia que vai além de jogar: assistir, consumir e interagir. Também relata que a operação contínua e as atualizações ajudaram alguns títulos a gerar receita por vários anos. São informações comerciais divulgadas por uma parte interessada, não provas de que uma tática garanta uma comunidade duradoura.', 'A ideia de design continua valiosa: um universo fica mais forte quando os pontos de contato ao redor parecem pertencer ao mesmo mundo. Os [nove amigos de bloquinhos](/mascots) de OutBrick, seus widgets, o bônus diário de moedas e as 167 vilas de tijolos levam todos ao mesmo tabuleiro. Nenhum é um produto separado disputando sua atenção.'] },
      'what-we-keep-for-outbrick': { title: 'O que levamos para OutBrick', paragraphs: ['Da história de Angry Birds, levamos o que é fácil de aplicar e difícil de fingir: continuar aprimorando o ofício, manter clara a primeira interação e fazer a personalidade do jogo acompanhar quem joga. Deixamos de lado a ideia de que sucesso se resume a uma posição no ranking de downloads.', 'OutBrick continua sendo um jogo pequeno. Sua ambição é oferecer um tabuleiro gostoso de jogar, permitir que as pessoas voltem sem tarefas pendentes e melhorar o trabalho bloco por bloco. Para outro caminho até a mesma ideia, leia [como Tetris mantém aberto um conjunto pequeno de regras](/blog/tetris-simple-rules-infinite-variation).'] },
    }, pullQuote: 'O avanço visível foi apoiado por muita iteração anterior, que raramente vira manchete.', faqs: [],
  },
  'monument-valley-less-game-more-experience': {
    title: 'Monument Valley: menos elementos, uma experiência completa', dek: 'Uma análise da ideia da ustwo de “menos jogo, mais experiência” e do que OutBrick aprende com ela.', imageAlt: 'Uma escadaria impossível em tons pastel, montada com blocos de brinquedo brilhantes e originais', tags: ['Monument Valley', 'jogos para celular', 'experiência do usuário', 'design de quebra-cabeças'],
    intro: 'Alguns jogos conquistam atenção acrescentando cada vez mais. Monument Valley virou referência ao transformar cada tela em um pequeno lugar completo. Sua história de design fala menos de minimalismo visual e mais de escolher o que merece a atenção de quem joga.',
    keyTakeaways: ['A ustwo descreve Monument Valley como uma jornada móvel completa, sem tarefas repetitivas, pressão por falhar ou dependência de rankings.', 'A GDC apresenta o design como um encontro entre arquitetura impossível e uma abordagem centrada na experiência do usuário.', 'OutBrick adota o princípio de um momento completo: cada tabuleiro deve ter forma, clima e encerramento próprios.'],
    sections: {
      'a-screen-can-be-a-place': { title: 'Uma tela pode ser um lugar', paragraphs: ['A página do projeto da ustwo descreve Monument Valley como uma experiência curta e completa, com mecânicas novas e sem repetição cansativa, pressão por falhar, estrelas colecionáveis ou rankings. O objetivo declarado do estúdio era que as pessoas terminassem o jogo inteiro no celular, do começo ao fim.', 'Esse relato do estúdio explica uma intenção, não mede causalidade. Ele não prova que uma decisão específica causou o sucesso do jogo. Ainda assim, expressa uma posição clara: um jogo para celular pode ser uma sequência de momentos bem compostos, em vez de uma demanda sem fim por mais tempo.'] },
      'less-game-more-experience': { title: 'Menos jogo, mais experiência', paragraphs: ['A apresentação da GDC pelo designer principal Ken Wong relaciona a arquitetura impossível de M. C. Escher à experiência da ustwo como estúdio de UX. Cada tela era tratada como uma obra, e a equipe pensava no jogo como uma experiência de usuário, não apenas como um teste de dificuldade.', 'Essa mudança é útil para quem cria quebra-cabeças. Dificuldade é só uma dimensão de valor. Um tabuleiro também pode marcar pela silhueta, por uma pequena surpresa ou pelo instante em que a regra aparece sob outro ângulo. A interface em índigo profundo e as vilas de tijolos de OutBrick dão contexto a esses momentos sem apressá-los com um relógio.'] },
      'complete-does-not-mean-easy': { title: 'Completo não quer dizer fácil', paragraphs: ['Uma experiência completa ainda pode exigir concentração. A diferença está em entender o propósito do desafio e em ser respeitado pelo jogo quando ele termina.', 'OutBrick permite que um tabuleiro seja difícil sem tornar o aplicativo inteiro hostil. O primeiro desfazer grátis em cada tabuleiro e outro desfazer grátis quando ele trava ligam a jornada emocional à resolução, não ao pagamento por um erro. O tabuleiro pode ser difícil. A relação com o jogo não precisa ser.'] },
      'the-outbrick-translation': { title: 'Como isso aparece em OutBrick', paragraphs: ['Para OutBrick, “menos jogo” significa menos atrito entre a pessoa e a ideia do tabuleiro. Uma tela pode bastar. Uma jogada pode ensinar uma regra. Um tabuleiro concluído pode encerrar uma sessão com uma sensação boa.', 'Não queremos fazer uma cópia menor do sucesso de outra pessoa. Queremos um universo em que um pequeno quebra-cabeça pareça completo nos próprios termos — também por isso [um tabuleiro de dois minutos pode ser uma pausa de verdade](/blog/why-two-minute-puzzles-feel-good).'] },
    }, pullQuote: 'O tabuleiro pode ser difícil. A relação com o jogo não precisa ser.', faqs: [],
  },
  'minecraft-layered-discovery': {
    title: 'Minecraft: deixar a descoberta criar novas camadas', dek: 'Como um começo aberto cresceu para incluir criação, sobrevivência, fabricação, multijogador e novas plataformas.', imageAlt: 'Uma paisagem original construída com blocos, com uma caverna, uma bancada de trabalho e o nascer do sol', tags: ['Minecraft', 'descoberta', 'design de sistemas', 'sucesso nos jogos'],
    intro: 'O começo de Minecraft mostra como novas camadas podem chegar na hora certa. A primeira versão oferecia um espaço aberto para cavar e construir; as adições seguintes deram mais textura, propósito e formas de compartilhar essa liberdade.',
    keyTakeaways: ['A retrospectiva da Xbox Wire descreve a evolução da construção no Classic para os modos Creative e Survival, fabricação, multijogador e mais plataformas.', 'Um sistema forte pode crescer aprofundando as ações existentes, em vez de substituí-las a cada atualização.', 'OutBrick aplica a ideia em escala menor: primeiro uma ação clara, depois tabuleiros e capítulos mais expressivos.'],
    sections: {
      'start-with-a-verb': { title: 'Comece por uma ação concreta', paragraphs: ['A retrospectiva de 15 anos da Xbox Wire informa que Markus Persson começou Minecraft em 2009, inspirado por Infiniminer e Dungeon Keeper. A primeira versão Classic permitia cavar e construir livremente. Vieram os modos Creative e Survival; em 2010, chegaram fabricação, carrinhos de mina e sobrevivência multijogador.', 'A cronologia detalhada vem do próprio veículo editorial da Microsoft, uma fonte útil sobre a história, mas não uma auditoria independente. Ainda assim, o padrão de design é claro: o jogo começou com uma ação fácil de entender e depois criou novos motivos para usá-la.'] },
      'layers-that-reward-curiosity': { title: 'Camadas que recompensam a curiosidade', paragraphs: ['Uma camada funciona quando faz você enxergar a ação original de outro jeito. Fabricar muda o sentido de coletar. Sobreviver muda o significado de um lugar seguro. O multijogador muda o significado de uma construção quando outra pessoa pode vê-la.', 'Isso é diferente de simplesmente acrescentar ruído. Os capítulos, estrelas, widgets, amigos de bloquinhos e a [jornada por 167 vilas](/#journey) de OutBrick giram em torno da mesma ação: levar cada bloco à porta correspondente. Cada camada deve trazer um novo contexto ao movimento sem exigir que você aprenda outro jogo.'], bullets: ['Aprofundar uma ação que já existe', 'Deixar cada pessoa escolher até onde explorar o sistema', 'Mostrar o progresso sem transformar a descoberta em tarefa', 'Abrir espaço para histórias pessoais surgirem ao jogar'] },
      'the-value-of-a-personal-trace': { title: 'O valor de uma marca pessoal', paragraphs: ['O projeto FabO do MIT estudou maneiras de levar objetos dos jogos para o mundo físico. Em uma pesquisa exploratória com 47 objetos criados a partir de 33 jogos, os pesquisadores observaram que os participantes associavam às criações ideias como orgulho, expressão criativa pessoal, recursos, brincadeira prolongada e experiências compartilhadas.', 'Poucos jogos precisam de uma impressora 3D. A ideia mais ampla é que jogar ganha significado quando deixa algo que parece seu. Em OutBrick, um capítulo concluído, um mascote favorito ou a terceira estrela de um tabuleiro rejogado podem ser uma pequena marca pessoal: lembrança de um momento, não cobrança por mais um.'] },
      'grow-the-world-with-care': { title: 'Faça o mundo crescer com cuidado', paragraphs: ['O sucesso de Minecraft costuma ser descrito como infinito, mas seu começo traz uma lição mais prática: ofereça uma ação forte, deixe as pessoas criarem significado com ela e acrescente sistemas que valorizem esse significado.', 'OutBrick pode aplicar a lição nessa mesma escala. Um novo recurso deve fazer o tabuleiro parecer ainda mais OutBrick, em vez de uma segunda aplicação instalada dentro do jogo.'] },
    }, pullQuote: 'Uma camada funciona quando faz você enxergar a ação original de outro jeito.', faqs: [],
  },
  'tetris-simple-rules-infinite-variation': {
    title: 'Tetris: regras simples, possibilidades sem fim', dek: 'Uma reflexão sobre a restrição, o ritmo e a variedade que cabem em um conjunto minúsculo de regras.', imageAlt: 'Blocos geométricos coloridos de brinquedo caindo em direção a uma grade organizada', tags: ['Tetris', 'design de quebra-cabeças', 'criação de jogos', 'regras'],
    intro: 'Um grande sistema de regras não precisa ser enorme. Ele precisa gerar consequências suficientes para que a mesma ação tenha outro significado na jogada seguinte. Quarenta anos depois, Tetris continua sendo um exemplo claro de como restrição pode virar expressão.',
    keyTakeaways: ['A história da The Tetris Company acompanha o jogo desde um experimento no Electronika 60 em 1984 até sua presença em plataformas no mundo todo.', 'Regras simples ganham profundidade quando tempo, espaço e comprometimento mudam continuamente o significado da próxima jogada.', 'OutBrick trata cada tabuleiro como um pequeno sistema que permite planejar, se recuperar e encontrar um caminho próprio.'],
    sections: {
      'a-small-origin': { title: 'Uma origem modesta', paragraphs: ['A história oficial de Tetris situa a primeira versão de Alexey Pajitnov em 1984, em um Electronika 60, em Moscou. Depois, conta como Henk Rogers descobriu o jogo, como foram negociados os direitos para consoles portáteis e como a Nintendo decidiu incluir Tetris no Game Boy.', 'A história do detentor dos direitos mistura fatos com narrativa de marca; números exatos de vendas devem ser entendidos como dados divulgados pela empresa. Para a lição de design, a trajetória geral basta: uma ideia compacta pode viajar quando suas regras funcionam em novos contextos.'] },
      'constraint-creates-meaning': { title: 'A restrição cria significado', paragraphs: ['Uma forma que cai só se torna urgente porque o espaço do tabuleiro é limitado. A mesma peça pode ser uma oportunidade, um problema ou uma preparação, dependendo do que já está ali. Regras simples geram variedade quando decisões anteriores mudam o sentido da próxima.', 'Os blocos deslizantes de OutBrick funcionam assim. “Leve o bloco até a porta” é fácil de dizer. O interessante é que cada movimento muda os corredores abertos, os blocos que ficam presos e as soluções que continuam possíveis. A regra permanece pequena enquanto a situação muda.'] },
      'rhythm-over-noise': { title: 'Ritmo em vez de ruído', paragraphs: ['Quebra-cabeças marcantes costumam ter um ritmo que a pessoa aprende: observar, prever, decidir e resolver. Sistemas adicionais podem ser ótimos, mas devem apoiar esse ritmo, não interrompê-lo.', 'Por isso OutBrick usa o retorno tátil, o cartão de conclusão e os movimentos de vitória dos amigos como pontuação. O tabuleiro concentra o raciocínio. O restante do universo ajuda a dar ritmo à sensação de vencer.'], bullets: ['Uma regra que cabe em uma frase', 'Um estado que muda a cada decisão', 'Um retorno que confirma, em vez de apenas decorar', 'Variedade que nasce do contexto, não da confusão'] },
      'the-next-piece': { title: 'A próxima peça', paragraphs: ['Tetris continua vivo porque a próxima peça sempre cria uma nova pergunta. A forma de OutBrick é mais tranquila: em cada um dos 2.000 tabuleiros verificados pelo solucionador, o próximo desafio tem outro formato, outro ponto de bloqueio e a chance de perceber algo que antes passou despercebido. Chaves, fechaduras, blocos congelados, esteiras e caixas aparecem aos poucos e mostram a mesma regra por novos ângulos.', 'Ser simples não significa ser superficial. Significa que dá para perceber de onde vem a profundidade.'] },
    }, pullQuote: 'Ser simples não significa ser superficial. Significa que dá para perceber de onde vem a profundidade.', faqs: [],
  },
  'daily-rituals-that-dont-demand-you': {
    title: 'Rituais diários de jogo sem cobrança', dek: 'Um jogo diário pode trazer um ritmo agradável quando não transforma os dias em que você falta em fracasso.', imageAlt: 'Uma peça brilhante de quebra-cabeça diário sobre um pequeno calendário de brinquedo', tags: ['jogos diários', 'hábitos', 'Wordle', 'jogos para celular'],
    intro: 'O encanto de um jogo diário não está só no quebra-cabeça: o convite também importa. Uma boa rotina dá um toque especial ao dia sem transformar o dia anterior em uma dívida.',
    keyTakeaways: ['Uma pesquisa de 2024 do Pew mostra que, para muitos adolescentes, jogos são parte da diversão cotidiana e uma forma de conexão social.', 'O limite diário do Wordle e sua lista de palavras cuidadosamente escolhida mostram o valor de limites intencionais.', 'O bloco diário de OutBrick foi pensado como uma saudação, não como uma sequência que pune quem falta.'],
    sections: {
      'the-social-shape-of-play': { title: 'A dimensão social de jogar', paragraphs: ['O Pew Research Center informou que 85% dos adolescentes dos EUA entrevistados em 2023 jogavam videogames e 41% jogavam diariamente. Entre os que jogavam, 72% disseram que passar tempo com outras pessoas era um motivo para jogar, e 47% fizeram amizades online por meio dos jogos.', 'Esses números descrevem uma amostra de adolescentes dos EUA, não todas as pessoas nem todos os jogos. Ainda assim, mostram que até uma experiência “para um jogador” pode fazer parte de um ritmo social. Mesmo sozinho com o celular, a pessoa compara, recomenda, lembra e compartilha.'] },
      'why-a-limit-can-help': { title: 'Por que um limite pode ajudar', paragraphs: ['Uma reportagem sobre a criação do Wordle descreve algumas escolhas deliberadas: uma lista curta de palavras conhecidas, um quebra-cabeça por dia inspirado nos jornais e um formato de resultados que as pessoas passaram a compartilhar. Esses limites deram ao jogo uma dimensão social e fizeram de cada desafio um acontecimento para conversar, sem um acúmulo de fases antigas.', 'Um limite diário pode fazer o jogo parecer mais uma rotina do que uma aba que nunca se fecha. Mas um limite deve ser uma moldura, não uma cerca. Se você perder um dia, o jogo deve continuar contente em encontrar você de novo.'] },
      'the-outbrick-daily-brick': { title: 'O bloco diário de OutBrick', paragraphs: ['O bloco diário é o menor convite recorrente que fazemos. Na primeira fase concluída no dia, você recebe 100 moedas extras além da recompensa normal. Ele dá um pouco de luz matinal à tela inicial, mas não é o único motivo para abrir o aplicativo. A [jornada](/#journey) avança no seu ritmo e continua gerando fases depois dos 2.000 tabuleiros. Um dia de folga não apaga o valor dos dias ao redor.', 'Essa escolha se conecta à compatibilidade com a vida. Pesquisas sobre jogos e bem-estar sugerem que contexto e valor percebido importam mais do que reduzir o tempo de jogo a uma única pontuação. Um recurso diário deve marcar um momento, não medir o valor de alguém.'] },
      'ritual-without-obligation': { title: 'Um ritual sem obrigação', paragraphs: ['A diferença entre ritual e obrigação é saber se você continua no controle. Poder escolher o horário, a duração e o significado. O design pode oferecer um pequeno ponto de luz sem exigir uma troca.', 'Queremos que OutBrick diga: “Se quiser, tem um tabuleiro aqui”. Isso basta como motivo para voltar. Para conhecer o outro lado da questão, leia [como os jogos viram hábitos](/blog/how-games-become-habits).'] },
    }, pullQuote: 'Uma boa rotina dá um toque especial ao dia sem transformar o dia anterior em uma dívida.', faqs: [],
  },
  'color-shape-accessibility': {
    title: 'Por que as pistas de um quebra-cabeça não devem depender só da cor', dek: 'Combine cor com forma, texto e outros sinais para criar tabuleiros mais fáceis de interpretar.', imageAlt: 'Blocos de quebra-cabeça brilhantes, cada um com uma forma gravada além da própria cor', tags: ['acessibilidade', 'visão de cores', 'design inclusivo', 'quebra-cabeças'],
    intro: 'A cor dá vida ao visual, mas não é confiável como único meio de transmitir significado. Um quebra-cabeça acolhedor pode usar cor para criar padrões bonitos e também reforçar as informações com formas, símbolos, espaçamento e movimento.',
    keyTakeaways: ['A diretriz 1.4.1 da WCAG diz que a cor não deve ser o único meio visual de transmitir informação.', 'As orientações de acessibilidade para jogos da Microsoft recomendam combinar cor com símbolos ou padrões e oferecer opções ajustáveis.', 'Os símbolos de acessibilidade de cores do OutBrick vêm ativados por padrão; tonalidade, forma e pinos ajudam a identificar cada bloco.'],
    sections: {
      'color-is-a-great-accent': { title: 'A cor é um ótimo destaque, não uma barreira', paragraphs: ['A orientação do W3C para o critério de sucesso 1.4.1 é direta: não use a cor como único meio visual de distinguir informações. O motivo é prático. Cada pessoa percebe as cores de um jeito, e uma informação codificada apenas pela tonalidade pode desaparecer.', 'Um produto não precisa ficar cinza para atender a essa orientação. A cor pode continuar definindo hierarquia, clima e destaque, enquanto outro sinal também comunica a regra que a pessoa não pode deixar passar.'] },
      'symbols-make-the-board-clearer': { title: 'Símbolos deixam o tabuleiro mais claro para todos', paragraphs: ['A visão geral de acessibilidade para jogos da Microsoft recomenda transmitir informações de mais de uma forma, como imagem e texto ou símbolo e cor. Também propõe verificar se o jogo continua jogável sem som, em uma tela em preto e branco e depois de uma pausa longa.', 'Essas perguntas são úteis para qualquer quebra-cabeça, não só para uma lista de acessibilidade. Quem confirma uma combinação pela forma não está fazendo trabalho extra: ganhou um segundo caminho para chegar à mesma compreensão.'] },
      'how-outbrick-does-it': { title: 'Como OutBrick faz isso', paragraphs: ['OutBrick comunica a identidade de cada bloco por três caminhos ao mesmo tempo: tonalidade, formato e pinos. O modo de acessibilidade para cores vem ativado por padrão e coloca um glifo diferente em cada bloco e porta, para que a cor nunca seja a única pista de combinação. A linguagem visual continua divertida porque esses sinais fazem parte do mundo dos brinquedos: marcas pequenas que os olhos e a memória reconhecem.', 'A mesma ideia vai além do tabuleiro. Cada bloco também é um elemento do VoiceOver, que anuncia cor, forma e posição; o texto ampliado se aplica em todo o jogo e a opção Reduzir Movimento é respeitada. Ainda precisamos testar com pessoas com diferentes necessidades de acesso: documentação não substitui ouvir quem joga. A [página de acessibilidade](/accessibility) explica o que está disponível hoje.'] },
      'accessibility-is-quality': { title: 'Acessibilidade é sinal de qualidade', paragraphs: ['O design inclusivo melhora a experiência básica porque leva a equipe a perguntar se o jogo está comunicando ou apenas decorando. Essa pergunta conduz a contraste mais forte, respostas mais claras, escolhas melhores e menos situações em que alguém precisa adivinhar o que a tela quer dizer.', 'Em um quebra-cabeça, clareza não é concessão. É parte do desafio. Se as regras não podem ser percebidas com confiança, a pessoa está resolvendo a interface em vez do tabuleiro.'] },
    }, pullQuote: 'Se as regras não podem ser percebidas com confiança, a pessoa está resolvendo a interface em vez do tabuleiro.', faqs: [],
  },
  'when-to-play-and-when-to-pause': {
    title: 'Quando jogar e quando fazer uma pausa', dek: 'Um guia franco para encaixar os jogos no sono, na atenção e no restante do seu dia.', imageAlt: 'Um pequeno tabuleiro de quebra-cabeça ao lado de um relógio iluminado e de um livro fechado', tags: ['jogo saudável', 'sono', 'hábitos de jogo', 'bem-estar'],
    intro: 'Jogar pode ser uma pausa agradável, um desafio ou um jeito de se conectar. Também pode atrapalhar o sono ou ocupar um espaço que você preferia usar de outra forma. A resposta honesta não é que todo jogo ajuda nem que todo jogo faz mal: contexto e escolha importam.',
    keyTakeaways: ['Pesquisas sobre sono sugerem cautela com jogos estimulantes perto da hora de dormir, embora os estudos tenham condições específicas.', 'Jogo problemático é uma condição clínica definida por perda de controle e prejuízo significativo, não um sinônimo de jogar por muito tempo uma vez.', 'OutBrick foi criado para facilitar pausas, sem sequências diárias, cronômetros ou recompensas que expiram.'],
    sections: {
      'sleep-is-a-real-design-constraint': { title: 'O sono é uma restrição real de design', paragraphs: ['Em um estudo controlado com adolescentes, jogar por cinquenta minutos antes de dormir atrasou o início do sono em comparação com assistir a um DVD. Outro experimento, com sessões prolongadas de jogos diferentes, observou mudanças na eficiência do sono e na lembrança de palavras na manhã seguinte. Esses resultados dependem das condições estudadas, mas apoiam um limite razoável: jogos intensos ou estimulantes antes de dormir talvez não sejam ideais para todo mundo.', 'Uma resposta honesta é facilitar a hora de parar, não fingir que uma partida até tarde nunca tem custo e oferecer informação suficiente para cada pessoa decidir. Chamar todos os jogos de prejudiciais não ajuda.'] },
      'problematic-is-not-the-same-as-ordinary': { title: 'Jogo problemático não é o mesmo que jogo comum', paragraphs: ['Uma revisão sistemática e meta-análise encontrou uma associação entre jogo problemático e menor duração do sono, com grande variação entre os estudos. Essa variação importa: os dados tratam de um padrão associado a prejuízos, não de todas as pessoas que jogam por diversão.', 'A Organização Mundial da Saúde define transtorno de jogos eletrônicos por controle prejudicado, prioridade crescente dada ao jogo e continuidade apesar de consequências negativas, com gravidade suficiente para causar prejuízo significativo — geralmente evidente por pelo menos doze meses. É uma definição clínica, não um sinônimo de “joguei mais do que planejava uma vez”.'] },
      'our-pause-friendly-defaults': { title: 'As escolhas de OutBrick que acolhem pausas', paragraphs: ['OutBrick não tem sequência diária para proteger nem algo que expire discretamente quando você se afasta. Terminar um tabuleiro e parar ali é a ação mais simples do jogo: não custa nada, e o cartão de conclusão dá um encerramento natural em vez de empurrar você para a próxima partida. Você pode perder o bloco diário sem que amanhã vire uma punição, e cada tabuleiro começa com um desfazer grátis para que uma jogada ruim possa ensinar, em vez de virar um erro pelo qual pagar.', 'Há um custo que merece ser claro: uma tentativa que acaba sem solução — inclusive abandonar um tabuleiro depois de fazer uma jogada — consome uma vida. Você tem cinco vidas, ou oito com o Brick Pass, e uma volta automaticamente a cada trinta minutos. Essa regra do gênero foi mantida porque, sem ela, o limite de jogadas não teria sentido. Nada mais consome vidas: jogar, concluir, desfazer ou abrir uma fase e mudar de ideia não custa vida. A lista completa está na página inicial, em [o que custa](/#fair). A ideia é que “mais um tabuleiro” seja uma escolha, não uma armadilha escondida na interface.'], bullets: ['Parar depois de concluir sem perder seu lugar', 'Um desfazer grátis em cada tabuleiro, sempre', 'As vidas voltam sozinhas, uma a cada meia hora', 'Configurações que respeitam o contexto de cada pessoa'] },
      'a-useful-question': { title: 'Uma pergunta útil', paragraphs: ['Em vez de perguntar se determinada quantidade de minutos é sempre boa ou ruim, pergunte: “Esta partida combina com o restante da minha vida hoje?”. Se a resposta for não — por cansaço, sono perdido ou sensação de não conseguir parar — uma escolha gentil é fazer uma pausa e mudar as condições ao redor do jogo.', 'OutBrick é um jogo, não um profissional de saúde. Se jogar causar sofrimento significativo ou atrapalhar o cotidiano, converse com um profissional qualificado. Um jogo bem pensado deve deixar espaço para essa frase.'] },
    }, pullQuote: 'Um jogo bem pensado deve deixar espaço para a pessoa fazer uma pausa.', faqs: [{ question: 'OutBrick recomenda um limite diário específico?', answer: 'Não. Cada pessoa e contexto são diferentes. Recomendamos prestar atenção ao sono, às responsabilidades e à sensação de manter o controle sobre o próprio jogo.' }, { question: 'Transtorno de jogos eletrônicos significa jogar todos os dias?', answer: 'Não. A definição da OMS considera perda de controle, prioridade dada ao jogo em detrimento de outras atividades, continuidade apesar de consequências negativas e prejuízo significativo no funcionamento ao longo do tempo.' }],
  },
  'kinder-difficulty-curve': {
    title: 'Uma curva de dificuldade mais acolhedora', dek: 'Desafios ficam mais agradáveis quando o jogo ensina, oferece apoio e deixa tempo para pensar.', imageAlt: 'Uma trilha de blocos de brinquedo que sobe gradualmente até uma pequena bandeira de conclusão', tags: ['design de jogos', 'dificuldade', 'acessibilidade', 'quebra-cabeças'],
    intro: 'Uma boa curva de dificuldade convida, em vez de testar se você merece estar ali. O desafio deve aumentar com o aprendizado e deixar espaço para diferenças de experiência, habilidade e confiança.',
    keyTakeaways: ['O modelo GameFlow relaciona desafio equilibrado a concentração, competência, controle, objetivos claros, retorno e interação.', 'Uma curva única não serve para todos: experiência, acesso e familiaridade mudam como o mesmo desafio é sentido.', 'OutBrick verifica os tabuleiros antes da publicação, evita cronômetros e oferece formas gratuitas de se recuperar de um bloqueio.'],
    sections: {
      'challenge-and-skill-need-each-other': { title: 'Desafio e habilidade precisam um do outro', paragraphs: ['Uma revisão de sistemas de reabilitação com jogos usa o modelo GameFlow para pensar em concentração, desafio, competência, controle, objetivos claros, retorno, imersão e interação social. Ela descreve a dificuldade adaptativa como uma forma de evitar que uma tarefa fique tão fácil a ponto de entediar ou tão difícil que provoque ansiedade.', 'A ideia também vale fora da reabilitação. Ninguém vive uma “dificuldade de nível 20” abstrata. A pessoa sente a relação entre o que o tabuleiro pede e o que a interface ensinou a perceber.'] },
      'one-curve-does-not-fit-everyone': { title: 'Uma única curva não serve para todos', paragraphs: ['Um estudo transversal de 2025 sobre uma tarefa de reabilitação com Kinect observou fluxo geral menor entre participantes mais velhos do que entre os mais jovens, com a maior diferença na sensação de controle. A tarefa e a amostra eram específicas; o estudo não justifica suposições sobre todas as pessoas com base na idade.', 'Ainda assim, reforça um princípio mais amplo: familiaridade, capacidade motora, confiança, velocidade de processamento e necessidades de acesso podem mudar a sensação de um mesmo desafio. Uma boa curva acolhe essas diferenças em vez de tratá-las como falhas da pessoa.'] },
      'our-tools-for-a-kinder-curve': { title: 'Ferramentas para uma curva mais acolhedora', paragraphs: ['Um solucionador completou os 2.000 tabuleiros de OutBrick antes da publicação: o jogo pode pedir planejamento sem pedir algo impossível por acidente. O limite de jogadas de cada tabuleiro é verificado em relação ao caminho que o solucionador realmente encontrou, sem margem menor que a solução demonstrada. Quando uma posição trava, o painel de recuperação informa isso e oferece uma saída; o desfazer é grátis e independente do estoque, porque um tabuleiro travado é uma situação do jogo, não culpa de quem joga. A pressão vem do limite de jogadas, nunca de um relógio: o cronômetro Rush opcional foi removido, e não há contagem regressiva no jogo.', 'Isso não elimina o desafio. Separa o atrito útil do acidental para que a pessoa use a atenção no quebra-cabeça, não para se defender da interface.'], bullets: ['Soluções verificadas antes da publicação', 'Um desfazer que ensina, em vez de repreender', 'Uma saída grátis quando a posição realmente trava', 'Pressão de um limite de jogadas, nunca de um relógio'] },
      'difficulty-as-an-invitation': { title: 'Dificuldade como convite', paragraphs: ['A dificuldade deve convidar a tentar, não provar que a pessoa pertence ao jogo. Um próximo passo bem calibrado parece possível, mesmo que exija atenção. Quando a pessoa erra, o jogo deve ajudá-la a entender o que aconteceu e tentar de novo.', 'É por isso que OutBrick apresenta as regras aos poucos, deixa as fases resolvíveis e oferece espaço para pensar sem cronômetro. Queremos que cada vitória venha da compreensão que você construiu, não da pressa ou de uma punição por experimentar.'] },
    }, pullQuote: 'A dificuldade deve convidar a tentar, não provar que a pessoa pertence ao jogo.', faqs: [],
  },
};
