import type { ExtraGuides } from '../../i18n/blog';
import { appStoreUrl } from '../../app-store-url.ts';

/** Journal batch 7 in Brazilian Portuguese. */
export const ptBR7: ExtraGuides = {
  'outbrick-iphone-duo-player-ideas': {
    title: 'OutBrick no iPhone Duo: o que você gostaria de jogar?',
    dek: 'Você gostaria de uma versão do OutBrick para o iPhone Duo? Conheça ideias para as telas externa e interna e conte o que faria a experiência valer a pena.',
    imageAlt: 'Peças coloridas do OutBrick e dois personagens de tijolo ao redor de um celular sobre uma grade azul-marinho',
    tags: ['design de jogos', 'opinião dos jogadores', 'iPhone', 'acessibilidade', 'quebra-cabeças'],
    intro: 'O anúncio do iPhone Duo levanta uma pergunta interessante para um jogo pequeno de quebra-cabeça: o que deveria mudar quando o celular se abre? Um tabuleiro maior parece a resposta óbvia, até você imaginar jogar no trem, mostrar uma posição difícil a um amigo ou fechar o aparelho para atender a porta. Queremos saber se você gostaria de uma adaptação do OutBrick e o que esperaria de cada tela. Este é um convite para conversar sobre possibilidades. Não anuncia compatibilidade, um projeto de desenvolvimento nem uma data de lançamento. Sua resposta pode ser animada, cautelosa ou simplesmente dizer que a experiência atual já basta.',
    keyTakeaways: [
      'O iPhone Duo foi anunciado e, em 30 de setembro de 2026, ainda não estava disponível ao público. A compatibilidade com o OutBrick não foi verificada.',
      'As ideias são pontos de partida para uma conversa: um tabuleiro compacto por fora, mais espaço por dentro e uma transição cuidadosa ao dobrar o aparelho.',
      'Conte em que situação gostaria de jogar, suas prioridades para cada tela e o que deveria continuar igual pela página de contato existente.'
    ],
    sections: {
      'announcement-and-open-question': { title: 'Um aparelho confirmado e uma pergunta em aberto sobre o jogo', paragraphs: [
        'A Apple anunciou o iPhone Duo em 9 de setembro de 2026, com tela externa de 5,4 polegadas e tela interna de 7,6 polegadas. As pré-vendas anunciadas começam em 16 de outubro, com disponibilidade inicial em 23 de outubro. Essas datas ainda são futuras quando publicamos este texto, em 30 de setembro. O anúncio dá contexto à conversa; não confirma que um aplicativo específico tenha sido adaptado ou testado.',
        'Para conhecer as informações confirmadas do aparelho e do lançamento, leia [o anúncio do iPhone Duo pela Apple](https://www.apple.com/newsroom/2026/09/apple-unveils-iphone-duo/). Nossa pergunta é mais específica que as características técnicas: abrir o celular ajudaria você a ler, mover peças ou retomar um quebra-cabeça de tijolos deslizantes? Mais espaço só é útil quando atende a uma atividade real.',
        'No OutBrick, a regra básica é deslizar uma peça até algo pará-la e conduzi-la à porta correspondente. O desafio está nas rotas e nos pontos de parada. Uma tela diferente poderia deixar essas relações mais claras sem mudar o quebra-cabeça. Por outro lado, talvez o layout atual seja mais confortável do que painéis extras.',
        'Nosso artigo sobre [jogar em diferentes dispositivos](/blog/playing-across-devices) explora como o mesmo jogo ocupa momentos distintos do dia. Aqui, queremos ouvir sobre esses momentos antes de tratar um novo aparelho como motivo para acrescentar recursos. Nenhuma ideia nesta página deve ser entendida como funcionalidade disponível ou compromisso de desenvolvimento.'
      ] },
      'compact-outside-play': { title: 'Possibilidade 1: um tabuleiro compacto na tela externa', paragraphs: [
        'Imagine uma espera rápida em que você queira conferir um tabuleiro conhecido sem abrir o celular. Uma experiência possível na tela externa poderia priorizar o tabuleiro, com controles grandes e previsíveis e poucas informações ao redor. É uma proposta para conversar, não uma prévia do produto. Você usaria esse modo ou normalmente abriria o aparelho antes de jogar?',
        'A diferença importante é entre um tabuleiro menor e uma tarefa mais simples. Reduzir todas as telas pode ficar desconfortável. Uma visualização intencionalmente limitada talvez seja mais clara, mas também pode esconder algo de que você depende. Conte se priorizaria o tabuleiro inteiro, o alcance dos controles, símbolos fáceis de ler ou um caminho rápido de volta à posição atual.',
        'O uso com uma mão também varia. Um layout que funciona para quem segura uma bolsa pode não servir para alguém que usa suporte ou tecnologia assistiva. Se o problema é alcançar a porta distante, explique isso. Se é distinguir o símbolo de uma peça, conte essa dificuldade. As situações levam a perguntas de design diferentes, embora ambas possam ser resumidas como “quero um botão maior”.',
        'Ryan et al. (2006) relacionaram competência e autonomia percebidas ao prazer em quatro estudos sobre jogos. Eles não estudaram celulares dobráveis nem o OutBrick. Usamos esse trabalho como motivo para perguntar se um layout ajudaria você a entender suas ações e escolher como jogar, em vez de presumir que uma tela maior seja automaticamente mais divertida.'
      ] },
      'roomier-inside-view': { title: 'Possibilidade 2: mais espaço para analisar uma posição', paragraphs: [
        'Ao abrir o aparelho, talvez o mesmo tabuleiro pudesse respirar mais. Poderíamos conversar sobre aumentar o tabuleiro, espaçar melhor os controles ou acrescentar uma área discreta de planejamento ao lado. Ela poderia explicar uma regra ou guardar uma observação sua, sem revelar uma jogada. Nenhuma dessas possibilidades descreve uma funcionalidade anunciada.',
        'Imagine uma situação concreta: uma peça azul precisa servir de ponto de parada para que uma vermelha alcance a própria porta. Uma visualização maior ajudaria você a perceber essa dependência? Informações ao lado do tabuleiro ajudariam ou competiriam com a rota que você está tentando entender? Se só pudéssemos fazer uma melhoria, qual você escolheria?',
        'Pereira et al. (2019) propõem uma estrutura de design de jogos centrada na participação. É uma pesquisa de design, não um teste que prove que o layout sugerido funciona. Ela nos convida a pensar além da interface pronta: que papel você gostaria de ter ao jogar, observar ou conversar sobre um tabuleiro? Sua resposta não precisa ser uma especificação.',
        'A tela interna também poderia facilitar compartilhar o jogo com outra pessoa. Isso traz uma pergunta cotidiana: você gostaria de manter o tabuleiro no centro, com os controles perto de quem move as peças? Ou costuma jogar só e prefere tudo ao alcance da mão? Nossa [abordagem para criar jogos para a vida real](/blog/designing-for-real-life-play) começa por essas circunstâncias.'
      ] },
      'folding-and-continuity': { title: 'Possibilidade 3: uma transição que respeite seu progresso', paragraphs: [
        'Imagine dobrar o celular enquanto pensa em uma rota. Uma possível adaptação poderia preservar sua posição, evitar tratar a dobra como uma jogada e facilitar a retomada. Talvez você prefira uma pausa intencional; talvez queira continuar na mesma hora. São perguntas sobre o comportamento desejado, não promessas de salvamento automático ou de uma transição testada.',
        'O que ajudaria você a reconhecer a posição ao abrir o aparelho de novo? Algumas pessoas talvez queiram manter a seleção atual. Outras preferem nenhuma seleção, para evitar que o primeiro toque faça algo sem querer. Um lembrete visual breve pode ajudar uma pessoa e distrair outra. Descrever o momento da interrupção é mais útil do que votar em “perfeito e contínuo” sem contexto.',
        'Acessibilidade precisa fazer parte da conversa desde o começo. Se você usa VoiceOver, texto maior, movimento reduzido ou símbolos para cores, conte quais informações precisam continuar claras durante uma mudança de layout. Nossa [página de acessibilidade](/accessibility) descreve os recursos atuais; ela não confirma como o aparelho se comportaria no iPhone Duo. Uma declaração geral de acessibilidade não substitui testes em um novo dispositivo.',
        'Khaled e Vasalou (2014) estudam participação no design de jogos sérios. O OutBrick não é uma intervenção de jogo sério, então não aplicamos os resultados deles ao nosso caso. A discussão traz um cuidado útil para este convite: só vale pedir contribuições quando elas podem questionar a ideia inicial de quem projeta. “Prefiro que continue simples” também é uma opinião importante.'
      ] },
      'feedback-that-can-shape-a-question': { title: 'Quatro perguntas para você responder', paragraphs: [
        'Sanders e Stappers (2008) descrevem a cocriação como uma relação em transformação entre designers e pessoas que usam o que eles fazem. Este artigo é uma primeira conversa modesta, não um estudo formal de codesign. Queremos conhecer sua experiência; uma mensagem de contato não torna você responsável por uma decisão futura sobre o produto.',
        'Primeiro: você teria interesse em uma adaptação para iPhone Duo? Por quê? Segundo: o que gostaria de fazer na tela externa que hoje é inconveniente? Terceiro: o que a tela interna deveria priorizar — um tabuleiro maior, controles mais claros, informações opcionais para planejar ou outra coisa? Quarto: o que deveria acontecer ao dobrar ou abrir o aparelho durante uma partida?',
        'Envie sua opinião pela [página de contato](/contact) que já existe. Uma descrição curta basta: “Jogo sentado com o celular no suporte e prefiro símbolos maiores a mais informações”. Você não precisa informar dados pessoais de saúde, comprar o aparelho ou desenhar uma tela. Identifique sugestões como ideias; se estiver relatando um erro real, informe separadamente a versão do app e o aparelho.',
        'Você também pode explicar o que abriria mão para ter sua primeira opção. Se um tabuleiro mais espaçoso significasse menos controles ao redor, tudo bem? Se mudar o layout pudesse atrapalhar sua orientação, você preferiria uma tela estável? Entender essas trocas ajuda a interpretar uma preferência; uma lista longa de recursos, sem uma situação concreta, é mais difícil de avaliar.',
        `Para conhecer mudanças já lançadas, veja [Novidades](/whats-new). Se quiser entender o jogo atual antes de sugerir algo, experimente um [tabuleiro no navegador](/play) ou [baixe o OutBrick na App Store](${appStoreUrl('journal-device')}). O navegador ensina a regra de movimentação; ele não demonstra o comportamento nativo no iPhone Duo. A pergunta continua sendo sua: o que faria valer a pena abrir a tela?`
      ] },
      'official-device-source': { title: 'Fonte oficial sobre o aparelho', paragraphs: [
        'Apple. (2026, 9 de setembro). Apple unveils iPhone Duo. Apple Newsroom. [Anúncio oficial e detalhes de disponibilidade](https://www.apple.com/newsroom/2026/09/apple-unveils-iphone-duo/).',
        'As referências acadêmicas abaixo ajudam a contextualizar participação e preferências dos jogadores. Elas não avaliaram o iPhone Duo nem o OutBrick.'
      ] }
    },
    pullQuote: 'Mais espaço na tela só é útil quando atende a uma atividade real.',
    faqs: [
      { question: 'O OutBrick está anunciando suporte ao iPhone Duo?', answer: 'Não. Este artigo pergunta se uma adaptação interessaria aos jogadores e o que esperariam de cada tela. Não confirma compatibilidade, recursos nem data de lançamento.' },
      { question: 'O iPhone Duo já está disponível?', answer: 'Na data deste artigo, 30 de setembro de 2026, a Apple havia anunciado pré-vendas para 16 de outubro e disponibilidade inicial em 23 de outubro. Consulte as informações atuais da Apple para mudanças posteriores e disponibilidade na sua região.' },
      { question: 'Onde posso enviar ideias para as telas?', answer: 'Use a [página de contato do OutBrick](/contact). Conte quando você joga, que melhoria gostaria de ver e o que deveria continuar familiar; uma mensagem curta basta.' },
      { question: 'Toda sugestão vai virar um recurso?', answer: 'Não há compromisso de criar recursos neste artigo. As sugestões ajudam a entender prioridades e as trocas que os jogadores aceitariam.' }
    ]
  },
  'iphone-puzzle-game-time-limits': {
    title: 'Como limitar o tempo de jogos no iPhone com iOS 27',
    dek: 'Use o Tempo de Uso no iOS 27 para definir limites para Jogos e horários de acesso, confira quais apps entram na conta e planeje pausas.',
    imageAlt: 'Peças coloridas do OutBrick e dois personagens de tijolo ao redor de um celular sobre uma grade azul-marinho',
    tags: ['tempo de tela', 'jogo equilibrado', 'iPhone', 'quebra-cabeças', 'hábitos de jogo'],
    intro: 'Um quebra-cabeça termina com um convite fácil de aceitar: jogar mais um tabuleiro. Se você quer que esse convite caiba entre o jantar, o trabalho ou uma noite com outras pessoas, um ajuste do iPhone pode apoiar uma decisão tomada com antecedência. No iOS 27, o Tempo de Uso usa Limites de Tempo e Programações do Tempo de Uso. Este guia explica os controles atuais, diferencia um limite da categoria de um limite para um jogo e sugere como conferir o resultado. Não existe aqui uma recomendação médica de minutos ideais. O objetivo é simples: fazer o celular respeitar o limite que você pretendia estabelecer.',
    keyTakeaways: [
      'No iOS 27, use Ajustes → Tempo de Uso → Limites de Tempo para definir um orçamento para Jogos; Programação do Tempo de Uso controla quando as categorias ficam disponíveis.',
      'Confira quais apps pertencem à categoria e se Compartilhar entre Dispositivos está ativado. O limite da categoria não é um limite separado para cada jogo.',
      'Escolha um limite ligado a um compromisso real, teste e reveja o ajuste. A pesquisa não define uma duração ideal de quebra-cabeça para todas as pessoas.'
    ],
    sections: {
      'start-with-the-boundary': { title: 'Decida o que o limite deve proteger', paragraphs: [
        'Antes de mexer no controle, complete esta frase: “Quero parar de jogar quando…”. Talvez quando o ônibus chegar, antes de preparar o jantar ou ao terminar uma pausa planejada. São situações diferentes. Um limite diário para Jogos controla o uso acumulado; uma programação define em que parte do dia esse uso é permitido. O ritual de concluir um tabuleiro pode ajudar, mas não garante um horário previsível para terminar.',
        'O OutBrick limita movimentos, não usa contagem regressiva nos tabuleiros. Isso dá tempo para pensar, mas não define a duração da sessão. O controle de tempo do sistema operacional tem outra finalidade que as regras do quebra-cabeça. A recarga de vidas também é uma mecânica do jogo, não uma avaliação de quanto você deveria jogar.',
        'Roffarello e De Russis (2023) revisaram e fizeram uma metanálise de ferramentas digitais de autocontrole, incluindo cronômetros e bloqueios. O trabalho destaca objetivos, estratégias e dificuldades de avaliação diferentes. Ele não valida o iOS 27 nem um limite para o OutBrick. A lição prática é definir o comportamento que você quer mudar antes de escolher a ferramenta.',
        'Se sua preocupação é esquecer um compromisso, programe o período relevante. Se você passa mais tempo em jogos do que gostaria, examine o limite da categoria. Se simplesmente sente que chegou a hora de sair, nosso guia [quando jogar e quando fazer uma pausa](/blog/when-to-play-and-when-to-pause) propõe perguntas que a tela de ajustes não responde.'
      ] },
      'set-a-games-allowance': { title: 'Defina um limite para Jogos nos menus do iOS 27', paragraphs: [
        'Abra Ajustes e depois Tempo de Uso. Se o relatório de atividade estiver desativado, abra Limites de Tempo e ative Atividade em Apps e Sites. Volte a Limites de Tempo, selecione Jogos e ajuste o período pelo controle deslizante ou pelos botões de mais e menos. Este caminho usa os nomes atuais do iOS 27, não a opção Limites de Apps encontrada em guias antigos.',
        'Confira quais apps pertencem à categoria em Gerenciar Categorias. Selecione a categoria para ver o uso médio e depois um app para consultar seus dados. Para incluir Jogos, use Gerenciar Categorias e o controle de adição. Pense em um orçamento compartilhado: o tempo em qualquer jogo incluído conta para o limite da categoria. Não presuma que cada um de três jogos receba o total completo.',
        'O guia da Apple informa que o uso pode atingir o limite da categoria ou o total diário. Confira os dois controles se um jogo ficar indisponível antes do esperado. Segundo a Apple, um site associado também pode compartilhar o limite do app; isso não determina como cada jogo no navegador ou este site será classificado. Confira a categoria e o relatório reais em vez de adivinhar.',
        'Para ver os controles e imagens atuais, consulte [o guia da Apple sobre Programações e Limites de Tempo do Tempo de Uso](https://support.apple.com/en-gb/guide/iphone/iphb0c7313c9/ios). Este artigo resume o caminho do iOS 27 conferido em 30 de setembro de 2026. Versões antigas, idioma configurado ou um aparelho administrado pela família podem mostrar outras telas; siga a orientação da Apple correspondente se as opções forem diferentes.',
        'Se quiser limitar apenas o OutBrick, não trate silenciosamente um limite amplo para Jogos como controle de um único app. Confira os apps listados em Gerenciar Categorias e consulte a orientação atual da Apple se precisar de algo mais específico. Estas etapas definem um limite de categoria, não um limite separado verificado para cada app. O importante é saber o que o ajuste realmente contabiliza.'
      ] },
      'schedule-and-shared-devices': { title: 'Adicione uma programação e confira os dispositivos', paragraphs: [
        'Para estabelecer um limite recorrente, abra Ajustes → Tempo de Uso → Programação do Tempo de Uso e ative a programação. Inclua os dias necessários. Edite o nome e os horários de uma Janela de Tempo e escolha quais categorias dos Limites de Tempo ficam disponíveis nesse período. Assim, você pode ter uma configuração para dias úteis e outra para o fim de semana.',
        'Em Limites de Tempo, a opção Ajustar à Programação do Tempo de Uso associa limites às janelas programadas. Confira qual janela está selecionada antes de ajustar um valor: um número adequado para uma noite talvez não sirva para uma pausa curta. Apps Sempre Permitidos são uma configuração separada; confira-os antes de esperar que a programação bloqueie todos os apps.',
        'Depois, abra Ajustes → Tempo de Uso → Gerenciar Tempo de Uso → Compartilhar entre Dispositivos. A Apple informa que, quando esse recurso está ativo, ajustes e relatórios são combinados entre iPhone, iPad e Mac conectados à mesma Conta Apple. Se pretendia criar um limite só para o celular, entenda essa diferença antes de ativá-lo. A sincronização do progresso do jogo pelo iCloud não determina como o Tempo de Uso calcula o tempo.',
        'A Apple informa que os recursos mais recentes do Tempo de Uso exigem a geração atual dos sistemas operacionais nos dispositivos relevantes, inclusive os de um grupo de Compartilhamento Familiar. O anúncio de 14 de setembro apresenta Limites de Tempo por categoria e controles familiares redesenhados. Para uma criança, use os ajustes da conta infantil administrada pela família e as orientações familiares atuais da Apple, em vez de alterar apenas os controles de uso do adulto responsável.',
        'Biedermann et al. (2021) revisaram 28 intervenções digitais de autocontrole. Os efeitos variaram; intervenções que só aumentavam a consciência do uso costumavam ser fracas, e a confiança na literatura era limitada por estudos curtos e amostras pequenas. Isso não é motivo para impor uma regra doméstica mais rígida. É um motivo para verificar se o lembrete, a programação ou a restrição escolhida realmente cumpre a função desejada.'
      ] },
      'test-with-a-real-session': { title: 'Teste o limite durante uma sessão comum', paragraphs: [
        'Escolha uma sessão normal em que nada importante dependa do ajuste. Confirme se o quebra-cabeça desejado aparece na categoria. Veja se outros jogos já consumiram parte do limite e se outro dispositivo contribui para o total. Então observe o que acontece ao atingir o limite. Se for fácil estender o acesso, decida se esse comportamento serve para sua situação.',
        'Um bom teste inclui a saída. Você sabe deixar um tabuleiro sem tentar encaixar mais uma conclusão? Consegue parar depois de perceber a próxima dependência e voltar mais tarde? Não é preciso terminar o quebra-cabeça para que a pausa valha a pena. Escolher com antecedência como parar pode ser mais concreto do que esperar que você simplesmente se sinta satisfeito.',
        'Parry et al. (2021) analisaram diferenças entre o uso de mídia digital registrado e o relatado pelas pessoas. A revisão constatou que a lembrança muitas vezes divergia dos registros. Isso apoia conferir o relatório em vez de depender apenas de “pareceu que foram dez minutos”. O registro, porém, não descreve a qualidade da sessão nem determina se o limite escolhido é adequado.',
        'Para consultar o resumo atual, abra Tempo de Uso → Média Diária e veja Dia ou Semana. Compare dias com rotinas parecidas, em vez de tratar uma tarde atípica como veredito. Acrescente contexto: “Parei antes do jantar, mas o total de Jogos também inclui um jogo em família”. Isso explica mais que o número sozinho.',
        'Se algum controle funcionar de um jeito inesperado, confira primeiro as categorias, o total diário, a programação selecionada e os dispositivos compartilhados. Para problemas nos controles do sistema, procure o suporte da Apple. O [suporte do OutBrick](/support) é o canal certo para questões sobre o tabuleiro ou como sair do jogo; informe a versão e os passos para reproduzir o problema.'
      ] },
      'review-without-a-perfect-number': { title: 'Reavalie o limite sem buscar um número perfeito', paragraphs: [
        'Depois de alguns dias, pergunte se o ajuste protegeu o compromisso que você escolheu. Se o limite bloqueou um uso necessário, reveja a configuração. Se não mudou o comportamento, pense se outra ferramenta seria mais adequada ou se o objetivo precisa ficar mais claro. Um ajuste útil é aquele que serve à sua rotina, não o que produz o menor número possível.',
        'Radtke et al. (2022) revisaram estudos sobre duração de uso e bem-estar. Os resultados não sustentam um único limite de tempo aplicável a todas as pessoas e atividades. O contexto, o motivo do uso e o que ele substitui importam. Por isso, este artigo não recomenda um número universal de minutos para jogar quebra-cabeças. Nosso artigo sobre [o que mostram os experimentos de desintoxicação digital](/blog/does-digital-detox-work) aprofunda essa diferença.',
        'Mantenha a conversa simples: que momento você queria proteger, o ajuste ajudou e o que mudaria na próxima semana? Para outras ideias sobre pausas, consulte [quando jogar e quando fazer uma pausa](/blog/when-to-play-and-when-to-pause).',
        `Se estiver experimentando o OutBrick, o [tabuleiro no navegador](/play) apresenta a regra de deslizar e a [página de suporte](/support) ajuda com dúvidas sobre o jogo. Você também pode [baixar o OutBrick na App Store](${appStoreUrl('journal-device')}); confira a compatibilidade atual. Nenhuma opção altera o limite do Tempo de Uso que você escolheu.`
      ] },
      'official-settings-source': { title: 'Fonte oficial sobre os ajustes', paragraphs: [
        'Apple. [Use as Programações e os Limites de Tempo do Tempo de Uso no iPhone](https://support.apple.com/en-gb/guide/iphone/iphb0c7313c9/ios). Consultado em 30 de setembro de 2026.',
        'Apple. “Configure o Tempo de Uso para você no iPhone”, no Manual de Uso do iPhone. O guia apresenta os caminhos atuais para consultar a atividade e ativar o compartilhamento entre dispositivos.',
        'Os nomes e a disponibilidade dos controles podem variar conforme a versão do sistema, o idioma e o gerenciamento familiar. Siga a orientação atual da Apple se as opções do aparelho forem diferentes.',
      ] }
    },
    pullQuote: 'O objetivo não é escolher o menor número possível; é fazer o celular respeitar o limite que você pretendia estabelecer.',
    faqs: [
      { question: 'Como limito o tempo de jogos no iPhone com iOS 27?', answer: 'Abra Ajustes → Tempo de Uso → Limites de Tempo, ative a atividade se necessário e ajuste a categoria Jogos. A programação controla em que horários as categorias ficam disponíveis.' },
      { question: 'O limite de Jogos vale separadamente para cada app?', answer: 'Não. É um limite compartilhado pela categoria. Confira em Gerenciar Categorias quais apps estão incluídos e como o uso de outros dispositivos entra no total.' },
      { question: 'Qual é a duração ideal para jogar quebra-cabeças?', answer: 'As pesquisas não estabelecem um número ideal para todas as pessoas. Escolha um limite ligado a uma necessidade real e veja se ele funciona na sua rotina.' },
      { question: 'O Tempo de Uso controla o OutBrick no navegador?', answer: 'Este guia não verifica como o iOS classifica cada jogo no navegador ou site. Confira a categoria e o relatório no seu aparelho e consulte a orientação atual da Apple.' }
    ]
  },
  'puzzle-game-privacy-labels': {
    title: 'Como entender os rótulos de privacidade de jogos',
    dek: 'Compare rótulos de privacidade na App Store, entenda dados vinculados e rastreamento e veja o que as declarações de um jogo realmente informam.',
    imageAlt: 'Um iPhone mostrando o OutBrick ao lado de peças coloridas e de ícones de privacidade',
    tags: ['privacidade', 'App Store', 'dados pessoais', 'jogos para celular', 'transparência'],
    intro: 'O rótulo de privacidade na App Store pode ajudar a comparar jogos antes de baixar, mas é fácil tirar conclusões maiores do que ele permite. “Dados não vinculados a você” não quer dizer que nenhum dado seja coletado; “não rastreia” tem um significado específico da Apple; e as respostas são declaradas pela equipe do app, não certificadas individualmente pela loja. Este guia explica como encontrar as informações, comparar categorias equivalentes e usar o OutBrick como exemplo sem transformar um rótulo em auditoria completa de privacidade.',
    keyTakeaways: [
      'Leia o rótulo completo na página do app e compare as mesmas categorias e finalidades, não apenas o resumo visual.',
      'Dados “vinculados a você” e “usados para rastrear” são conceitos diferentes; ausência de rastreamento não significa ausência de coleta.',
      'As declarações são fornecidas pela equipe do app e devem ser mantidas atualizadas. Um rótulo é uma descrição, não uma verificação independente de toda prática.'
    ],
    sections: {
      'find-the-right-label': { title: 'Encontre o rótulo certo', paragraphs: [
        'Na App Store, abra a página de um app e procure a seção “Privacidade do App”. Toque para ver os detalhes. Confira o nome do desenvolvedor e se está olhando para o app correto: jogos com nomes parecidos podem pertencer a empresas diferentes. Se estiver comparando dois títulos, abra os dois rótulos completos em vez de decidir apenas pelos ícones ou pelo resumo.',
        'A Apple organiza as informações por tipos de dados e finalidade. Uma categoria pode aparecer como vinculada à identidade ou não vinculada. Outra pergunta é se os dados são usados para rastrear você entre apps e sites de outras empresas. Leia as definições e os exemplos da Apple antes de comparar termos; a ausência de uma categoria não responde automaticamente a todas as perguntas sobre o app.'
        ,'Kelley et al. (2010) compararam avisos de privacidade padronizados com outros formatos em um estudo online. Nesse contexto, as pessoas encontraram informações relevantes com mais rapidez e precisão. O resultado favorece declarações fáceis de examinar, mas não comprova que todos os rótulos atuais estejam corretos. Clareza e veracidade são requisitos diferentes.',
        'Antes de comparar, anote sua prioridade: anúncios, uso por uma criança, criação de conta ou funcionamento sem enviar dados ao estúdio. Nosso texto sobre [padrões manipulativos em jogos para celular](/blog/dark-patterns-in-mobile-games) discute como interfaces orientam escolhas; aqui, a ideia é identificar quais informações você precisa conferir antes de tocar em Baixar.'
      ] },
      'linked-not-linked-and-tracking': { title: 'Dados vinculados, não vinculados e rastreamento', paragraphs: [
        '“Vinculados a você” significa que os dados podem ser associados à identidade da pessoa, por exemplo, a uma conta ou identificador. “Não vinculados” indica que, segundo a declaração do desenvolvedor, foram tratados de modo a não serem associados à identidade. Isso não significa que os dados não sejam coletados nem que sejam anônimos em qualquer circunstância.',
        'Rastreamento, no vocabulário da Apple, diz respeito a vincular dados do app a dados de terceiros para publicidade direcionada ou medição, ou compartilhar dados com corretoras de dados. Portanto, um app pode coletar dados sem declarar que faz rastreamento. A pergunta “coleta dados?” é diferente de “usa dados para rastrear?”.',
        'Leia a finalidade indicada em cada categoria. Publicidade de terceiros, análise e funcionalidades do app são usos diferentes. Pergunte quem processa os dados: a medição de uma rede de anúncios pode aparecer na declaração mesmo que o estúdio não opere seu próprio serviço de análise.',
        'As [orientações da Apple sobre privacidade](https://developer.apple.com/app-store/app-privacy-details/) explicam essas definições e incluem SDKs de terceiros na responsabilidade de declaração. Um pedido de permissão responde a outra pergunta: se você autorizou determinado acesso ou rastreamento. Recusar o rastreamento não significa que toda coleta, como diagnósticos ou serviços necessários, tenha parado.',
        'Uma comparação cuidadosa poderia dizer: “Este app declara coleta de dados de diagnóstico para funcionar; aquele também declara identificadores para publicidade”. A conclusão é útil. Dizer que o primeiro é totalmente privado vai além do que o rótulo comprova.'
      ] },
      'label-policy-and-update': { title: 'O rótulo depende da declaração e pode mudar', paragraphs: [
        'A Apple pede que os desenvolvedores informem suas práticas de dados e atualizem as respostas quando elas mudarem. Isso significa que o rótulo é uma declaração da equipe responsável pelo app, sujeita às regras da plataforma; não é uma auditoria pública, linha por linha, de cada versão e serviço conectado. A [orientação da Apple sobre os detalhes de privacidade](https://developer.apple.com/app-store/app-privacy-details/) explica as definições e inclui SDKs de terceiros nas responsabilidades de declaração. Um aviso de permissão responde a outra pergunta: se determinada permissão de acesso ou rastreamento foi concedida. Recusar um pedido de rastreamento não significa que toda coleta, inclusive diagnósticos ou serviços necessários, tenha parado.',
        'A versão do app, os recursos usados e integrações com terceiros podem alterar quais dados são relevantes. Uma pessoa que cria uma conta pode compartilhar informações diferentes de outra que joga sem conta. Consulte a política de privacidade do desenvolvedor para mais detalhes e a data da versão atual do app para situar o rótulo.',
        'Li et al. (2022) examinaram ecossistemas de apps e mostraram como bibliotecas e serviços de terceiros tornam as práticas difíceis de avaliar apenas pela interface. Isso não prova uma violação por parte de um app específico; é um motivo para ler o rótulo como um resumo declarado e procurar informações adicionais quando a decisão exigir mais segurança.',
        'Li et al. (2022) também acompanharam como rótulos e metadados da App Store mudam ao longo do tempo. O estudo não auditou o jogo que você está considerando hoje; ele reforça que vale conferir se a declaração continua atual após atualizações, em vez de presumir que ficou correta para sempre.',
        'O uso de um recurso opcional também importa. Não solicitar um vídeo premiado pode mudar quais tratamentos de dados acontecem; uma declaração sobre anúncios não prova que você os assiste continuamente, e optar por uma recompensa não elimina a obrigação de declarar dados relevantes. Consulte as explicações sobre o SDK e o que a opção de remover anúncios altera.'
      ] },
      'outbrick-as-a-worked-example': { title: 'O OutBrick como exemplo prático', paragraphs: [
        'Ao consultar o OutBrick, leia o rótulo apresentado na página atual da App Store e confira a política de privacidade ligada a ela. Recursos como compras opcionais, publicidade premiada ou serviços de análise podem envolver finalidades e dados diferentes. Consulte as declarações vigentes, em vez de depender de uma descrição antiga ou de um resumo reproduzido em outro site.',
        'Pergunte o que é necessário para jogar, quais dados podem ser usados para análise ou publicidade, se há uma conta e quais controles existem. O fato de uma recompensa em vídeo ser opcional não responde, por si só, quais dados o provedor de anúncios processa. Da mesma forma, um rótulo sem rastreamento não significa que o app não use nenhum dado.',
        `A página [Privacidade](/privacy) do OutBrick apresenta a política completa. Ela informa que o estúdio não mantém um sistema de contas nem recebe os dados locais de jogo, e que o progresso pode sincronizar pela conta iCloud do próprio jogador. Também descreve o SDK de publicidade do Google para vídeos premiados opcionais. “Sem SDK de análise do estúdio” é mais específico que “nenhum serviço processa informações”; não auditamos o tráfego de rede neste artigo. Se uma categoria ou finalidade não estiver clara, [fale conosco](/contact). A página [suas opções de privacidade](/privacy-choices) explica como recusar vídeos, rever as opções de publicidade nas configurações do jogo e conferir a permissão de rastreamento do iOS. Remover Anúncios ou manter o Passe de Tijolos ativo interrompe pedidos de anúncios. Se as práticas publicadas forem adequadas para você, [baixe o OutBrick na App Store](${appStoreUrl('journal-device')}) após ler a ficha atual; caso contrário, escolha outro quebra-cabeça. O rótulo e a política devem ser revistos após mudanças importantes no app ou na publicidade.`,
        'O rótulo do OutBrick na App Store, consultado em 30 de setembro de 2026, declara Localização, Identificadores e Dados de Uso para rastreamento, além de dados vinculados para publicidade, análise e funcionalidades e dados de falha declarados como não vinculados. Portanto, não é uma declaração de “nenhum dado coletado”.',
        'Consentimento para publicidade em determinadas regiões e a autorização de rastreamento da Apple são controles separados. A política descreve opções para o Espaço Econômico Europeu, o Reino Unido e a Suíça. Não presuma que responder a um pedido de rastreamento altera todos os consentimentos regionais; confira as telas atuais. Você pode experimentar os tabuleiros básicos sem solicitar um vídeo.'
      ] },
      'make-a-comparison-you-can-use': { title: 'Faça uma comparação que ajude na sua decisão', paragraphs: [
        'Escolha dois apps que você realmente considera instalar e confira a mesma seção de cada rótulo. Compare os tipos de dados e as finalidades correspondentes. Não trate mais categorias como prova automática de um app pior: um jogo pode ter recursos diferentes, e as declarações descrevem esses recursos de maneiras específicas.',
        'Depois, abra as políticas de privacidade se precisar entender detalhes como retenção, exclusão de conta, contato ou serviços terceirizados. Se um ponto continuar vago, pergunte ao desenvolvedor. Um rótulo serve para começar uma conversa informada, não para substituir a política inteira nem uma análise independente.',
        'A privacidade também depende das configurações do aparelho e das escolhas que você faz. Revise permissões, anúncios personalizados e controles de rastreamento do sistema. Essas preferências podem limitar determinados usos, mas não transformam automaticamente em privada toda atividade no app. Para uma decisão familiar, combine esta leitura com nosso guia sobre [jogos tranquilos para crianças](/blog/calm-games-for-kids): privacidade, adequação, controles de compra e ritmo são questões distintas.',
        'Kelley et al. (2013) testaram um resumo curto de privacidade em um estudo de laboratório com 20 pessoas e em um experimento online com 366. Informações mais claras no momento da escolha ajudaram participantes a selecionar apps que pediam menos permissões. Eram estudos sobre apps Android da época, não sobre os jogos iOS atuais; a lição é examinar a privacidade antes de baixar, quando ainda é fácil comparar alternativas.'
      ] },
      'official-privacy-sources': { title: 'Fontes oficiais sobre privacidade', paragraphs: [
        'Apple. “Detalhes de privacidade dos apps”. Apple Developer. Consulte as [definições das declarações da Apple](https://developer.apple.com/app-store/app-privacy-details/); acesso em 30 de setembro de 2026.',
        'Hamdi, M. (s.d.). OutBrick: Block Sort Puzzle [app para dispositivos móveis]. App Store. Declaração de privacidade consultada em 30 de setembro de 2026.',
        'OutBrick. (24 de setembro de 2026). Política de privacidade do OutBrick: dados, anúncios e escolhas. [Política de privacidade](/privacy).',
        'OutBrick. (24 de setembro de 2026). Suas escolhas e controles de privacidade no OutBrick. [Opções de privacidade](/privacy-choices).',
        'Os estudos revisados por pares citados neste artigo examinam comunicação de privacidade e práticas de plataformas. Nenhum deles auditou o OutBrick de forma independente.'
      ] }
    },
    pullQuote: 'Um rótulo de privacidade é um ponto de partida para comparar apps, não uma auditoria independente de todas as práticas.',
    faqs: [
      { question: 'O que significa “dados vinculados a você” na App Store?', answer: 'Significa que, segundo a declaração do desenvolvedor, os dados podem ser associados à sua identidade, como uma conta ou identificador. É diferente de dizer se os dados são coletados.' },
      { question: '“Não rastreia” quer dizer que o app não coleta dados?', answer: 'Não. Rastreamento tem uma definição específica da Apple relacionada a dados de terceiros e publicidade. Um app pode coletar dados para outras finalidades sem declarar rastreamento.' },
      { question: 'A Apple verifica cada rótulo de privacidade?', answer: 'As informações são fornecidas pelo desenvolvedor e devem refletir as práticas do app. O rótulo é um resumo padronizado, não uma auditoria independente de cada versão e serviço.' },
      { question: 'Onde encontro mais detalhes sobre a privacidade do OutBrick?', answer: 'Leia o rótulo atual na página do OutBrick na App Store e a [política de privacidade](/privacy), que explica as práticas com mais detalhes.' }
    ]
  }
};
