import type { ExtraGuides } from '../../i18n/blog';
import { appStoreUrl } from '../../app-store-url.ts';

/** Journal batch 10 in Brazilian Portuguese. */
export const ptBR10: ExtraGuides = {
  'puzzle-walkthrough-board-mismatch': {
    title: 'Por que o tabuleiro não bate com o passo a passo?',
    dek: 'Antes de copiar outra jogada, confira jogo, versão, modo e posição inicial. O número da fase, sozinho, não identifica a solução de um quebra-cabeça.',
    imageAlt: 'Uma captura do OutBrick em um celular, com peças coloridas e dois amigos de tijolo sobre uma grade azul-marinho',
    tags: ['quebra-cabeças', 'resolução de problemas', 'blocos deslizantes', 'dicas', 'OutBrick'],
    intro: 'O vídeo diz fase 48. Seu jogo também diz fase 48. Mesmo assim, o primeiro movimento manda uma peça azul para uma faixa vazia que está ocupada na sua tela. Você volta ao início, tenta de novo e se pergunta o que deixou passar. Antes de gastar outra tentativa, compare os dois tabuleiros. O número de uma fase é um rótulo dentro de determinado jogo e versão; não descreve por completo um quebra-cabeça. Este guia mostra como identificar um passo a passo incompatível, encontrar a primeira divergência e aproveitar uma ideia útil sem presumir que a sequência demonstrada precisa funcionar.',
    keyTakeaways: [
      'Antes de seguir uma sequência, confira o jogo, o modo, a versão e todo o estado inicial.',
      'O histórico publicado do OutBrick registra mudanças de layout e da ordem dos tabuleiros; um número antigo pode identificar outro quebra-cabeça.',
      'Quando uma sequência falhar, pare na primeira diferença. Aproveite uma ideia de planejamento que se aplique ou peça ajuda com seu tabuleiro real.'
    ],
    sections: {
      'identify-the-right-game': { title: 'Primeiro, confirme que é o mesmo jogo', paragraphs: [
        'Comece pelo nome completo do app e pelo desenvolvedor, não pela miniatura de um resultado de busca. Muitos quebra-cabeças para celular usam blocos, saídas da mesma cor e títulos parecidos. Um vídeo chamado “block sort fase 48” pode ser de outro aplicativo. Abra a página do jogo na loja pelas configurações do próprio app ou confira o desenvolvedor. Arte parecida é motivo para olhar com atenção, não prova de que as regras são iguais.',
        'Depois, confira como as peças se movem. O bloco vai até onde consegue, anda uma casa ou segue o caminho arrastado? Uma personagem empurra caixas? A cor precisa chegar a uma porta, ocupar um alvo ou completar uma linha? Na regra Slide & Match atual do OutBrick, uma peça para onde você solta, sai por uma porta da mesma cor ou troca de lugar com uma vizinha, e três ou mais da mesma cor em linha somem. Nos tabuleiros clássicos, que ainda dá para jogar no navegador, uma peça desliza até algo pará-la; nosso [guia para resolver quebra-cabeças de blocos deslizantes](/blog/how-to-solve-sliding-block-puzzles) explica esse modelo de movimento clássico.',
        'Hearn e Demaine (2005) estudaram problemas formais de movimento com restrições diferentes, incluindo blocos deslizantes e Sokoban. Os resultados teóricos tratam de famílias generalizadas de problemas, não da dificuldade de um app específico. A distinção útil aqui é mais simples: movimento permitido e objetivo fazem parte da identidade do quebra-cabeça. Uma sequência para um jogo de empurrar peças não pode ser presumida válida em um jogo de deslizar até parar.',
        'Antes de pesquisar outra vez, anote o nome do app, o desenvolvedor, o modo e a fase. Acrescente a plataforma e a versão visível do app, se conseguir encontrá-las. Esta é uma recomendação prática de solução de problemas, não uma lista validada pelo artigo de pesquisa. Ela ajuda quem fez o guia ou outro jogador a entender de qual tabuleiro você está falando, sem adivinhar por uma captura cortada.'
      ] },
      'check-version-mode-and-date': { title: 'Um número conhecido pode esconder um tabuleiro diferente', paragraphs: [
        'A data de publicação de um vídeo ajuda a contextualizar, mas não é necessariamente a versão do app usada na gravação. A pessoa pode publicar um vídeo antigo ou atualizar o título sem substituir o vídeo. Procure a versão na descrição, nos comentários ou nas configurações mostradas. Se não encontrar, trate essa informação como desconhecida. Datas diferentes, sozinhas, não provam que o guia esteja errado nem que haja defeito no seu aparelho.',
        'O OutBrick oferece um exemplo concreto para conferir. As [notas de versão 4.2](/whats-new#4-2) informam que 1.301 dos 2.000 tabuleiros receberam novos layouts. É uma mudança histórica, não uma afirmação de que 4.2 seja a versão mais recente. A [página e o histórico da App Store](https://apps.apple.com/us/app/outbrick-block-sort-puzzle/id6807997465), consultados em 30 de setembro de 2026, mostram a versão 4.5 e relatam reconstruções e reordenações adicionais (Hamdi, s.d.). Portanto, o número de uma gravação antiga talvez não identifique a disposição atual.',
        'Confira também o modo. Uma fase da progressão principal, uma amostra no navegador e um desafio diário com data não são intercambiáveis só porque usam as mesmas cores. O [tabuleiro diário no navegador](/daily) percorre um conjunto fixo conforme a data UTC. Se comparar uma gravação diária, anote a data junto à captura. Isso descreve a implementação atual do site; não promete que o recurso diário nativo funcione da mesma forma.',
        'Essas observações não provam que exista aleatorização por jogador, experimentos ou dificuldade personalizada oculta. Uma diferença visível não revela qual explicação se aplica. Use a informação documentada quando houver uma e não trate hipóteses como fatos. Nosso artigo sobre [como verificamos os tabuleiros](/blog/verifying-2000-sliding-block-boards) trata de solucionabilidade; um tabuleiro solucionável e um passo a passo compatível são coisas diferentes.'
      ] },
      'compare-the-complete-starting-state': { title: 'Compare toda a posição inicial', paragraphs: [
        'Pause o vídeo antes da primeira jogada e compare com o tabuleiro antes de você mover qualquer peça. Se reiniciar puder custar progresso ou uma tentativa, confira primeiro as regras do jogo em vez de redefinir automaticamente. Uma captura do estado atual ainda ajuda; identifique-a como “depois de três jogadas”, por exemplo, em vez de apresentá-la como início. Um guia não consegue reproduzir a sequência inicial a partir de uma posição intermediária diferente.',
        'Confira o contorno, depois os objetivos e então as peças. O tamanho e os espaços bloqueados são iguais? As portas coloridas estão nas mesmas bordas? Cada peça tem o mesmo formato, orientação e posição? Compare chaves, fechaduras e outros obstáculos. Por fim, compare os espaços vazios. Uma casa vazia faz parte da disposição: pode determinar uma rota ou o ponto onde uma peça para.',
        'Ito et al. (2023), ao analisarem modelos formais de classificação de bolas e água, tratam conteúdo ordenado, capacidade dos recipientes e recipientes vazios como partes do problema. O resultado é sobre modelos de pilhas, não sobre o OutBrick. A comparação é útil: um quebra-cabeça é mais específico que sua paleta de cores. Dois jogos de tubos com as mesmas cores podem permitir despejos diferentes por causa da ordem ou da capacidade livre. Em um quebra-cabeça deslizante, examine o estado espacial conforme as regras daquele jogo.',
        'Use rótulos estáveis ao pedir que alguém compare imagens. Diga “a peça azul horizontal perto da porta inferior esquerda” em vez de “aquela azul”, ou combinem que linhas são contadas de cima e colunas da esquerda. Larkin e Simon (1987) analisaram como representações alteram o esforço de busca e inferência, mesmo quando contêm a mesma informação. Deixe os dois tabuleiros visíveis e use as mesmas coordenadas para inspecionar diferenças, sem precisar guardar uma imagem na memória.'
      ] },
      'stop-at-the-first-divergence': { title: 'Pare na primeira divergência da sequência', paragraphs: [
        'Se as posições iniciais forem iguais, reproduza uma ação de cada vez. Compare o resultado imediatamente, inclusive onde a peça parou e o que restou no tabuleiro. A primeira diferença informa mais que a décima. Continuar depois dela cria outra disposição; as instruções seguintes podem falhar por causa da diferença inicial.',
        'Por exemplo, um vídeo pode mover uma peça vermelha para baixo até uma azul pará-la. No seu tabuleiro, a peça azul já saiu pela porta. Agora a vermelha desliza mais longe, então “mova a vermelha para baixo” não produz o estado mostrado. A instrução parece igual, mas a condição que a sustentava desapareceu. É um exemplo ilustrativo da regra de deslizar, não um diagnóstico de uma fase publicada.',
        'Separe um movimento recusado de um resultado inesperado. Se o movimento for recusado, confira a peça, a direção e o obstáculo ou porta envolvidos. Se funcionar, mas parar em outro lugar, compare a condição de parada. Se a disposição for igual e a ação ainda se comportar de outro jeito, registre essa observação específica para o suporte. Não conclua que o tabuleiro é impossível só porque não dá para seguir um vídeo.',
        'Uma mensagem útil inclui, se possível, a versão do app, o modo, o número da fase ou a data do desafio diário, duas capturas e a primeira ação diferente. Remova das imagens qualquer informação pessoal que não tenha relação. Diga se prefere uma dica pequena ou a sequência inteira; nosso [guia de dicas sem spoilers](/blog/puzzle-hints-without-spoilers) traz exemplos. A [página de suporte](/support) é um bom primeiro passo antes de enviar um relato pelo canal de contato existente.'
      ] },
      'keep-the-idea-not-the-sequence': { title: 'Aproveite a ideia, não a sequência, e escolha a ajuda que quer', paragraphs: [
        'Um guia incompatível ainda pode mostrar uma relação útil: colocar um bloqueio no lugar antes de enviar uma peça longa pela faixa, ou liberar uma rota antes de mover a peça que vai usá-la. Pergunte o que cada jogada faz e de quais condições depende. Se essas condições não existem no seu tabuleiro, não force o movimento. Uma ideia de planejamento precisa ser conferida de novo no estado real.',
        'Chi et al. (1989) estudaram estudantes que analisavam exemplos resolvidos de mecânica, usando protocolos de verbalização em voz alta. Estudantes com melhores resultados explicavam a ligação entre ações e princípios e acompanhavam a própria compreensão. O estudo trata de aprendizagem de física, não de vídeos de quebra-cabeças. Nossa aplicação é modesta: entenda o propósito da jogada demonstrada antes de adotá-la, em vez de presumir que copiar a direção reproduzirá o efeito.',
        'Também não é obrigatório extrair uma lição de todo vídeo. Se você queria uma solução direta e o tabuleiro não corresponde, procure um exemplo compatível ou peça ajuda com a captura exata. Se prefere descobrir por conta própria, feche a sequência e peça apenas a relação ou dependência relevante. Nenhuma preferência faz de você um jogador melhor ou pior. A ajuda deve responder à pergunta que você realmente fez.',
        `Você pode praticar a conferência de movimentos nos [tabuleiros do OutBrick no navegador](/play), onde os controles permitem reiniciar ou desfazer uma experiência. Para explorar o jogo instalado, [baixe o OutBrick na App Store](${appStoreUrl('journal-walkthrough-mismatch')}) e confira os requisitos e as informações de compra atuais. O app inclui vidas e publicidade premiada opcional; a amostra do site não comprova todos os recursos da versão nativa.`,
        'Referência de produto: Hamdi, M. (s.d.). OutBrick: Block Sort Puzzle [aplicativo móvel]. App Store. Consultado em 30 de setembro de 2026, na página vinculada acima. As referências de pesquisa abaixo apoiam as distinções deste guia; nenhuma avaliou o OutBrick nem validou esta lista de solução de problemas.'
      ] }
    },
    pullQuote: 'O número da fase é um rótulo dentro de um jogo e versão específicos; não descreve o quebra-cabeça por completo.',
    faqs: [
      { question: 'Por que o passo a passo mostra outro tabuleiro na mesma fase?', answer: 'Primeiro confira se é o mesmo app, modo e posição inicial. Uma atualização também pode mudar layouts ou reordenar tabuleiros; o histórico do OutBrick documenta essas mudanças, mas uma diferença, por si só, não comprova aleatorização nem defeito.' },
      { question: 'Devo continuar seguindo o vídeo depois que uma jogada divergir?', answer: 'Pare na primeira diferença e compare os estados. As instruções posteriores podem depender de um ponto de parada ou espaço vazio que não existe mais no seu tabuleiro.' },
      { question: 'Um passo a passo incompatível significa que o tabuleiro do OutBrick é impossível?', answer: 'Não. Um guia de outro layout não demonstra se seu tabuleiro é solucionável. A verificação publicada dos tabuleiros trata de solucionabilidade, não da compatibilidade de um vídeo externo com sua versão.' },
      { question: 'O que devo incluir ao pedir ajuda com um tabuleiro?', answer: 'Informe o app, modo, fase ou data do desafio diário, versão se conhecida, uma captura clara e a primeira ação que diverge do guia. Diga se quer uma dica ou a solução completa e remova informações pessoais sem relação.' }
    ]
  }
};
