import type { ExtraGuides } from '../../i18n/blog';
import { appStoreUrl } from '../../app-store-url.ts';

export const ptBR8: ExtraGuides = {
  'block-blast-plus-vs-outbrick': {
    title: 'Block Blast!+ e OutBrick: dois tipos de quebra-cabeça com blocos',
    dek: 'Compare as mecânicas: encaixar peças para completar linhas ou deslizar blocos até as saídas. Veja também como cada jogo funciona em relação a custos.',
    imageAlt: 'Blocos e personagens coloridos de OutBrick ao redor de um celular sobre um fundo geométrico escuro',
    tags: ['jogos de quebra-cabeça', 'ordenar blocos', 'design de jogos', 'hábitos de jogo', 'jogos para celular'],
    intro: 'Uma grade de blocos coloridos pode esconder quebra-cabeças bem diferentes. Em um, você escolhe onde encaixar uma nova peça. No outro, todas as peças já estão no tabuleiro, e você precisa descobrir como tirá-las dali. Block Blast!+ e OutBrick ajudam a entender essa diferença: os dois recompensam a leitura do espaço, mas fazem perguntas distintas. Se você procurou um jogo parecido com Block Blast, uma resposta útil não é uma lista de capturas de tela semelhantes, e sim uma explicação do que você realmente fará. Este guia de mecânicas, escrito pela equipe de OutBrick, se baseia em fontes consultadas em 30 de setembro de 2026. Não fizemos uma comparação prática nem medimos as preferências dos jogadores.',
    keyTakeaways: [
      'Block Blast!+ gira em torno de encaixar peças e completar linhas ou colunas; OutBrick, de deslizar blocos existentes por portões da mesma cor.',
      'Block Blast!+ é a edição do Apple Arcade. As condições de assinatura, anúncios e compras dessa edição não se aplicam automaticamente ao app Block Blast! padrão, listado separadamente.',
      'Escolha encaixar peças se gosta de organizar formas e preservar espaço; escolha deslizar se gosta de planejar rotas, pontos de parada e ordem dos movimentos.',
    ],
    sections: {
      'placing-versus-routing': { title: 'A primeira diferença está no verbo', paragraphs: [
        'A Apple descreve Block Blast!+ como um jogo de encaixar blocos em uma grade, completar linhas e colunas e formar combinações (Apple, 2026). A pergunta central é: “Onde esta peça cabe?”. Um espaço vazio permite encaixar algo; uma linha quase completa pode liberar espaço. Você compara o formato da peça com os espaços disponíveis.',
        'A pergunta de OutBrick é: “O que precisa se mover antes que este bloco possa sair?”. Você seleciona um bloco que já está no tabuleiro e o desliza. Ele segue até algo pará-lo, em direção ao portão da sua cor. Um espaço vazio pode abrir uma rota, mas também pode deixar o bloco avançar mais do que você queria. Mais espaço livre não significa necessariamente uma posição melhor.',
        'Imagine um corredor comprido e reto. Em um quebra-cabeça de encaixe, mantê-lo vazio pode reservar espaço para uma peça comprida. Em um jogo de deslizamento, o corredor aberto pode fazer um bloco passar do ponto em que deveria virar. Talvez outro bloco precise funcionar como freio temporário. O mesmo elemento visual tem outro significado estratégico porque as regras de movimento mudam o que você pode fazer.',
        'Nossa [introdução aos quebra-cabeças de blocos deslizantes](/blog/how-to-solve-sliding-block-puzzles) explica essa regra. Para conhecer jogos de encaixe, peças que caem e rotas, veja [o que mantém jogos como Tetris interessantes](/blog/games-like-tetris). Uma mecânica não é uma versão mais avançada da outra: cada uma torna o espaço limitado interessante de um jeito.',
      ] },
      'two-ways-to-plan': { title: 'Duas maneiras de pensar no próximo movimento', paragraphs: [
        'Em um quebra-cabeça de encaixe, observe a peça disponível, os lugares em que ela pode ser colocada e como o tabuleiro ficará depois. Uma posição pode ser permitida e ainda assim inconveniente: talvez crie um vão estreito ou ocupe o único espaço que serviria para outra peça. Completar uma linha muda o formato e a quantidade de espaço disponível. Esta é uma descrição geral, não uma estratégia ideal para todos os modos de Block Blast.',
        'Em OutBrick, observe todo o percurso e o ponto onde o bloco vai parar. Tirar um obstáculo do caminho pode abrir uma rota até o portão, mas também remover o apoio de que outro bloco precisa para parar. Um plano útil descreve dependências: o azul precisa parar aqui antes que o vermelho se alinhe com a saída. Você reorganiza um sistema em vez de apenas escolher um destino vazio.',
        'Isaksen et al. (2017) separaram decisões estratégicas das exigências de execução em simulações de variantes de Tetris e Puzzle Bobble. O trabalho mostra por que uma única classificação de dificuldade pode esconder exigências diferentes. O estudo não avaliou Block Blast!+ nem OutBrick. Usamos essa distinção para perguntar se você gosta tanto de decidir quanto de executar um movimento.',
        'Isso importa se você gosta de quebra-cabeças reflexivos, mas não de certo tipo de controle. Arrastar uma peça até um lugar e indicar uma direção para um bloco existente são interações diferentes. Uma captura de tela não revela qual será mais clara para você. Experimente algo simples, leia as instruções e observe o que acontece quando um movimento não é aceito antes de concluir que o controle desconhecido torna o jogo difícil demais.',
      ] },
      'satisfaction-without-ranking': { title: 'Que tipo de satisfação você procura?', paragraphs: [
        'Algumas pessoas gostam de ver linhas desaparecerem repetidamente. Outras preferem limpar um tabuleiro e descobrir a rota aos poucos. Você pode gostar dos dois em momentos diferentes. A diferença está no tipo de sessão agradável, não em considerar superficial a busca por pontos ou intelectualmente superior um tabuleiro com fim definido.',
        'Ryan et al. (2006) estudaram a motivação para jogar em quatro pesquisas e relacionaram competência e autonomia percebidas com prazer e preferências. O estudo não classifica estes apps. Ele sugere uma pergunta pessoal: você entende o que aconteceu e sente que as decisões foram suas? Uma mecânica conhecida pode trazer essa sensação logo; uma nova talvez exija alguns tabuleiros.',
        'Abuhamdeh e Csikszentmihalyi (2012) estudaram desafios no xadrez pela internet e em atividades cotidianas. A relação entre desafio e prazer variava conforme a motivação e a atividade. Não existe um vencedor universal entre o quebra-cabeça mais fácil e o mais difícil. Se você quer fazer pontos, preservar espaço pode ser atraente; se prefere desembaraçar uma configuração limitada, talvez goste mais dos portões por cor.',
        'Faça um teste concreto: depois de uma sessão curta, diga qual decisão foi prazerosa — reservar espaço, completar uma combinação, criar um ponto de parada ou encontrar a ordem de saída. “Gostei de decidir isso” informa mais do que “deveria gostar deste jogo popular”. Também é válido concluir que nenhum dos dois combina com você agora e continuar procurando.',
      ] },
      'arcade-and-standalone': { title: 'Confira a edição antes de comparar os custos', paragraphs: [
        'A Apple anunciou que Block Blast!+ chegaria ao Apple Arcade em 3 de setembro de 2026 e descreveu essa edição como livre de anúncios e compras dentro do app (Apple, 2026). Essa informação é sobre Block Blast!+. O app padrão Block Blast! tem uma página separada; o sinal de “+” identifica uma distribuição diferente. Confira de qual edição uma recomendação, captura de tela ou análise está falando.',
        'O acesso ao Arcade depende de uma assinatura e das condições vigentes. OutBrick é um download independente da App Store, com compras dentro do app e anúncios opcionais com recompensa. Também há vidas e limites de movimentos. “Download grátis” não promete acesso, tentativas ou extras sempre gratuitos; as condições de um jogo por assinatura não descrevem automaticamente um app independente.',
        'Se você já assina o Arcade, consulte a página atual de Block Blast!+ para verificar compatibilidade e preferências. Se não assina, considere o catálogo e as condições antes de pagar para ter acesso a um jogo. Nossa [explicação sobre jogo justo](/#fair) detalha vidas, desfazer e anúncios opcionais de OutBrick. Uma comparação ajuda quando esclarece essas escolhas.',
        'OutBrick removeu o Rush na versão 4.2; o quebra-cabeça atual usa limite de movimentos, não uma contagem regressiva. Isso não determina o ritmo de todas as edições ou modos de Block Blast. Consulte a descrição atual da edição que pretende instalar em vez de deduzir se há cronômetro pelo nome, placar ou visual colorido.',
      ] },
      'a-small-fit-test': { title: 'Um teste rápido vale mais que um veredito geral', paragraphs: [
        'Primeiro, explique a regra para si mesmo. No encaixe, coloque uma peça em um espaço válido e avance para completar uma linha. Em OutBrick, escolha a direção de um bloco, preveja onde ele vai parar e procure a saída correspondente. Jogue devagar o suficiente para perceber se cada ação confirma sua explicação. A comparação deve ajudar a encontrar o quebra-cabeça certo, não convencer você a tolerar o errado.',
        'Iacovides et al. (2015) usaram estudos de caso, observações e entrevistas para examinar aprendizado e envolvimento em jogos. Os relatos relacionaram avanços de compreensão ao envolvimento, especialmente quando os jogadores se sentiam responsáveis pelo próprio progresso. São resultados qualitativos sobre outros jogos. Eles incentivam prestar atenção à própria compreensão, sem prometer que um teste breve revele uma preferência universal.',
        `Você pode [experimentar um tabuleiro de OutBrick no navegador](/play) para observar como funciona o deslizamento até parar. A demonstração apresenta a mecânica, não todos os recursos, custos ou aspectos de acessibilidade do app instalado. Se gostar, [consulte OutBrick na App Store](${appStoreUrl('journal-block-blast-comparison')}) e confira compatibilidade e compras antes de baixar.`,
        'O resultado pode ser simples: “Prefiro encaixar peças novas a redirecionar as que já estão no tabuleiro”, ou o contrário. Isso basta. Quebra-cabeças com blocos compartilham um vocabulário visual, mas os verbos definem a experiência. Escolha o verbo que quer continuar praticando.',
      ] },
      'official-source': { title: 'Fonte oficial do produto', paragraphs: [
        'Apple. (2026, 11 de agosto). Apple Arcade’s lineup of hit puzzle games gets even bigger with the addition of Block Blast!+ and Art of Fauna: Cozy Puzzles+. Apple Newsroom. [Anúncio oficial do Arcade](https://www.apple.com/newsroom/2026/08/apple-arcade-levels-up-with-block-blast-plus-and-art-of-fauna-cozy-puzzles-plus/). Os estudos abaixo contextualizam design e motivação; nenhum testou os jogos desta comparação.',
      ] },
    },
    pullQuote: 'Mais espaço livre não significa necessariamente uma posição melhor.',
    faqs: [
      { question: 'OutBrick é o mesmo tipo de quebra-cabeça que Block Blast!+?', answer: 'As mecânicas principais são diferentes. Block Blast!+ pede que você encaixe peças para completar linhas e colunas; OutBrick pede que deslize blocos existentes por portões da mesma cor.' },
      { question: 'Block Blast!+ é o mesmo app que Block Blast! padrão?', answer: 'Block Blast!+ é a edição do Apple Arcade, com acesso por assinatura e as condições de anúncios e compras descritas pela Apple. Consulte a página separada do app padrão em vez de presumir que as condições são iguais.' },
      { question: 'Qual dos dois exige mais planejamento?', answer: 'Os dois exigem planejamento de restrições diferentes. Encaixar peças muda o espaço restante; em OutBrick, a ordem dos movimentos e os pontos de parada mudam as rotas.' },
      { question: 'Posso experimentar OutBrick sem instalar?', answer: 'O [tabuleiro no navegador](/play) permite testar como os blocos deslizam até parar. Consulte também a página da App Store para ver compatibilidade, recursos e custos do app instalado.' },
    ],
  },
  'sokoban-vs-sliding-block-puzzles': {
    title: 'Sokoban e quebra-cabeças de blocos deslizantes: empurrar, deslizar e planejar',
    dek: 'Entenda a diferença entre empurrar no Sokoban e deslizar blocos até pararem, com exemplos de cantos, passagens e pontos de parada temporários.',
    imageAlt: 'Celular com OutBrick e blocos coloridos diante de um fundo escuro com caminhos geométricos',
    tags: ['jogos de quebra-cabeça', 'blocos deslizantes', 'design de jogos', 'resolução de problemas', 'ordenar blocos'],
    intro: 'Uma caixa está a uma casa do objetivo. Movê-la parece óbvio, até você perceber que não consegue chegar ao lado de onde precisa empurrá-la. Um bloco colorido está ao lado da saída. Também parece óbvio movê-lo, até um corredor aberto fazê-lo passar do ponto. Sokoban e quebra-cabeças de deslizamento envolvem espaço e ordem, mas o obstáculo a planejar muda. Aqui comparamos as regras clássicas de Sokoban com o deslizamento até parar de OutBrick. Explicamos mecânicas sem classificar dificuldade; os exemplos são situações inventadas, não soluções de fases específicas.',
    keyTakeaways: [
      'No Sokoban clássico, o personagem precisa chegar ao lado correto para empurrar as caixas; em OutBrick, você seleciona um bloco e o desliza até algo pará-lo.',
      'Um canto pode prender uma caixa no Sokoban para sempre. No deslizamento, remover um obstáculo também pode eliminar o ponto de parada necessário para outra rota.',
      'Alguns hábitos de planejamento se aplicam aos dois, mas uma estratégia só funciona quando as regras de movimento e objetivo permitem. Leia as regras antes de reutilizar um plano conhecido.',
    ],
    sections: {
      'what-a-move-means': { title: 'O que um movimento realmente significa?', paragraphs: [
        'No Sokoban clássico há um personagem, caixas, paredes e espaços de armazenamento em uma grade. O personagem anda pelos espaços vazios e empurra uma caixa se o espaço atrás dela estiver livre. Não pode puxar, empurrar uma cadeia de caixas nem atravessar paredes. O objetivo é colocar as caixas nos espaços marcados. Existem variantes; aqui falamos das regras clássicas, não de todo app chamado Sokoban.',
        'A posição do personagem faz parte do quebra-cabeça. Mesmo que haja espaço à direita de uma caixa, só é possível empurrá-la para lá se o personagem conseguir chegar à esquerda dela. Pensar apenas no destino deixa metade da ação de fora. Um caminho curto para chegar atrás da caixa pode ser essencial, mesmo sem aproximá-la do objetivo.',
        'Em OutBrick, você escolhe diretamente um bloco e indica uma direção. Ele desliza até parar e sai por um portão da mesma cor. Não há um personagem cuja rota a pé precise ser preservada. O foco está no percurso, nas paradas e na relação com os outros blocos. Chaves, fechaduras e caixas aparecem em outras fases, mas não tornam o movimento básico igual ao do Sokoban.',
        '“Quebra-cabeça de blocos deslizantes” é uma categoria ampla. Alguns permitem deslocamentos curtos ou em uma só direção; outros deslizam até parar. Nossa [história dos quebra-cabeças de blocos deslizantes](/blog/history-of-sliding-block-puzzles) explica o contexto. Identifique a regra específica antes de presumir que já sabe resolver o jogo.',
      ] },
      'the-corner-and-the-brake': { title: 'Um canto em um jogo, um freio no outro', paragraphs: [
        'Imagine uma caixa junto à parede de baixo, com outra parede imediatamente à esquerda. Se ela for empurrada para esse canto e ele não for um objetivo, não poderá sair pelas regras clássicas. Para empurrá-la à direita, o personagem precisaria ocupar a parede à esquerda; para movê-la para cima, precisaria ficar abaixo da parede inferior. A caixa fica presa mesmo que o restante do depósito esteja vazio.',
        'Junghanns e Schaeffer (2001) estudaram Sokoban como um problema de busca difícil para um único agente. O solucionador deles usa conhecimento específico do domínio, detecção de impasses e redução de buscas improdutivas. É pesquisa em computação, não um experimento de treinamento humano. Ela ajuda a destacar uma diferença: um movimento permitido pode tornar o objetivo inalcançável.',
        'Agora imagine um bloco que precisa parar em uma coluna central antes de chegar ao portão. Outro bloco ocupa a casa depois do ponto de parada e funciona como freio. Removê-lo parece organizar o tabuleiro, mas deixa o primeiro bloco passar do alinhamento. O obstáculo tinha uma função. O exemplo depende da regra de deslizar até parar e não se aplica a todo quebra-cabeça deslizante.',
        'Os exemplos não significam que você nunca deva ir a um canto ou liberar uma passagem. Um objetivo no canto pode justificar o empurrão; outro freio pode tornar a passagem segura. A pergunta é o que continuará possível depois. Um tabuleiro organizado e um tabuleiro solucionável não são a mesma coisa.',
      ] },
      'routes-have-two-ends': { title: 'Preserve os acessos, não só os destinos', paragraphs: [
        'Imagine uma passagem no Sokoban que conecta duas salas. Empurrar uma caixa para a entrada pode aproximá-la do objetivo e bloquear a passagem do personagem. Talvez você precise chegar ao outro lado depois, mas a única rota já foi fechada. Antes de empurrar, pergunte por onde o personagem andará em seguida e quais lados das outras caixas continuarão acessíveis.',
        'Em OutBrick, a pergunta equivalente envolve trajetos e pontos de parada. Se o azul precisa atravessar antes da saída do vermelho, tirar o vermelho primeiro pode remover um freio ou alterar o caminho. Mantê-lo para sempre também pode bloquear o azul. É uma dependência temporária: preserve a peça enquanto ela for útil e remova-a quando sua função terminar.',
        'Anote relações em vez de uma longa sequência de direções. No Sokoban: “Mantenha a porta livre até eu chegar atrás da caixa de cima”. No deslizamento: “Mantenha este bloco como ponto de parada até alinhar o outro”. Assim, o motivo fica claro. Se o tabuleiro mudar, verifique se a relação continua válida em vez de tentar lembrar uma sequência que já não serve.',
        'Nossa [guia para analisar o tabuleiro antes de mover](/blog/how-to-read-a-puzzle-before-moving) ajuda a identificar dependências. Você não precisa de um plano perfeito até o fim. Muitas vezes basta perceber qual acesso precisa continuar aberto e qual posição útil ainda não deve ser desfeita.',
      ] },
      'what-transfers-and-what-does-not': { title: 'O que se aplica quando você troca de jogo?', paragraphs: [
        'Verificar as consequências ajuda nos dois tipos de quebra-cabeça, assim como perceber que uma peça talvez precise se afastar do objetivo antes de chegar lá. É menos seguro presumir que o movimento funciona igual. Quem joga Sokoban pode esperar deslocamentos de uma casa; quem joga deslizamento pode esquecer o espaço que o personagem precisa para ficar atrás da caixa.',
        'Iacovides et al. (2015) estudaram ação, compreensão e envolvimento em vários jogos por meio de estudos de caso. Os relatos qualitativos destacam avanços de compreensão; não medem transferência de habilidade entre Sokoban e OutBrick. Nossa aplicação prática é tratar uma surpresa primeiro como possível mal-entendido da regra, antes de culpar sua capacidade de planejar.',
        'Hearn e Demaine (2005) analisaram a complexidade computacional formal de quebra-cabeças deslizantes e outros problemas com restrições. A demonstração trata de famílias matemáticas, não da dificuldade de uma fase comercial. Ela reforça um limite importante: as regras de movimento definem o problema. Uma mudança nas regras pode exigir outro raciocínio em tabuleiros parecidos; o artigo não classifica Sokoban e OutBrick.',
        'Experimente um tabuleiro simples ao mudar de categoria. Preveja um movimento permitido e o resultado exato, faça o movimento e compare. Se puder testar sem risco, repita com um movimento bloqueado. Esta é uma sugestão editorial, não um programa de treino comprovado; ela pode ajudar a evitar que regras antigas sejam aplicadas a um tabuleiro novo.',
      ] },
      'choose-your-favourite-constraint': { title: 'Escolha a restrição que você gosta de planejar', paragraphs: [
        'Sokoban combina com quem gosta de planejar o acesso do personagem e as consequências de empurrões irreversíveis. Experimente o deslizamento se prefere criar pontos de parada e redirecionar as peças diretamente. Não é necessário afirmar que um gênero melhora mais o cérebro: cada mecânica pode ser divertida por si só.',
        'Kotovsky et al. (1985) investigaram por que diferentes apresentações de problemas formalmente equivalentes da Torre de Hanói tinham graus distintos de dificuldade. O estudo não tratou desses dois gêneros. Ele ajuda a separar a estrutura da tarefa da facilidade de entender as regras: uma apresentação desconhecida pode parecer mais difícil sem acrescentar peças. Dificuldade e preferência pessoal são perguntas diferentes.',
        `Você pode [experimentar uma demonstração de OutBrick](/play) para ver como a regra de deslizamento muda um corredor. Leia nossas [dicas para quebra-cabeças de ordenação por cores](/blog/colour-sort-puzzle-tips) para relacionar movimento e portões correspondentes. Se gostar, [consulte OutBrick na App Store](${appStoreUrl('journal-sokoban-comparison')}) para ver compatibilidade e compras atuais. O app tem limites de movimentos, vidas e anúncios opcionais com recompensa; um quebra-cabeça sem cronômetro não significa acesso ilimitado.`,
        'Leve uma pergunta útil para o próximo tabuleiro: “O que precisa continuar disponível depois deste movimento?”. No Sokoban, pode ser a casa em que o personagem precisa ficar. Em OutBrick, pode ser uma superfície que servirá de parada. Essa diferença transforma uma semelhança visual vaga em uma escolha mais clara sobre o que você quer jogar.',
      ] },
      'classic-rules-source': { title: 'Regras clássicas e limites das evidências', paragraphs: [
        'Sokoban.jp. (s.d.). Rules. [Regras clássicas de Sokoban](https://sokoban.jp/rule.html). Acesso em 30 de setembro de 2026. Os exemplos são ilustrações originais dessas regras e da mecânica de OutBrick. As pesquisas a seguir contextualizam busca, envolvimento e motivação; nenhuma avalia OutBrick de forma independente.',
      ] },
    },
    pullQuote: 'Um tabuleiro organizado e um tabuleiro solucionável não são a mesma coisa.',
    faqs: [
      { question: 'É possível puxar uma caixa no Sokoban clássico?', answer: 'Não. O personagem pode empurrar uma caixa para uma casa vazia, mas não pode puxá-la nem empurrar uma sequência de caixas. Variantes podem ter regras diferentes.' },
      { question: 'Por que um canto é perigoso no Sokoban?', answer: 'Uma caixa empurrada para um canto que não é objetivo pode ficar imóvel, pois o personagem não consegue chegar aos lados necessários para tirá-la dali. Confira o destino e os acessos futuros do personagem.' },
      { question: 'OutBrick move uma casa por vez, como Sokoban?', answer: 'Os blocos de OutBrick deslizam na direção escolhida até algo pará-los. O planejamento envolve pontos de parada e saídas da mesma cor, não a posição de onde um personagem empurraria.' },
      { question: 'Saber jogar Sokoban torna OutBrick fácil automaticamente?', answer: 'Alguns hábitos, como conferir a ordem dos movimentos e preservar rotas, podem ajudar. As regras de movimento são diferentes; confira se cada tática funciona no novo jogo em vez de presumir que será transferida.' },
    ],
  },
  'puzzle-hints-without-spoilers': {
    title: 'Dicas sem spoilers: como ajudar alguém em um quebra-cabeça',
    dek: 'Peça e ofereça dicas sem revelar toda a resposta: combine os limites, dê uma pista de cada vez e deixe quem está resolvendo no controle.',
    imageAlt: 'Dois personagens de OutBrick ao lado de blocos coloridos e um celular sobre fundo geométrico escuro',
    tags: ['jogos sociais', 'jogos de quebra-cabeça', 'resolução de problemas', 'hábitos de jogo', 'jogos em família'],
    intro: 'Você percebe o próximo movimento antes do seu amigo. Sua mão vai em direção ao celular dele, pronta para dizer: “É só mover aquele bloco”. Então você se lembra de que ficar preso também faz parte da diversão. Uma dica pode abrir uma possibilidade, mas também tirar uma decisão que a pessoa queria tomar. O mais útil é combinar quanta ajuda faz sentido naquele momento. Este guia propõe uma forma gradual de pedir e dar pistas, seja ao compartilhar o desafio diário, observar alguém da família ou responder a uma captura de tela no grupo. Os exemplos são originais; as pesquisas dão contexto sobre feedback, tutoria e experiência de jogo, mas não testaram um sistema de dicas para OutBrick.',
    keyTakeaways: [
      'Peça permissão e combine se a pessoa quer uma pergunta, uma dica pequena, o próximo movimento ou a solução completa.',
      'Dê uma pista delimitada e pare. Uma sequência de dicas não solicitadas pode revelar tanto quanto um passo a passo.',
      'Seja específico e respeitoso, sinalize spoilers em espaços públicos e deixe quem resolve decidir quando quer mais informação.',
    ],
    sections: {
      'agree-on-the-help': { title: 'Combine a ajuda antes de oferecê-la', paragraphs: [
        '“Quer uma dica?” é um bom começo, mas não define o tamanho dela. Uma pessoa pode querer que você aponte o que passou despercebido; outra pode querer saber o próximo movimento para continuar. Depois de pedir permissão, ofereça opções simples: uma pergunta sobre o tabuleiro, uma pista sobre uma área, um movimento direto ou a resposta completa. São pedidos diferentes, nenhum é moralmente melhor que outro.',
        'Quem pede ajuda pode dizer: “Quero uma dica pequena, não o movimento. Tentei liberar o corredor da direita, mas não consigo alinhar o bloco azul”. Isso identifica o problema e o limite do spoiler. Se quer um passo a passo, diga. Ninguém precisa provar que sofreu o bastante nem transformar o lazer em uma prova.',
        'Koedinger e Aleven (2007) revisaram experimentos com tutores cognitivos e descreveram o equilíbrio difícil entre dar informação e retê-la para apoiar o aprendizado. O dilema deles se refere a ambientes educativos, não à etiqueta em um chat de jogo. A analogia é útil: mais informação nem sempre é a informação certa, mas esconder tudo também não é necessariamente útil.',
        'A preferência pode mudar. Quem pediu uma pista leve talvez depois queira o movimento exato; quem queria companhia pode preferir resolver sozinho. Pergunte novamente em uma pausa natural em vez de presumir que o primeiro acordo controla a sessão inteira. Quem está com o quebra-cabeça continua escolhendo como quer passar a tarde.',
      ] },
      'a-ladder-of-clues': { title: 'Avance pelas pistas uma etapa de cada vez', paragraphs: [
        'Imagine um tabuleiro de deslizamento em que o bloco vermelho precisa de um ponto de parada antes de se alinhar com o portão. Comece perguntando: “Onde o vermelho vai parar se o corredor estiver vazio?”. Isso não revela uma sequência; convida a conferir uma regra e observar o resultado. Se a pessoa já entende, não repita a mesma dica em voz mais alta. Pergunte se ela quer avançar.',
        'Uma pista direcional poderia ser: “Outro bloco pode funcionar como freio”. Uma mais específica: “Olhe a peça acima do cruzamento”. Uma dica explícita diria qual movimento fazer; uma solução completa apresentaria a sequência desde uma posição definida. Esta é uma proposta de conversa, não uma garantia de que cada pista será igualmente sutil em todo tabuleiro.',
        'O tamanho do spoiler depende do quebra-cabeça. “Use o bloco verde” pode revelar quase tudo em um tabuleiro pequeno e quase nada em um grande. Por isso, descreva a informação antes de oferecê-la: “Posso dizer qual peça, se você quiser”. Assim, a pessoa decide sem receber primeiro justamente o que queria evitar.',
        'Depois de dar uma dica, pare de escrever e deixe a pessoa pensar. Não emende “e depois”, “é óbvio” nem uma sequência de setas enquanto ela ainda está considerando. Nossa [guia para ler o tabuleiro antes de mover](/blog/how-to-read-a-puzzle-before-moving) sugere perguntas que não entregam a solução. A meta é ajudar a notar algo, não provar que você é esperto.',
      ] },
      'be-specific-without-judging': { title: 'Seja específico sobre o jogo e gentil com a pessoa', paragraphs: [
        '“Pense melhor” não é uma dica nem um diagnóstico útil. “Você está olhando para a coisa errada” pode até ser verdade, mas não diz o que observar. Uma sugestão melhor aponta uma consequência que a pessoa pode verificar: “Se você mover esse obstáculo agora, o que vai parar o bloco comprido?”. Assim, você orienta sem julgar a capacidade de alguém por uma posição no tabuleiro.',
        'Shute (2008) revisou feedback formativo e destacou informações específicas e de apoio, cuja eficácia depende de quem aprende e da tarefa. É uma revisão educacional ampla, não uma prova de que determinada frase melhore o desempenho em quebra-cabeças. Aplicamos a diferença prática entre comentar a tarefa e avaliar a pessoa: explique a restrição em vez de chamar alguém de distraído ou lento.',
        'Um bom feedback também pode confirmar uma ideia válida. “Sim, faz sentido manter essa passagem aberta; o problema é o ponto de parada depois” mostra qual parte do raciocínio funciona. Isso evita substituir o plano inteiro quando só uma suposição precisa mudar. Se não souber a resposta, diga e investiguem juntos em vez de apresentar um palpite como solução confirmada.',
        'Evite pegar o aparelho, mover uma peça sem perguntar ou narrar cada pensamento por cima do ombro. Esses hábitos tiram o tempo que a pessoa teria para relacionar a pista ao tabuleiro. Nossa [guia de competição amigável](/blog/friendly-competition-with-friends) também recomenda combinar a experiência que vocês querem compartilhar. Ajudar é tanto um acordo social quanto uma troca de informações.',
      ] },
      'give-the-solver-space': { title: 'Dê espaço para a pessoa usar a dica', paragraphs: [
        'Mesmo depois de ler uma pista, a pessoa pode precisar de tempo para entender por que ela importa. Se quiser companhia, pergunte o que ela está considerando, mas não exija uma explicação correta antes de oferecer outra dica. “Acho que o azul precisa ficar onde está” pode bastar para retomar a exploração. Às vezes, entender o beco sem saída já ajuda, mesmo antes de encontrar a saída.',
        'Aleven et al. (2016) revisaram a busca por ajuda em sistemas de tutoria inteligentes. O feedback em sala levou os alunos a usar a ajuda com mais intenção, inclusive depois que o feedback terminou, mas não melhorou os resultados de aprendizagem no domínio. Esse limite importa: usar ajuda com critério e ter um desempenho melhor são afirmações diferentes. Não prometemos que pistas graduais tornarão alguém melhor em quebra-cabeças.',
        'Iacovides et al. (2015) usaram estudos de caso para examinar compreensão e envolvimento em jogos. Os relatos destacaram a importância de a pessoa sentir que é responsável pelo próprio progresso. Isso sustenta a decisão editorial de deixar as escolhas com quem joga, mas não prova que revelar um movimento estrague a diversão. Para quem quer a resposta completa, recebê-la pode ser exatamente o que torna a sessão agradável.',
        'Se a dica não ajudou, confira se vocês estão olhando para a mesma posição. Uma captura de tela feita antes de vários movimentos pode deixar uma dica correta sem utilidade. Identifique a posição atual, o jogo ou fase e qualquer regra diferente antes de enviar uma sequência. Vocês também podem voltar a um [desafio diário de OutBrick](/daily) e praticar perguntas de observação, com permissão.',
      ] },
      'public-spoilers-and-clean-finishes': { title: 'Deixe claro o limite para spoilers em público', paragraphs: [
        'Em um grupo, quem pediu ajuda não é a única pessoa que pode ler a mensagem. Identifique o quebra-cabeça e a data antes da resposta e use os controles de spoiler do serviço, se houver. Se não houver, deixe a solução fora da prévia pública e pergunte se a pessoa quer uma resposta privada. Evite enviar a imagem do tabuleiro resolvido sem aviso: ela pode entregar tudo antes que alguém leia o alerta abaixo.',
        'Use um rótulo simples, como “dica pequena: pontos de parada” ou “a seguir, solução completa”. Não coloque o movimento revelador no título, na notificação ou na primeira linha antes do aviso. Explique se a sequência começa no tabuleiro original ou na posição enviada pela pessoa. Esse detalhe pode evitar que instruções úteis confundam os demais.',
        'Quando o quebra-cabeça terminar, pergunte se a pessoa quer conversar sobre como a dica ajudou. Talvez goste de reconstruir o momento decisivo ou prefira seguir em frente. Se revelar mais do que pretendia, reconheça brevemente e faça diferente na próxima vez. Não precisa defender o spoiler dizendo que a resposta era óbvia.',
        `Vocês podem praticar a regra de deslizar até parar em nossos [tabuleiros no navegador](/play) ou [baixar OutBrick pela App Store](${appStoreUrl('journal-hint-etiquette')}) após conferir a página atual. Para dúvidas sobre o jogo ou comportamentos inesperados, a [página de suporte](/support) oferece o canal de contato existente. Uma amizade pode pedir companhia, um empurrãozinho ou uma resposta. Uma boa etiqueta torna essa escolha fácil de expressar e respeitar.`,
      ] },
    },
    pullQuote: 'A meta é ajudar a notar algo, não provar que você é esperto.',
    faqs: [
      { question: 'Como pedir uma dica sem receber spoilers?', answer: 'Diga quanta ajuda quer e o que já tentou, por exemplo: “uma pergunta de observação, não o próximo movimento”. Peça que a pessoa espere antes de dar uma pista mais explícita.' },
      { question: 'O que devo fazer antes de dar uma dica?', answer: 'Peça permissão e combine se a pessoa quer uma pergunta, uma pista pequena, um movimento direto ou a solução completa. Dê uma resposta delimitada e deixe que ela decida se quer mais.' },
      { question: 'Usar uma dica é trapacear?', answer: 'Em uma atividade de lazer individual, você escolhe quanta ajuda quer. Se participar de uma competição ou desafio compartilhado, combine as regras antes e informe com honestidade que tipo de ajuda recebeu.' },
      { question: 'Como compartilhar a solução do desafio diário com segurança?', answer: 'Identifique o quebra-cabeça e a data, sinalize o spoiler e use os controles disponíveis. Mantenha movimentos reveladores e imagens resolvidas fora de títulos, prévias e primeiras linhas sem proteção.' },
    ],
  },
};
