import type { ExtraGuides } from '../../i18n/blog';

export const ptBR2: ExtraGuides = {
  'gaming-before-bed-sleep': {
    title: 'Jogar antes de dormir prejudica o sono?',
    dek: 'O que estudos do sono, grandes levantamentos e pesquisas sobre adiar a hora de dormir revelam sobre jogos à noite.',
    imageAlt: 'Flurry e Peach ao lado de um iPhone com o mapa Jornada de OutBrick em uma parede de blocos azul-marinho',
    tags: ['sono', 'jogos saudáveis', 'hábitos de jogo', 'hora de dormir', 'tempo de tela'],
    intro: 'São onze e meia da noite, as luzes estão apagadas e falta um tabuleiro para você dormir. Ou três. A preocupação de que jogar tarde esteja roubando seu descanso é comum, e há pesquisas sobre isso. Mas os resultados complicam a resposta simples: a duração da sessão e o que ela toma do seu tempo parecem importar mais do que simplesmente jogar.',
    keyTakeaways: ['Em laboratório, uma sessão comum antes de dormir atrasou o sono só um pouco; uma sessão bem mais longa reduziu o descanso em quase meia hora.', 'Levantamentos associam mais tempo de jogo a horários tardios e sono pior, mas não mostram causa e efeito; as associações costumam ser pequenas.', 'O risco maior pode ser adiar o sono porque o jogo não oferece um momento natural para parar.'],
    sections: {
      'what-the-sleep-lab-found': { title: 'O que acontece no laboratório do sono', paragraphs: ['As evidências mais controladas vêm de estudos em laboratórios do sono. Weaver e colegas pediram que 13 adolescentes do sexo masculino, que se descreviam como notívagos, jogassem um videogame ativo ou assistissem a um DVD por 50 minutos antes de dormir. Depois do jogo, demoraram um pouco mais para adormecer e sentiram menos sono, mas as mudanças foram pequenas; a estrutura do sono não mudou.', 'A duração parece fazer diferença. King e colegas observaram 17 adolescentes jogando um título de ação violento por 50 ou 150 minutos em noites diferentes. Após a sessão longa, o tempo total de sono caiu cerca de 27 minutos, a eficiência ficou abaixo de 85% e eles relataram levar aproximadamente 17 minutos a mais para dormir. A frequência cardíaca não mudou entre as noites.', 'Os dois estudos são pequenos, envolveram apenas adolescentes do sexo masculino e usaram jogos de ação. Não dizem o que um quebra-cabeça tranquilo faz com uma pessoa de 40 anos. Sugerem, porém, que uma sessão normal não é igual a jogar até a meia-noite.'] },
      'what-surveys-show': { title: 'O que grandes levantamentos mostram — e o que não mostram', paragraphs: ['Levantamentos alcançam mais pessoas. Exelmans e Van den Bulck entrevistaram 844 adultos flamengos, de 18 a 94 anos. Mesmo considerando idade, sexo, escolaridade, exercício e estresse, quem jogava mais relatou pior qualidade do sono, mais cansaço e mais sintomas de insônia. Cada hora diária adicional de jogo esteve associada a dormir cerca de sete minutos mais tarde e acordar cerca de 14 minutos mais tarde.', 'Uma revisão de 67 estudos com crianças e adolescentes encontrou associação entre tempo de tela e sono mais curto ou mais tardio em 90% dos estudos. Os autores ressaltaram que isso não demonstra causa e efeito, que as medidas eram imperfeitas e que poucos estudos analisaram o conteúdo da tela.', 'Em uma análise pré-registrada de mais de 50 mil crianças dos Estados Unidos, cada hora de tela esteve associada a três a oito minutos a menos de sono por noite. O tempo de tela explicou menos de 2% das diferenças no sono; o contexto, como a rotina familiar, pareceu mais relevante.', 'Também há uma dúvida de causa e efeito: alguém que já dorme mal pode recorrer a um jogo porque não consegue dormir. Um levantamento feito em um único momento não distingue essas possibilidades. As associações servem como motivo para observar sua rotina, não como prova de que o jogo seja culpado.'] },
      displacement: { title: 'O custo costuma ser o tempo que o jogo ocupa', paragraphs: ['Se jogar não deixa o cérebro muito agitado, por que sessões tardias ainda pesam? Uma resposta é simples: o sono que não começa não acontece. Em outro estudo, 338 jovens adultos levavam em média 39 minutos entre deitar e desligar as luzes. Quem demorava mais de uma hora tinha probabilidade mais de nove vezes maior de ser classificado como alguém que dormia mal. Como a amostra foi de conveniência, os números são indicativos, não representativos.', 'A procrastinação na hora de dormir é ir para a cama mais tarde do que se pretendia, sem uma razão externa. Em uma amostra representativa de 2.431 adultos holandeses, esse comportamento era comum e ajudava a explicar a relação entre menor autorregulação e sono insuficiente. Atividades sem fim natural, como muitos jogos, facilitam esse adiamento.', 'A pergunta mais útil talvez seja “o jogo faz mal ao sono?” ou “ele terminou quando eu queria parar?”. A absorção associada ao [estado de fluxo](/blog/flow-in-puzzle-games) também pode fazer o tempo passar sem perceber. Veja nosso artigo sobre [quando jogar e quando deixar o celular de lado](/blog/when-to-play-and-when-to-pause).'] },
      'playing-at-night-without-paying-for-it': { title: 'Como jogar à noite sem pagar o preço no sono', paragraphs: ['Você não precisa abandonar um jogo à noite. Vale decidir como será a sessão antes de começar. As sugestões abaixo decorrem das pesquisas, mas nenhuma foi testada como tratamento para problemas de sono.', 'OutBrick é um exemplo do formato que buscamos: cada tabuleiro tem limite de movimentos, nunca cronômetro, e terminar leva a uma tela que funciona como ponto final. O [tabuleiro diário](/daily) acaba depois de uma partida. Ao dormir, lembre-se: abandonar um tabuleiro depois de fazer um movimento conta como tentativa perdida e consome uma vida. Termine o tabuleiro ou pare entre partidas. A página inicial explica [o custo de vidas, ações de desfazer e anúncios](/#fair).'], bullets: ['Decida quantos tabuleiros ou rodadas vai jogar antes de começar.', 'Quando estiver tarde, prefira jogos com um fim claro a modos intermináveis.', 'Deixe sessões longas e tensas para mais cedo; no laboratório, os efeitos aumentaram com a duração.', 'Se você adia o sono já na cama, tire o jogo da rotina do quarto em vez de depender apenas da força de vontade.', 'Prefira uma experiência tranquila, sem cronômetros ou recompensas piscantes; veja nosso [guia sobre jogos de quebra-cabeça relaxantes](/blog/relaxing-puzzle-games-what-makes-one-calm).'] },
      'when-to-look-closer': { title: 'Quando vale observar mais de perto', paragraphs: ['A maioria das pessoas que joga antes de dormir não terá um problema de sono por causa disso. Se você fica acordado com frequência, desperta sem se sentir descansado ou depende de um jogo para atravessar a noite, o jogo pode ser sintoma, não causa. O NHS oferece orientações práticas sobre [como adormecer mais rápido e dormir melhor](https://www.nhs.uk/every-mind-matters/mental-wellbeing-tips/how-to-fall-asleep-faster-and-sleep-better/); vale conversar com um clínico geral sobre insônia persistente.', 'Para ver como essas perguntas se aplicam às telas em geral, leia nossa análise dos [mitos sobre tempo de tela](/blog/screen-time-myths-research).'] },
    },
    pullQuote: 'A pergunta mais útil talvez seja “o jogo faz mal ao sono?” ou “ele terminou quando eu queria parar?”.',
    faqs: [{ question: 'Faz mal jogar videogame antes de dormir?', answer: 'Não necessariamente. Estudos de laboratório observaram apenas um pequeno atraso após uma sessão comum; uma sessão de duas horas e meia reduziu o sono total em cerca de 27 minutos. A duração e o sono que a sessão substitui parecem importar mais.' }, { question: 'Quanto tempo antes de dormir devo parar de jogar?', answer: 'Nenhum estudo estabeleceu um limite universal. Uma opção prática é decidir quantas partidas fará antes de começar e parar em um fim natural, sem esperar sentir sono.' }, { question: 'Jogos de quebra-cabeça são melhores que jogos de ação antes de dormir?', answer: 'Poucos estudos compararam gêneros diretamente. Os experimentos com efeitos mais claros usaram jogos de ação em sessões longas. Uma partida curta, tranquila e com fim definido pode ser uma escolha razoável, mas não foi comprovada como melhor para o sono.' }, { question: 'O que é procrastinação na hora de dormir?', answer: 'É ir para a cama mais tarde do que se pretendia sem uma razão externa. Uma grande amostra holandesa encontrou esse comportamento com frequência e sua associação com dormir menos.' }],
  },
  'micro-breaks-at-work-short-game': {
    title: 'Pausa no trabalho: um jogo curto ajuda a recarregar?', dek: 'Uma meta-análise indica que pausas de até dez minutos aumentam a energia, mas pouco alteram o desempenho. Veja onde um jogo curto pode caber.', imageAlt: 'Poppy com sua varinha de estrela e Bricko ao lado de um iPhone com um tabuleiro Super Difícil de OutBrick', tags: ['micropausas', 'bem-estar', 'sessões curtas', 'jogos casuais', 'recuperação'],
    intro: 'No meio da tarde, a atenção começa a falhar. Você relê o mesmo parágrafo, abre uma aba e esquece por quê. Muita gente pega o celular; um jogo rápido é uma das opções. Isso é uma pausa de verdade ou apenas outra forma de gastar atenção? Pesquisas sobre micropausas oferecem uma resposta mais útil do que “jogos são perda de tempo” ou “jogos renovam o cérebro”.', keyTakeaways: ['Uma meta-análise de 2022 concluiu que pausas de até dez minutos aumentam a energia e reduzem o cansaço, ainda que modestamente.', 'A mesma análise não encontrou melhora clara no desempenho geral, exceto em tarefas menos exigentes; trabalhos cansativos podem pedir pausas maiores.', 'Um jogo casual curto pode melhorar o humor após uma tarefa exigente, mas há poucas evidências de que recupere a concentração.'],
    sections: {
      'what-a-micro-break-does': { title: 'O que uma micropausa realmente faz', paragraphs: ['Micropausa é uma pausa de até cerca de dez minutos durante o trabalho, não o almoço ou uma noite livre. A síntese mais abrangente é uma revisão sistemática e meta-análise de 2022, de Albulescu e colegas, que reuniu 22 amostras e 2.335 participantes.', 'Os resultados foram consistentes, mas modestos: as pausas aumentaram o vigor e reduziram o cansaço, com efeitos pequenos, de cerca de um terço de desvio-padrão. O efeito no desempenho geral não foi estatisticamente confiável. As pausas ajudaram apenas em tarefas menos exigentes; para se recuperar de trabalho muito desgastante, talvez sejam necessários mais de dez minutos.', 'Um efeito de aproximadamente um terço de desvio-padrão é uma diferença que você pode notar em algumas tardes e não em outras. É real, mas não transforma o dia. Os estudos também variaram entre trabalhadores e estudantes e geralmente mediram como as pessoas se sentiam logo após a pausa.', 'A expectativa razoável é voltar se sentindo um pouco melhor, sem esperar ficar visivelmente mais afiado para uma tarefa difícil.'] },
      'not-all-breaks-are-equal': { title: 'Nem toda pausa ajuda da mesma forma', paragraphs: ['O que você faz na pausa parece importar. Kim, Park e Niu acompanharam 86 trabalhadores de escritório sul-coreanos durante dez dias úteis. Relaxar e conversar com colegas amenizou a relação entre carga de trabalho pesada e mau humor no fim do dia. Bebidas com cafeína também tiveram esse efeito.', 'A surpresa foi a categoria chamada de atividades cognitivas: tarefas que mantêm a mente ocupada durante a pausa. Em dias puxados, elas intensificaram a relação entre carga de trabalho e mau humor. O estudo não testou jogos, e um quebra-cabeça não é uma caixa de entrada. Ainda assim, uma pausa que continua exigindo atenção pode não parecer descanso às cinco da tarde.'] },
      'the-attention-question': { title: 'Trocar de tarefa recupera a atenção?', paragraphs: ['Uma ideia popular diz que mudar brevemente de atividade reinicia a atenção. Ariga e Lleras deram às pessoas uma tarefa longa e monótona de vigilância. Quem precisava interrompê-la de vez em quando para recordar números não apresentou a queda de desempenho habitual. O estudo é citado como prova de que pequenas pausas mantêm o foco.', 'Um estudo posterior bem maior não encontrou o mesmo resultado. Helton e Russell testaram 498 pessoas em condições com breves trocas de tarefa, sinais sem conteúdo e controles. Todos tiveram a mesma queda constante; a análise favoreceu a ausência de efeito. O mecanismo segue em debate, e trocar rapidamente de tarefa não é uma solução confiável para a concentração em queda.'] },
      'where-a-short-game-fits': { title: 'Onde um jogo curto pode se encaixar', paragraphs: ['O teste mais direto foi um estudo de laboratório de Rupp e colegas. Depois de uma tarefa cansativa de vigilância, participantes fizeram uma pausa passiva, um exercício guiado de relaxamento ou jogaram um videogame casual. O grupo do jogo relatou mais envolvimento e maior melhora no humor do que o grupo de relaxamento; a pausa simples piorou um pouco o humor. Nenhuma condição recuperou o desempenho em um teste de memória de trabalho.', 'As pessoas já usam jogos assim. Em uma pesquisa com 833 trabalhadores que jogavam jogos casuais on-line, Reinecke observou que a sensação de recuperação durante o jogo era o principal fator associado a jogar no trabalho, e pessoas mais cansadas jogavam com mais frequência. Como a amostra respondeu a uma pesquisa sobre jogos, ela descreve alguns jogadores, não comprova eficácia.', 'Em conjunto, os estudos sugerem que um jogo curto pode ser uma pausa para o humor, não um tônico de concentração. Funciona melhor se continuar curto e terminar de forma clara. Se dez minutos viram quarenta, o restante da tarde sofre. Veja [por que um quebra-cabeça de dois minutos pode parecer uma pausa de verdade](/blog/why-two-minute-puzzles-feel-good) e [como encaixar um jogo no trajeto](/blog/commuter-puzzle-two-minute).'] },
      'a-better-micro-break': { title: 'Uma pausa melhor, com ou sem jogo', paragraphs: ['As pesquisas apontam para variedade, não um truque único. Se escolher um jogo, prefira um com fim definido. Um tabuleiro de OutBrick tem objetivos e limite de movimentos, não tem cronômetro e termina com uma tela de conclusão. Também dá para jogar [um tabuleiro no navegador](/play), sem instalar nada. Encare-o como uma opção entre outras, algumas com evidências mais fortes.', 'O lugar da pausa pode importar tanto quanto a atividade. Alguns minutos ao ar livre ou perto de uma janela podem ajudar mais uma mente cansada do que uma tela; explicamos isso em [restauração da atenção e cenas tranquilas](/blog/attention-restoration-calm-scenes). Uma micropausa também não substitui o descanso depois do trabalho, tema de [jogos casuais e recuperação após o expediente](/blog/casual-games-stress-recovery-after-work).'], bullets: ['Levante e se movimente ou converse com alguém: relaxamento e interação social tiveram os benefícios mais claros para o humor.', 'Mantenha a pausa curta e defina a duração antes; um tabuleiro ou uma rodada, depois volte.', 'Espere se sentir melhor, não pensar mais rápido, especialmente após trabalho exigente.', 'Depois de tarefas muito desgastantes, faça uma pausa mais longa em vez de várias pausas minúsculas.', 'Se a pausa virou mais leitura e rolagem de tela, observe se ela está trazendo descanso.'] },
    }, pullQuote: 'Em conjunto, os estudos sugerem que um jogo curto pode ser uma pausa para o humor, não um tônico de concentração.', faqs: [{ question: 'Quanto deve durar uma micropausa?', answer: 'Em geral, até dez minutos. Uma meta-análise de 2022 concluiu que elas aumentam a energia e reduzem o cansaço; pausas mais longas tendiam a ajudar mais o desempenho, então tarefas muito desgastantes podem exigir mais tempo.' }, { question: 'Jogar durante uma pausa melhora a produtividade?', answer: 'As evidências são mais fortes para o humor do que para o desempenho. Um estudo de laboratório observou melhora no humor e no envolvimento após uma tarefa exigente, mas não recuperou a memória de trabalho.' }, { question: 'O que fazer em uma pausa curta?', answer: 'Em um estudo de dez dias com trabalhadores de escritório, relaxamento e interação social foram os mais úteis para o humor no fim do dia; atividades mentalmente exigentes tiveram efeito oposto. Caminhar, conversar ou jogar algo curto e delimitado são opções razoáveis.' }],
  },
  'flow-in-puzzle-games': {
    title: 'Fluxo em jogos de quebra-cabeça: desafio na medida', dek: 'Por que algumas partidas parecem naturais, o que estudos com Tetris revelam sobre fluxo e como encontrar seu nível de desafio.', imageAlt: 'Um tabuleiro colorido de OutBrick com blocos alinhados e uma saída aberta', tags: ['estado de fluxo', 'jogos de quebra-cabeça', 'dificuldade', 'design de jogos', 'atenção'],
    intro: 'Às vezes, um quebra-cabeça prende sua atenção sem esforço. Em outras, é fácil demais ou tão difícil que dá vontade de desistir. Psicólogos chamam de fluxo a experiência de envolvimento profundo entre esses extremos. A ideia é útil para pensar em jogos, mas não é uma fórmula mágica nem um resultado garantido. Equilibrar desafio e habilidade ajuda, mas não basta para produzir fluxo. Leia também: [leia também](/blog/relaxing-puzzle-games-what-makes-one-calm), [saiba mais](/blog/kinder-difficulty-curve), [veja também](/blog/colour-sort-puzzle-tips), [leia mais](/blog/gaming-before-bed-sleep), [este artigo relacionado](/play)',
    keyTakeaways: ['Fluxo descreve envolvimento intenso, com metas claras e retorno compreensível sobre suas ações.', 'Equilibrar desafio e habilidade ajuda, mas não basta para produzir fluxo.', 'Um bom jogo permite ajustar o desafio e fazer pausas; a experiência varia de pessoa para pessoa.'],
    sections: {
      'what-flow-feels-like': { title: 'Como é o fluxo e como ele é medido', paragraphs: ['O fluxo é uma experiência de concentração e envolvimento em que a ação parece seguir sem esforço. Jackson e Marsh desenvolveram uma escala para medir esses relatos; ela capta vários aspectos, não um botão que liga ou desliga uma experiência universal.', 'A escala inclui dimensões como equilíbrio entre desafio e habilidade, metas claras e retorno sobre as ações. Ela mede relatos da experiência, não comprova uma causa.'], bullets: ['Metas claras ajudam a entender o que fazer.', 'O retorno sobre as ações permite ajustar o próximo movimento.', 'A tarefa exige habilidade, mas não parece impossível.', 'A atenção fica concentrada na atividade.', 'A noção do tempo pode mudar.', 'A experiência pode ser gratificante por si só.'] },
      'the-balance-experiments': { title: 'Testando o ponto ideal', paragraphs: ['O modelo popular prevê fluxo quando o desafio combina com a habilidade. Estudos experimentais investigam essa relação, mas os resultados dependem de como desafio e habilidade são medidos.', 'Harmat e colegas estudaram respostas fisiológicas durante partidas de computador, incluindo Tetris. Medidas do corpo podem acompanhar o envolvimento, mas não provam que todo jogador esteja em fluxo nem que um jogo cause bem-estar.', 'O equilíbrio é uma explicação útil para ajustar a dificuldade, não uma garantia. Preferências, objetivos e contexto também influenciam a experiência. Equilibrar desafio e habilidade ajuda, mas não basta para produzir fluxo.'] },
      'balance-is-not-enough': { title: 'Equilíbrio é necessário, mas não suficiente', paragraphs: ['Keller e Bless mostraram que a compatibilidade entre desafio e habilidade interage com as metas da pessoa. Uma tarefa equilibrada pode ainda não envolver alguém que não veja sentido nela.', 'Fullagar e colegas também relacionaram equilíbrio entre desafio e habilidade, fluxo e ansiedade de desempenho. Pressão e contexto podem mudar como a mesma tarefa é sentida.'] },
      'how-games-design-for-flow': { title: 'Como jogos podem favorecer o fluxo', paragraphs: ['O modelo GameFlow de Sweetser e Wyeth organiza fatores de prazer em jogos, como concentração, desafio, habilidade, controle e retorno. É uma estrutura para avaliar design, não uma comprovação de que qualquer recurso produza fluxo.', 'Em um quebra-cabeça, regras legíveis e movimentos previsíveis ajudam a pessoa a formar um plano. Se a regra surpreende sem explicação, a dificuldade parece injusta em vez de estimulante.', 'Ajustes graduais permitem que a pessoa encontre um desafio adequado. Um jogo também deve deixar claro quando a partida terminou, para que o envolvimento não vire obrigação.'] },
      'finding-your-sweet-spot': { title: 'Encontre seu próprio ponto ideal', paragraphs: ['Seu ponto ideal pode mudar de um dia para o outro. Perceba se a partida parece interessante e compreensível, e escolha um nível que combine com sua energia atual.', 'Não existe um nível ideal igual para todo mundo; suas preferências e seu contexto também contam.'], bullets: ['Comece por um desafio que você consiga explicar.', 'Se estiver fácil demais, avance um pouco.', 'Se estiver frustrante, reduza o ritmo ou faça uma pausa.', 'Observe o que torna a partida agradável para você.'] },
    }, pullQuote: 'Equilibrar desafio e habilidade ajuda, mas não basta para produzir fluxo.', faqs: [{ question: 'O que é fluxo em um jogo?', answer: 'É um estado de envolvimento profundo, geralmente associado a concentração, metas claras e retorno compreensível sobre as ações. As pessoas vivenciam isso de formas diferentes.' }, { question: 'Um jogo precisa ser difícil para gerar fluxo?', answer: 'Não. O desafio precisa combinar com a habilidade da pessoa, mas outros fatores, como metas, controle e interesse, também importam.' }, { question: 'Jogar Tetris causa fluxo?', answer: 'Estudos examinaram o envolvimento e respostas fisiológicas durante jogos como Tetris. Isso não significa que toda partida cause fluxo para todos.' }, { question: 'Como encontro um jogo que me coloque em fluxo?', answer: 'Procure regras compreensíveis, metas claras e um nível de desafio que você possa ajustar. Se a experiência ficar frustrante ou cansativa, faça uma pausa.' }],
  },
  'screen-time-myths-research': {
    title: 'Mitos sobre tempo de tela: o que os estudos mostram', dek: 'O que grandes estudos realmente encontraram sobre telas, bem-estar, tempo de uso e a qualidade das medidas.', imageAlt: 'Uma pessoa usando o celular para jogar um quebra-cabeça', tags: ['tempo de tela', 'bem-estar digital', 'pesquisa', 'adolescentes', 'jogo saudável'],
    intro: 'Discussões sobre telas costumam oscilar entre “qualquer uso faz mal” e “telas não importam”. Grandes estudos oferecem uma resposta menos dramática: as associações médias com bem-estar tendem a ser pequenas, variam conforme a pessoa e não explicam sozinhas o que acontece na vida de alguém. O tempo de tela, sozinho, explica uma parte pequena das diferenças observadas. Leia também: [leia também](/blog/relaxing-puzzle-games-what-makes-one-calm), [este artigo relacionado](/blog/kinder-difficulty-curve), [saiba mais](/blog/colour-sort-puzzle-tips), [veja também](/blog/gaming-before-bed-sleep), [leia mais](/play) Leia também: [leia também](/blog/gaming-before-bed-sleep), [este artigo relacionado](/blog/does-digital-detox-work), [saiba mais](/blog/is-gaming-good-or-bad-for-mood), [veja também](/blog/designing-for-real-life-play), [leia mais](/research)', keyTakeaways: ['Estudos grandes encontram associações pequenas entre tecnologia digital e bem-estar adolescente.', 'Isso não prova que o tempo de tela cause mudanças de humor, boas ou ruins.', 'Autorrelatos de uso podem divergir dos registros digitais; contexto e conteúdo também contam.'],
    sections: {
      'myth-more-screens-worse-wellbeing': { title: 'Mito: mais tela significa menos bem-estar', paragraphs: ['Orben e Przybylski analisaram grandes conjuntos de dados sobre adolescentes. A associação entre uso de tecnologia digital e bem-estar foi negativa, mas muito pequena.', 'Uma associação média não descreve cada pessoa. Ela também não informa se o uso da tela piorou o bem-estar ou se pessoas que se sentiam mal usaram mais a tecnologia.', 'A conclusão responsável é que o tempo de tela, sozinho, explica uma parte pequena das diferenças observadas.'] },
      'myth-any-amount-harms': { title: 'Mito: qualquer quantidade faz mal', paragraphs: ['Przybylski e Weinstein testaram a hipótese “Goldilocks”: talvez uma quantidade moderada de uso digital coexistisse com bem-estar, enquanto muito pouco ou muito uso se associasse a resultados piores. Os dados não sustentam regras universais simples.', 'Os estudos observacionais não definem um limite diário que sirva para todo adolescente. Rotina, sono, relações e atividade importam junto com a tela.', 'O resultado não é que todo uso seja inofensivo. É que os dados não justificam tratar qualquer minuto como prejudicial.'] },
      'myth-we-know-our-screen-time': { title: 'Mito: sabemos quanto usamos o celular', paragraphs: ['Parry e colegas compararam registros digitais com estimativas das próprias pessoas em uma revisão sistemática e meta-análise. Os dois tipos de medida frequentemente divergiram.', 'Por isso, uma resposta aproximada à pergunta “quanto tempo passo no celular?” pode não corresponder aos registros. Cada método também tem limites e pode medir coisas diferentes.'] },
      'myth-screens-dont-matter': { title: 'O mito oposto: telas não importam', paragraphs: ['Associações pequenas não significam que o uso seja sempre irrelevante. Uma atividade pode afetar o sono ou substituir uma conversa mesmo quando a relação média em um estudo é fraca.', 'Odgers e Jensen pedem que a pesquisa deixe de lado tanto o alarmismo quanto a displicência. Os efeitos podem depender de quem está usando a tecnologia, de como e em que momento.'] },
      'a-better-question': { title: 'Uma pergunta melhor do que “quantas horas?”', paragraphs: ['Em vez de buscar um número universal, observe o que a atividade substitui e como você se sente. Pesquisas amplas descrevem padrões de grupo; não diagnosticam a rotina de uma pessoa.', 'As próprias medidas têm incerteza, então pequenos números não devem ser tratados como fronteiras precisas.'], bullets: ['O uso está adiando o sono?', 'Você consegue parar quando pretende?', 'A atividade substitui algo importante para você?', 'Como você se sente durante e depois?'] },
    }, pullQuote: 'A conclusão responsável é que o tempo de tela, sozinho, explica uma parte pequena das diferenças observadas.', faqs: [{ question: 'Quanto tempo de tela é demais?', answer: 'As pesquisas não estabeleceram um limite universal que sirva para todas as pessoas. O contexto e o que a tela substitui também importam.' }, { question: 'O tempo de tela causa problemas de saúde mental?', answer: 'Estudos observacionais encontram associações, mas não demonstram por si só que o tempo de tela seja a causa. Em grandes estudos, as associações médias costumam ser pequenas.' }, { question: 'As pessoas sabem quanto tempo passam no celular?', answer: 'Nem sempre. Uma meta-análise constatou divergências frequentes entre estimativas pessoais e registros digitais.' }, { question: 'Devo reduzir meu tempo de tela?', answer: 'Se o uso estiver prejudicando sono, atividades importantes ou relações, experimente uma mudança específica e observe o resultado. Um número isolado não conta a história toda.' }],
  },
  'does-digital-detox-work': {
    title: 'Desintoxicação digital funciona? O que estudos dizem', dek: 'Experimentos sobre reduzir o uso de telas tiveram resultados variados. Veja o que funcionou, o que não funcionou e como testar uma mudança menor.', imageAlt: 'Celular deixado de lado ao lado de um livro e uma xícara', tags: ['desintoxicação digital', 'tempo de tela', 'bem-estar', 'hábitos digitais', 'celulares'],
    intro: 'A ideia de se afastar das telas por completo pode parecer atraente quando o celular ocupa muito espaço. Mas “detox digital” significa coisas diferentes em estudos diferentes. As pesquisas não apontam uma resposta única: reduzir uma atividade específica pode ajudar algumas pessoas, enquanto uma abstinência ampla não garante melhora. Leia também: [leia também](/blog/screen-time-myths-research), [este artigo relacionado](/blog/how-long-to-form-a-habit), [saiba mais](/blog/attention-restoration-calm-scenes), [veja também](/daily), [leia mais](/blog/when-to-play-and-when-to-pause)', keyTakeaways: ['“Detox digital” pode significar desde uma pausa curta até reduzir um aplicativo específico.', 'Experimentos encontraram benefícios em alguns contextos, mas outros não observaram mudanças claras.', 'Uma experiência pequena e mensurável pode ensinar mais do que uma promessa de abstinência total.'],
    sections: {
      'what-counts-as-a-detox': { title: 'O que conta como detox digital', paragraphs: ['Radtke e colegas revisaram estudos sobre detox digital e encontraram definições e métodos variados. Alguns estudos pediram que participantes parassem de usar uma plataforma; outros trataram de reduzir o uso do celular ou fazer uma pausa.', 'Isso dificulta comparar resultados: uma semana sem redes sociais não é a mesma intervenção que limitar notificações. O objetivo e a medida de resultado também variam.', 'Por isso, “detox funciona?” é uma pergunta ampla demais. É melhor especificar qual comportamento se quer mudar e qual resultado espera observar.'] },
      'when-cutting-back-helped': { title: 'Quando reduzir o uso ajudou', paragraphs: ['Hunt e colegas conduziram um experimento com estudantes universitários que limitaram o uso de redes sociais. O grupo de intervenção relatou redução da solidão e de sintomas depressivos após a mudança.', 'Esse achado se refere à intervenção e à amostra estudadas. Não demonstra que todas as pessoas se beneficiarão de uma pausa igual nem que qualquer tela tenha o mesmo efeito.', 'A mudança pode ser mais útil quando mira uma atividade que a própria pessoa percebe como problemática e é possível acompanhar o que acontece depois.'] },
      'when-it-did-not': { title: 'Quando parar não fez diferença', paragraphs: ['Outros estudos não encontraram melhora consistente depois de uma abstinência ou redução. Participantes podem substituir uma atividade por outra, e efeitos esperados podem não aparecer em medidas de bem-estar.', 'A ausência de mudança em um estudo não prova que ninguém se beneficie. Ela mostra que a intervenção testada não produziu um efeito confiável naquele contexto.'] },
      'why-results-differ': { title: 'Por que os resultados apontam em direções diferentes', paragraphs: ['As intervenções, os participantes e os resultados medidos variam. Reduzir um aplicativo específico pode ser diferente de deixar o telefone de lado, e bem-estar não é a mesma coisa que tempo de uso.', 'Também importa o motivo para mudar. Uma pausa escolhida pela pessoa pode ser diferente de uma regra imposta, e resultados de curto prazo não garantem mudanças duradouras.'] },
      'a-smaller-experiment': { title: 'Experimente uma mudança menor', paragraphs: ['Em vez de prometer nunca mais usar telas, escolha uma experiência que caiba na sua rotina. Defina o que vai mudar, por quanto tempo e o que observar. Isso não é tratamento nem substitui ajuda profissional quando necessária.', 'Uma mudança específica pode revelar se uma notificação, um horário ou um aplicativo está interferindo no que importa para você.', 'Se a mudança não ajudar, isso também é informação. Ajuste a experiência em vez de concluir que você falhou.'], bullets: ['Escolha um comportamento concreto para mudar.', 'Defina um período realista e curto.', 'Observe sono, humor ou tempo disponível, conforme seu objetivo.', 'Evite mudar muitas coisas ao mesmo tempo.', 'Mantenha o que funciona e reveja o que não funciona.'] },
    }, pullQuote: 'É melhor especificar qual comportamento se quer mudar e qual resultado espera observar.', faqs: [{ question: 'Um detox digital funciona?', answer: 'Depende do que significa “detox”, da pessoa e do resultado observado. Alguns estudos encontram benefícios em intervenções específicas; outros não encontram mudanças claras.' }, { question: 'Quanto tempo deve durar uma pausa digital?', answer: 'As pesquisas não definiram uma duração universal. Escolha um período viável e uma mudança concreta que permita avaliar o resultado.' }, { question: 'Preciso abandonar todas as telas?', answer: 'Não. Estudos testaram intervenções diferentes, incluindo reduzir o uso de uma plataforma. Uma mudança direcionada pode ser mais prática.' }, { question: 'Reduzir redes sociais melhora o humor?', answer: 'Um experimento com estudantes encontrou redução de solidão e sintomas depressivos após limitar o uso, mas esse resultado não garante o mesmo efeito para todas as pessoas.' }],
  },
  'attention-restoration-calm-scenes': {
    title: 'Restauração da atenção: por que cenas tranquilas ajudam', dek: 'O que a pesquisa sobre atenção restaurada sugere — e por que uma paisagem na tela não equivale a um parque.', imageAlt: 'Uma paisagem tranquila com árvores, água e luz suave', tags: ['atenção', 'restauração', 'natureza', 'pausas', 'bem-estar'],
    intro: 'Depois de muito tempo concentrado, até tarefas simples podem parecer pesadas. A teoria da restauração da atenção sugere que alguns ambientes ajudam a mente a se recuperar. Isso não quer dizer que qualquer imagem calma reproduza os efeitos de estar ao ar livre: a evidência depende do ambiente, da pessoa e da medida usada. Leia também: [leia também](/blog/relaxing-puzzle-games-what-makes-one-calm), [este artigo relacionado](/#journey), [saiba mais](/blog/micro-breaks-at-work-short-game), [veja também](/blog/why-two-minute-puzzles-feel-good)', keyTakeaways: ['A atenção dirigida exige esforço e pode ficar cansada.', 'Pesquisas sobre natureza e restauração são promissoras, mas variam em método e resultado.', 'Uma cena tranquila em um jogo pode tomar emprestadas algumas qualidades, sem equivaler a um parque.'],
    sections: {
      'two-kinds-of-attention': { title: 'Dois tipos de atenção', paragraphs: ['A teoria distingue a atenção dirigida, que usamos para ignorar distrações e manter o foco, de uma atenção mais espontânea atraída por algo interessante. Uma cena tranquila em um jogo pode tomar emprestadas algumas qualidades, sem equivaler a um parque.', 'A primeira pode cansar após esforço prolongado. Um ambiente restaurador talvez permita que ela descanse enquanto a atenção se volta a estímulos suaves.', 'Isso é uma estrutura teórica para pensar em experiências, não uma garantia de que toda pessoa se recuperará do mesmo modo.'] },
      'what-the-evidence-shows': { title: 'O que as evidências mostram', paragraphs: ['Estudos sobre ambientes naturais relatam resultados variados em medidas de atenção, estresse e humor. Alguns comparam caminhadas ou vistas, enquanto outros usam imagens ou tarefas de laboratório.', 'Uma paisagem real envolve sons, movimento, ar e escolha de percurso. Uma imagem em uma tela oferece apenas parte dessa experiência.', 'Os métodos e as amostras variam, então não é possível transformar uma descoberta isolada em promessa de benefício para todos.', 'A conclusão cautelosa é que ambientes naturais podem ser restauradores para algumas pessoas e em certos contextos; a pesquisa não demonstra que um jogo reproduza esse efeito.'] },
      'pictures-are-not-parks': { title: 'Imagens não são parques', paragraphs: ['Uma fotografia de árvores pode ser agradável, mas não oferece o mesmo que caminhar por um parque. Ela não substitui movimento, contato com o ambiente nem o afastamento físico do trabalho.', 'Se puder, uma pausa fora de casa ou perto de uma janela é uma experiência diferente de observar uma imagem no celular.'] },
      'what-a-game-can-borrow': { title: 'O que um jogo tranquilo pode aproveitar', paragraphs: ['Um jogo pode adotar ritmo calmo, metas compreensíveis e ausência de pressão. Esses recursos podem tornar a experiência menos urgente, embora não provem restauração da atenção.', 'O resultado depende de como você reage ao desafio. Um quebra-cabeça frustrante pode exigir ainda mais atenção; uma atividade agradável pode servir como pausa subjetiva.', 'Se o objetivo for descansar, compare o jogo com opções fora da tela e escolha o que funciona para você.'] },
      'an-order-of-preference': { title: 'Uma ordem prática para escolher', paragraphs: ['Pense na pausa como uma escolha, não como uma prescrição.'], bullets: ['Se puder, saia um pouco ou olhe pela janela.', 'Faça uma pausa sem tela quando a atenção estiver cansada.', 'Escolha uma atividade leve que você possa encerrar facilmente.', 'Perceba se a pausa realmente ajudou.', 'Volte ao trabalho com uma expectativa realista.'] },
    }, pullQuote: 'Uma cena tranquila em um jogo pode tomar emprestadas algumas qualidades, sem equivaler a um parque.', faqs: [{ question: 'O que é restauração da atenção?', answer: 'É a ideia de que certos ambientes podem ajudar a recuperar a atenção dirigida após esforço. Os resultados dependem do contexto e de como são medidos.' }, { question: 'Ver imagens da natureza ajuda a concentração?', answer: 'Alguns estudos examinaram imagens e encontraram resultados variados. Uma imagem não equivale a estar em um ambiente natural.' }, { question: 'Um jogo relaxante restaura a atenção?', answer: 'Não há base para afirmar que jogos reproduzem os efeitos de ambientes naturais. Um jogo tranquilo pode ser uma pausa agradável para algumas pessoas.' }, { question: 'Qual é a melhor pausa quando estou cansado?', answer: 'Se possível, experimente sair ou olhar para fora. Uma atividade sem tela e de baixa pressão também pode ajudar; observe o que funciona para você.' }],
  },
  'rewards-streaks-motivation': {
    title: 'Recompensas, sequências e motivação: quando pesam', dek: 'O que estudos sobre recompensas dizem e por que sequências podem transformar incentivo em pressão.', imageAlt: 'Uma sequência de dias marcada em um calendário ao lado de um jogo', tags: ['motivação', 'recompensas', 'sequências', 'design de jogos', 'autonomia do jogador'],
    intro: 'Pontos, distintivos e sequências podem tornar o progresso visível. Também podem fazer uma atividade parecer uma obrigação. Pesquisas sobre motivação mostram que os efeitos dependem de como a recompensa é apresentada e do que ela substitui; não existe uma resposta única para todo jogador. Uma sequência deve apoiar uma rotina escolhida, não punir uma pausa. Leia também: [leia também](/blog/daily-rituals-that-dont-demand-you), [este artigo relacionado](/blog/how-games-become-habits), [saiba mais](/#fair), [veja também](/blog/how-long-to-form-a-habit)', keyTakeaways: ['Recompensas podem mudar a motivação, e o efeito depende do contexto.', 'Uma revisão de 128 estudos encontrou diferenças entre tipos de recompensa e tarefas.', 'Sequências devem apoiar uma rotina escolhida, não punir uma pausa.'],
    sections: {
      'the-marker-experiment': { title: 'O experimento dos marcadores', paragraphs: ['Um estudo clássico deu a crianças a opção de desenhar com canetas coloridas. Quando algumas receberam uma recompensa esperada por desenhar, demonstraram menos interesse depois, em comparação com crianças que não esperavam prêmio.', 'O resultado é conhecido como efeito de recompensa sobre a motivação intrínseca. Não significa que todo prêmio reduza o interesse: a tarefa, a recompensa e a expectativa importam.'] },
      'what-128-studies-say': { title: 'O que dizem 128 estudos', paragraphs: ['Uma meta-análise de 128 estudos examinou recompensas extrínsecas e motivação intrínseca. Seus resultados não sustentam a regra simplista de que recompensas sempre ajudam ou sempre prejudicam.', 'O tipo de recompensa e a forma como ela é vinculada ao desempenho fazem diferença. Uma informação positiva sobre competência pode ter efeito diferente de um prêmio esperado apenas por concluir a tarefa.', 'Esses experimentos não descrevem todos os jogos comerciais nem permitem prever a reação de cada pessoa.'] },
      'the-trouble-with-streaks': { title: 'O problema das sequências', paragraphs: ['Uma sequência transforma repetição em algo visível. Isso pode ajudar a lembrar de uma atividade, mas também pode criar pressão para não interromper um contador.', 'Se manter a sequência importa mais do que a própria atividade, um dia de pausa pode parecer fracasso. Pesquisas sobre recompensas não provam que toda sequência cause esse efeito; é uma possibilidade de design a observar.'] },
      'points-badges-leaderboards': { title: 'Pontos, distintivos e placares', paragraphs: ['Pontos e distintivos tornam o progresso explícito. Placares acrescentam comparação social. Cada recurso pode ser motivador para algumas pessoas e irrelevante ou incômodo para outras.', 'Uma recompensa funciona melhor quando informa algo significativo sem tirar a escolha da pessoa. Os estudos sobre motivação não dizem que uma mecânica específica seja boa para todos.', 'Considere se o recurso torna a atividade mais interessante ou apenas cria algo a perder. Essa distinção ajuda a avaliar a experiência.'] },
      'how-we-think-about-it': { title: 'Como pensamos sobre recompensas em OutBrick', paragraphs: ['Em OutBrick, recompensas devem acompanhar o jogo sem transformar uma partida em obrigação. O objetivo é dar retorno claro e permitir que a pessoa escolha quando jogar.', 'Uma recompensa funciona melhor quando informa algo significativo sem tirar a escolha da pessoa.'], bullets: ['Trate uma sequência como informação, não como dívida.', 'Faça pausas sem sentir que perdeu o progresso real.', 'Prefira metas que você escolheu.', 'Observe se uma recompensa aumenta o prazer ou só a pressão.'] },
    }, pullQuote: 'Uma recompensa funciona melhor quando informa algo significativo sem tirar a escolha da pessoa.', faqs: [{ question: 'Recompensas reduzem a motivação?', answer: 'Podem reduzir certos tipos de motivação em alguns contextos, mas os resultados variam conforme a recompensa, a tarefa e a expectativa.' }, { question: 'Sequências são ruins para jogadores?', answer: 'Não necessariamente. Elas podem ajudar a acompanhar uma rotina, mas também podem gerar pressão. O efeito depende de como são usadas e sentidas.' }, { question: 'Pontos e distintivos ajudam a aprender?', answer: 'Eles podem tornar o progresso visível, mas não garantem aprendizado ou interesse. O design da tarefa e o significado do retorno importam.' }, { question: 'Como usar recompensas de forma saudável?', answer: 'Escolha metas que façam sentido para você e permita pausas. Observe se a recompensa torna a atividade mais agradável ou cria uma obrigação.' }],
  },
  'how-long-to-form-a-habit': {
    title: 'Quanto tempo leva para criar um hábito?', dek: 'O que o estudo dos 66 dias realmente encontrou, o que pesquisas posteriores acrescentaram e como criar uma rotina escolhida.', imageAlt: 'Uma rotina diária marcada em um calendário', tags: ['hábitos', 'rotina', '66 dias', 'comportamento', 'bem-estar'],
    intro: 'A ideia de que um hábito se forma em 21 dias é popular, mas não é uma regra científica. Um estudo conhecido encontrou uma mediana de 66 dias para que certos comportamentos se tornassem mais automáticos. O tempo variou muito entre participantes e hábitos. Leia também: [leia também](/blog/rewards-streaks-motivation), [este artigo relacionado](/blog/how-games-become-habits), [saiba mais](/blog/does-digital-detox-work), [veja também](/daily), [leia mais](/blog/daily-rituals-that-dont-demand-you)', keyTakeaways: ['O número de 66 dias é uma mediana de um estudo, não prazo universal.', 'A automaticidade cresceu de formas diferentes e alguns comportamentos levaram mais tempo.', 'Uma rotina sustentável depende de repetição em contexto estável, não de uma sequência perfeita.'],
    sections: {
      'the-66-day-study': { title: 'O estudo por trás dos 66 dias', paragraphs: ['Lally e colegas acompanharam 96 pessoas que escolheram um comportamento para repetir diariamente em um contexto específico, como comer uma fruta após o almoço.', 'Entre as pessoas cujos dados permitiram ajustar uma curva, a mediana para chegar perto do nível máximo de automaticidade foi de 66 dias. Houve ampla variação: alguns levaram menos tempo, outros muito mais.', 'Perder uma oportunidade não apagou o processo no estudo. O resultado não estabelece um prazo obrigatório nem se aplica automaticamente a qualquer hábito.'] },
      'newer-evidence': { title: 'O que pesquisas mais recentes acrescentam', paragraphs: ['Revisões posteriores apontam grande variação entre estudos, definições e comportamentos. Muitas pesquisas acompanham rotinas de saúde, e não qualquer tipo de hábito.', 'Por isso, uma estimativa única pode esconder diferenças importantes. O contexto, a frequência e a dificuldade da ação influenciam o processo.'] },
      'what-a-habit-is': { title: 'O que é um hábito', paragraphs: ['Um hábito é uma ação que se torna mais automática quando uma pista ou contexto familiar a desencadeia. Automaticidade não significa que a pessoa perdeu a escolha.', 'A repetição em uma situação estável pode ajudar a ligar o contexto à ação. Se o contexto muda, a ação pode deixar de ocorrer automaticamente.', 'Hábito também não é sinônimo de sequência perfeita. Um dia perdido não define se a rotina está consolidada.'] },
      'building-a-habit-you-want': { title: 'Crie um hábito que você realmente queira', paragraphs: ['Comece por uma ação pequena e escolha um momento ou contexto para repeti-la.'], bullets: ['Escolha uma ação específica e viável.', 'Associe-a a um momento ou rotina estável.', 'Deixe o primeiro passo fácil de iniciar.', 'Observe a repetição sem exigir perfeição.', 'Ajuste o plano se a rotina não couber no seu dia.', 'Dê tempo ao processo; não use 21 ou 66 dias como prazo fixo.'] },
      'why-games-should-not-hijack-habits': { title: 'Por que jogos não devem sequestrar hábitos', paragraphs: ['Jogos podem se encaixar em uma rotina agradável, mas uma sequência não deve virar obrigação. Um contador pode ajudar a lembrar e também fazer a pessoa sentir que não pode parar.', 'O número de 66 dias descreve uma mediana observada em um estudo de formação de hábitos. Não é uma meta que um jogo deva usar para manter alguém jogando.', 'Uma experiência saudável permite começar e parar por escolha. Se o jogo estiver ocupando um espaço que você não queria ceder, reveja a rotina.', 'O propósito é apoiar um hábito que você valoriza, não tornar o aplicativo indispensável.'] },
    }, pullQuote: 'O número de 66 dias descreve uma mediana observada em um estudo de formação de hábitos.', faqs: [{ question: 'Um hábito leva 21 dias para se formar?', answer: 'Não há regra universal de 21 dias. Um estudo conhecido encontrou uma mediana de 66 dias, com grande variação entre as pessoas e os comportamentos.' }, { question: 'O que acontece se eu perder um dia?', answer: 'No estudo de 66 dias, uma oportunidade perdida não apagou o processo. O importante é a repetição ao longo do tempo, não uma sequência perfeita.' }, { question: 'Como criar um novo hábito?', answer: 'Escolha uma ação pequena, associe-a a um contexto estável e torne o início fácil. Observe o que funciona e ajuste a rotina.' }, { question: 'Quanto tempo devo esperar para um hábito ficar automático?', answer: 'O tempo varia. Os 66 dias são uma mediana de um estudo específico, não uma previsão individual.' }],
  },
  'casual-games-stress-recovery-after-work': {
    title: 'Jogos casuais para relaxar e se recuperar do trabalho', dek: 'Como jogos casuais se relacionam com a recuperação após o expediente e o que a pesquisa não permite concluir.', imageAlt: 'Uma pessoa jogando um quebra-cabeça casual depois do trabalho', tags: ['recuperação', 'estresse no trabalho', 'jogos casuais', 'descanso', 'equilíbrio entre trabalho e vida pessoal'],
    intro: 'Depois de um dia exigente, algumas pessoas jogam para relaxar. A pesquisa sobre recuperação do trabalho descreve experiências que ajudam a pessoa a se desligar das demandas. Jogos podem oferecer algumas delas, mas não são a única opção nem uma solução garantida para estresse. Leia também: [leia também](/blog/flow-in-puzzle-games), [este artigo relacionado](/play), [saiba mais](/blog/relaxing-puzzle-games-what-makes-one-calm), [veja também](/blog/when-to-play-and-when-to-pause), [leia mais](/blog/gaming-before-bed-sleep)', keyTakeaways: ['Jogos podem oferecer algumas experiências de recuperação, mas não são a única opção nem uma solução garantida para estresse. A recuperação do trabalho inclui desligamento psicológico, relaxamento, domínio e controle.', 'Algumas pessoas usam jogos para se recuperar, mas estudos observacionais não provam que funcionem para todos.', 'Jogar pode ser uma opção entre várias; observe se ajuda ou se está servindo para evitar algo importante.'],
    sections: {
      'four-recovery-experiences': { title: 'Quatro ingredientes da recuperação', paragraphs: ['Sonnentag e Fritz descrevem quatro experiências de recuperação: desligamento psicológico do trabalho, relaxamento, domínio de uma atividade e controle sobre como usar o tempo livre.', 'A pessoa pode se desligar das tarefas sem necessariamente dormir ou ficar inativa. Uma atividade escolhida pode ajudar a mudar o foco.', 'Essas dimensões são formas de estudar a recuperação, não uma lista que toda pessoa precise cumprir.'] },
      'people-use-games-to-recover': { title: 'As pessoas já usam jogos para se recuperar', paragraphs: ['Reinecke estudou o uso recreativo de jogos durante o expediente e observou que a recuperação relatada se associava a jogar no trabalho. Isso descreve uma amostra de jogadores, não prova que jogar aumente o desempenho.', 'Em outro estudo sobre jogos e recuperação, as pessoas relataram usar videogames e jogos de computador para descansar de estresse e esforço. A pesquisa ajuda a descrever esse uso, mas não estabelece um efeito universal.', 'Pessoas cansadas podem procurar jogos com mais frequência. Uma associação entre jogo e recuperação não determina qual veio primeiro.'] },
      'games-against-other-options': { title: 'Jogos comparados a outras formas de relaxar', paragraphs: ['Reinecke e colegas compararam mídia de entretenimento interativa e não interativa em relação à satisfação de necessidades de recuperação. Os resultados dependem da experiência e da atividade; não dizem que jogos sejam sempre superiores.', 'Collins e Cox também investigaram jogos digitais como auxílio à recuperação após o trabalho. O estudo considera jogos uma possibilidade, não um substituto obrigatório de descanso, convívio ou outras atividades.'] },
      'a-puzzle-and-the-four-ingredients': { title: 'Como um quebra-cabeça se relaciona aos quatro ingredientes', paragraphs: ['Um jogo pode ajudar a direcionar a atenção para fora do trabalho, mas isso depende de a pessoa conseguir se desligar das preocupações.', 'Uma experiência tranquila pode ser relaxante para alguém e frustrante para outra pessoa. O gênero, a dificuldade e o momento fazem diferença.', 'Aprender uma estratégia ou resolver um desafio pode oferecer sensação de domínio. Essa experiência pode ser agradável sem ser necessariamente restauradora.', 'Escolher quando jogar dá algum controle sobre o tempo livre. Se o jogo passa a decidir quando parar, esse controle diminui.'] },
      'when-unwinding-becomes-avoiding': { title: 'Quando relaxar vira evitar', paragraphs: ['Uma atividade pode ser descanso e também uma forma de adiar algo. A diferença depende do que acontece depois e de como você se sente.', 'Se jogar estiver interferindo no sono, nas relações ou em tarefas que importam, vale observar o padrão e experimentar outro limite.'], bullets: ['Perceba se consegue parar quando planejou.', 'Observe se o jogo melhora seu descanso ou prolonga o estresse.', 'Escolha entre várias formas de recuperação, incluindo atividades fora da tela.'] },
    }, pullQuote: 'Sonnentag e Fritz descrevem quatro experiências de recuperação: desligamento psicológico do trabalho, relaxamento, domínio de uma atividade e controle sobre como usar o tempo livre.', faqs: [{ question: 'Jogos ajudam a aliviar o estresse depois do trabalho?', answer: 'Algumas pessoas relatam usar jogos para se recuperar, mas as pesquisas não demonstram que funcionem para todos. A experiência depende do contexto e da pessoa.' }, { question: 'Quais são os quatro ingredientes da recuperação?', answer: 'Desligamento psicológico do trabalho, relaxamento, domínio de uma atividade e controle sobre o tempo livre.' }, { question: 'Jogar é melhor do que outras formas de relaxar?', answer: 'Não há uma opção melhor para todas as pessoas. Estudos comparam experiências diferentes, e o resultado depende do que ajuda cada pessoa a se recuperar.' }, { question: 'Como saber se estou relaxando ou evitando?', answer: 'Observe se consegue parar quando pretende e se a atividade está interferindo no sono, nas relações ou em responsabilidades importantes.' }],
  },
  'is-gaming-good-or-bad-for-mood': {
    title: 'Jogos fazem bem ou mal ao humor? O que estudos mostram', dek: 'Estudos com diários e experimentos naturais encontraram efeitos variados. Entenda o que dizem sobre humor durante o jogo e tempo de uso.', imageAlt: 'Uma pessoa jogando no celular e registrando como se sente', tags: ['jogos', 'humor', 'bem-estar', 'pesquisa', 'tempo de jogo'],
    intro: 'Perguntar se jogos fazem bem ou mal ao humor simplifica demais a questão. O que a pessoa sente durante uma partida pode ser diferente de como ela se sente ao longo de semanas. Estudos com diários e experimentos naturais ajudam a separar essas perguntas, mas não dão uma resposta universal. Leia também: [leia também](/blog/screen-time-myths-research), [este artigo relacionado](/blog/designing-for-real-life-play), [saiba mais](/blog/casual-games-stress-recovery-after-work), [veja também](/daily), [leia mais](/play)', keyTakeaways: ['A experiência durante uma sessão não é igual à relação entre horas jogadas e bem-estar.', 'Estudos diários encontram mudanças pequenas de humor durante o jogo.', 'Resultados médios não preveem como cada pessoa reagirá.'],
    sections: {
      'why-method-matters': { title: 'Por que o método importa', paragraphs: ['Estudos que perguntam às pessoas como se sentem após uma partida medem uma coisa; estudos que relacionam horas semanais a bem-estar medem outra.', 'Diários podem captar mudanças próximas à atividade, enquanto levantamentos amplos mostram associações entre pessoas. Nenhum método sozinho responde a todas as perguntas.'] },
      'mood-during-play': { title: 'Humor durante o jogo: uma pequena melhora rápida', paragraphs: ['Em estudos que acompanham experiências cotidianas, jogar pode coincidir com uma pequena melhora momentânea no humor. O tamanho e a duração desse efeito variam.', 'Uma melhora breve não significa que o jogo trate sofrimento emocional ou produza benefícios duradouros.'] },
      'mood-and-hours-played': { title: 'Humor e horas de jogo: pouca relação', paragraphs: ['Orben e Przybylski analisaram dados sobre uso de tecnologia e bem-estar adolescente e encontraram uma associação média pequena.', 'Os dados não mostram que jogar mais cause pior humor. Outras diferenças entre pessoas e contextos podem influenciar os resultados.', 'A quantidade de horas também não revela o que a atividade substituiu nem se a pessoa escolheu jogar.', 'É possível que uma sessão seja agradável sem que as horas totais se relacionem de forma clara ao bem-estar geral.'] },
      'a-natural-experiment': { title: 'Um experimento natural do Japão', paragraphs: ['Koga e colaboradores usaram mudanças na disponibilidade de consoles no Japão como experimento natural para estudar jogos e bem-estar. A abordagem ajuda a investigar relações causais, mas depende de pressupostos e não equivale a um experimento controlado aleatório.', 'Os resultados se referem à população e ao período analisados. Não permitem prever o efeito de qualquer jogo em qualquer pessoa.'] },
      'what-it-adds-up-to': { title: 'O que podemos concluir', paragraphs: ['As pesquisas não sustentam um veredito único. Considere sua própria experiência e o contexto em que joga. Uma melhora breve não significa que o jogo trate sofrimento emocional ou produza benefícios duradouros.', 'Também vale distinguir uma mudança de humor durante uma sessão de um efeito persistente no bem-estar.'], bullets: ['Diferencie o humor durante a partida do bem-estar ao longo do tempo.', 'Observe se o jogo interfere em sono, trabalho ou relações.', 'Não transforme um resultado médio em previsão pessoal.'] },
    }, pullQuote: 'Uma melhora breve não significa que o jogo trate sofrimento emocional ou produza benefícios duradouros.', faqs: [{ question: 'Jogar melhora o humor?', answer: 'Pode coincidir com uma pequena melhora momentânea para algumas pessoas. Isso não demonstra um benefício duradouro nem vale para todas as experiências.' }, { question: 'Jogar muitas horas causa mau humor?', answer: 'Estudos encontram associações médias pequenas e não demonstram, por si só, que o tempo de jogo cause mudanças de humor.' }, { question: 'O que estudos com diários medem?', answer: 'Eles registram experiências próximas ao momento em que acontecem, como o humor durante ou depois de jogar. Isso difere de medir horas totais e bem-estar geral.' }, { question: 'Jogos podem tratar depressão?', answer: 'Os estudos discutidos aqui não demonstram que jogos tratem depressão. Procure um profissional de saúde para orientações sobre sofrimento persistente.' }],
  },
};
