import type { Locale } from './locales';
const en = { board: (n?: number) => n ? `Daily board #${n}` : 'Daily board', today: 'Today’s board', target: (n: number) => `target ${n}`, play: (n: number, name: string) => `Play OutBrick daily board #${n}, ${name}`, title: (n: number, stars: number) => `I cleared OutBrick daily board #${n} with ${stars} ${stars === 1 ? 'star' : 'stars'}`, text: (n: number, name: string, moves: number, target: number, stars: string) => `OutBrick daily board #${n}, ${name}: cleared in ${moves} ${moves === 1 ? 'move' : 'moves'} (target ${target}) ${stars}` };
export const dailyWords: Record<Locale, typeof en> = {
  en,
  fr: { board: n => n ? `Plateau du jour nº ${n}` : 'Plateau du jour', today: 'Le plateau d’aujourd’hui', target: n => `objectif ${n}`, play: (n, name) => `Jouer au plateau du jour OutBrick nº ${n}, ${name}`, title: (n, s) => `J’ai vidé le plateau du jour OutBrick nº ${n} avec ${s} ${s === 1 ? 'étoile' : 'étoiles'}`, text: (n, name, m, t, s) => `Plateau du jour OutBrick nº ${n}, ${name} : vidé en ${m} ${m === 1 ? 'coup' : 'coups'} (objectif ${t}) ${s}` },
  de: { board: n => n ? `Tagesbrett Nr. ${n}` : 'Tagesbrett', today: 'Das heutige Brett', target: n => `Ziel ${n}`, play: (n, name) => `OutBrick-Tagesbrett Nr. ${n} spielen, ${name}`, title: (n, s) => `Ich habe OutBrick-Tagesbrett Nr. ${n} mit ${s} ${s === 1 ? 'Stern' : 'Sternen'} geleert`, text: (n, name, m, t, s) => `OutBrick-Tagesbrett Nr. ${n}, ${name}: in ${m} ${m === 1 ? 'Zug' : 'Zügen'} geleert (Ziel ${t}) ${s}` },
  es: { board: n => n ? `Tablero del día n.º ${n}` : 'Tablero del día', today: 'El tablero de hoy', target: n => `objetivo ${n}`, play: (n, name) => `Jugar al tablero del día de OutBrick n.º ${n}, ${name}`, title: (n, s) => `He vaciado el tablero del día de OutBrick n.º ${n} con ${s} ${s === 1 ? 'estrella' : 'estrellas'}`, text: (n, name, m, t, s) => `Tablero del día de OutBrick n.º ${n}, ${name}: vaciado en ${m} ${m === 1 ? 'movimiento' : 'movimientos'} (objetivo ${t}) ${s}` },
  ja: { board: n => n ? `今日の盤面 #${n}` : '今日の盤面', today: '本日の盤面', target: n => `目標 ${n}手`, play: (n, name) => `OutBrickの今日の盤面 #${n}「${name}」をプレイ`, title: (n, s) => `OutBrickの今日の盤面 #${n} を星${s}個でクリアしました`, text: (n, name, m, t, s) => `OutBrickの今日の盤面 #${n}「${name}」：${m}手でクリア（目標${t}手）${s}` },
  'pt-BR': { board: n => n ? `Tabuleiro diário nº ${n}` : 'Tabuleiro diário', today: 'Tabuleiro de hoje', target: n => `meta ${n}`, play: (n, name) => `Jogue o tabuleiro diário nº ${n} de OutBrick, ${name}`, title: (n, s) => `Concluí o tabuleiro diário nº ${n} de OutBrick com ${s} ${s === 1 ? 'estrela' : 'estrelas'}`, text: (n, name, m, t, s) => `Tabuleiro diário nº ${n} de OutBrick, ${name}: concluído em ${m} ${m === 1 ? 'movimento' : 'movimentos'} (meta ${t}) ${s}` },
};
