import type { Locale } from './locales';
const en = {
  field: 'this field', optional: 'optional', required: 'Fields are required unless marked optional.', empty: 'Leave this empty:', sending: 'Sending…', consent: 'Please tick this box so we can use your details to reply.', checkbox: 'Please tick this box to continue.', email: 'Enter an email address in the form name@example.com.', url: 'Enter a full web address, starting with https://', failed: 'That did not send — the connection may have dropped. Your answers are still here, so try again in a moment.',
  enter: (s:string)=>`Enter ${s}.`, choose:(s:string)=>`Choose ${s}.`, check:(s:string)=>`Check ${s}.`, short:(n:number)=>`Please write at least ${n} characters.`, long:(n:number)=>`Please keep this under ${n} characters.`, summary:(n:number)=>n===1?'One field needs attention before this can be sent.':`${n} fields need attention before this can be sent.`,
};
export const formWords: Record<Locale, typeof en> = {
 en,
 fr: { field:'ce champ', optional:'facultatif', required:'Les champs sont obligatoires sauf indication contraire.', empty:'Laissez ce champ vide :', sending:'Envoi…', consent:'Cochez cette case pour que nous puissions utiliser vos coordonnées afin de vous répondre.', checkbox:'Cochez cette case pour continuer.', email:'Saisissez une adresse e-mail au format nom@exemple.com.', url:'Saisissez une adresse web complète commençant par https://', failed:'L’envoi a échoué : la connexion a peut-être été interrompue. Vos réponses sont toujours ici. Réessayez dans un instant.', enter:s=>`Saisissez ${s}.`, choose:s=>`Choisissez ${s}.`, check:s=>`Vérifiez ${s}.`, short:n=>`Écrivez au moins ${n} caractères.`, long:n=>`Ne dépassez pas ${n} caractères.`, summary:n=>`${n} ${n===1?'champ doit être vérifié':'champs doivent être vérifiés'} avant l’envoi.` },
 de: { field:'dieses Feld', optional:'optional', required:'Alle Felder sind Pflichtfelder, sofern sie nicht als optional gekennzeichnet sind.', empty:'Bitte leer lassen:', sending:'Wird gesendet…', consent:'Aktivieren Sie dieses Kästchen, damit wir Ihre Angaben für unsere Antwort verwenden dürfen.', checkbox:'Aktivieren Sie dieses Kästchen, um fortzufahren.', email:'Geben Sie eine E-Mail-Adresse im Format name@beispiel.com ein.', url:'Geben Sie eine vollständige Webadresse ein, die mit https:// beginnt.', failed:'Das Senden ist fehlgeschlagen. Möglicherweise wurde die Verbindung unterbrochen. Ihre Antworten sind noch vorhanden. Versuchen Sie es gleich noch einmal.', enter:s=>`Bitte ausfüllen: ${s}.`, choose:s=>`Bitte auswählen: ${s}.`, check:s=>`Bitte prüfen: ${s}.`, short:n=>`Schreiben Sie mindestens ${n} Zeichen.`, long:n=>`Verwenden Sie höchstens ${n} Zeichen.`, summary:n=>`${n} ${n===1?'Feld muss':'Felder müssen'} vor dem Senden geprüft werden.` },
 es: { field:'este campo', optional:'opcional', required:'Los campos son obligatorios salvo que se indiquen como opcionales.', empty:'Deja este campo vacío:', sending:'Enviando…', consent:'Marca esta casilla para que podamos usar tus datos para responderte.', checkbox:'Marca esta casilla para continuar.', email:'Introduce una dirección de correo con el formato nombre@ejemplo.com.', url:'Introduce una dirección web completa que empiece por https://', failed:'No se ha enviado. Puede que se haya perdido la conexión. Tus respuestas siguen aquí; inténtalo de nuevo en un momento.', enter:s=>`Introduce ${s}.`, choose:s=>`Selecciona ${s}.`, check:s=>`Revisa ${s}.`, short:n=>`Escribe al menos ${n} caracteres.`, long:n=>`No superes los ${n} caracteres.`, summary:n=>`${n===1?'Hay un campo que debes revisar':`Hay ${n} campos que debes revisar`} antes de enviar.` },
 ja: { field:'この項目', optional:'任意', required:'「任意」と表示された項目以外は入力が必要です。', empty:'この欄は空白にしてください：', sending:'送信中…', consent:'返信のために入力内容を使用できるよう、この項目にチェックを入れてください。', checkbox:'続けるにはチェックを入れてください。', email:'name@example.com の形式でメールアドレスを入力してください。', url:'https:// で始まる完全なウェブアドレスを入力してください。', failed:'送信できませんでした。接続が切れた可能性があります。入力内容は保持されていますので、少し待ってからもう一度お試しください。', enter:s=>`${s}を入力してください。`, choose:s=>`${s}を選択してください。`, check:s=>`${s}を確認してください。`, short:n=>`${n}文字以上で入力してください。`, long:n=>`${n}文字以内で入力してください。`, summary:n=>`送信前に${n}件の項目を確認してください。` },
 'pt-BR': { field:'este campo', optional:'opcional', required:'Os campos são obrigatórios, a menos que estejam marcados como opcionais.', empty:'Deixe este campo vazio:', sending:'Enviando…', consent:'Marque esta caixa para que possamos usar seus dados para responder.', checkbox:'Marque esta caixa para continuar.', email:'Digite um endereço de e-mail no formato nome@exemplo.com.', url:'Digite um endereço completo começando com https://', failed:'Não foi possível enviar. Talvez a conexão tenha caído. Suas respostas continuam aqui; tente novamente em instantes.', enter:s=>`Digite ${s}.`, choose:s=>`Escolha ${s}.`, check:s=>`Confira ${s}.`, short:n=>`Escreva pelo menos ${n} caracteres.`, long:n=>`Use menos de ${n} caracteres.`, summary:n=>n===1?'Um campo precisa de atenção antes do envio.':`${n} campos precisam de atenção antes do envio.` },
};
