import type { Locale } from './locales';
const en = { apply: (role: string) => `Apply for ${role}`, roles: (shown: number, total: number, team?: string) => `Showing ${shown} of ${total} roles${team ? ` in ${team}` : ''}.`, level: (n?: number) => n ? `Level ${n}` : 'Level', title: (n: number) => `Level ${n} — an OutBrick challenge`, journey: 'Journey', target: (n: number) => `Journey · target ${n}`, puzzle: 'a sliding-brick puzzle', board: 'a board of OutBrick', beat: (n: number) => `Beat their ${n} moves.`, clear: (n: number) => `Clear it in ${n} moves.`, question: 'Can you clear it?', clearBoard: 'Clear the board.' };
export const interactiveWords: Record<Locale, typeof en> = {
 en,
 fr: { apply:r=>`Postuler au poste de ${r}`, roles:(n,t,g)=>`${n} postes affichés sur ${t}${g ? ` dans ${g}` : ''}.`, level:n=>n?`Niveau ${n}`:'Niveau', title:n=>`Niveau ${n} — un défi OutBrick`, journey:'Le Voyage', target:n=>`Le Voyage · objectif ${n}`, puzzle:'un puzzle de briques coulissantes', board:'un plateau d’OutBrick', beat:n=>`Faites mieux que ses ${n} coups.`, clear:n=>`Videz le plateau en ${n} coups.`, question:'Pouvez-vous vider ce plateau ?', clearBoard:'Videz le plateau.' },
 de: { apply:r=>`Für ${r} bewerben`, roles:(n,t,g)=>`${n} von ${t} Stellen${g ? ` im Bereich ${g}` : ''} angezeigt.`, level:n=>n?`Stufe ${n}`:'Stufe', title:n=>`Stufe ${n} — eine OutBrick-Herausforderung`, journey:'Die Reise', target:n=>`Die Reise · Ziel ${n}`, puzzle:'ein Schiebestein-Puzzle', board:'ein OutBrick-Brett', beat:n=>`Unterbieten Sie die ${n} Züge.`, clear:n=>`Leeren Sie es in ${n} Zügen.`, question:'Können Sie es leeren?', clearBoard:'Leeren Sie das Brett.' },
 es: { apply:r=>`Solicitar el puesto de ${r}`, roles:(n,t,g)=>`Se muestran ${n} de ${t} puestos${g ? ` en ${g}` : ''}.`, level:n=>n?`Nivel ${n}`:'Nivel', title:n=>`Nivel ${n} — un desafío de OutBrick`, journey:'El Viaje', target:n=>`El Viaje · objetivo ${n}`, puzzle:'un puzle de bloques deslizantes', board:'un tablero de OutBrick', beat:n=>`Mejora sus ${n} movimientos.`, clear:n=>`Vacíalo en ${n} movimientos.`, question:'¿Puedes vaciarlo?', clearBoard:'Vacía el tablero.' },
 ja: { apply:r=>`「${r}」に応募`, roles:(n,t,g)=>`${t}件中${n}件の求人${g ? `（${g}）` : ''}を表示しています。`, level:n=>n?`ステージ${n}`:'ステージ', title:n=>`ステージ${n} — OutBrickのチャレンジ`, journey:'ジャーニー', target:n=>`ジャーニー · 目標${n}手`, puzzle:'ブロックを滑らせるパズル', board:'OutBrickの盤面', beat:n=>`${n}手より少ない手数でクリアしましょう。`, clear:n=>`${n}手でクリアしましょう。`, question:'クリアできますか？', clearBoard:'盤面を空にしましょう。' },
 'pt-BR': { apply:r=>`Candidate-se para ${r}`, roles:(n,t,g)=>`Exibindo ${n} de ${t} vagas${g ? ` em ${g}` : ''}.`, level:n=>n?`Fase ${n}`:'Fase', title:n=>`Fase ${n} — um desafio OutBrick`, journey:'Jornada', target:n=>`Jornada · meta ${n}`, puzzle:'um quebra-cabeça de blocos deslizantes', board:'um tabuleiro de OutBrick', beat:n=>`Supere os ${n} movimentos.`, clear:n=>`Conclua em ${n} movimentos.`, question:'Você consegue concluir?', clearBoard:'Conclua o tabuleiro.' },
};
