import type { Locale } from './locales';
const en = { heading: 'Get a letter when there’s a new village', intro: 'New villages, big updates and the odd note from the bench. About once a month, never more than that.', done: 'You’re on the list.', thanks: 'Thank you. The next letter comes when there’s a new village or a big update, about once a month at most. To come off the list, reply to any letter.', privacyNote: 'How we look after your email', label: 'Newsletter sign-up', empty: 'Leave this empty:', email: 'Email address', language: 'Language', consent: 'Email me about OutBrick updates. Unsubscribe any time.', privacy: 'Privacy policy', sending: 'Signing you up…', submit: 'Sign me up' };
export const newsletterWords: Record<Locale, typeof en> = {
 en,
 fr: { heading: 'Recevez une lettre lorsqu’un nouveau village arrive', intro: 'De nouveaux villages, de grandes mises à jour et, parfois, une note de l’atelier. Environ une fois par mois, jamais davantage.', done: 'Vous êtes sur la liste.', thanks: 'Merci. La prochaine lettre arrivera avec un nouveau village ou une grande mise à jour, au maximum environ une fois par mois. Pour vous désinscrire, répondez à l’une de nos lettres.', privacyNote: 'Comment nous protégeons votre adresse e-mail', label: 'Inscription à la lettre d’information', empty: 'Laissez ce champ vide :', email: 'Adresse e-mail', language: 'Langue', consent: 'Envoyez-moi les nouvelles d’OutBrick par e-mail. Je peux me désinscrire à tout moment.', privacy: 'Politique de confidentialité', sending: 'Inscription…', submit: 'M’inscrire' },
 de: { heading: 'Eine Nachricht, wenn ein neues Dorf erscheint', intro: 'Neue Dörfer, große Updates und gelegentlich eine Notiz aus der Werkstatt. Etwa einmal im Monat, niemals öfter.', done: 'Sie sind auf der Liste.', thanks: 'Vielen Dank. Die nächste Nachricht kommt, wenn ein neues Dorf oder ein großes Update erscheint, höchstens etwa einmal im Monat. Zum Abbestellen antworten Sie auf eine beliebige Nachricht.', privacyNote: 'So schützen wir Ihre E-Mail-Adresse', label: 'Newsletter-Anmeldung', empty: 'Bitte leer lassen:', email: 'E-Mail-Adresse', language: 'Sprache', consent: 'Ich möchte E-Mails über OutBrick-Updates erhalten. Ich kann mich jederzeit abmelden.', privacy: 'Datenschutzerklärung', sending: 'Anmeldung läuft…', submit: 'Anmelden' },
 es: { heading: 'Recibe una carta cuando haya un nuevo pueblo', intro: 'Nuevos pueblos, grandes actualizaciones y alguna nota del taller. Aproximadamente una vez al mes, nunca más.', done: 'Ya estás en la lista.', thanks: 'Gracias. La próxima carta llegará cuando haya un nuevo pueblo o una gran actualización, como máximo aproximadamente una vez al mes. Para darte de baja, responde a cualquier carta.', privacyNote: 'Cómo cuidamos tu correo', label: 'Suscripción al boletín', empty: 'Deja este campo vacío:', email: 'Correo electrónico', language: 'Idioma', consent: 'Quiero recibir novedades de OutBrick por correo. Puedo darme de baja en cualquier momento.', privacy: 'Política de privacidad', sending: 'Suscribiendo…', submit: 'Suscribirme' },
 ja: { heading: '新しい村が登場したら、お便りをお届けします', intro: '新しい村、大きなアップデート、ときどき制作の話。月に約1回、それ以上は送りません。', done: '登録が完了しました。', thanks: 'ありがとうございます。次のお便りは、新しい村や大きなアップデートが登場したときにお届けします。頻度は多くても月に約1回です。配信を停止するには、届いたお便りに返信してください。', privacyNote: 'メールアドレスの取り扱いについて', label: 'ニュースレター登録', empty: 'この欄は空白にしてください：', email: 'メールアドレス', language: '言語', consent: 'OutBrickの更新情報をメールで受け取ります。いつでも配信を停止できます。', privacy: 'プライバシーポリシー', sending: '登録中…', submit: '登録する' },
};
