import type { Locale } from './locales';
/**
 * The version of the sign-up wording below (heading, intro, consent line) a reader agreed to.
 * The form posts it and the confirmation stores it (newsletter_subscribers.consent_text_version):
 * change the date whenever that wording changes in any language.
 */
export const NEWSLETTER_CONSENT_VERSION = '2026-10-09';
const en = { heading: 'Get a letter when there’s a new village', intro: 'New villages, big updates and the odd note from the bench. About once a month, never more than that.', done: 'Check your inbox to confirm.', thanks: 'Thank you. We’ve sent you an email with a button in it: press it within 7 days and you’re on the list. Until then, nothing is added. The letters come about once a month at most, and every one has a one-click unsubscribe link.', privacyNote: 'How we look after your email', label: 'Newsletter sign-up', empty: 'Leave this empty:', email: 'Email address', language: 'Language', consent: 'Email me about OutBrick updates. Unsubscribe any time.', privacy: 'Privacy policy', sending: 'Signing you up…', submit: 'Sign me up' };
export const newsletterWords: Record<Locale, typeof en> = {
 en,
 fr: { heading: 'Recevez une lettre lorsqu’un nouveau village arrive', intro: 'De nouveaux villages, de grandes mises à jour et, parfois, une note de l’atelier. Environ une fois par mois, jamais davantage.', done: 'Vérifiez votre boîte de réception pour confirmer.', thanks: 'Merci. Nous vous avons envoyé un e-mail avec un bouton : appuyez dessus dans les 7 jours et vous serez sur la liste. D’ici là, rien n’est ajouté. Les lettres arrivent au maximum environ une fois par mois, et chacune contient un lien de désinscription en un clic.', privacyNote: 'Comment nous protégeons votre adresse e-mail', label: 'Inscription à la lettre d’information', empty: 'Laissez ce champ vide :', email: 'Adresse e-mail', language: 'Langue', consent: 'Envoyez-moi les nouvelles d’OutBrick par e-mail. Je peux me désinscrire à tout moment.', privacy: 'Politique de confidentialité', sending: 'Inscription…', submit: 'M’inscrire' },
 de: { heading: 'Eine Nachricht, wenn ein neues Dorf erscheint', intro: 'Neue Dörfer, große Updates und gelegentlich eine Notiz aus der Werkstatt. Etwa einmal im Monat, niemals öfter.', done: 'Bitte bestätigen Sie die Anmeldung in Ihrem Posteingang.', thanks: 'Vielen Dank. Wir haben Ihnen eine E-Mail mit einer Schaltfläche geschickt: Tippen Sie innerhalb von 7 Tagen darauf, und Sie sind auf der Liste. Bis dahin wird nichts eingetragen. Die Nachrichten kommen höchstens etwa einmal im Monat, und jede enthält einen Link zum Abmelden mit einem Klick.', privacyNote: 'So schützen wir Ihre E-Mail-Adresse', label: 'Newsletter-Anmeldung', empty: 'Bitte leer lassen:', email: 'E-Mail-Adresse', language: 'Sprache', consent: 'Ich möchte E-Mails über OutBrick-Updates erhalten. Ich kann mich jederzeit abmelden.', privacy: 'Datenschutzerklärung', sending: 'Anmeldung läuft…', submit: 'Anmelden' },
 es: { heading: 'Recibe una carta cuando haya un nuevo pueblo', intro: 'Nuevos pueblos, grandes actualizaciones y alguna nota del taller. Aproximadamente una vez al mes, nunca más.', done: 'Revisa tu bandeja de entrada para confirmar.', thanks: 'Gracias. Te hemos enviado un correo con un botón: púlsalo en los próximos 7 días y estarás en la lista. Hasta entonces, no se añade nada. Las cartas llegan como máximo aproximadamente una vez al mes, y cada una tiene un enlace para darte de baja con un clic.', privacyNote: 'Cómo cuidamos tu correo', label: 'Suscripción al boletín', empty: 'Deja este campo vacío:', email: 'Correo electrónico', language: 'Idioma', consent: 'Quiero recibir novedades de OutBrick por correo. Puedo darme de baja en cualquier momento.', privacy: 'Política de privacidad', sending: 'Suscribiendo…', submit: 'Suscribirme' },
 ja: { heading: '新しい村が登場したら、お便りをお届けします', intro: '新しい村、大きなアップデート、ときどき制作の話。月に約1回、それ以上は送りません。', done: '受信トレイを確認して登録を完了してください。', thanks: 'ありがとうございます。ボタン付きのメールをお送りしました。7日以内にボタンを押すと登録が完了します。それまではリストに何も追加されません。お便りは多くても月に約1回で、毎回ワンクリックで配信を停止できるリンクが付いています。', privacyNote: 'メールアドレスの取り扱いについて', label: 'ニュースレター登録', empty: 'この欄は空白にしてください：', email: 'メールアドレス', language: '言語', consent: 'OutBrickの更新情報をメールで受け取ります。いつでも配信を停止できます。', privacy: 'プライバシーポリシー', sending: '登録中…', submit: '登録する' },
 'pt-BR': { heading: 'Receba uma carta quando uma nova vila chegar', intro: 'Novas vilas, grandes atualizações e, de vez em quando, um recado da oficina. Cerca de uma vez por mês, nunca mais do que isso.', done: 'Confira sua caixa de entrada para confirmar.', thanks: 'Obrigado. Enviamos um e-mail com um botão: clique nele em até 7 dias para confirmar sua inscrição. Até lá, nada será adicionado. As cartas chegam no máximo uma vez por mês, e todas têm um link para cancelar a inscrição com um clique.', privacyNote: 'Como cuidamos do seu e-mail', label: 'Inscrição na newsletter', empty: 'Deixe este campo vazio:', email: 'Endereço de e-mail', language: 'Idioma', consent: 'Quero receber novidades da OutBrick por e-mail. Posso cancelar a inscrição quando quiser.', privacy: 'Política de privacidade', sending: 'Inscrevendo…', submit: 'Quero me inscrever' },
};
