import type { Locale } from './locales';
const en = { earlier: 'Earlier releases', history: (date: string, version: string) => `OutBrick first went on sale on the App Store on ${date}, as version ${version}. The notes for the updates between then and 4.2 aren’t reproduced here; this page starts with 4.2.`, newsletter: 'Newsletter', next: 'Hear about the next one first.', note: 'One short email when a new village opens or a big update lands. About once a month, never more.', get: 'What you’ll get', schema: 'OutBrick release notes' };
export const releaseExtras: Record<Locale, typeof en> = {
 en,
 fr: { earlier:'Versions précédentes', history:(d,v)=>`OutBrick a été mis en vente pour la première fois sur l’App Store le ${d}, en version ${v}. Les notes des mises à jour intervenues entre cette date et la version 4.2 ne sont pas reproduites ici : cette page commence à la version 4.2.`, newsletter:'Lettre d’information', next:'Soyez parmi les premiers au courant de la prochaine mise à jour.', note:'Un bref e-mail lorsqu’un nouveau village ouvre ou qu’une grande mise à jour arrive. Environ une fois par mois, jamais davantage.', get:'Ce que vous recevrez', schema:'Notes de version d’OutBrick' },
 de: { earlier:'Frühere Versionen', history:(d,v)=>`OutBrick erschien erstmals am ${d} im App Store, als Version ${v}. Die Hinweise zu den Updates zwischen diesem Zeitpunkt und Version 4.2 werden hier nicht wiedergegeben; diese Seite beginnt mit 4.2.`, newsletter:'Newsletter', next:'Erfahren Sie zuerst von der nächsten Version.', note:'Eine kurze E-Mail, wenn ein neues Dorf öffnet oder ein großes Update erscheint. Etwa einmal im Monat, niemals öfter.', get:'Was Sie erhalten', schema:'OutBrick-Versionshinweise' },
 es: { earlier:'Versiones anteriores', history:(d,v)=>`OutBrick se puso a la venta por primera vez en el App Store el ${d}, como versión ${v}. Aquí no se reproducen las notas de las actualizaciones entre esa fecha y la versión 4.2; esta página empieza con la 4.2.`, newsletter:'Boletín', next:'Entérate de la próxima actualización antes que nadie.', note:'Un correo breve cuando abra un nuevo pueblo o llegue una gran actualización. Aproximadamente una vez al mes, nunca más.', get:'Qué recibirás', schema:'Notas de versión de OutBrick' },
 ja: { earlier:'過去のリリース', history:(d,v)=>`OutBrickは${d}にバージョン${v}としてApp Storeで初めて販売されました。その後バージョン4.2までの更新内容はここには掲載していません。このページは4.2からの記録です。`, newsletter:'ニュースレター', next:'次の更新をいち早く知る。', note:'新しい村が開いたときや大きなアップデートが届いたときに、短いメールを1通。月に約1回、それ以上は送りません。', get:'届く内容について', schema:'OutBrickのリリースノート' },
 'pt-BR': { earlier:'Versões anteriores', history:(d,v)=>`OutBrick chegou pela primeira vez à App Store em ${d}, na versão ${v}. As notas das atualizações entre essa data e a versão 4.2 não estão reproduzidas aqui; esta página começa pela versão 4.2.`, newsletter:'Boletim por e-mail', next:'Saiba primeiro quando sair a próxima atualização.', note:'Um e-mail curto quando um novo vilarejo abrir ou uma grande atualização chegar. Cerca de uma vez por mês, nunca mais.', get:'O que você vai receber', schema:'Notas de versão do OutBrick' },
};
