import type { Locale } from './locales';
export const siteWords: Record<Locale, { organization: string; website: string; icon: string; support: string; social: string; on: (name: string) => string }> = {
 en: { organization: 'The studio behind OutBrick: Block Sort Puzzle, a calm slide-and-match brick puzzle, and the OutBrick Journal on puzzle design and calmer play.', website: 'The official site of OutBrick: Block Sort Puzzle, a calm slide-and-match brick puzzle, and the OutBrick Journal.', icon: 'The OutBrick app icon', support: 'customer support', social: 'OutBrick on social media', on: n => `OutBrick on ${n}` },
 fr: { organization: 'Le studio à l’origine d’OutBrick: Block Sort Puzzle, un puzzle apaisant où l’on glisse et aligne des briques, et du journal OutBrick sur la conception de puzzles et le jeu plus calme.', website: 'Le site officiel d’OutBrick: Block Sort Puzzle, un puzzle apaisant où l’on glisse et aligne des briques, et du journal OutBrick.', icon: 'Icône de l’application OutBrick', support: 'assistance clientèle', social: 'OutBrick sur les réseaux sociaux', on: n => `OutBrick sur ${n}` },
 de: { organization: 'Das Studio hinter OutBrick: Block Sort Puzzle, einem ruhigen Schiebe- und Kombinierrätsel mit Steinen, und dem OutBrick-Journal über Puzzle-Design und ruhigeres Spielen.', website: 'Die offizielle Website von OutBrick: Block Sort Puzzle, einem ruhigen Schiebe- und Kombinierrätsel mit Steinen, und dem OutBrick-Journal.', icon: 'Das OutBrick-App-Symbol', support: 'Kundensupport', social: 'OutBrick in sozialen Medien', on: n => `OutBrick auf ${n}` },
 es: { organization: 'El estudio creador de OutBrick: Block Sort Puzzle, un tranquilo puzle de deslizar y combinar ladrillos, y del journal de OutBrick sobre diseño de puzles y juego más tranquilo.', website: 'El sitio oficial de OutBrick: Block Sort Puzzle, un tranquilo puzle de deslizar y combinar ladrillos, y del journal de OutBrick.', icon: 'Icono de la aplicación OutBrick', support: 'atención al cliente', social: 'OutBrick en las redes sociales', on: n => `OutBrick en ${n}` },
 ja: { organization: 'ブロックをすべらせてそろえる落ち着いたパズル「OutBrick: Block Sort Puzzle」と、パズル設計や落ち着いた遊びについてのOutBrickジャーナルを制作するスタジオ。', website: 'ブロックをすべらせてそろえる落ち着いたパズル「OutBrick: Block Sort Puzzle」とOutBrickジャーナルの公式サイト。', icon: 'OutBrickアプリのアイコン', support: 'カスタマーサポート', social: 'OutBrickのソーシャルメディア', on: n => `${n}のOutBrick` },
 'pt-BR': { organization: 'O estúdio por trás de OutBrick: Block Sort Puzzle, um quebra-cabeça tranquilo de deslizar e combinar tijolos, e do Diário OutBrick, sobre design de jogos e partidas mais tranquilas.', website: 'O site oficial de OutBrick: Block Sort Puzzle, um quebra-cabeça tranquilo de deslizar e combinar tijolos, e do Diário OutBrick.', icon: 'Ícone do app OutBrick', support: 'suporte ao cliente', social: 'OutBrick nas redes sociais', on: n => `OutBrick no ${n}` },
};
