/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv cloudflare/bindings.d.ts` (hash: e4ff43ba853fbee8c388962b3e9c1683)
interface __BaseEnv_CloudflareEnv {
	UPLOADS: R2Bucket;
	SIGNALS: R2Bucket;
	ASSETS: Fetcher;
	CONTEXT: string;
	SITE_ID: string;
	JOBS_ENABLED: string;
	CLOUDFLARE_TRANSLATION_ENABLED: string;
	TRANSLATION_BUDGET: DurableObjectNamespace /* TranslationBudget from outbrick-translation-budget */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTEXT" | "SITE_ID" | "JOBS_ENABLED" | "CLOUDFLARE_TRANSLATION_ENABLED">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}