// Reviewed editorial source -> additive, idempotent SQL migration. Never edit player replies.
import fs from 'node:fs';
import { playerGuides, guideWords } from '../lib/community/player-guides.ts';
import { renderMarkdown } from '../netlify/community/markdown.ts';
import { locales } from '../lib/i18n/locales.ts';
const literal = (text: string) => `'${text.replaceAll("'", "''")}'`;
let sql = `-- Generated by scripts/build-player-guide-seed.mts from reviewed five-language team guides.\n-- No notifications, fake player accounts, or edits to existing community content.\nCREATE TABLE IF NOT EXISTS player_guides (\n  locale text NOT NULL, key text NOT NULL, thread_id bigint NOT NULL UNIQUE REFERENCES threads(id),\n  PRIMARY KEY (locale, key)\n);\n`;
for (const locale of locales) {
  const guides = playerGuides(locale),
    w = guideWords[locale];
  const all = [
    ...guides,
    {
      key: 'index',
      title: w.hub,
      category: 'help',
      body:
        `${w.checkpoint}\n\n${w.intro}\n\n` +
        guides.map((g) => `- [${g.title}](guide:${g.key})`).join('\n'),
    },
  ];
  for (const g of all) {
    const related =
      g.key === 'index'
        ? ''
        : `\n\n## ${w.related}\n\n[${w.hub}](guide:index)\n\n` +
          guides
            .filter((x) => x.key !== g.key)
            .map((x) => `- [${x.title}](guide:${x.key})`)
            .join('\n');
    // Safe path placeholders survive the normal allow-list renderer; SQL resolves real ids below.
    const body = (g.body + related).replaceAll(
      '(guide:',
      '(/community/guide-placeholder/',
    );
    const html = renderMarkdown(body).html;
    sql += `\nDO $guide$\nDECLARE tid bigint; aid bigint;\nBEGIN\n IF NOT EXISTS (SELECT 1 FROM player_guides WHERE locale = ${literal(locale)} AND key = ${literal(g.key)}) THEN\n  SELECT id INTO STRICT aid FROM members WHERE email = 'releases@outbrick.site' AND role = 'team';\n  INSERT INTO threads (category_id, author_id, title, slug, language, pinned, last_poster_id)\n  VALUES ((SELECT id FROM categories WHERE slug = ${literal(g.category)}), aid, ${literal(g.title)}, ${literal(`player-guide-${g.key}-${locale}`)}, ${literal(locale)}, ${g.key === 'index'}, aid) RETURNING id INTO tid;\n  INSERT INTO player_guides VALUES (${literal(locale)}, ${literal(g.key)}, tid);\n  INSERT INTO posts (thread_id, author_id, number, body_md, body_html) VALUES (tid, aid, 1, ${literal(body)}, ${literal(html)});\n END IF;\nEND $guide$;\n`;
  }
  // Resolve only owned opening posts, not comments. Replay leaves already-resolved bodies intact.
  sql += `\nDO $links$\nDECLARE target record;\nBEGIN\n FOR target IN SELECT g.key, t.id, t.slug FROM player_guides g JOIN threads t ON t.id = g.thread_id WHERE g.locale = ${literal(locale)} LOOP\n  UPDATE posts SET body_md = replace(body_md, '/community/guide-placeholder/' || target.key, ${literal(locale === 'en' ? '/community/t/' : `/${locale}/community/t/`)} || target.id || '/' || target.slug),\n   body_html = replace(body_html, '/community/guide-placeholder/' || target.key, ${literal(locale === 'en' ? '/community/t/' : `/${locale}/community/t/`)} || target.id || '/' || target.slug)\n  WHERE number = 1 AND thread_id IN (SELECT thread_id FROM player_guides WHERE locale = ${literal(locale)});\n END LOOP;\nEND $links$;\n`;
}
const dir = 'netlify/database/migrations/20261007170000_player-guides';
fs.mkdirSync(dir, { recursive: true });
fs.writeFileSync(`${dir}/migration.sql`, sql);
console.log(
  `Generated ${locales.length * 9} team guides with locale-specific thread links.`,
);
