// The seeded player-guide threads (migrations 20261007170000_player-guides and
// 20261007190100_brazilian_portuguese_player_guides) describe 5.0.1. This writes one additive,
// idempotent migration that puts a short note at the top of each guide's opening post, in the
// thread's own language, pointing to the matching illustrated Help Centre page. The seed's rows
// are found exactly as the seed made them (player_guides by locale and key, post number 1);
// body_html is the allow-list renderer's own output for the note, joined to the stored HTML the
// way the renderer joins blocks, so body_md and body_html stay in step. `search` is a generated
// column and translations are keyed by a hash of the body, so both follow on their own.
//
//   node --experimental-strip-types scripts/build-guide-help-notes.mts
import fs from 'node:fs';
import { renderMarkdown } from '../netlify/community/markdown.ts';
import type { Locale } from '../lib/i18n/locales.ts';

const SITE = 'https://www.outbrick.site';
export const guideHelpSlugs: Record<string, string> = {
  'first-board': 'welcome',
  'specials-and-stars': 'bricks-specials-and-blockers',
  journey: 'journey-and-villages',
  voiceover: 'voiceover',
  settings: 'accessibility',
  'lives-moves-undos': 'lives-moves-and-undos',
  'asking-for-help': 'reporting-bugs',
  versions: 'troubleshooting',
  index: '',
};

/** The note, by language: one for a guide, one for the library thread that lists them. */
const notes: Record<Locale, { guide: (url: string) => string; library: (url: string) => string }> = {
  en: {
    guide: (u) => `**Illustrated guide:** this guide is also in the [Help Centre](${u}), with real screenshots from the game.`,
    library: (u) => `**Illustrated guides:** the player guides are also in the [Help Centre](${u}), with real screenshots from the game.`,
  },
  fr: {
    guide: (u) => `**Guide illustré** : ce guide se trouve aussi dans le [centre d’aide](${u}) illustré, avec de vraies captures d’écran du jeu.`,
    library: (u) => `**Guides illustrés** : les guides de jeu se trouvent aussi dans le [centre d’aide](${u}) illustré, avec de vraies captures d’écran du jeu.`,
  },
  de: {
    guide: (u) => `**Bebilderte Anleitung:** Diese Anleitung steht auch im bebilderten [Hilfe-Center](${u}), mit echten Bildschirmfotos aus dem Spiel.`,
    library: (u) => `**Bebilderte Anleitungen:** Die Spielanleitungen stehen auch im bebilderten [Hilfe-Center](${u}), mit echten Bildschirmfotos aus dem Spiel.`,
  },
  es: {
    guide: (u) => `**Guía ilustrada:** esta guía también está en el [centro de ayuda](${u}) ilustrado, con capturas reales del juego.`,
    library: (u) => `**Guías ilustradas:** las guías de juego también están en el [centro de ayuda](${u}) ilustrado, con capturas reales del juego.`,
  },
  ja: {
    guide: (u) => `**図解ガイド**：このガイドは、ゲームの実際の画面写真入りの[ヘルプセンター](${u})でも読めます。`,
    library: (u) => `**図解ガイド**：プレイヤーガイドは、ゲームの実際の画面写真入りの[ヘルプセンター](${u})でも読めます。`,
  },
  'pt-BR': {
    guide: (u) => `**Guia ilustrado:** este guia também está na [Central de Ajuda](${u}) ilustrada, com capturas de tela reais do jogo.`,
    library: (u) => `**Guias ilustrados:** os guias do jogo também estão na [Central de Ajuda](${u}) ilustrada, com capturas de tela reais do jogo.`,
  },
};

export function helpUrl(locale: Locale, key: string): string {
  const slug = guideHelpSlugs[key];
  return `${SITE}${locale === 'en' ? '' : `/${locale}`}/community/help${slug ? `/${slug}` : ''}`;
}

export function noteFor(locale: Locale, key: string): { md: string; html: string } {
  const url = helpUrl(locale, key);
  const md = key === 'index' ? notes[locale].library(url) : notes[locale].guide(url);
  return { md, html: renderMarkdown(md).html };
}

const literal = (text: string) => `'${text.replaceAll("'", "''")}'`;

function buildMigration(): string {
  let sql = `-- Generated by scripts/build-guide-help-notes.mts. Additive and idempotent: puts a note at the top of
-- each seeded player-guide thread's opening post (all six languages) pointing to its illustrated Help
-- Centre page. Touches only the posts the seeds made (player_guides, post 1); skips a post that already
-- carries its Help Centre link, so a replay changes nothing. No notifications, no edited_at: this is
-- an editorial note, not a member's edit.
`;
  for (const locale of ['en', 'fr', 'de', 'es', 'ja', 'pt-BR'] as const) {
    for (const key of Object.keys(guideHelpSlugs)) {
      const { md, html } = noteFor(locale, key);
      sql += `
UPDATE posts SET
  body_md = ${literal(md)} || '\n\n' || body_md,
  body_html = ${literal(html)} || '\n' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = ${literal(locale)} AND key = ${literal(key)})
  AND position(${literal(`](${helpUrl(locale, key)})`)} IN body_md) = 0
  AND char_length(body_md) + ${Array.from(md).length + 2} <= 20000;
`;
    }
  }
  return sql;
}

const migration = 'netlify/database/migrations/20261008170000_player-guide-help-centre-notes/migration.sql';
if (import.meta.url === `file://${process.argv[1]}`) {
  const sql = buildMigration();
  if (fs.existsSync(migration) && fs.readFileSync(migration, 'utf8') !== sql)
    throw new Error(`Migration ${migration} is immutable once applied; write changes in a new additive migration.`);
  fs.mkdirSync(migration.slice(0, migration.lastIndexOf('/')), { recursive: true });
  fs.writeFileSync(migration, sql);
  console.log(`wrote ${migration}`);
}
