-- Generated by scripts/build-guide-help-notes.mts. Additive and idempotent: puts a note at the top of
-- each seeded player-guide thread's opening post (all six languages) pointing to its illustrated Help
-- Centre page. Touches only the posts the seeds made (player_guides, post 1); skips a post that already
-- carries its Help Centre link, so a replay changes nothing. No notifications, no edited_at: this is
-- an editorial note, not a member's edit.

UPDATE posts SET
  body_md = '**Illustrated guide:** this guide is also in the [Help Centre](https://www.outbrick.site/community/help/welcome), with real screenshots from the game.' || '

' || body_md,
  body_html = '<p><strong>Illustrated guide:</strong> this guide is also in the <a href="https://www.outbrick.site/community/help/welcome" rel="ugc nofollow noopener">Help Centre</a>, with real screenshots from the game.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'en' AND key = 'first-board')
  AND position('](https://www.outbrick.site/community/help/welcome)' IN body_md) = 0
  AND char_length(body_md) + 152 <= 20000;

UPDATE posts SET
  body_md = '**Illustrated guide:** this guide is also in the [Help Centre](https://www.outbrick.site/community/help/bricks-specials-and-blockers), with real screenshots from the game.' || '

' || body_md,
  body_html = '<p><strong>Illustrated guide:</strong> this guide is also in the <a href="https://www.outbrick.site/community/help/bricks-specials-and-blockers" rel="ugc nofollow noopener">Help Centre</a>, with real screenshots from the game.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'en' AND key = 'specials-and-stars')
  AND position('](https://www.outbrick.site/community/help/bricks-specials-and-blockers)' IN body_md) = 0
  AND char_length(body_md) + 173 <= 20000;

UPDATE posts SET
  body_md = '**Illustrated guide:** this guide is also in the [Help Centre](https://www.outbrick.site/community/help/journey-and-villages), with real screenshots from the game.' || '

' || body_md,
  body_html = '<p><strong>Illustrated guide:</strong> this guide is also in the <a href="https://www.outbrick.site/community/help/journey-and-villages" rel="ugc nofollow noopener">Help Centre</a>, with real screenshots from the game.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'en' AND key = 'journey')
  AND position('](https://www.outbrick.site/community/help/journey-and-villages)' IN body_md) = 0
  AND char_length(body_md) + 165 <= 20000;

UPDATE posts SET
  body_md = '**Illustrated guide:** this guide is also in the [Help Centre](https://www.outbrick.site/community/help/voiceover), with real screenshots from the game.' || '

' || body_md,
  body_html = '<p><strong>Illustrated guide:</strong> this guide is also in the <a href="https://www.outbrick.site/community/help/voiceover" rel="ugc nofollow noopener">Help Centre</a>, with real screenshots from the game.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'en' AND key = 'voiceover')
  AND position('](https://www.outbrick.site/community/help/voiceover)' IN body_md) = 0
  AND char_length(body_md) + 154 <= 20000;

UPDATE posts SET
  body_md = '**Illustrated guide:** this guide is also in the [Help Centre](https://www.outbrick.site/community/help/accessibility), with real screenshots from the game.' || '

' || body_md,
  body_html = '<p><strong>Illustrated guide:</strong> this guide is also in the <a href="https://www.outbrick.site/community/help/accessibility" rel="ugc nofollow noopener">Help Centre</a>, with real screenshots from the game.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'en' AND key = 'settings')
  AND position('](https://www.outbrick.site/community/help/accessibility)' IN body_md) = 0
  AND char_length(body_md) + 158 <= 20000;

UPDATE posts SET
  body_md = '**Illustrated guide:** this guide is also in the [Help Centre](https://www.outbrick.site/community/help/lives-moves-and-undos), with real screenshots from the game.' || '

' || body_md,
  body_html = '<p><strong>Illustrated guide:</strong> this guide is also in the <a href="https://www.outbrick.site/community/help/lives-moves-and-undos" rel="ugc nofollow noopener">Help Centre</a>, with real screenshots from the game.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'en' AND key = 'lives-moves-undos')
  AND position('](https://www.outbrick.site/community/help/lives-moves-and-undos)' IN body_md) = 0
  AND char_length(body_md) + 166 <= 20000;

UPDATE posts SET
  body_md = '**Illustrated guide:** this guide is also in the [Help Centre](https://www.outbrick.site/community/help/reporting-bugs), with real screenshots from the game.' || '

' || body_md,
  body_html = '<p><strong>Illustrated guide:</strong> this guide is also in the <a href="https://www.outbrick.site/community/help/reporting-bugs" rel="ugc nofollow noopener">Help Centre</a>, with real screenshots from the game.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'en' AND key = 'asking-for-help')
  AND position('](https://www.outbrick.site/community/help/reporting-bugs)' IN body_md) = 0
  AND char_length(body_md) + 159 <= 20000;

UPDATE posts SET
  body_md = '**Illustrated guide:** this guide is also in the [Help Centre](https://www.outbrick.site/community/help/troubleshooting), with real screenshots from the game.' || '

' || body_md,
  body_html = '<p><strong>Illustrated guide:</strong> this guide is also in the <a href="https://www.outbrick.site/community/help/troubleshooting" rel="ugc nofollow noopener">Help Centre</a>, with real screenshots from the game.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'en' AND key = 'versions')
  AND position('](https://www.outbrick.site/community/help/troubleshooting)' IN body_md) = 0
  AND char_length(body_md) + 160 <= 20000;

UPDATE posts SET
  body_md = '**Illustrated guides:** the player guides are also in the [Help Centre](https://www.outbrick.site/community/help), with real screenshots from the game.' || '

' || body_md,
  body_html = '<p><strong>Illustrated guides:</strong> the player guides are also in the <a href="https://www.outbrick.site/community/help" rel="ugc nofollow noopener">Help Centre</a>, with real screenshots from the game.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'en' AND key = 'index')
  AND position('](https://www.outbrick.site/community/help)' IN body_md) = 0
  AND char_length(body_md) + 153 <= 20000;

UPDATE posts SET
  body_md = '**Guide illustré** : ce guide se trouve aussi dans le [centre d’aide](https://www.outbrick.site/fr/community/help/welcome) illustré, avec de vraies captures d’écran du jeu.' || '

' || body_md,
  body_html = '<p><strong>Guide illustré</strong> : ce guide se trouve aussi dans le <a href="https://www.outbrick.site/fr/community/help/welcome" rel="ugc nofollow noopener">centre d’aide</a> illustré, avec de vraies captures d’écran du jeu.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'fr' AND key = 'first-board')
  AND position('](https://www.outbrick.site/fr/community/help/welcome)' IN body_md) = 0
  AND char_length(body_md) + 174 <= 20000;

UPDATE posts SET
  body_md = '**Guide illustré** : ce guide se trouve aussi dans le [centre d’aide](https://www.outbrick.site/fr/community/help/bricks-specials-and-blockers) illustré, avec de vraies captures d’écran du jeu.' || '

' || body_md,
  body_html = '<p><strong>Guide illustré</strong> : ce guide se trouve aussi dans le <a href="https://www.outbrick.site/fr/community/help/bricks-specials-and-blockers" rel="ugc nofollow noopener">centre d’aide</a> illustré, avec de vraies captures d’écran du jeu.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'fr' AND key = 'specials-and-stars')
  AND position('](https://www.outbrick.site/fr/community/help/bricks-specials-and-blockers)' IN body_md) = 0
  AND char_length(body_md) + 195 <= 20000;

UPDATE posts SET
  body_md = '**Guide illustré** : ce guide se trouve aussi dans le [centre d’aide](https://www.outbrick.site/fr/community/help/journey-and-villages) illustré, avec de vraies captures d’écran du jeu.' || '

' || body_md,
  body_html = '<p><strong>Guide illustré</strong> : ce guide se trouve aussi dans le <a href="https://www.outbrick.site/fr/community/help/journey-and-villages" rel="ugc nofollow noopener">centre d’aide</a> illustré, avec de vraies captures d’écran du jeu.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'fr' AND key = 'journey')
  AND position('](https://www.outbrick.site/fr/community/help/journey-and-villages)' IN body_md) = 0
  AND char_length(body_md) + 187 <= 20000;

UPDATE posts SET
  body_md = '**Guide illustré** : ce guide se trouve aussi dans le [centre d’aide](https://www.outbrick.site/fr/community/help/voiceover) illustré, avec de vraies captures d’écran du jeu.' || '

' || body_md,
  body_html = '<p><strong>Guide illustré</strong> : ce guide se trouve aussi dans le <a href="https://www.outbrick.site/fr/community/help/voiceover" rel="ugc nofollow noopener">centre d’aide</a> illustré, avec de vraies captures d’écran du jeu.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'fr' AND key = 'voiceover')
  AND position('](https://www.outbrick.site/fr/community/help/voiceover)' IN body_md) = 0
  AND char_length(body_md) + 176 <= 20000;

UPDATE posts SET
  body_md = '**Guide illustré** : ce guide se trouve aussi dans le [centre d’aide](https://www.outbrick.site/fr/community/help/accessibility) illustré, avec de vraies captures d’écran du jeu.' || '

' || body_md,
  body_html = '<p><strong>Guide illustré</strong> : ce guide se trouve aussi dans le <a href="https://www.outbrick.site/fr/community/help/accessibility" rel="ugc nofollow noopener">centre d’aide</a> illustré, avec de vraies captures d’écran du jeu.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'fr' AND key = 'settings')
  AND position('](https://www.outbrick.site/fr/community/help/accessibility)' IN body_md) = 0
  AND char_length(body_md) + 180 <= 20000;

UPDATE posts SET
  body_md = '**Guide illustré** : ce guide se trouve aussi dans le [centre d’aide](https://www.outbrick.site/fr/community/help/lives-moves-and-undos) illustré, avec de vraies captures d’écran du jeu.' || '

' || body_md,
  body_html = '<p><strong>Guide illustré</strong> : ce guide se trouve aussi dans le <a href="https://www.outbrick.site/fr/community/help/lives-moves-and-undos" rel="ugc nofollow noopener">centre d’aide</a> illustré, avec de vraies captures d’écran du jeu.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'fr' AND key = 'lives-moves-undos')
  AND position('](https://www.outbrick.site/fr/community/help/lives-moves-and-undos)' IN body_md) = 0
  AND char_length(body_md) + 188 <= 20000;

UPDATE posts SET
  body_md = '**Guide illustré** : ce guide se trouve aussi dans le [centre d’aide](https://www.outbrick.site/fr/community/help/reporting-bugs) illustré, avec de vraies captures d’écran du jeu.' || '

' || body_md,
  body_html = '<p><strong>Guide illustré</strong> : ce guide se trouve aussi dans le <a href="https://www.outbrick.site/fr/community/help/reporting-bugs" rel="ugc nofollow noopener">centre d’aide</a> illustré, avec de vraies captures d’écran du jeu.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'fr' AND key = 'asking-for-help')
  AND position('](https://www.outbrick.site/fr/community/help/reporting-bugs)' IN body_md) = 0
  AND char_length(body_md) + 181 <= 20000;

UPDATE posts SET
  body_md = '**Guide illustré** : ce guide se trouve aussi dans le [centre d’aide](https://www.outbrick.site/fr/community/help/troubleshooting) illustré, avec de vraies captures d’écran du jeu.' || '

' || body_md,
  body_html = '<p><strong>Guide illustré</strong> : ce guide se trouve aussi dans le <a href="https://www.outbrick.site/fr/community/help/troubleshooting" rel="ugc nofollow noopener">centre d’aide</a> illustré, avec de vraies captures d’écran du jeu.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'fr' AND key = 'versions')
  AND position('](https://www.outbrick.site/fr/community/help/troubleshooting)' IN body_md) = 0
  AND char_length(body_md) + 182 <= 20000;

UPDATE posts SET
  body_md = '**Guides illustrés** : les guides de jeu se trouvent aussi dans le [centre d’aide](https://www.outbrick.site/fr/community/help) illustré, avec de vraies captures d’écran du jeu.' || '

' || body_md,
  body_html = '<p><strong>Guides illustrés</strong> : les guides de jeu se trouvent aussi dans le <a href="https://www.outbrick.site/fr/community/help" rel="ugc nofollow noopener">centre d’aide</a> illustré, avec de vraies captures d’écran du jeu.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'fr' AND key = 'index')
  AND position('](https://www.outbrick.site/fr/community/help)' IN body_md) = 0
  AND char_length(body_md) + 179 <= 20000;

UPDATE posts SET
  body_md = '**Bebilderte Anleitung:** Diese Anleitung steht auch im bebilderten [Hilfe-Center](https://www.outbrick.site/de/community/help/welcome), mit echten Bildschirmfotos aus dem Spiel.' || '

' || body_md,
  body_html = '<p><strong>Bebilderte Anleitung:</strong> Diese Anleitung steht auch im bebilderten <a href="https://www.outbrick.site/de/community/help/welcome" rel="ugc nofollow noopener">Hilfe-Center</a>, mit echten Bildschirmfotos aus dem Spiel.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'de' AND key = 'first-board')
  AND position('](https://www.outbrick.site/de/community/help/welcome)' IN body_md) = 0
  AND char_length(body_md) + 180 <= 20000;

UPDATE posts SET
  body_md = '**Bebilderte Anleitung:** Diese Anleitung steht auch im bebilderten [Hilfe-Center](https://www.outbrick.site/de/community/help/bricks-specials-and-blockers), mit echten Bildschirmfotos aus dem Spiel.' || '

' || body_md,
  body_html = '<p><strong>Bebilderte Anleitung:</strong> Diese Anleitung steht auch im bebilderten <a href="https://www.outbrick.site/de/community/help/bricks-specials-and-blockers" rel="ugc nofollow noopener">Hilfe-Center</a>, mit echten Bildschirmfotos aus dem Spiel.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'de' AND key = 'specials-and-stars')
  AND position('](https://www.outbrick.site/de/community/help/bricks-specials-and-blockers)' IN body_md) = 0
  AND char_length(body_md) + 201 <= 20000;

UPDATE posts SET
  body_md = '**Bebilderte Anleitung:** Diese Anleitung steht auch im bebilderten [Hilfe-Center](https://www.outbrick.site/de/community/help/journey-and-villages), mit echten Bildschirmfotos aus dem Spiel.' || '

' || body_md,
  body_html = '<p><strong>Bebilderte Anleitung:</strong> Diese Anleitung steht auch im bebilderten <a href="https://www.outbrick.site/de/community/help/journey-and-villages" rel="ugc nofollow noopener">Hilfe-Center</a>, mit echten Bildschirmfotos aus dem Spiel.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'de' AND key = 'journey')
  AND position('](https://www.outbrick.site/de/community/help/journey-and-villages)' IN body_md) = 0
  AND char_length(body_md) + 193 <= 20000;

UPDATE posts SET
  body_md = '**Bebilderte Anleitung:** Diese Anleitung steht auch im bebilderten [Hilfe-Center](https://www.outbrick.site/de/community/help/voiceover), mit echten Bildschirmfotos aus dem Spiel.' || '

' || body_md,
  body_html = '<p><strong>Bebilderte Anleitung:</strong> Diese Anleitung steht auch im bebilderten <a href="https://www.outbrick.site/de/community/help/voiceover" rel="ugc nofollow noopener">Hilfe-Center</a>, mit echten Bildschirmfotos aus dem Spiel.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'de' AND key = 'voiceover')
  AND position('](https://www.outbrick.site/de/community/help/voiceover)' IN body_md) = 0
  AND char_length(body_md) + 182 <= 20000;

UPDATE posts SET
  body_md = '**Bebilderte Anleitung:** Diese Anleitung steht auch im bebilderten [Hilfe-Center](https://www.outbrick.site/de/community/help/accessibility), mit echten Bildschirmfotos aus dem Spiel.' || '

' || body_md,
  body_html = '<p><strong>Bebilderte Anleitung:</strong> Diese Anleitung steht auch im bebilderten <a href="https://www.outbrick.site/de/community/help/accessibility" rel="ugc nofollow noopener">Hilfe-Center</a>, mit echten Bildschirmfotos aus dem Spiel.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'de' AND key = 'settings')
  AND position('](https://www.outbrick.site/de/community/help/accessibility)' IN body_md) = 0
  AND char_length(body_md) + 186 <= 20000;

UPDATE posts SET
  body_md = '**Bebilderte Anleitung:** Diese Anleitung steht auch im bebilderten [Hilfe-Center](https://www.outbrick.site/de/community/help/lives-moves-and-undos), mit echten Bildschirmfotos aus dem Spiel.' || '

' || body_md,
  body_html = '<p><strong>Bebilderte Anleitung:</strong> Diese Anleitung steht auch im bebilderten <a href="https://www.outbrick.site/de/community/help/lives-moves-and-undos" rel="ugc nofollow noopener">Hilfe-Center</a>, mit echten Bildschirmfotos aus dem Spiel.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'de' AND key = 'lives-moves-undos')
  AND position('](https://www.outbrick.site/de/community/help/lives-moves-and-undos)' IN body_md) = 0
  AND char_length(body_md) + 194 <= 20000;

UPDATE posts SET
  body_md = '**Bebilderte Anleitung:** Diese Anleitung steht auch im bebilderten [Hilfe-Center](https://www.outbrick.site/de/community/help/reporting-bugs), mit echten Bildschirmfotos aus dem Spiel.' || '

' || body_md,
  body_html = '<p><strong>Bebilderte Anleitung:</strong> Diese Anleitung steht auch im bebilderten <a href="https://www.outbrick.site/de/community/help/reporting-bugs" rel="ugc nofollow noopener">Hilfe-Center</a>, mit echten Bildschirmfotos aus dem Spiel.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'de' AND key = 'asking-for-help')
  AND position('](https://www.outbrick.site/de/community/help/reporting-bugs)' IN body_md) = 0
  AND char_length(body_md) + 187 <= 20000;

UPDATE posts SET
  body_md = '**Bebilderte Anleitung:** Diese Anleitung steht auch im bebilderten [Hilfe-Center](https://www.outbrick.site/de/community/help/troubleshooting), mit echten Bildschirmfotos aus dem Spiel.' || '

' || body_md,
  body_html = '<p><strong>Bebilderte Anleitung:</strong> Diese Anleitung steht auch im bebilderten <a href="https://www.outbrick.site/de/community/help/troubleshooting" rel="ugc nofollow noopener">Hilfe-Center</a>, mit echten Bildschirmfotos aus dem Spiel.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'de' AND key = 'versions')
  AND position('](https://www.outbrick.site/de/community/help/troubleshooting)' IN body_md) = 0
  AND char_length(body_md) + 188 <= 20000;

UPDATE posts SET
  body_md = '**Bebilderte Anleitungen:** Die Spielanleitungen stehen auch im bebilderten [Hilfe-Center](https://www.outbrick.site/de/community/help), mit echten Bildschirmfotos aus dem Spiel.' || '

' || body_md,
  body_html = '<p><strong>Bebilderte Anleitungen:</strong> Die Spielanleitungen stehen auch im bebilderten <a href="https://www.outbrick.site/de/community/help" rel="ugc nofollow noopener">Hilfe-Center</a>, mit echten Bildschirmfotos aus dem Spiel.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'de' AND key = 'index')
  AND position('](https://www.outbrick.site/de/community/help)' IN body_md) = 0
  AND char_length(body_md) + 180 <= 20000;

UPDATE posts SET
  body_md = '**Guía ilustrada:** esta guía también está en el [centro de ayuda](https://www.outbrick.site/es/community/help/welcome) ilustrado, con capturas reales del juego.' || '

' || body_md,
  body_html = '<p><strong>Guía ilustrada:</strong> esta guía también está en el <a href="https://www.outbrick.site/es/community/help/welcome" rel="ugc nofollow noopener">centro de ayuda</a> ilustrado, con capturas reales del juego.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'es' AND key = 'first-board')
  AND position('](https://www.outbrick.site/es/community/help/welcome)' IN body_md) = 0
  AND char_length(body_md) + 163 <= 20000;

UPDATE posts SET
  body_md = '**Guía ilustrada:** esta guía también está en el [centro de ayuda](https://www.outbrick.site/es/community/help/bricks-specials-and-blockers) ilustrado, con capturas reales del juego.' || '

' || body_md,
  body_html = '<p><strong>Guía ilustrada:</strong> esta guía también está en el <a href="https://www.outbrick.site/es/community/help/bricks-specials-and-blockers" rel="ugc nofollow noopener">centro de ayuda</a> ilustrado, con capturas reales del juego.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'es' AND key = 'specials-and-stars')
  AND position('](https://www.outbrick.site/es/community/help/bricks-specials-and-blockers)' IN body_md) = 0
  AND char_length(body_md) + 184 <= 20000;

UPDATE posts SET
  body_md = '**Guía ilustrada:** esta guía también está en el [centro de ayuda](https://www.outbrick.site/es/community/help/journey-and-villages) ilustrado, con capturas reales del juego.' || '

' || body_md,
  body_html = '<p><strong>Guía ilustrada:</strong> esta guía también está en el <a href="https://www.outbrick.site/es/community/help/journey-and-villages" rel="ugc nofollow noopener">centro de ayuda</a> ilustrado, con capturas reales del juego.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'es' AND key = 'journey')
  AND position('](https://www.outbrick.site/es/community/help/journey-and-villages)' IN body_md) = 0
  AND char_length(body_md) + 176 <= 20000;

UPDATE posts SET
  body_md = '**Guía ilustrada:** esta guía también está en el [centro de ayuda](https://www.outbrick.site/es/community/help/voiceover) ilustrado, con capturas reales del juego.' || '

' || body_md,
  body_html = '<p><strong>Guía ilustrada:</strong> esta guía también está en el <a href="https://www.outbrick.site/es/community/help/voiceover" rel="ugc nofollow noopener">centro de ayuda</a> ilustrado, con capturas reales del juego.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'es' AND key = 'voiceover')
  AND position('](https://www.outbrick.site/es/community/help/voiceover)' IN body_md) = 0
  AND char_length(body_md) + 165 <= 20000;

UPDATE posts SET
  body_md = '**Guía ilustrada:** esta guía también está en el [centro de ayuda](https://www.outbrick.site/es/community/help/accessibility) ilustrado, con capturas reales del juego.' || '

' || body_md,
  body_html = '<p><strong>Guía ilustrada:</strong> esta guía también está en el <a href="https://www.outbrick.site/es/community/help/accessibility" rel="ugc nofollow noopener">centro de ayuda</a> ilustrado, con capturas reales del juego.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'es' AND key = 'settings')
  AND position('](https://www.outbrick.site/es/community/help/accessibility)' IN body_md) = 0
  AND char_length(body_md) + 169 <= 20000;

UPDATE posts SET
  body_md = '**Guía ilustrada:** esta guía también está en el [centro de ayuda](https://www.outbrick.site/es/community/help/lives-moves-and-undos) ilustrado, con capturas reales del juego.' || '

' || body_md,
  body_html = '<p><strong>Guía ilustrada:</strong> esta guía también está en el <a href="https://www.outbrick.site/es/community/help/lives-moves-and-undos" rel="ugc nofollow noopener">centro de ayuda</a> ilustrado, con capturas reales del juego.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'es' AND key = 'lives-moves-undos')
  AND position('](https://www.outbrick.site/es/community/help/lives-moves-and-undos)' IN body_md) = 0
  AND char_length(body_md) + 177 <= 20000;

UPDATE posts SET
  body_md = '**Guía ilustrada:** esta guía también está en el [centro de ayuda](https://www.outbrick.site/es/community/help/reporting-bugs) ilustrado, con capturas reales del juego.' || '

' || body_md,
  body_html = '<p><strong>Guía ilustrada:</strong> esta guía también está en el <a href="https://www.outbrick.site/es/community/help/reporting-bugs" rel="ugc nofollow noopener">centro de ayuda</a> ilustrado, con capturas reales del juego.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'es' AND key = 'asking-for-help')
  AND position('](https://www.outbrick.site/es/community/help/reporting-bugs)' IN body_md) = 0
  AND char_length(body_md) + 170 <= 20000;

UPDATE posts SET
  body_md = '**Guía ilustrada:** esta guía también está en el [centro de ayuda](https://www.outbrick.site/es/community/help/troubleshooting) ilustrado, con capturas reales del juego.' || '

' || body_md,
  body_html = '<p><strong>Guía ilustrada:</strong> esta guía también está en el <a href="https://www.outbrick.site/es/community/help/troubleshooting" rel="ugc nofollow noopener">centro de ayuda</a> ilustrado, con capturas reales del juego.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'es' AND key = 'versions')
  AND position('](https://www.outbrick.site/es/community/help/troubleshooting)' IN body_md) = 0
  AND char_length(body_md) + 171 <= 20000;

UPDATE posts SET
  body_md = '**Guías ilustradas:** las guías de juego también están en el [centro de ayuda](https://www.outbrick.site/es/community/help) ilustrado, con capturas reales del juego.' || '

' || body_md,
  body_html = '<p><strong>Guías ilustradas:</strong> las guías de juego también están en el <a href="https://www.outbrick.site/es/community/help" rel="ugc nofollow noopener">centro de ayuda</a> ilustrado, con capturas reales del juego.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'es' AND key = 'index')
  AND position('](https://www.outbrick.site/es/community/help)' IN body_md) = 0
  AND char_length(body_md) + 167 <= 20000;

UPDATE posts SET
  body_md = '**図解ガイド**：このガイドは、ゲームの実際の画面写真入りの[ヘルプセンター](https://www.outbrick.site/ja/community/help/welcome)でも読めます。' || '

' || body_md,
  body_html = '<p><strong>図解ガイド</strong>：このガイドは、ゲームの実際の画面写真入りの<a href="https://www.outbrick.site/ja/community/help/welcome" rel="ugc nofollow noopener">ヘルプセンター</a>でも読めます。</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'ja' AND key = 'first-board')
  AND position('](https://www.outbrick.site/ja/community/help/welcome)' IN body_md) = 0
  AND char_length(body_md) + 102 <= 20000;

UPDATE posts SET
  body_md = '**図解ガイド**：このガイドは、ゲームの実際の画面写真入りの[ヘルプセンター](https://www.outbrick.site/ja/community/help/bricks-specials-and-blockers)でも読めます。' || '

' || body_md,
  body_html = '<p><strong>図解ガイド</strong>：このガイドは、ゲームの実際の画面写真入りの<a href="https://www.outbrick.site/ja/community/help/bricks-specials-and-blockers" rel="ugc nofollow noopener">ヘルプセンター</a>でも読めます。</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'ja' AND key = 'specials-and-stars')
  AND position('](https://www.outbrick.site/ja/community/help/bricks-specials-and-blockers)' IN body_md) = 0
  AND char_length(body_md) + 123 <= 20000;

UPDATE posts SET
  body_md = '**図解ガイド**：このガイドは、ゲームの実際の画面写真入りの[ヘルプセンター](https://www.outbrick.site/ja/community/help/journey-and-villages)でも読めます。' || '

' || body_md,
  body_html = '<p><strong>図解ガイド</strong>：このガイドは、ゲームの実際の画面写真入りの<a href="https://www.outbrick.site/ja/community/help/journey-and-villages" rel="ugc nofollow noopener">ヘルプセンター</a>でも読めます。</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'ja' AND key = 'journey')
  AND position('](https://www.outbrick.site/ja/community/help/journey-and-villages)' IN body_md) = 0
  AND char_length(body_md) + 115 <= 20000;

UPDATE posts SET
  body_md = '**図解ガイド**：このガイドは、ゲームの実際の画面写真入りの[ヘルプセンター](https://www.outbrick.site/ja/community/help/voiceover)でも読めます。' || '

' || body_md,
  body_html = '<p><strong>図解ガイド</strong>：このガイドは、ゲームの実際の画面写真入りの<a href="https://www.outbrick.site/ja/community/help/voiceover" rel="ugc nofollow noopener">ヘルプセンター</a>でも読めます。</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'ja' AND key = 'voiceover')
  AND position('](https://www.outbrick.site/ja/community/help/voiceover)' IN body_md) = 0
  AND char_length(body_md) + 104 <= 20000;

UPDATE posts SET
  body_md = '**図解ガイド**：このガイドは、ゲームの実際の画面写真入りの[ヘルプセンター](https://www.outbrick.site/ja/community/help/accessibility)でも読めます。' || '

' || body_md,
  body_html = '<p><strong>図解ガイド</strong>：このガイドは、ゲームの実際の画面写真入りの<a href="https://www.outbrick.site/ja/community/help/accessibility" rel="ugc nofollow noopener">ヘルプセンター</a>でも読めます。</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'ja' AND key = 'settings')
  AND position('](https://www.outbrick.site/ja/community/help/accessibility)' IN body_md) = 0
  AND char_length(body_md) + 108 <= 20000;

UPDATE posts SET
  body_md = '**図解ガイド**：このガイドは、ゲームの実際の画面写真入りの[ヘルプセンター](https://www.outbrick.site/ja/community/help/lives-moves-and-undos)でも読めます。' || '

' || body_md,
  body_html = '<p><strong>図解ガイド</strong>：このガイドは、ゲームの実際の画面写真入りの<a href="https://www.outbrick.site/ja/community/help/lives-moves-and-undos" rel="ugc nofollow noopener">ヘルプセンター</a>でも読めます。</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'ja' AND key = 'lives-moves-undos')
  AND position('](https://www.outbrick.site/ja/community/help/lives-moves-and-undos)' IN body_md) = 0
  AND char_length(body_md) + 116 <= 20000;

UPDATE posts SET
  body_md = '**図解ガイド**：このガイドは、ゲームの実際の画面写真入りの[ヘルプセンター](https://www.outbrick.site/ja/community/help/reporting-bugs)でも読めます。' || '

' || body_md,
  body_html = '<p><strong>図解ガイド</strong>：このガイドは、ゲームの実際の画面写真入りの<a href="https://www.outbrick.site/ja/community/help/reporting-bugs" rel="ugc nofollow noopener">ヘルプセンター</a>でも読めます。</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'ja' AND key = 'asking-for-help')
  AND position('](https://www.outbrick.site/ja/community/help/reporting-bugs)' IN body_md) = 0
  AND char_length(body_md) + 109 <= 20000;

UPDATE posts SET
  body_md = '**図解ガイド**：このガイドは、ゲームの実際の画面写真入りの[ヘルプセンター](https://www.outbrick.site/ja/community/help/troubleshooting)でも読めます。' || '

' || body_md,
  body_html = '<p><strong>図解ガイド</strong>：このガイドは、ゲームの実際の画面写真入りの<a href="https://www.outbrick.site/ja/community/help/troubleshooting" rel="ugc nofollow noopener">ヘルプセンター</a>でも読めます。</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'ja' AND key = 'versions')
  AND position('](https://www.outbrick.site/ja/community/help/troubleshooting)' IN body_md) = 0
  AND char_length(body_md) + 110 <= 20000;

UPDATE posts SET
  body_md = '**図解ガイド**：プレイヤーガイドは、ゲームの実際の画面写真入りの[ヘルプセンター](https://www.outbrick.site/ja/community/help)でも読めます。' || '

' || body_md,
  body_html = '<p><strong>図解ガイド</strong>：プレイヤーガイドは、ゲームの実際の画面写真入りの<a href="https://www.outbrick.site/ja/community/help" rel="ugc nofollow noopener">ヘルプセンター</a>でも読めます。</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'ja' AND key = 'index')
  AND position('](https://www.outbrick.site/ja/community/help)' IN body_md) = 0
  AND char_length(body_md) + 97 <= 20000;

UPDATE posts SET
  body_md = '**Guia ilustrado:** este guia também está na [Central de Ajuda](https://www.outbrick.site/pt-BR/community/help/welcome) ilustrada, com capturas de tela reais do jogo.' || '

' || body_md,
  body_html = '<p><strong>Guia ilustrado:</strong> este guia também está na <a href="https://www.outbrick.site/pt-BR/community/help/welcome" rel="ugc nofollow noopener">Central de Ajuda</a> ilustrada, com capturas de tela reais do jogo.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'pt-BR' AND key = 'first-board')
  AND position('](https://www.outbrick.site/pt-BR/community/help/welcome)' IN body_md) = 0
  AND char_length(body_md) + 168 <= 20000;

UPDATE posts SET
  body_md = '**Guia ilustrado:** este guia também está na [Central de Ajuda](https://www.outbrick.site/pt-BR/community/help/bricks-specials-and-blockers) ilustrada, com capturas de tela reais do jogo.' || '

' || body_md,
  body_html = '<p><strong>Guia ilustrado:</strong> este guia também está na <a href="https://www.outbrick.site/pt-BR/community/help/bricks-specials-and-blockers" rel="ugc nofollow noopener">Central de Ajuda</a> ilustrada, com capturas de tela reais do jogo.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'pt-BR' AND key = 'specials-and-stars')
  AND position('](https://www.outbrick.site/pt-BR/community/help/bricks-specials-and-blockers)' IN body_md) = 0
  AND char_length(body_md) + 189 <= 20000;

UPDATE posts SET
  body_md = '**Guia ilustrado:** este guia também está na [Central de Ajuda](https://www.outbrick.site/pt-BR/community/help/journey-and-villages) ilustrada, com capturas de tela reais do jogo.' || '

' || body_md,
  body_html = '<p><strong>Guia ilustrado:</strong> este guia também está na <a href="https://www.outbrick.site/pt-BR/community/help/journey-and-villages" rel="ugc nofollow noopener">Central de Ajuda</a> ilustrada, com capturas de tela reais do jogo.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'pt-BR' AND key = 'journey')
  AND position('](https://www.outbrick.site/pt-BR/community/help/journey-and-villages)' IN body_md) = 0
  AND char_length(body_md) + 181 <= 20000;

UPDATE posts SET
  body_md = '**Guia ilustrado:** este guia também está na [Central de Ajuda](https://www.outbrick.site/pt-BR/community/help/voiceover) ilustrada, com capturas de tela reais do jogo.' || '

' || body_md,
  body_html = '<p><strong>Guia ilustrado:</strong> este guia também está na <a href="https://www.outbrick.site/pt-BR/community/help/voiceover" rel="ugc nofollow noopener">Central de Ajuda</a> ilustrada, com capturas de tela reais do jogo.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'pt-BR' AND key = 'voiceover')
  AND position('](https://www.outbrick.site/pt-BR/community/help/voiceover)' IN body_md) = 0
  AND char_length(body_md) + 170 <= 20000;

UPDATE posts SET
  body_md = '**Guia ilustrado:** este guia também está na [Central de Ajuda](https://www.outbrick.site/pt-BR/community/help/accessibility) ilustrada, com capturas de tela reais do jogo.' || '

' || body_md,
  body_html = '<p><strong>Guia ilustrado:</strong> este guia também está na <a href="https://www.outbrick.site/pt-BR/community/help/accessibility" rel="ugc nofollow noopener">Central de Ajuda</a> ilustrada, com capturas de tela reais do jogo.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'pt-BR' AND key = 'settings')
  AND position('](https://www.outbrick.site/pt-BR/community/help/accessibility)' IN body_md) = 0
  AND char_length(body_md) + 174 <= 20000;

UPDATE posts SET
  body_md = '**Guia ilustrado:** este guia também está na [Central de Ajuda](https://www.outbrick.site/pt-BR/community/help/lives-moves-and-undos) ilustrada, com capturas de tela reais do jogo.' || '

' || body_md,
  body_html = '<p><strong>Guia ilustrado:</strong> este guia também está na <a href="https://www.outbrick.site/pt-BR/community/help/lives-moves-and-undos" rel="ugc nofollow noopener">Central de Ajuda</a> ilustrada, com capturas de tela reais do jogo.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'pt-BR' AND key = 'lives-moves-undos')
  AND position('](https://www.outbrick.site/pt-BR/community/help/lives-moves-and-undos)' IN body_md) = 0
  AND char_length(body_md) + 182 <= 20000;

UPDATE posts SET
  body_md = '**Guia ilustrado:** este guia também está na [Central de Ajuda](https://www.outbrick.site/pt-BR/community/help/reporting-bugs) ilustrada, com capturas de tela reais do jogo.' || '

' || body_md,
  body_html = '<p><strong>Guia ilustrado:</strong> este guia também está na <a href="https://www.outbrick.site/pt-BR/community/help/reporting-bugs" rel="ugc nofollow noopener">Central de Ajuda</a> ilustrada, com capturas de tela reais do jogo.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'pt-BR' AND key = 'asking-for-help')
  AND position('](https://www.outbrick.site/pt-BR/community/help/reporting-bugs)' IN body_md) = 0
  AND char_length(body_md) + 175 <= 20000;

UPDATE posts SET
  body_md = '**Guia ilustrado:** este guia também está na [Central de Ajuda](https://www.outbrick.site/pt-BR/community/help/troubleshooting) ilustrada, com capturas de tela reais do jogo.' || '

' || body_md,
  body_html = '<p><strong>Guia ilustrado:</strong> este guia também está na <a href="https://www.outbrick.site/pt-BR/community/help/troubleshooting" rel="ugc nofollow noopener">Central de Ajuda</a> ilustrada, com capturas de tela reais do jogo.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'pt-BR' AND key = 'versions')
  AND position('](https://www.outbrick.site/pt-BR/community/help/troubleshooting)' IN body_md) = 0
  AND char_length(body_md) + 176 <= 20000;

UPDATE posts SET
  body_md = '**Guias ilustrados:** os guias do jogo também estão na [Central de Ajuda](https://www.outbrick.site/pt-BR/community/help) ilustrada, com capturas de tela reais do jogo.' || '

' || body_md,
  body_html = '<p><strong>Guias ilustrados:</strong> os guias do jogo também estão na <a href="https://www.outbrick.site/pt-BR/community/help" rel="ugc nofollow noopener">Central de Ajuda</a> ilustrada, com capturas de tela reais do jogo.</p>' || '
' || body_html
WHERE number = 1
  AND thread_id = (SELECT thread_id FROM player_guides WHERE locale = 'pt-BR' AND key = 'index')
  AND position('](https://www.outbrick.site/pt-BR/community/help)' IN body_md) = 0
  AND char_length(body_md) + 170 <= 20000;
