import type { SupportCopy } from '../model.ts';

export const de: SupportCopy = {
  supportCrumb: 'Hilfe',
  hub: {
    title: 'Hilfe, wie es dir passt',
    lede: 'Löse es selbst in ein paar Schritten, sieh nach, ob wir das Problem schon kennen, oder verfolge eine Nachricht, die du uns geschickt hast.',
    fixTitle: 'Schritt für Schritt lösen',
    fixText: 'Wähle, was nicht stimmt, und probier eine Sache nach der anderen. Hilft nichts davon, übernehmen wir.',
    issuesTitle: 'Bekannte Probleme und Korrekturen',
    issuesText: 'Was gerade nicht funktioniert, was du bis dahin tun kannst und welches Update es behebt.',
    trackTitle: 'Deine Anfrage verfolgen',
    trackText: 'Sieh nach, wo deine Nachricht steht, lies jede Antwort des Teams und ergänze Details.',
    levelsTitle: 'Hilfe bei einem Level',
    levelsText: 'Kommst du bei einem Brett nicht weiter? Sieh nach, was andere Spieler dazu gesagt haben, oder frag sie.',
    involvedTitle: 'Gestalte OutBrick mit',
    involvedText: 'Teste Updates, bevor sie erscheinen, mach im Barrierefreiheits-Panel mit und hör jeden Monat vom Team.',
    promise: 'Ein Mensch aus dem Team liest jede Nachricht. Wir versuchen, innerhalb von zwei Werktagen zu antworten.',
  },

  levels: {
    metaTitle: 'Hilfe bei einem OutBrick-Level',
    metaDescription: 'Du hängst in OutBrick an einem Level fest? Sieh nach, was andere Spieler zu diesem Brett gesagt haben, frag die Community und hol dir Tipps für schwere Bretter.',
    eyebrow: 'OutBrick-Hilfe',
    title: 'Hilfe bei einem Level',
    lede: 'Gib die Nummer des Levels ein, bei dem du feststeckst, um zu sehen, was andere Spieler zu diesem Brett gesagt haben, oder frag sie. Die Nummer steht oben auf dem Brett.',
    label: 'Levelnummer',
    hint: 'Von 1 bis 2.000 und darüber hinaus.',
    action: 'Hilfe finden',
    invalid: 'Gib eine Levelnummer ein, zum Beispiel 512.',
    resultsTitle: (level) => `Level ${level} in der Community`,
    none: (level) => `Zu Level ${level} hat noch niemand gefragt. Mach den Anfang: Hier knobeln alle gern mit.`,
    loading: 'Themen werden gesucht …',
    failed: 'Wir konnten die Community gerade nicht laden. Bitte versuch es gleich noch einmal.',
    solved: 'Gelöst',
    replies: (n) => (n === 1 ? '1 Antwort' : `${n} Antworten`),
    askTitle: 'Zu diesem Level fragen',
    askText: 'Beschreib, was du schon probiert hast und wo du nicht weiterkommst. Andere Spieler und das Team antworten öffentlich.',
    askAction: 'Community fragen',
    askThreadTitle: (level) => `Level ${level}: `,
    bugAction: 'Problem mit diesem Level melden',
    tipsTitle: 'Bevor du fragst: Tipps für schwere Bretter',
    tips: [
      'Bei jedem Versuch bekommst du einen **Tipp**, eine **Rakete** und ein **UFO** gratis: Nutz zuerst den Tipp, er zeigt dir einen Zug, der weiterhilft.',
      'Lies die Ziele vor deinem ersten Zug: Ein Brett ist geschafft, sobald seine Ziele erreicht sind, und übrige Züge werden zu Liniensteinen.',
      '**Das erste Rückgängig** auf jedem Brett ist gratis. Nutz es, um einen anderen Tausch auszuprobieren.',
      'Ab deinem sechsten Versuch an einem Brett schenkt dir eine **helfende Hand** einmal am Tag drei Extrazüge.',
      'Ist kein Zug möglich, wird das Brett kostenlos neu gemischt, wirklich festsitzen kannst du also nie. Mehr dazu in [Leben, keine Züge mehr und Rückgängig](help:lives-moves-and-undos).',
    ],
    spoilersTitle: 'Ein Wort zu Spoilern',
    spoilersText: 'Viele Spieler knobeln ein Brett lieber selbst aus. Wenn du antwortest, gib zuerst einen kleinen Anstoß und verrate die ganze Lösung erst, wenn jemand danach fragt.',
  },

  involved: {
    metaTitle: 'Gestalte OutBrick mit: Betatest und Barrierefreiheits-Panel',
    metaDescription: 'Teste OutBrick-Updates mit TestFlight, bevor sie erscheinen, mach im Barrierefreiheits-Panel für Spieler mit VoiceOver, Sprachsteuerung und Schaltersteuerung mit und hör jeden Monat vom Team.',
    eyebrow: 'OutBrick-Community',
    title: 'Gestalte OutBrick mit',
    lede: 'OutBrick wird besser, weil Spieler uns sagen, was funktioniert und was nicht. Hier sind drei Wege, dabei zu sein.',
    beta: {
      title: 'Updates testen, bevor sie erscheinen',
      text: 'Tritt der Betagruppe bei und spiel neue Versionen von OutBrick mit Apples App TestFlight, ein paar Tage vor allen anderen.',
      points: [
        'Vor jedem Update laden wir Tester in kleinen Gruppen ein; die Einladung kommt per E-Mail von TestFlight.',
        'Du brauchst ein iPhone oder iPad mit einem aktuellen iOS und die kostenlose App TestFlight.',
        'Sag uns direkt in TestFlight oder in der Community, was nicht funktioniert oder sich falsch anfühlt.',
        'Du kannst die Beta jederzeit verlassen, und dein Fortschritt bleibt deiner.',
      ],
      action: 'Der Betagruppe beitreten',
    },
    panel: {
      title: 'Mach im Barrierefreiheits-Panel mit',
      text: 'Wenn du mit VoiceOver, Sprachsteuerung, Schaltersteuerung, einer Tastatur, Größerem Text oder Zoom spielst, prägt deine Erfahrung jedes Brett, das wir bauen.',
      points: [
        'Wir fragen das Panel zu neuen Brettern und Funktionen, bevor sie erscheinen, und setzen um, was wir hören.',
        'Ab und zu ein paar kurze Fragen oder ein Test-Build, nie mehr, als du möchtest.',
        'Sag uns, welche Bedienungshilfe du nutzt und wie wir dich am besten erreichen.',
      ],
      action: 'Beim Panel mitmachen',
    },
    monthly: {
      title: 'Jeden Monat vom Team',
      text: 'Einmal im Monat schreiben wir in den Ankündigungen, was erschienen ist, was wir von euch gehört haben und was als Nächstes kommt. Beobachte die Kategorie, um es per E-Mail zu bekommen, oder abonnier den OutBrick-Newsletter.',
      followAction: 'Ankündigungen beobachten',
      newsAction: 'OutBrick-Newsletter abonnieren',
    },
    honest: 'Mitmachen ist freiwillig und unbezahlt und ändert nie etwas an deinem Spiel. Du kannst jederzeit aussteigen, indem du auf eine unserer E-Mails antwortest.',
  },

  banner: {
    level: { info: 'Hinweis', warning: 'Achtung', outage: 'Störung' },
    more: 'Mehr erfahren',
    dismiss: 'Diesen Hinweis ausblenden',
  },

  attach: {
    label: 'Bildschirmfotos',
    hint: 'Bis zu drei Bilder. Wir entfernen Standort- und Kameradaten, bevor wir sie speichern, und nur das Team und du könnt sie sehen.',
    add: 'Bildschirmfoto hinzufügen',
    remove: 'Entfernen',
    uploading: 'Wird hochgeladen …',
    failed: 'Dieses Bild konnte nicht angehängt werden. Versuch es bitte mit einem PNG oder JPEG.',
    tooBig: 'Dieses Bild ist größer als 8 MB.',
    tooMany: 'Du kannst bis zu drei Bilder anhängen.',
    alt: (n) => `Bildschirmfoto ${n}`,
    title: 'Bildschirmfotos',
  },

  issues: {
    metaTitle: 'OutBrick: bekannte Probleme und Korrekturen',
    metaDescription: 'Die Probleme, die wir in OutBrick auf iPhone und iPad kennen, was du bis zur Korrektur tun kannst und welches Update sie bringt.',
    eyebrow: 'OutBrick-Hilfe',
    title: 'Bekannte Probleme und Korrekturen',
    lede: 'Etwas funktioniert nicht? Hier steht alles, wovon wir wissen, dass es gerade nicht funktioniert, was du bis zur Korrektur tun kannst und welches Update sie bringt. Wir halten diese Seite ehrlich und aktuell.',
    reviewed: (date) => `Zuletzt geprüft am ${date}`,
    openTitle: 'Daran arbeiten wir',
    resolvedTitle: 'Kürzlich behoben',
    noneOpen: 'Gerade ist uns kein Problem bekannt. Wenn bei dir etwas nicht funktioniert, sag uns bitte Bescheid.',
    status: { investigating: 'Wird untersucht', 'fix-coming': 'Korrektur unterwegs', fixed: 'Behoben' },
    affects: 'Wen es betrifft',
    whatHappens: 'Was passiert',
    workaround: 'Bis zur Korrektur',
    fix: 'Die Korrektur',
    readMore: 'Mehr dazu',
    notListedTitle: 'Nicht in der Liste?',
    notListedText: 'Dann kennen wir es vielleicht noch nicht. Ein Bericht mit Gerät, iOS-Version, OutBrick-Version und Level hilft uns, es schnell zu finden.',
    reportAction: 'Fehler melden',
    contactAction: 'Uns privat schreiben',
    stayTitle: 'Erfahren, wann eine Korrektur erscheint',
    stayText: 'Jede neue Version steht in den Ankündigungen, sobald sie im App Store ist. Beobachte die Kategorie, um eine E-Mail zu bekommen, und lass automatische Updates eingeschaltet, damit Korrekturen ganz von selbst bei dir ankommen.',
    stayAction: 'Ankündigungen beobachten',
  },

  fix: {
    metaTitle: 'Schritt für Schritt lösen: OutBrick-Problemlöser',
    metaDescription: 'Wähle, was in OutBrick nicht stimmt, und probier eine Lösung nach der anderen: fehlender Fortschritt, Käufe, Leben, Ton, Mitteilungen, Widgets, Videos und VoiceOver.',
    eyebrow: 'OutBrick-Hilfe',
    title: 'Schritt für Schritt lösen',
    lede: 'Wähle, was nicht stimmt, und wir gehen es mit dir Schritt für Schritt durch. Die meisten Probleme sind in ein, zwei Minuten gelöst, und wenn deins nicht dazugehört, übernimmt ein Mensch aus dem Team.',
    chooseTitle: 'Was stimmt nicht?',
    chooseHint: 'Wähle, was am besten passt.',
    stepOf: (step, total) => `Schritt ${step} von ${total}`,
    quickCheck: 'Kurz prüfen',
    worked: 'Das hat geholfen',
    next: 'Geht immer noch nicht',
    back: 'Zurück',
    another: 'Anderes Problem wählen',
    fixedTitle: 'Schön, dass es jetzt klappt.',
    fixedText: 'Danke, dass du die Schritte ausprobiert hast. Viel Spaß beim nächsten Brett.',
    stillTitle: 'Geht immer noch nicht? Ab hier übernehmen wir.',
    stillText: 'Schreib uns, und ein Mensch aus dem Team sieht sich das an. Deine Nachricht enthält, was du schon probiert hast, damit dich niemand bittet, es noch einmal zu tun.',
    contactAction: 'Support kontaktieren',
    askAction: 'Community fragen',
    bugAction: 'Fehler melden',
    knownIssue: 'Das ist ein bekanntes Problem, und eine Korrektur ist unterwegs.',
    allSteps: 'Alle Schritte',
    readGuide: 'Ganze Anleitung lesen',
  },

  request: {
    metaTitle: 'Deine Anfrage an den OutBrick-Support',
    metaDescription: 'Verfolge deine Anfrage an den OutBrick-Support: wo sie steht, jede Antwort des Teams und eine Möglichkeit, Details zu ergänzen.',
    eyebrow: 'OutBrick-Hilfe',
    title: 'Deine Anfrage',
    lede: 'Wo deine Nachricht steht, jede Antwort des Teams und ein Platz für alles, was wir noch wissen sollten.',
    loading: 'Deine Anfrage wird geöffnet …',
    invalid: 'Dieser Link öffnet keine Anfrage. Prüf, ob du ihn vollständig kopiert hast, oder fordere unten einen neuen Link an.',
    expired: 'Dieser Link ist abgelaufen. Fordere unten einen neuen an, er kommt innerhalb einer Minute.',
    failed: 'Wir konnten deine Anfrage gerade nicht öffnen. Bitte versuch es gleich noch einmal.',
    reference: 'Referenz',
    topic: 'Thema',
    opened: 'Gesendet',
    updated: 'Zuletzt aktualisiert',
    statusTitle: {
      open: 'Beim Team',
      replied: 'Wir haben geantwortet',
      fix_pending: 'Eine Korrektur ist unterwegs',
      resolved: 'Gelöst',
      closed: 'Geschlossen',
    },
    statusText: {
      open: 'Ein Mensch aus dem Team hat deine Nachricht und antwortet dir per E-Mail. Du kannst unten jederzeit Details ergänzen.',
      replied: 'Wir haben dir per E-Mail geantwortet. Hat das nicht geholfen, schreib es unten, und es geht direkt zurück ans Team.',
      fix_pending: 'Wir haben die Ursache gefunden und behoben. Wir schreiben dir, sobald das Update mit der Korrektur im App Store ist.',
      resolved: 'Diese Anfrage ist gelöst. Taucht das Problem wieder auf, schreib unten, und wir kümmern uns erneut darum.',
      closed: 'Diese Anfrage ist geschlossen. Brauchst du noch Hilfe, schreib unten, dann wird sie wieder geöffnet.',
    },
    stages: { received: 'Erhalten', answered: 'Beantwortet', fixing: 'Korrektur unterwegs', solved: 'Gelöst' },
    historyTitle: 'Verlauf',
    yourMessage: 'Deine Nachricht',
    detailsTitle: 'Deine Angaben',
    detail: {
      level: 'Level',
      'purchase-item': 'Kauf',
      'purchase-date': 'Gekauft am',
      assistive: 'Bedienungshilfe',
      tried: 'Schon probiert',
      guide: 'Aus der Anleitung',
      device: 'Gerät',
      ios: 'iOS-Version',
      app: 'OutBrick-Version',
    },
    event: {
      created: 'Du hast deine Nachricht gesendet',
      reply: (staff) => `${staff} vom Team hat geantwortet`,
      fixedIn: (version) => `Wir haben es in OutBrick ${version} behoben`,
      fixedShipped: (version) => `OutBrick ${version} mit der Korrektur ist im App Store erschienen`,
      resolved: 'Als gelöst markiert',
      closed: 'Geschlossen',
      reopened: 'Wieder geöffnet',
      solvedYes: 'Du hast uns gesagt, dass es gelöst ist',
      solvedNo: 'Du hast uns gesagt, dass es noch nicht gelöst ist',
      rated: (stars) => `Du hast unserer Hilfe ${stars === 1 ? '1 Stern' : `${stars} Sterne`} von 5 gegeben`,
      playerNote: 'Deine Ergänzung',
    },
    addTitle: 'Details ergänzen',
    addHint: 'Eine Levelnummer, was du probiert hast, was sich geändert hat. Bitte keine Passwörter und keine Kartendaten. Für ein Bildschirmfoto antworte auf unsere E-Mail und häng es an.',
    addLabel: 'Deine Nachricht',
    addAction: 'Ans Team senden',
    addSending: 'Wird gesendet …',
    added: 'Danke. Das Team hat deine Ergänzung.',
    addReopens: 'Damit wird deine Anfrage wieder geöffnet.',
    feedbackTitle: 'Haben wir es gelöst?',
    feedbackText: 'Ein Tippen genügt. Ein „Noch nicht“ geht direkt zurück ans Team.',
    solvedYes: 'Ja, gelöst',
    solvedNo: 'Noch nicht',
    rateLabel: 'Wie war unsere Hilfe?',
    lookupTitle: 'Link verloren?',
    lookupText: 'Gib deine Referenz und die E-Mail-Adresse ein, von der du geschrieben hast, und wir schicken dir den Link zu deiner Anfrage per E-Mail.',
    refLabel: 'Referenz',
    refHint: 'Sie sieht aus wie OB-7K2QXM und steht im Betreff unserer E-Mails.',
    emailLabel: 'Deine E-Mail-Adresse',
    lookupAction: 'Link per E-Mail schicken',
    lookupSending: 'Wird gesendet …',
    lookupSent: 'Wenn Referenz und Adresse zu einer Anfrage passen, ist ihr Link auf dem Weg an diese Adresse. Sieh in deinem Posteingang und im Spam-Ordner nach.',
    noLinkTitle: 'Eine Anfrage verfolgen',
    noLinkText: 'Jede Nachricht an uns bekommt eine Referenz wie OB-7K2QXM und einen privaten Link in unserer Antwort-E-Mail. Öffne diesen Link, um zu sehen, wo deine Anfrage steht, jede Antwort zu lesen und Details zu ergänzen.',
    tooMany: 'Das waren viele Versuche in kurzer Zeit. Bitte warte ein paar Minuten und versuch es dann noch einmal.',
    newRequest: 'Neue Nachricht schreiben',
  },

  feedback: {
    question: 'War diese Anleitung hilfreich?',
    pageQuestion: 'War diese Seite hilfreich?',
    yes: 'Ja',
    no: 'Nein',
    thanksYes: 'Danke! Schön, dass sie geholfen hat.',
    whyTitle: 'Das tut uns leid. Was hat nicht gepasst?',
    reasons: {
      unclear: 'Sie war schwer zu verstehen',
      missing: 'Meine Frage wurde nicht beantwortet',
      outdated: 'Sie passt nicht zum Spiel',
      'didnt-work': 'Ich bin ihr gefolgt, aber es hat nicht geklappt',
      other: 'Etwas anderes',
    },
    commentLabel: 'Erzähl uns mehr (optional)',
    commentHint: 'Wir lesen jede Antwort und verbessern damit die Anleitungen. Von hier kommt keine Antwort zurück, lass persönliche Angaben also bitte weg.',
    send: 'Senden',
    sending: 'Wird gesendet …',
    thanksNo: 'Danke. Wir lesen jede Antwort und verbessern damit die Anleitungen.',
    escalate: 'Brauchst du noch Hilfe? Ein Mensch aus dem Team hilft dir.',
    contactAction: 'Support kontaktieren',
    askAction: 'Community fragen',
    failed: 'Das wurde nicht gesendet. Bitte versuch es noch einmal.',
  },
};
