import type { SupportCopy } from '../model.ts';

export const en: SupportCopy = {
  supportCrumb: 'Support',
  hub: {
    title: 'Get help your way',
    lede: 'Fix it yourself in a few steps, check whether we already know about it, or follow a message you sent us.',
    fixTitle: 'Fix it step by step',
    fixText: 'Pick what is wrong and try one thing at a time. If nothing works, we take it from there.',
    issuesTitle: 'Known issues and fixes',
    issuesText: 'What we know is broken, what to do in the meantime, and which update fixes it.',
    trackTitle: 'Track your request',
    trackText: 'See where your message stands, read every reply from the team and add details.',
    levelsTitle: 'Help with a level',
    levelsText: 'Stuck on one board? See what other players said about it, or ask them.',
    involvedTitle: 'Help shape OutBrick',
    involvedText: 'Test updates before they ship, join the accessibility panel, and hear from the team every month.',
    promise: 'A person on the team reads every message. We aim to reply within two working days.',
  },

  levels: {
    metaTitle: 'Help with an OutBrick level: tips and community answers',
    metaDescription: 'Stuck on an OutBrick level? Find what other players said about that board, ask the community, and get tips for hard boards.',
    eyebrow: 'OutBrick support',
    title: 'Help with a level',
    lede: 'Enter the number of the level you are stuck on to see what other players have said about that board, or ask them. The number is at the top of the board.',
    label: 'Level number',
    hint: 'From 1 to 2,000 and beyond.',
    action: 'Find help',
    invalid: 'Enter a level number, like 512.',
    resultsTitle: (level) => `Level ${level} in the community`,
    none: (level) => `Nobody has asked about level ${level} yet. Be the first: players love a puzzle.`,
    loading: 'Looking for threads…',
    failed: 'We could not load the community just now. Please try again in a moment.',
    solved: 'Solved',
    replies: (n) => (n === 1 ? '1 reply' : `${n} replies`),
    askTitle: 'Ask about this level',
    askText: 'Describe what you have tried and where you get stuck. Other players and the team answer in the open.',
    askAction: 'Ask the community',
    askThreadTitle: (level) => `Level ${level}: `,
    bugAction: 'Report a problem with this level',
    tipsTitle: 'Before you ask: tips for hard boards',
    tips: [
      'Every attempt comes with a free **Hint**, **Rocket** and **UFO**: use the Hint first, it shows a move that helps.',
      'Read the goals before your first move: a board finishes as soon as its goals are met, and leftover moves become blasters.',
      'The first **undo** on every board is free. Use it to try a different swap.',
      'From your sixth attempt at a board, a **helping hand** adds three extra moves, once a day.',
      'If no move is possible, the board reshuffles for free, so you can never be truly stuck. More in [Lives, running out of moves, and undos](help:lives-moves-and-undos).',
    ],
    spoilersTitle: 'A word on spoilers',
    spoilersText: 'Many players like to work a board out themselves. When you answer, start with a nudge, and give the full solution only when someone asks for it.',
  },

  involved: {
    metaTitle: 'Help shape OutBrick: beta testing and the accessibility panel',
    metaDescription: 'Test OutBrick updates before they ship with TestFlight, join the accessibility panel of VoiceOver, Voice Control and Switch Control players, and hear from the team every month.',
    eyebrow: 'OutBrick community',
    title: 'Help shape OutBrick',
    lede: 'OutBrick is better because players tell us what works and what does not. Here are three ways to be part of it.',
    beta: {
      title: 'Test updates before they ship',
      text: 'Join the beta group and play new versions of OutBrick through Apple’s TestFlight app, a few days before everyone else.',
      points: [
        'We invite testers in small groups before each update; an invitation arrives by email from TestFlight.',
        'You need an iPhone or iPad on a recent iOS and the free TestFlight app.',
        'Tell us what breaks or feels wrong from inside TestFlight, or in the community.',
        'You can leave the beta at any time, and your progress stays yours.',
      ],
      action: 'Join the beta group',
    },
    panel: {
      title: 'Join the accessibility panel',
      text: 'If you play with VoiceOver, Voice Control, Switch Control, a keyboard, Larger Text or Zoom, your experience shapes every board we build.',
      points: [
        'We ask the panel about new boards and features before they ship, and act on what we hear.',
        'A few short questions or a test build now and then, never more than you want.',
        'Tell us which assistive technology you use, and how you would like us to reach you.',
      ],
      action: 'Join the panel',
    },
    monthly: {
      title: 'From the team, every month',
      text: 'Once a month we post what shipped, what we heard from you and what comes next, in Announcements. Follow the category to get it by email, or subscribe to OutBrick News.',
      followAction: 'Follow Announcements',
      newsAction: 'Subscribe to OutBrick News',
    },
    honest: 'Taking part is voluntary and unpaid, and it never changes anything about your game. Leave any time by replying to any of our emails.',
  },

  banner: {
    level: { info: 'Notice', warning: 'Heads up', outage: 'Service problem' },
    more: 'Find out more',
    dismiss: 'Dismiss this notice',
  },

  attach: {
    label: 'Screenshots',
    hint: 'Up to three images. We remove location and camera data before storing them, and only the team and you can see them.',
    add: 'Add a screenshot',
    remove: 'Remove',
    uploading: 'Uploading…',
    failed: 'That image could not be attached. Please try a PNG or JPEG.',
    tooBig: 'That image is larger than 8 MB.',
    tooMany: 'You can attach up to three images.',
    alt: (n) => `Screenshot ${n}`,
    title: 'Screenshots',
  },

  issues: {
    metaTitle: 'OutBrick known issues and fixes',
    metaDescription: 'The problems we know about in OutBrick on iPhone and iPad, what to do until they are fixed, and which update brings the fix.',
    eyebrow: 'OutBrick support',
    title: 'Known issues and fixes',
    lede: 'Something not working? Here is everything we know is broken right now, what you can do until it is fixed, and which update brings the fix. We keep this page honest and up to date.',
    reviewed: (date) => `Last reviewed ${date}`,
    openTitle: 'Being worked on',
    resolvedTitle: 'Recently fixed',
    noneOpen: 'Nothing is known to be broken right now. If something is not working for you, please tell us.',
    status: { investigating: 'Looking into it', 'fix-coming': 'Fix on its way', fixed: 'Fixed' },
    affects: 'Who it affects',
    whatHappens: 'What happens',
    workaround: 'Until it is fixed',
    fix: 'The fix',
    readMore: 'Read more',
    notListedTitle: 'Not on the list?',
    notListedText: 'Then we may not know about it yet. A report with your device, iOS version, OutBrick version and level helps us find it quickly.',
    reportAction: 'Report a bug',
    contactAction: 'Write to us privately',
    stayTitle: 'Hear when a fix ships',
    stayText: 'Every release is posted in Announcements the moment the App Store has it. Follow the category to get an email, and keep automatic updates on so fixes reach you without a thought.',
    stayAction: 'Follow Announcements',
  },

  fix: {
    metaTitle: 'Fix it step by step: OutBrick troubleshooter',
    metaDescription: 'Choose what is wrong in OutBrick and try one fix at a time: missing progress, purchases, lives, sound, notifications, widgets, videos and VoiceOver.',
    eyebrow: 'OutBrick support',
    title: 'Fix it step by step',
    lede: 'Choose what is wrong and we will walk you through one thing at a time. Most problems are solved in a minute or two, and if yours is not, a person on the team takes it from there.',
    chooseTitle: 'What is wrong?',
    chooseHint: 'Choose the closest match.',
    stepOf: (step, total) => `Step ${step} of ${total}`,
    quickCheck: 'Quick check',
    worked: 'That fixed it',
    next: 'Still not working',
    back: 'Back',
    another: 'Choose another problem',
    fixedTitle: 'Glad that sorted it.',
    fixedText: 'Thank you for trying the steps. Enjoy your next board.',
    stillTitle: 'Still not working? We will take it from here.',
    stillText: 'Write to us and a person on the team will look into it. Your message says what you have already tried, so nobody asks you to do it again.',
    contactAction: 'Contact support',
    askAction: 'Ask the community',
    bugAction: 'Report a bug',
    knownIssue: 'This is a known issue, and a fix is on its way.',
    allSteps: 'All the steps',
    readGuide: 'Read the full guide',
  },

  request: {
    metaTitle: 'Your OutBrick support request',
    metaDescription: 'Follow your OutBrick support request: where it stands, every reply from the team, and a way to add details.',
    eyebrow: 'OutBrick support',
    title: 'Your request',
    lede: 'Where your message stands, every reply from the team, and a place to add anything we should know.',
    loading: 'Opening your request…',
    invalid: 'This link does not open a request. Check that you copied all of it, or ask for a new link below.',
    expired: 'This link has expired. Ask for a new one below and it will arrive in a minute.',
    failed: 'We could not open your request just now. Please try again in a moment.',
    reference: 'Reference',
    topic: 'Topic',
    opened: 'Sent',
    updated: 'Last update',
    statusTitle: {
      open: 'With the team',
      replied: 'We replied',
      fix_pending: 'A fix is on its way',
      resolved: 'Solved',
      closed: 'Closed',
    },
    statusText: {
      open: 'A person on the team has your message and will reply by email. You can add details below at any time.',
      replied: 'We answered by email. If it did not solve things, say so below and it goes straight back to the team.',
      fix_pending: 'We found the cause and fixed it. We will email you the moment the update with the fix is on the App Store.',
      resolved: 'This request is solved. If the problem comes back, write below and we will pick it up again.',
      closed: 'This request is closed. If you still need help, write below and it reopens.',
    },
    stages: { received: 'Received', answered: 'Answered', fixing: 'Fix on its way', solved: 'Solved' },
    historyTitle: 'History',
    yourMessage: 'Your message',
    detailsTitle: 'Details you gave',
    detail: {
      level: 'Level',
      'purchase-item': 'Purchase',
      'purchase-date': 'Bought on',
      assistive: 'Assistive technology',
      tried: 'Already tried',
      guide: 'From the guide',
      device: 'Device',
      ios: 'iOS version',
      app: 'OutBrick version',
    },
    event: {
      created: 'You sent your message',
      reply: (staff) => `${staff} from the team replied`,
      fixedIn: (version) => `We fixed it in OutBrick ${version}`,
      fixedShipped: (version) => `OutBrick ${version}, with the fix, reached the App Store`,
      resolved: 'Marked as solved',
      closed: 'Closed',
      reopened: 'Reopened',
      solvedYes: 'You told us it is solved',
      solvedNo: 'You told us it is not solved yet',
      rated: (stars) => `You rated our help ${stars} out of 5`,
      playerNote: 'You added',
    },
    addTitle: 'Add details',
    addHint: 'A level number, what you tried, what changed. Please leave out passwords and card details. To send a screenshot, reply to our email with it attached.',
    addLabel: 'Your message',
    addAction: 'Send to the team',
    addSending: 'Sending…',
    added: 'Thank you. The team has your update.',
    addReopens: 'Sending this reopens your request.',
    feedbackTitle: 'Did we solve it?',
    feedbackText: 'One tap tells us. A “not yet” goes straight back to the team.',
    solvedYes: 'Yes, solved',
    solvedNo: 'Not yet',
    rateLabel: 'How was our help?',
    lookupTitle: 'Lost your link?',
    lookupText: 'Enter your reference and the email address you wrote from, and we will email you the link to your request.',
    refLabel: 'Reference',
    refHint: 'It looks like OB-7K2QXM and is in the subject of our emails.',
    emailLabel: 'Your email address',
    lookupAction: 'Email me the link',
    lookupSending: 'Sending…',
    lookupSent: 'If that reference and address match a request, its link is on its way to that address. Check your inbox and spam folder.',
    noLinkTitle: 'Follow a request',
    noLinkText: 'Every message you send us gets a reference, like OB-7K2QXM, and a private link in the email we send back. Open that link to see where your request stands, read every reply and add details.',
    tooMany: 'That is a lot of tries in a short time. Please wait a few minutes and try again.',
    newRequest: 'Write a new message',
  },

  feedback: {
    question: 'Was this guide helpful?',
    pageQuestion: 'Was this page helpful?',
    yes: 'Yes',
    no: 'No',
    thanksYes: 'Thank you! We are glad it helped.',
    whyTitle: 'Sorry about that. What went wrong?',
    reasons: {
      unclear: 'It was hard to follow',
      missing: 'My question was not answered',
      outdated: 'It does not match the game',
      'didnt-work': 'I followed it, but it did not work',
      other: 'Something else',
    },
    commentLabel: 'Tell us more (optional)',
    commentHint: 'We read every answer and use it to improve the guides. No reply comes back from here, so please leave out personal details.',
    send: 'Send',
    sending: 'Sending…',
    thanksNo: 'Thank you. We read every answer and use it to fix the guides.',
    escalate: 'Still need a hand? A person on the team will help.',
    contactAction: 'Contact support',
    askAction: 'Ask the community',
    failed: 'That did not send. Please try again.',
  },
};
