import type { SupportCopy } from '../model.ts';

export const en: SupportCopy = {
  supportCrumb: 'Support',
  hub: {
    title: 'Get help your way',
    lede: 'Fix it yourself in a few steps, check whether we already know about it, or follow a message you sent us.',
    fixTitle: 'Fix it step by step',
    fixText: 'Pick what is wrong and try one thing at a time. If nothing works, we take it from there.',
    issuesTitle: 'Known issues and fixes',
    issuesText: 'What we know is broken, what to do in the meantime, and which update fixes it.',
    trackTitle: 'Track your request',
    trackText: 'See where your message stands, read every reply from the team and add details.',
  },

  issues: {
    metaTitle: 'OutBrick known issues and fixes',
    metaDescription: 'The problems we know about in OutBrick on iPhone and iPad, what to do until they are fixed, and which update brings the fix.',
    eyebrow: 'OutBrick support',
    title: 'Known issues and fixes',
    lede: 'Something not working? Here is everything we know is broken right now, what you can do until it is fixed, and which update brings the fix. We keep this page honest and up to date.',
    reviewed: (date) => `Last reviewed ${date}`,
    openTitle: 'Being worked on',
    resolvedTitle: 'Recently fixed',
    noneOpen: 'Nothing is known to be broken right now. If something is not working for you, please tell us.',
    status: { investigating: 'Looking into it', 'fix-coming': 'Fix on its way', fixed: 'Fixed' },
    affects: 'Who it affects',
    whatHappens: 'What happens',
    workaround: 'Until it is fixed',
    fix: 'The fix',
    readMore: 'Read more',
    notListedTitle: 'Not on the list?',
    notListedText: 'Then we may not know about it yet. A report with your device, iOS version, OutBrick version and level helps us find it quickly.',
    reportAction: 'Report a bug',
    contactAction: 'Write to us privately',
    stayTitle: 'Hear when a fix ships',
    stayText: 'Every release is posted in Announcements the moment the App Store has it. Follow the category to get an email, and keep automatic updates on so fixes reach you without a thought.',
    stayAction: 'Follow Announcements',
  },

  fix: {
    metaTitle: 'Fix it step by step: OutBrick troubleshooter',
    metaDescription: 'Choose what is wrong in OutBrick and try one fix at a time: missing progress, purchases, lives, sound, notifications, widgets, videos and VoiceOver.',
    eyebrow: 'OutBrick support',
    title: 'Fix it step by step',
    lede: 'Choose what is wrong and we will walk you through one thing at a time. Most problems are solved in a minute or two, and if yours is not, a person on the team takes it from there.',
    chooseTitle: 'What is wrong?',
    chooseHint: 'Choose the closest match.',
    stepOf: (step, total) => `Step ${step} of ${total}`,
    quickCheck: 'Quick check',
    worked: 'That fixed it',
    next: 'Still not working',
    back: 'Back',
    another: 'Choose another problem',
    fixedTitle: 'Glad that sorted it.',
    fixedText: 'Thank you for trying the steps. Enjoy your next board.',
    stillTitle: 'Still not working? We will take it from here.',
    stillText: 'Write to us and a person on the team will look into it. Your message says what you have already tried, so nobody asks you to do it again.',
    contactAction: 'Contact support',
    askAction: 'Ask the community',
    bugAction: 'Report a bug',
    knownIssue: 'This is a known issue, and a fix is on its way.',
    allSteps: 'All the steps',
    readGuide: 'Read the full guide',
  },

  request: {
    metaTitle: 'Your OutBrick support request',
    metaDescription: 'Follow your OutBrick support request: where it stands, every reply from the team, and a way to add details.',
    eyebrow: 'OutBrick support',
    title: 'Your request',
    lede: 'Where your message stands, every reply from the team, and a place to add anything we should know.',
    loading: 'Opening your request…',
    invalid: 'This link does not open a request. Check that you copied all of it, or ask for a new link below.',
    expired: 'This link has expired. Ask for a new one below and it will arrive in a minute.',
    failed: 'We could not open your request just now. Please try again in a moment.',
    reference: 'Reference',
    topic: 'Topic',
    opened: 'Sent',
    updated: 'Last update',
    statusTitle: {
      open: 'With the team',
      replied: 'We replied',
      fix_pending: 'A fix is on its way',
      resolved: 'Solved',
      closed: 'Closed',
    },
    statusText: {
      open: 'A person on the team has your message and will reply by email. You can add details below at any time.',
      replied: 'We answered by email. If it did not solve things, say so below and it goes straight back to the team.',
      fix_pending: 'We found the cause and fixed it. We will email you the moment the update with the fix is on the App Store.',
      resolved: 'This request is solved. If the problem comes back, write below and we will pick it up again.',
      closed: 'This request is closed. If you still need help, write below and it reopens.',
    },
    stages: { received: 'Received', answered: 'Answered', fixing: 'Fix on its way', solved: 'Solved' },
    historyTitle: 'History',
    yourMessage: 'Your message',
    detailsTitle: 'Details you gave',
    detail: {
      level: 'Level',
      'purchase-item': 'Purchase',
      'purchase-date': 'Bought on',
      assistive: 'Assistive technology',
      tried: 'Already tried',
      guide: 'From the guide',
      device: 'Device',
      ios: 'iOS version',
      app: 'OutBrick version',
    },
    event: {
      created: 'You sent your message',
      reply: (staff) => `${staff} from the team replied`,
      fixedIn: (version) => `We fixed it in OutBrick ${version}`,
      fixedShipped: (version) => `OutBrick ${version}, with the fix, reached the App Store`,
      resolved: 'Marked as solved',
      closed: 'Closed',
      reopened: 'Reopened',
      solvedYes: 'You told us it is solved',
      solvedNo: 'You told us it is not solved yet',
      rated: (stars) => `You rated our help ${stars} out of 5`,
      playerNote: 'You added',
    },
    addTitle: 'Add details',
    addHint: 'A level number, what you tried, what changed. Please leave out passwords and card details. To send a screenshot, reply to our email with it attached.',
    addLabel: 'Your message',
    addAction: 'Send to the team',
    addSending: 'Sending…',
    added: 'Thank you. The team has your update.',
    addReopens: 'Sending this reopens your request.',
    feedbackTitle: 'Did we solve it?',
    feedbackText: 'One tap tells us. A “not yet” goes straight back to the team.',
    solvedYes: 'Yes, solved',
    solvedNo: 'Not yet',
    rateLabel: 'How was our help?',
    lookupTitle: 'Lost your link?',
    lookupText: 'Enter your reference and the email address you wrote from, and we will email you the link to your request.',
    refLabel: 'Reference',
    refHint: 'It looks like OB-7K2QXM and is in the subject of our emails.',
    emailLabel: 'Your email address',
    lookupAction: 'Email me the link',
    lookupSending: 'Sending…',
    lookupSent: 'If that reference and address match a request, its link is on its way to that address. Check your inbox and spam folder.',
    noLinkTitle: 'Follow a request',
    noLinkText: 'Every message you send us gets a reference, like OB-7K2QXM, and a private link in the email we send back. Open that link to see where your request stands, read every reply and add details.',
    tooMany: 'That is a lot of tries in a short time. Please wait a few minutes and try again.',
    newRequest: 'Write a new message',
  },

  feedback: {
    question: 'Was this guide helpful?',
    pageQuestion: 'Was this page helpful?',
    yes: 'Yes',
    no: 'No',
    thanksYes: 'Thank you! We are glad it helped.',
    whyTitle: 'Sorry about that. What went wrong?',
    reasons: {
      unclear: 'It was hard to follow',
      missing: 'My question was not answered',
      outdated: 'It does not match the game',
      'didnt-work': 'I followed it, but it did not work',
      other: 'Something else',
    },
    commentLabel: 'Tell us more (optional)',
    commentHint: 'We read every answer and use it to improve the guides. No reply comes back from here, so please leave out personal details.',
    send: 'Send',
    sending: 'Sending…',
    thanksNo: 'Thank you. We read every answer and use it to fix the guides.',
    escalate: 'Still need a hand? A person on the team will help.',
    contactAction: 'Contact support',
    askAction: 'Ask the community',
    failed: 'That did not send. Please try again.',
  },
};
