import type { SupportCopy } from '../model.ts';

export const es: SupportCopy = {
  supportCrumb: 'Soporte',
  hub: {
    title: 'La ayuda que prefieras',
    lede: 'Arréglalo tú mismo en unos pocos pasos, mira si ya lo conocemos o sigue un mensaje que nos enviaste.',
    fixTitle: 'Soluciónalo paso a paso',
    fixText: 'Elige qué falla y prueba una cosa cada vez. Si nada funciona, nos encargamos nosotros.',
    issuesTitle: 'Problemas conocidos y soluciones',
    issuesText: 'Lo que sabemos que falla, qué hacer mientras tanto y qué actualización lo corrige.',
    trackTitle: 'Sigue tu solicitud',
    trackText: 'Mira en qué punto está tu mensaje, lee cada respuesta del equipo y añade detalles.',
  },

  issues: {
    metaTitle: 'OutBrick: problemas conocidos y soluciones',
    metaDescription: 'Los problemas que conocemos en OutBrick para iPhone y iPad, qué hacer hasta que se corrijan y qué actualización trae la corrección.',
    eyebrow: 'Soporte de OutBrick',
    title: 'Problemas conocidos y soluciones',
    lede: '¿Algo no funciona? Aquí está todo lo que sabemos que falla ahora mismo, lo que puedes hacer hasta que se corrija y qué actualización trae la corrección. Mantenemos esta página honesta y al día.',
    reviewed: (date) => `Última revisión: ${date}`,
    openTitle: 'En ello',
    resolvedTitle: 'Corregido hace poco',
    noneOpen: 'Ahora mismo no sabemos de nada que falle. Si algo no te funciona, cuéntanoslo.',
    status: { investigating: 'Lo estamos investigando', 'fix-coming': 'Corrección en camino', fixed: 'Corregido' },
    affects: 'A quién afecta',
    whatHappens: 'Qué pasa',
    workaround: 'Hasta que se corrija',
    fix: 'La corrección',
    readMore: 'Más información',
    notListedTitle: '¿No está en la lista?',
    notListedText: 'Entonces puede que aún no lo conozcamos. Un informe con tu dispositivo, la versión de iOS, la versión de OutBrick y el nivel nos ayuda a encontrarlo rápido.',
    reportAction: 'Informar de un error',
    contactAction: 'Escríbenos en privado',
    stayTitle: 'Entérate cuando salga una corrección',
    stayText: 'Cada versión se publica en Anuncios en cuanto llega al App Store. Sigue la categoría para recibir un correo, y mantén activadas las actualizaciones automáticas para que las correcciones te lleguen sin pensarlo.',
    stayAction: 'Seguir Anuncios',
  },

  fix: {
    metaTitle: 'Soluciónalo paso a paso: asistente de OutBrick',
    metaDescription: 'Elige qué falla en OutBrick y prueba una solución cada vez: progreso que falta, compras, vidas, sonido, notificaciones, widgets, vídeos y VoiceOver.',
    eyebrow: 'Soporte de OutBrick',
    title: 'Soluciónalo paso a paso',
    lede: 'Elige qué falla y te guiamos de una cosa en una. La mayoría de los problemas se arreglan en un minuto o dos, y si el tuyo no, una persona del equipo se encarga.',
    chooseTitle: '¿Qué falla?',
    chooseHint: 'Elige lo que más se parezca.',
    stepOf: (step, total) => `Paso ${step} de ${total}`,
    quickCheck: 'Comprobación rápida',
    worked: 'Ya está arreglado',
    next: 'Sigue sin funcionar',
    back: 'Atrás',
    another: 'Elegir otro problema',
    fixedTitle: 'Nos alegra que se haya arreglado.',
    fixedText: 'Gracias por probar los pasos. ¡Disfruta de tu próximo tablero!',
    stillTitle: '¿Sigue sin funcionar? Nos encargamos nosotros.',
    stillText: 'Escríbenos y una persona del equipo lo revisará. Tu mensaje indica lo que ya has probado, así que nadie te pedirá que lo repitas.',
    contactAction: 'Contactar con soporte',
    askAction: 'Preguntar a la comunidad',
    bugAction: 'Informar de un error',
    knownIssue: 'Es un problema conocido y hay una corrección en camino.',
    allSteps: 'Todos los pasos',
    readGuide: 'Leer la guía completa',
  },

  request: {
    metaTitle: 'Tu solicitud de soporte de OutBrick',
    metaDescription: 'Sigue tu solicitud de soporte de OutBrick: en qué punto está, cada respuesta del equipo y una forma de añadir detalles.',
    eyebrow: 'Soporte de OutBrick',
    title: 'Tu solicitud',
    lede: 'En qué punto está tu mensaje, cada respuesta del equipo y un lugar para añadir todo lo que debamos saber.',
    loading: 'Abriendo tu solicitud…',
    invalid: 'Este enlace no abre ninguna solicitud. Comprueba que lo copiaste entero o pide un enlace nuevo abajo.',
    expired: 'Este enlace ha caducado. Pide uno nuevo abajo y te llegará en un minuto.',
    failed: 'No hemos podido abrir tu solicitud ahora mismo. Vuelve a intentarlo en un momento.',
    reference: 'Referencia',
    topic: 'Tema',
    opened: 'Enviada',
    updated: 'Última actualización',
    statusTitle: {
      open: 'En manos del equipo',
      replied: 'Te hemos respondido',
      fix_pending: 'Hay una corrección en camino',
      resolved: 'Resuelta',
      closed: 'Cerrada',
    },
    statusText: {
      open: 'Una persona del equipo tiene tu mensaje y te responderá por correo. Puedes añadir detalles abajo cuando quieras.',
      replied: 'Te hemos respondido por correo. Si no se ha solucionado, dilo abajo y vuelve directamente al equipo.',
      fix_pending: 'Hemos encontrado la causa y la hemos corregido. Te escribiremos en cuanto la actualización con la corrección esté en el App Store.',
      resolved: 'Esta solicitud está resuelta. Si el problema vuelve, escribe abajo y la retomaremos.',
      closed: 'Esta solicitud está cerrada. Si aún necesitas ayuda, escribe abajo y se volverá a abrir.',
    },
    stages: { received: 'Recibida', answered: 'Respondida', fixing: 'Corrección en camino', solved: 'Resuelta' },
    historyTitle: 'Historial',
    yourMessage: 'Tu mensaje',
    detailsTitle: 'Los detalles que nos diste',
    detail: {
      level: 'Nivel',
      'purchase-item': 'Compra',
      'purchase-date': 'Fecha de compra',
      assistive: 'Tecnología de asistencia',
      tried: 'Ya probado',
      guide: 'Desde la guía',
      device: 'Dispositivo',
      ios: 'Versión de iOS',
      app: 'Versión de OutBrick',
    },
    event: {
      created: 'Has enviado tu mensaje',
      reply: (staff) => `${staff}, del equipo, ha respondido`,
      fixedIn: (version) => `Lo hemos corregido en OutBrick ${version}`,
      fixedShipped: (version) => `OutBrick ${version}, con la corrección, ha llegado al App Store`,
      resolved: 'Marcada como resuelta',
      closed: 'Cerrada',
      reopened: 'Reabierta',
      solvedYes: 'Nos has dicho que está resuelto',
      solvedNo: 'Nos has dicho que aún no está resuelto',
      rated: (stars) => `Has valorado nuestra ayuda con ${stars} ${stars === 1 ? 'estrella' : 'estrellas'} de 5`,
      playerNote: 'Has añadido',
    },
    addTitle: 'Añadir detalles',
    addHint: 'Un número de nivel, lo que has probado, lo que ha cambiado. No incluyas contraseñas ni datos de tarjetas. Para enviar una captura, responde a nuestro correo con la imagen adjunta.',
    addLabel: 'Tu mensaje',
    addAction: 'Enviar al equipo',
    addSending: 'Enviando…',
    added: 'Gracias. El equipo ya tiene tu actualización.',
    addReopens: 'Al enviar esto, tu solicitud se vuelve a abrir.',
    feedbackTitle: '¿Lo hemos solucionado?',
    feedbackText: 'Con un toque nos lo dices. Un «aún no» vuelve directamente al equipo.',
    solvedYes: 'Sí, solucionado',
    solvedNo: 'Aún no',
    rateLabel: '¿Qué te ha parecido nuestra ayuda?',
    lookupTitle: '¿Has perdido tu enlace?',
    lookupText: 'Introduce tu referencia y la dirección de correo desde la que nos escribiste, y te enviaremos por correo el enlace a tu solicitud.',
    refLabel: 'Referencia',
    refHint: 'Es parecida a OB-7K2QXM y aparece en el asunto de nuestros correos.',
    emailLabel: 'Tu dirección de correo',
    lookupAction: 'Enviarme el enlace por correo',
    lookupSending: 'Enviando…',
    lookupSent: 'Si esa referencia y esa dirección coinciden con una solicitud, su enlace va de camino a esa dirección. Revisa tu bandeja de entrada y la carpeta de spam.',
    noLinkTitle: 'Seguir una solicitud',
    noLinkText: 'Cada mensaje que nos envías recibe una referencia, como OB-7K2QXM, y un enlace privado en el correo con el que te respondemos. Abre ese enlace para ver en qué punto está tu solicitud, leer cada respuesta y añadir detalles.',
    tooMany: 'Son muchos intentos en poco tiempo. Espera unos minutos y vuelve a intentarlo.',
    newRequest: 'Escribir un mensaje nuevo',
  },

  feedback: {
    question: '¿Te ha servido esta guía?',
    pageQuestion: '¿Te ha servido esta página?',
    yes: 'Sí',
    no: 'No',
    thanksYes: '¡Gracias! Nos alegra que te haya servido.',
    whyTitle: 'Lo sentimos. ¿Qué ha fallado?',
    reasons: {
      unclear: 'Era difícil de seguir',
      missing: 'No respondía a mi pregunta',
      outdated: 'No coincide con el juego',
      'didnt-work': 'La seguí, pero no funcionó',
      other: 'Otra cosa',
    },
    commentLabel: 'Cuéntanos más (opcional)',
    commentHint: 'Leemos cada respuesta y la usamos para mejorar las guías. Desde aquí no recibirás respuesta, así que no incluyas datos personales.',
    send: 'Enviar',
    sending: 'Enviando…',
    thanksNo: 'Gracias. Leemos cada respuesta y la usamos para corregir las guías.',
    escalate: '¿Aún necesitas ayuda? Una persona del equipo te echará una mano.',
    contactAction: 'Contactar con soporte',
    askAction: 'Preguntar a la comunidad',
    failed: 'No se ha podido enviar. Vuelve a intentarlo.',
  },
};
