import type { SupportCopy } from '../model.ts';

export const es: SupportCopy = {
  supportCrumb: 'Soporte',
  hub: {
    title: 'La ayuda que prefieras',
    lede: 'Arréglalo tú mismo en unos pocos pasos, mira si ya lo conocemos o sigue un mensaje que nos enviaste.',
    fixTitle: 'Soluciónalo paso a paso',
    fixText: 'Elige qué falla y prueba una cosa cada vez. Si nada funciona, nos encargamos nosotros.',
    issuesTitle: 'Problemas conocidos y soluciones',
    issuesText: 'Lo que sabemos que falla, qué hacer mientras tanto y qué actualización lo corrige.',
    trackTitle: 'Sigue tu solicitud',
    trackText: 'Mira en qué punto está tu mensaje, lee cada respuesta del equipo y añade detalles.',
    levelsTitle: 'Ayuda con un nivel',
    levelsText: '¿Te has atascado en un tablero? Mira lo que han dicho otros jugadores o pregúntales.',
    involvedTitle: 'Ayuda a dar forma a OutBrick',
    involvedText: 'Prueba las actualizaciones antes de que salgan, únete al panel de accesibilidad y recibe noticias del equipo cada mes.',
    promise: 'Una persona del equipo lee cada mensaje. Intentamos responder en dos días laborables.',
  },

  levels: {
    metaTitle: 'Ayuda con un nivel de OutBrick',
    metaDescription: '¿Te has atascado en un nivel de OutBrick? Descubre qué han dicho otros jugadores de ese tablero, pregunta a la comunidad y consigue consejos para los tableros difíciles.',
    eyebrow: 'Soporte de OutBrick',
    title: 'Ayuda con un nivel',
    lede: 'Escribe el número del nivel en el que te has atascado para ver lo que otros jugadores han dicho de ese tablero, o pregúntales. El número aparece en la parte superior del tablero.',
    label: 'Número de nivel',
    hint: 'Del 1 al 2.000, y más allá.',
    action: 'Buscar ayuda',
    invalid: 'Escribe un número de nivel, como 512.',
    resultsTitle: (level) => `El nivel ${level} en la comunidad`,
    none: (level) => `Nadie ha preguntado todavía por el nivel ${level}. Sé el primero: a los jugadores les encanta un buen rompecabezas.`,
    loading: 'Buscando temas…',
    failed: 'No hemos podido cargar la comunidad ahora mismo. Vuelve a intentarlo en un momento.',
    solved: 'Resuelto',
    replies: (n) => (n === 1 ? '1 respuesta' : `${n} respuestas`),
    askTitle: 'Pregunta por este nivel',
    askText: 'Describe lo que has probado y dónde te atascas. Otros jugadores y el equipo responden en abierto.',
    askAction: 'Preguntar a la comunidad',
    askThreadTitle: (level) => `Nivel ${level}: `,
    bugAction: 'Informar de un problema con este nivel',
    tipsTitle: 'Antes de preguntar: consejos para tableros difíciles',
    tips: [
      'Cada intento incluye una **Pista**, un **Cohete** y un **OVNI** gratis: usa primero la Pista, que te muestra un movimiento que ayuda.',
      'Lee los objetivos antes de tu primer movimiento: un tablero termina en cuanto se cumplen sus objetivos, y los movimientos que te quedan se convierten en blasters.',
      'El primer **deshacer** de cada tablero es gratis. Úsalo para probar otro cambio.',
      'A partir de tu sexto intento en un tablero, una **ayudita** te da tres movimientos extra, una vez al día.',
      'Si no hay ningún movimiento posible, el tablero se mezcla gratis, así que nunca te quedarás atascado del todo. Más información en [Vidas, movimientos y deshacer](help:lives-moves-and-undos).',
    ],
    spoilersTitle: 'Sobre los spoilers',
    spoilersText: 'A muchos jugadores les gusta resolver un tablero por su cuenta. Cuando respondas, empieza con un empujoncito y da la solución completa solo si alguien te la pide.',
  },

  involved: {
    metaTitle: 'Da forma a OutBrick: pruebas beta y panel de accesibilidad',
    metaDescription: 'Prueba las actualizaciones de OutBrick con TestFlight antes de que salgan, únete al panel de accesibilidad de jugadores de VoiceOver, Control por voz y Control por botón, y recibe noticias del equipo cada mes.',
    eyebrow: 'Comunidad de OutBrick',
    title: 'Ayuda a dar forma a OutBrick',
    lede: 'OutBrick mejora porque los jugadores nos cuentan qué funciona y qué no. Aquí tienes tres formas de participar.',
    beta: {
      title: 'Prueba las actualizaciones antes de que salgan',
      text: 'Únete al grupo beta y juega a las nuevas versiones de OutBrick con la app TestFlight de Apple, unos días antes que nadie.',
      points: [
        'Invitamos a los probadores en grupos pequeños antes de cada actualización; la invitación te llega por correo desde TestFlight.',
        'Necesitas un iPhone o iPad con una versión reciente de iOS y la app gratuita TestFlight.',
        'Cuéntanos qué falla o qué no te parece bien desde TestFlight o en la comunidad.',
        'Puedes dejar la beta cuando quieras, y tu progreso sigue siendo tuyo.',
      ],
      action: 'Unirme al grupo beta',
    },
    panel: {
      title: 'Únete al panel de accesibilidad',
      text: 'Si juegas con VoiceOver, Control por voz, Control por botón, un teclado, Texto más grande o Zoom, tu experiencia da forma a cada tablero que creamos.',
      points: [
        'Consultamos al panel sobre los nuevos tableros y funciones antes de que salgan, y actuamos según lo que nos dice.',
        'Unas pocas preguntas breves o una versión de prueba de vez en cuando, nunca más de lo que quieras.',
        'Dinos qué tecnología de asistencia usas y cómo prefieres que contactemos contigo.',
      ],
      action: 'Unirme al panel',
    },
    monthly: {
      title: 'Noticias del equipo, cada mes',
      text: 'Una vez al mes publicamos en Anuncios lo que ha salido, lo que nos has contado y lo que viene después. Sigue la categoría para recibirlo por correo o suscríbete a las noticias de OutBrick.',
      followAction: 'Seguir Anuncios',
      newsAction: 'Suscribirme a las noticias de OutBrick',
    },
    honest: 'Participar es voluntario y no remunerado, y nunca cambia nada de tu juego. Puedes dejarlo cuando quieras respondiendo a cualquiera de nuestros correos.',
  },

  banner: {
    level: { info: 'Aviso', warning: 'Atención', outage: 'Incidencia en el servicio' },
    more: 'Más información',
    dismiss: 'Cerrar este aviso',
  },

  attach: {
    label: 'Capturas de pantalla',
    hint: 'Hasta tres imágenes. Eliminamos los datos de ubicación y de la cámara antes de guardarlas, y solo tú y el equipo podéis verlas.',
    add: 'Añadir una captura',
    remove: 'Quitar',
    uploading: 'Subiendo…',
    failed: 'No se ha podido adjuntar esa imagen. Prueba con un PNG o un JPEG.',
    tooBig: 'Esa imagen ocupa más de 8 MB.',
    tooMany: 'Puedes adjuntar hasta tres imágenes.',
    alt: (n) => `Captura de pantalla ${n}`,
    title: 'Capturas de pantalla',
  },

  issues: {
    metaTitle: 'OutBrick: problemas conocidos y soluciones',
    metaDescription: 'Los problemas que conocemos en OutBrick para iPhone y iPad, qué hacer hasta que se corrijan y qué actualización trae la corrección.',
    eyebrow: 'Soporte de OutBrick',
    title: 'Problemas conocidos y soluciones',
    lede: '¿Algo no funciona? Aquí está todo lo que sabemos que falla ahora mismo, lo que puedes hacer hasta que se corrija y qué actualización trae la corrección. Mantenemos esta página honesta y al día.',
    reviewed: (date) => `Última revisión: ${date}`,
    openTitle: 'En ello',
    resolvedTitle: 'Corregido hace poco',
    noneOpen: 'Ahora mismo no sabemos de nada que falle. Si algo no te funciona, cuéntanoslo.',
    status: { investigating: 'Lo estamos investigando', 'fix-coming': 'Corrección en camino', fixed: 'Corregido' },
    affects: 'A quién afecta',
    whatHappens: 'Qué pasa',
    workaround: 'Hasta que se corrija',
    fix: 'La corrección',
    readMore: 'Más información',
    notListedTitle: '¿No está en la lista?',
    notListedText: 'Entonces puede que aún no lo conozcamos. Un informe con tu dispositivo, la versión de iOS, la versión de OutBrick y el nivel nos ayuda a encontrarlo rápido.',
    reportAction: 'Informar de un error',
    contactAction: 'Escríbenos en privado',
    stayTitle: 'Entérate cuando salga una corrección',
    stayText: 'Cada versión se publica en Anuncios en cuanto llega al App Store. Sigue la categoría para recibir un correo, y mantén activadas las actualizaciones automáticas para que las correcciones te lleguen sin pensarlo.',
    stayAction: 'Seguir Anuncios',
  },

  fix: {
    metaTitle: 'Soluciónalo paso a paso: asistente de OutBrick',
    metaDescription: 'Elige qué falla en OutBrick y prueba una solución cada vez: progreso que falta, compras, vidas, sonido, notificaciones, widgets, vídeos y VoiceOver.',
    eyebrow: 'Soporte de OutBrick',
    title: 'Soluciónalo paso a paso',
    lede: 'Elige qué falla y te guiamos de una cosa en una. La mayoría de los problemas se arreglan en un minuto o dos, y si el tuyo no, una persona del equipo se encarga.',
    chooseTitle: '¿Qué falla?',
    chooseHint: 'Elige lo que más se parezca.',
    stepOf: (step, total) => `Paso ${step} de ${total}`,
    quickCheck: 'Comprobación rápida',
    worked: 'Ya está arreglado',
    next: 'Sigue sin funcionar',
    back: 'Atrás',
    another: 'Elegir otro problema',
    fixedTitle: 'Nos alegra que se haya arreglado.',
    fixedText: 'Gracias por probar los pasos. ¡Disfruta de tu próximo tablero!',
    stillTitle: '¿Sigue sin funcionar? Nos encargamos nosotros.',
    stillText: 'Escríbenos y una persona del equipo lo revisará. Tu mensaje indica lo que ya has probado, así que nadie te pedirá que lo repitas.',
    contactAction: 'Contactar con soporte',
    askAction: 'Preguntar a la comunidad',
    bugAction: 'Informar de un error',
    knownIssue: 'Es un problema conocido y hay una corrección en camino.',
    allSteps: 'Todos los pasos',
    readGuide: 'Leer la guía completa',
  },

  request: {
    metaTitle: 'Tu solicitud de soporte de OutBrick',
    metaDescription: 'Sigue tu solicitud de soporte de OutBrick: en qué punto está, cada respuesta del equipo y una forma de añadir detalles.',
    eyebrow: 'Soporte de OutBrick',
    title: 'Tu solicitud',
    lede: 'En qué punto está tu mensaje, cada respuesta del equipo y un lugar para añadir todo lo que debamos saber.',
    loading: 'Abriendo tu solicitud…',
    invalid: 'Este enlace no abre ninguna solicitud. Comprueba que lo copiaste entero o pide un enlace nuevo abajo.',
    expired: 'Este enlace ha caducado. Pide uno nuevo abajo y te llegará en un minuto.',
    failed: 'No hemos podido abrir tu solicitud ahora mismo. Vuelve a intentarlo en un momento.',
    reference: 'Referencia',
    topic: 'Tema',
    opened: 'Enviada',
    updated: 'Última actualización',
    statusTitle: {
      open: 'En manos del equipo',
      replied: 'Te hemos respondido',
      fix_pending: 'Hay una corrección en camino',
      resolved: 'Resuelta',
      closed: 'Cerrada',
    },
    statusText: {
      open: 'Una persona del equipo tiene tu mensaje y te responderá por correo. Puedes añadir detalles abajo cuando quieras.',
      replied: 'Te hemos respondido por correo. Si no se ha solucionado, dilo abajo y vuelve directamente al equipo.',
      fix_pending: 'Hemos encontrado la causa y la hemos corregido. Te escribiremos en cuanto la actualización con la corrección esté en el App Store.',
      resolved: 'Esta solicitud está resuelta. Si el problema vuelve, escribe abajo y la retomaremos.',
      closed: 'Esta solicitud está cerrada. Si aún necesitas ayuda, escribe abajo y se volverá a abrir.',
    },
    stages: { received: 'Recibida', answered: 'Respondida', fixing: 'Corrección en camino', solved: 'Resuelta' },
    historyTitle: 'Historial',
    yourMessage: 'Tu mensaje',
    detailsTitle: 'Los detalles que nos diste',
    detail: {
      level: 'Nivel',
      'purchase-item': 'Compra',
      'purchase-date': 'Fecha de compra',
      assistive: 'Tecnología de asistencia',
      tried: 'Ya probado',
      guide: 'Desde la guía',
      device: 'Dispositivo',
      ios: 'Versión de iOS',
      app: 'Versión de OutBrick',
    },
    event: {
      created: 'Has enviado tu mensaje',
      reply: (staff) => `${staff}, del equipo, ha respondido`,
      fixedIn: (version) => `Lo hemos corregido en OutBrick ${version}`,
      fixedShipped: (version) => `OutBrick ${version}, con la corrección, ha llegado al App Store`,
      resolved: 'Marcada como resuelta',
      closed: 'Cerrada',
      reopened: 'Reabierta',
      solvedYes: 'Nos has dicho que está resuelto',
      solvedNo: 'Nos has dicho que aún no está resuelto',
      rated: (stars) => `Has valorado nuestra ayuda con ${stars} ${stars === 1 ? 'estrella' : 'estrellas'} de 5`,
      playerNote: 'Has añadido',
    },
    addTitle: 'Añadir detalles',
    addHint: 'Un número de nivel, lo que has probado, lo que ha cambiado. No incluyas contraseñas ni datos de tarjetas.',
    addLabel: 'Tu mensaje',
    addAction: 'Enviar al equipo',
    addSending: 'Enviando…',
    added: 'Gracias. El equipo ya tiene tu actualización.',
    addReopens: 'Al enviar esto, tu solicitud se vuelve a abrir.',
    feedbackTitle: '¿Lo hemos solucionado?',
    feedbackText: 'Con un toque nos lo dices. Un «aún no» vuelve directamente al equipo.',
    solvedYes: 'Sí, solucionado',
    solvedNo: 'Aún no',
    rateLabel: '¿Qué te ha parecido nuestra ayuda?',
    lookupTitle: '¿Has perdido tu enlace?',
    lookupText: 'Introduce tu referencia y la dirección de correo desde la que nos escribiste, y te enviaremos por correo el enlace a tu solicitud.',
    refLabel: 'Referencia',
    refHint: 'Es parecida a OB-7K2QXM y aparece en el asunto de nuestros correos.',
    emailLabel: 'Tu dirección de correo',
    lookupAction: 'Enviarme el enlace por correo',
    lookupSending: 'Enviando…',
    lookupSent: 'Si esa referencia y esa dirección coinciden con una solicitud, su enlace va de camino a esa dirección. Revisa tu bandeja de entrada y la carpeta de spam.',
    noLinkTitle: 'Seguir una solicitud',
    noLinkText: 'Cada mensaje que nos envías recibe una referencia, como OB-7K2QXM, y un enlace privado en el correo con el que te respondemos. Abre ese enlace para ver en qué punto está tu solicitud, leer cada respuesta y añadir detalles.',
    tooMany: 'Son muchos intentos en poco tiempo. Espera unos minutos y vuelve a intentarlo.',
    newRequest: 'Escribir un mensaje nuevo',
  },

  feedback: {
    question: '¿Te ha servido esta guía?',
    pageQuestion: '¿Te ha servido esta página?',
    yes: 'Sí',
    no: 'No',
    thanksYes: '¡Gracias! Nos alegra que te haya servido.',
    whyTitle: 'Lo sentimos. ¿Qué ha fallado?',
    reasons: {
      unclear: 'Era difícil de seguir',
      missing: 'No respondía a mi pregunta',
      outdated: 'No coincide con el juego',
      'didnt-work': 'La seguí, pero no funcionó',
      other: 'Otra cosa',
    },
    commentLabel: 'Cuéntanos más (opcional)',
    commentHint: 'Leemos cada respuesta y la usamos para mejorar las guías. Desde aquí no recibirás respuesta, así que no incluyas datos personales.',
    send: 'Enviar',
    sending: 'Enviando…',
    thanksNo: 'Gracias. Leemos cada respuesta y la usamos para corregir las guías.',
    escalate: '¿Aún necesitas ayuda? Una persona del equipo te echará una mano.',
    contactAction: 'Contactar con soporte',
    askAction: 'Preguntar a la comunidad',
    failed: 'No se ha podido enviar. Vuelve a intentarlo.',
  },
};
