import type { SupportCopy } from '../model.ts';

export const fr: SupportCopy = {
  supportCrumb: 'Assistance',
  hub: {
    title: 'L’aide qui vous convient',
    lede: 'Réglez le problème vous-même en quelques étapes, vérifiez si nous le connaissons déjà, ou suivez un message que vous nous avez envoyé.',
    fixTitle: 'Dépanner pas à pas',
    fixText: 'Choisissez ce qui ne va pas et essayez une chose à la fois. Si rien ne marche, nous prenons le relais.',
    issuesTitle: 'Problèmes connus et correctifs',
    issuesText: 'Ce que nous savons cassé, quoi faire en attendant, et quelle mise à jour le corrige.',
    trackTitle: 'Suivre votre demande',
    trackText: 'Voyez où en est votre message, lisez chaque réponse de l’équipe et ajoutez des détails.',
    levelsTitle: 'Aide pour un niveau',
    levelsText: 'Bloqué sur un plateau ? Voyez ce que les autres joueurs en ont dit, ou posez-leur la question.',
    involvedTitle: 'Contribuez à OutBrick',
    involvedText: 'Testez les mises à jour avant leur sortie, rejoignez le panel accessibilité et recevez des nouvelles de l’équipe chaque mois.',
    promise: 'Une personne de l’équipe lit chaque message. Nous nous efforçons de répondre sous deux jours ouvrés.',
  },

  levels: {
    metaTitle: 'Aide pour un niveau d’OutBrick',
    metaDescription: 'Bloqué sur un niveau d’OutBrick ? Découvrez ce que les autres joueurs ont dit de ce plateau, posez la question à la communauté et suivez nos astuces pour les plateaux difficiles.',
    eyebrow: 'Assistance OutBrick',
    title: 'Aide pour un niveau',
    lede: 'Saisissez le numéro du niveau sur lequel vous bloquez pour voir ce que les autres joueurs ont dit de ce plateau, ou posez-leur la question. Le numéro figure en haut du plateau.',
    label: 'Numéro du niveau',
    hint: 'De 1 à 2 000, et au-delà.',
    action: 'Trouver de l’aide',
    invalid: 'Saisissez un numéro de niveau, par exemple 512.',
    resultsTitle: (level) => `Le niveau ${level} dans la communauté`,
    none: (level) => `Personne n’a encore posé de question sur le niveau ${level}. Soyez le premier : les joueurs adorent les casse-tête.`,
    loading: 'Recherche des discussions…',
    failed: 'Impossible de charger la communauté pour le moment. Réessayez dans un instant.',
    solved: 'Résolue',
    replies: (n) => (n <= 1 ? `${n} réponse` : `${n} réponses`),
    askTitle: 'Poser une question sur ce niveau',
    askText: 'Décrivez ce que vous avez essayé et où vous bloquez. Les autres joueurs et l’équipe répondent publiquement.',
    askAction: 'Demander à la communauté',
    askThreadTitle: (level) => `Niveau ${level} : `,
    bugAction: 'Signaler un problème sur ce niveau',
    tipsTitle: 'Avant de demander : astuces pour les plateaux difficiles',
    tips: [
      'Chaque essai vous offre un **Indice**, une **Fusée** et un **OVNI** gratuits : commencez par l’Indice, il montre un coup qui vous aide.',
      'Lisez les objectifs avant votre premier coup : un plateau se termine dès que ses objectifs sont atteints, et les coups qui vous restent deviennent des blasters.',
      'La première **annulation** de chaque plateau est gratuite. Servez-vous-en pour tenter un autre échange.',
      'À partir de votre sixième essai sur un plateau, un **coup de main** ajoute trois coups, une fois par jour.',
      'Si aucun coup n’est possible, le plateau est mélangé gratuitement : vous ne pouvez donc jamais être vraiment bloqué. Plus de détails dans [Vies, coups et annulations](help:lives-moves-and-undos).',
    ],
    spoilersTitle: 'Un mot sur les spoilers',
    spoilersText: 'Beaucoup de joueurs aiment trouver la solution d’un plateau par eux-mêmes. Quand vous répondez, commencez par une piste, et ne donnez la solution complète que si on vous la demande.',
  },

  involved: {
    metaTitle: 'Contribuez à OutBrick : tests bêta et panel accessibilité',
    metaDescription: 'Testez les mises à jour d’OutBrick avant leur sortie avec TestFlight, rejoignez le panel accessibilité des joueurs qui utilisent VoiceOver, Contrôle vocal et Contrôle de sélection, et recevez des nouvelles de l’équipe chaque mois.',
    eyebrow: 'Communauté OutBrick',
    title: 'Contribuez à OutBrick',
    lede: 'OutBrick s’améliore parce que les joueurs nous disent ce qui marche et ce qui ne marche pas. Voici trois façons d’y prendre part.',
    beta: {
      title: 'Testez les mises à jour avant leur sortie',
      text: 'Rejoignez le groupe bêta et jouez aux nouvelles versions d’OutBrick avec l’app TestFlight d’Apple, quelques jours avant tout le monde.',
      points: [
        'Nous invitons les testeurs par petits groupes avant chaque mise à jour ; l’invitation vous arrive par e-mail de la part de TestFlight.',
        'Il vous faut un iPhone ou un iPad avec une version récente d’iOS, et l’app gratuite TestFlight.',
        'Dites-nous ce qui ne marche pas ou vous paraît bizarre, depuis TestFlight ou dans la communauté.',
        'Vous pouvez quitter la bêta à tout moment, et votre progression reste la vôtre.',
      ],
      action: 'Rejoindre le groupe bêta',
    },
    panel: {
      title: 'Rejoignez le panel accessibilité',
      text: 'Si vous jouez avec VoiceOver, Contrôle vocal, Contrôle de sélection, un clavier, la Police plus grande ou le Zoom, votre expérience façonne chaque plateau que nous créons.',
      points: [
        'Nous consultons le panel sur les nouveaux plateaux et les nouvelles fonctionnalités avant leur sortie, et nous agissons en fonction de ce que nous entendons.',
        'Quelques questions courtes ou une version de test de temps en temps, jamais plus que vous ne le souhaitez.',
        'Dites-nous quelle technologie d’assistance vous utilisez, et comment vous préférez que nous vous contactions.',
      ],
      action: 'Rejoindre le panel',
    },
    monthly: {
      title: 'Des nouvelles de l’équipe, chaque mois',
      text: 'Une fois par mois, nous publions dans les Annonces ce qui est sorti, ce que vous nous avez dit et ce qui arrive ensuite. Suivez la catégorie pour le recevoir par e-mail, ou abonnez-vous aux nouvelles d’OutBrick.',
      followAction: 'Suivre les Annonces',
      newsAction: 'S’abonner aux nouvelles d’OutBrick',
    },
    honest: 'La participation est volontaire et non rémunérée, et elle ne change jamais rien à votre jeu. Vous pouvez arrêter à tout moment en répondant à n’importe lequel de nos e-mails.',
  },

  banner: {
    level: { info: 'Information', warning: 'Attention', outage: 'Panne en cours' },
    more: 'En savoir plus',
    dismiss: 'Masquer cet avis',
  },

  attach: {
    label: 'Captures d’écran',
    hint: 'Jusqu’à trois images. Nous supprimons les données de localisation et d’appareil photo avant de les conserver, et seuls l’équipe et vous pouvez les voir.',
    add: 'Ajouter une capture d’écran',
    remove: 'Retirer',
    uploading: 'Envoi…',
    failed: 'Impossible de joindre cette image. Essayez avec un fichier PNG ou JPEG.',
    tooBig: 'Cette image dépasse 8 Mo.',
    tooMany: 'Vous pouvez joindre jusqu’à trois images.',
    alt: (n) => `Capture d’écran ${n}`,
    title: 'Captures d’écran',
  },

  issues: {
    metaTitle: 'OutBrick : problèmes connus et correctifs',
    metaDescription: 'Les problèmes que nous connaissons dans OutBrick sur iPhone et iPad, quoi faire en attendant qu’ils soient corrigés, et quelle mise à jour apporte le correctif.',
    eyebrow: 'Assistance OutBrick',
    title: 'Problèmes connus et correctifs',
    lede: 'Quelque chose ne marche pas ? Voici tout ce que nous savons cassé en ce moment, ce que vous pouvez faire en attendant le correctif, et quelle mise à jour l’apporte. Nous tenons cette page honnête et à jour.',
    reviewed: (date) => `Dernière vérification : ${date}`,
    openTitle: 'En cours de correction',
    resolvedTitle: 'Corrigés récemment',
    noneOpen: 'Aucun problème connu en ce moment. Si quelque chose ne marche pas pour vous, dites-le-nous.',
    status: { investigating: 'Nous enquêtons', 'fix-coming': 'Correctif en route', fixed: 'Corrigé' },
    affects: 'Qui est concerné',
    whatHappens: 'Ce qui se passe',
    workaround: 'En attendant le correctif',
    fix: 'Le correctif',
    readMore: 'En savoir plus',
    notListedTitle: 'Pas dans la liste ?',
    notListedText: 'Alors nous ne le connaissons peut-être pas encore. Un signalement avec votre appareil, votre version d’iOS, votre version d’OutBrick et le niveau nous aide à le trouver vite.',
    reportAction: 'Signaler un bug',
    contactAction: 'Nous écrire en privé',
    stayTitle: 'Soyez prévenu quand un correctif sort',
    stayText: 'Chaque version est publiée dans les Annonces dès qu’elle arrive sur l’App Store. Suivez la catégorie pour recevoir un e-mail, et laissez les mises à jour automatiques activées pour que les correctifs vous parviennent sans y penser.',
    stayAction: 'Suivre les Annonces',
  },

  fix: {
    metaTitle: 'Dépanner pas à pas : l’assistant de dépannage OutBrick',
    metaDescription: 'Choisissez ce qui ne va pas dans OutBrick et essayez une solution à la fois : progression manquante, achats, vies, son, notifications, widgets, vidéos et VoiceOver.',
    eyebrow: 'Assistance OutBrick',
    title: 'Dépanner pas à pas',
    lede: 'Choisissez ce qui ne va pas et nous vous guidons une étape à la fois. La plupart des problèmes se règlent en une minute ou deux, et sinon, une personne de l’équipe prend le relais.',
    chooseTitle: 'Qu’est-ce qui ne va pas ?',
    chooseHint: 'Choisissez ce qui s’en rapproche le plus.',
    stepOf: (step, total) => `Étape ${step} sur ${total}`,
    quickCheck: 'Vérification rapide',
    worked: 'C’est réglé',
    next: 'Ça ne marche toujours pas',
    back: 'Retour',
    another: 'Choisir un autre problème',
    fixedTitle: 'Ravis que ce soit réglé.',
    fixedText: 'Merci d’avoir suivi les étapes. Bon prochain plateau !',
    stillTitle: 'Toujours pas réglé ? Nous prenons le relais.',
    stillText: 'Écrivez-nous et une personne de l’équipe s’en occupera. Votre message indique ce que vous avez déjà essayé, pour que personne ne vous demande de le refaire.',
    contactAction: 'Contacter l’assistance',
    askAction: 'Demander à la communauté',
    bugAction: 'Signaler un bug',
    knownIssue: 'C’est un problème connu, et un correctif est en route.',
    allSteps: 'Toutes les étapes',
    readGuide: 'Lire le guide complet',
  },

  request: {
    metaTitle: 'Votre demande d’assistance OutBrick',
    metaDescription: 'Suivez votre demande d’assistance OutBrick : où elle en est, chaque réponse de l’équipe, et un moyen d’ajouter des détails.',
    eyebrow: 'Assistance OutBrick',
    title: 'Votre demande',
    lede: 'Où en est votre message, chaque réponse de l’équipe, et un endroit pour ajouter tout ce que nous devrions savoir.',
    loading: 'Ouverture de votre demande…',
    invalid: 'Ce lien n’ouvre aucune demande. Vérifiez que vous l’avez copié en entier, ou demandez un nouveau lien ci-dessous.',
    expired: 'Ce lien a expiré. Demandez-en un nouveau ci-dessous : il arrive en une minute.',
    failed: 'Impossible d’ouvrir votre demande pour le moment. Réessayez dans un instant.',
    reference: 'Référence',
    topic: 'Sujet',
    opened: 'Envoyée',
    updated: 'Dernière mise à jour',
    statusTitle: {
      open: 'Entre les mains de l’équipe',
      replied: 'Nous avons répondu',
      fix_pending: 'Un correctif est en route',
      resolved: 'Résolue',
      closed: 'Fermée',
    },
    statusText: {
      open: 'Une personne de l’équipe a votre message et vous répondra par e-mail. Vous pouvez ajouter des détails ci-dessous à tout moment.',
      replied: 'Nous avons répondu par e-mail. Si cela n’a pas réglé le problème, dites-le ci-dessous et votre demande retourne directement à l’équipe.',
      fix_pending: 'Nous avons trouvé la cause et l’avons corrigée. Nous vous écrirons dès que la mise à jour avec le correctif sera sur l’App Store.',
      resolved: 'Cette demande est résolue. Si le problème revient, écrivez ci-dessous et nous la reprendrons.',
      closed: 'Cette demande est fermée. Si vous avez encore besoin d’aide, écrivez ci-dessous et elle sera rouverte.',
    },
    stages: { received: 'Reçue', answered: 'Réponse envoyée', fixing: 'Correctif en route', solved: 'Résolue' },
    historyTitle: 'Historique',
    yourMessage: 'Votre message',
    detailsTitle: 'Les détails que vous avez donnés',
    detail: {
      level: 'Niveau',
      'purchase-item': 'Achat',
      'purchase-date': 'Acheté le',
      assistive: 'Technologie d’assistance',
      tried: 'Déjà essayé',
      guide: 'Depuis le guide',
      device: 'Appareil',
      ios: 'Version d’iOS',
      app: 'Version d’OutBrick',
    },
    event: {
      created: 'Vous avez envoyé votre message',
      reply: (staff) => `${staff}, de l’équipe, a répondu`,
      fixedIn: (version) => `Nous l’avons corrigé dans OutBrick ${version}`,
      fixedShipped: (version) => `OutBrick ${version}, avec le correctif, est arrivé sur l’App Store`,
      resolved: 'Marquée comme résolue',
      closed: 'Fermée',
      reopened: 'Rouverte',
      solvedYes: 'Vous nous avez dit que c’est résolu',
      solvedNo: 'Vous nous avez dit que ce n’est pas encore résolu',
      rated: (stars) => `Vous avez donné ${stars} ${stars > 1 ? 'étoiles' : 'étoile'} sur 5 à notre aide`,
      playerNote: 'Vous avez ajouté',
    },
    addTitle: 'Ajouter des détails',
    addHint: 'Un numéro de niveau, ce que vous avez essayé, ce qui a changé. N’indiquez ni mot de passe ni numéro de carte. Pour envoyer une capture d’écran, répondez à notre e-mail en la joignant.',
    addLabel: 'Votre message',
    addAction: 'Envoyer à l’équipe',
    addSending: 'Envoi…',
    added: 'Merci. L’équipe a bien reçu votre mise à jour.',
    addReopens: 'Envoyer ce message rouvre votre demande.',
    feedbackTitle: 'Avons-nous réglé le problème ?',
    feedbackText: 'Un toucher suffit pour nous le dire. Un « pas encore » renvoie directement votre demande à l’équipe.',
    solvedYes: 'Oui, c’est réglé',
    solvedNo: 'Pas encore',
    rateLabel: 'Comment avez-vous trouvé notre aide ?',
    lookupTitle: 'Vous avez perdu votre lien ?',
    lookupText: 'Saisissez votre référence et l’adresse e-mail depuis laquelle vous nous avez écrit, et nous vous enverrons par e-mail le lien vers votre demande.',
    refLabel: 'Référence',
    refHint: 'Elle ressemble à OB-7K2QXM et figure dans l’objet de nos e-mails.',
    emailLabel: 'Votre adresse e-mail',
    lookupAction: 'M’envoyer le lien par e-mail',
    lookupSending: 'Envoi…',
    lookupSent: 'Si cette référence et cette adresse correspondent à une demande, son lien est en route vers cette adresse. Vérifiez votre boîte de réception et vos courriers indésirables.',
    noLinkTitle: 'Suivre une demande',
    noLinkText: 'Chaque message que vous nous envoyez reçoit une référence, comme OB-7K2QXM, et un lien privé dans l’e-mail que nous vous renvoyons. Ouvrez ce lien pour voir où en est votre demande, lire chaque réponse et ajouter des détails.',
    tooMany: 'Cela fait beaucoup d’essais en peu de temps. Patientez quelques minutes, puis réessayez.',
    newRequest: 'Écrire un nouveau message',
  },

  feedback: {
    question: 'Ce guide vous a-t-il aidé ?',
    pageQuestion: 'Cette page vous a-t-elle aidé ?',
    yes: 'Oui',
    no: 'Non',
    thanksYes: 'Merci ! Nous sommes ravis qu’il vous ait aidé.',
    whyTitle: 'Désolés. Qu’est-ce qui n’a pas marché ?',
    reasons: {
      unclear: 'C’était difficile à suivre',
      missing: 'Ma question n’a pas trouvé de réponse',
      outdated: 'Cela ne correspond pas au jeu',
      'didnt-work': 'J’ai suivi les étapes, mais ça n’a pas marché',
      other: 'Autre chose',
    },
    commentLabel: 'Dites-nous en plus (facultatif)',
    commentHint: 'Nous lisons chaque réponse et nous en servons pour améliorer les guides. Aucune réponse ne vous sera envoyée d’ici : n’indiquez donc pas d’informations personnelles.',
    send: 'Envoyer',
    sending: 'Envoi…',
    thanksNo: 'Merci. Nous lisons chaque réponse et nous en servons pour corriger les guides.',
    escalate: 'Besoin d’un coup de main ? Une personne de l’équipe va vous aider.',
    contactAction: 'Contacter l’assistance',
    askAction: 'Demander à la communauté',
    failed: 'L’envoi a échoué. Veuillez réessayer.',
  },
};
