import type { SupportCopy } from '../model.ts';

export const fr: SupportCopy = {
  supportCrumb: 'Assistance',
  hub: {
    title: 'L’aide qui vous convient',
    lede: 'Réglez le problème vous-même en quelques étapes, vérifiez si nous le connaissons déjà, ou suivez un message que vous nous avez envoyé.',
    fixTitle: 'Dépanner pas à pas',
    fixText: 'Choisissez ce qui ne va pas et essayez une chose à la fois. Si rien ne marche, nous prenons le relais.',
    issuesTitle: 'Problèmes connus et correctifs',
    issuesText: 'Ce que nous savons cassé, quoi faire en attendant, et quelle mise à jour le corrige.',
    trackTitle: 'Suivre votre demande',
    trackText: 'Voyez où en est votre message, lisez chaque réponse de l’équipe et ajoutez des détails.',
  },

  issues: {
    metaTitle: 'OutBrick : problèmes connus et correctifs',
    metaDescription: 'Les problèmes que nous connaissons dans OutBrick sur iPhone et iPad, quoi faire en attendant qu’ils soient corrigés, et quelle mise à jour apporte le correctif.',
    eyebrow: 'Assistance OutBrick',
    title: 'Problèmes connus et correctifs',
    lede: 'Quelque chose ne marche pas ? Voici tout ce que nous savons cassé en ce moment, ce que vous pouvez faire en attendant le correctif, et quelle mise à jour l’apporte. Nous tenons cette page honnête et à jour.',
    reviewed: (date) => `Dernière vérification : ${date}`,
    openTitle: 'En cours de correction',
    resolvedTitle: 'Corrigés récemment',
    noneOpen: 'Aucun problème connu en ce moment. Si quelque chose ne marche pas pour vous, dites-le-nous.',
    status: { investigating: 'Nous enquêtons', 'fix-coming': 'Correctif en route', fixed: 'Corrigé' },
    affects: 'Qui est concerné',
    whatHappens: 'Ce qui se passe',
    workaround: 'En attendant le correctif',
    fix: 'Le correctif',
    readMore: 'En savoir plus',
    notListedTitle: 'Pas dans la liste ?',
    notListedText: 'Alors nous ne le connaissons peut-être pas encore. Un signalement avec votre appareil, votre version d’iOS, votre version d’OutBrick et le niveau nous aide à le trouver vite.',
    reportAction: 'Signaler un bug',
    contactAction: 'Nous écrire en privé',
    stayTitle: 'Soyez prévenu quand un correctif sort',
    stayText: 'Chaque version est publiée dans les Annonces dès qu’elle arrive sur l’App Store. Suivez la catégorie pour recevoir un e-mail, et laissez les mises à jour automatiques activées pour que les correctifs vous parviennent sans y penser.',
    stayAction: 'Suivre les Annonces',
  },

  fix: {
    metaTitle: 'Dépanner pas à pas : l’assistant de dépannage OutBrick',
    metaDescription: 'Choisissez ce qui ne va pas dans OutBrick et essayez une solution à la fois : progression manquante, achats, vies, son, notifications, widgets, vidéos et VoiceOver.',
    eyebrow: 'Assistance OutBrick',
    title: 'Dépanner pas à pas',
    lede: 'Choisissez ce qui ne va pas et nous vous guidons une étape à la fois. La plupart des problèmes se règlent en une minute ou deux, et sinon, une personne de l’équipe prend le relais.',
    chooseTitle: 'Qu’est-ce qui ne va pas ?',
    chooseHint: 'Choisissez ce qui s’en rapproche le plus.',
    stepOf: (step, total) => `Étape ${step} sur ${total}`,
    quickCheck: 'Vérification rapide',
    worked: 'C’est réglé',
    next: 'Ça ne marche toujours pas',
    back: 'Retour',
    another: 'Choisir un autre problème',
    fixedTitle: 'Ravis que ce soit réglé.',
    fixedText: 'Merci d’avoir suivi les étapes. Bon prochain plateau !',
    stillTitle: 'Toujours pas réglé ? Nous prenons le relais.',
    stillText: 'Écrivez-nous et une personne de l’équipe s’en occupera. Votre message indique ce que vous avez déjà essayé, pour que personne ne vous demande de le refaire.',
    contactAction: 'Contacter l’assistance',
    askAction: 'Demander à la communauté',
    bugAction: 'Signaler un bug',
    knownIssue: 'C’est un problème connu, et un correctif est en route.',
    allSteps: 'Toutes les étapes',
    readGuide: 'Lire le guide complet',
  },

  request: {
    metaTitle: 'Votre demande d’assistance OutBrick',
    metaDescription: 'Suivez votre demande d’assistance OutBrick : où elle en est, chaque réponse de l’équipe, et un moyen d’ajouter des détails.',
    eyebrow: 'Assistance OutBrick',
    title: 'Votre demande',
    lede: 'Où en est votre message, chaque réponse de l’équipe, et un endroit pour ajouter tout ce que nous devrions savoir.',
    loading: 'Ouverture de votre demande…',
    invalid: 'Ce lien n’ouvre aucune demande. Vérifiez que vous l’avez copié en entier, ou demandez un nouveau lien ci-dessous.',
    expired: 'Ce lien a expiré. Demandez-en un nouveau ci-dessous : il arrive en une minute.',
    failed: 'Impossible d’ouvrir votre demande pour le moment. Réessayez dans un instant.',
    reference: 'Référence',
    topic: 'Sujet',
    opened: 'Envoyée',
    updated: 'Dernière mise à jour',
    statusTitle: {
      open: 'Entre les mains de l’équipe',
      replied: 'Nous avons répondu',
      fix_pending: 'Un correctif est en route',
      resolved: 'Résolue',
      closed: 'Fermée',
    },
    statusText: {
      open: 'Une personne de l’équipe a votre message et vous répondra par e-mail. Vous pouvez ajouter des détails ci-dessous à tout moment.',
      replied: 'Nous avons répondu par e-mail. Si cela n’a pas réglé le problème, dites-le ci-dessous et votre demande retourne directement à l’équipe.',
      fix_pending: 'Nous avons trouvé la cause et l’avons corrigée. Nous vous écrirons dès que la mise à jour avec le correctif sera sur l’App Store.',
      resolved: 'Cette demande est résolue. Si le problème revient, écrivez ci-dessous et nous la reprendrons.',
      closed: 'Cette demande est fermée. Si vous avez encore besoin d’aide, écrivez ci-dessous et elle sera rouverte.',
    },
    stages: { received: 'Reçue', answered: 'Réponse envoyée', fixing: 'Correctif en route', solved: 'Résolue' },
    historyTitle: 'Historique',
    yourMessage: 'Votre message',
    detailsTitle: 'Les détails que vous avez donnés',
    detail: {
      level: 'Niveau',
      'purchase-item': 'Achat',
      'purchase-date': 'Acheté le',
      assistive: 'Technologie d’assistance',
      tried: 'Déjà essayé',
      guide: 'Depuis le guide',
      device: 'Appareil',
      ios: 'Version d’iOS',
      app: 'Version d’OutBrick',
    },
    event: {
      created: 'Vous avez envoyé votre message',
      reply: (staff) => `${staff}, de l’équipe, a répondu`,
      fixedIn: (version) => `Nous l’avons corrigé dans OutBrick ${version}`,
      fixedShipped: (version) => `OutBrick ${version}, avec le correctif, est arrivé sur l’App Store`,
      resolved: 'Marquée comme résolue',
      closed: 'Fermée',
      reopened: 'Rouverte',
      solvedYes: 'Vous nous avez dit que c’est résolu',
      solvedNo: 'Vous nous avez dit que ce n’est pas encore résolu',
      rated: (stars) => `Vous avez donné ${stars} ${stars > 1 ? 'étoiles' : 'étoile'} sur 5 à notre aide`,
      playerNote: 'Vous avez ajouté',
    },
    addTitle: 'Ajouter des détails',
    addHint: 'Un numéro de niveau, ce que vous avez essayé, ce qui a changé. N’indiquez ni mot de passe ni numéro de carte. Pour envoyer une capture d’écran, répondez à notre e-mail en la joignant.',
    addLabel: 'Votre message',
    addAction: 'Envoyer à l’équipe',
    addSending: 'Envoi…',
    added: 'Merci. L’équipe a bien reçu votre mise à jour.',
    addReopens: 'Envoyer ce message rouvre votre demande.',
    feedbackTitle: 'Avons-nous réglé le problème ?',
    feedbackText: 'Un toucher suffit pour nous le dire. Un « pas encore » renvoie directement votre demande à l’équipe.',
    solvedYes: 'Oui, c’est réglé',
    solvedNo: 'Pas encore',
    rateLabel: 'Comment avez-vous trouvé notre aide ?',
    lookupTitle: 'Vous avez perdu votre lien ?',
    lookupText: 'Saisissez votre référence et l’adresse e-mail depuis laquelle vous nous avez écrit, et nous vous enverrons par e-mail le lien vers votre demande.',
    refLabel: 'Référence',
    refHint: 'Elle ressemble à OB-7K2QXM et figure dans l’objet de nos e-mails.',
    emailLabel: 'Votre adresse e-mail',
    lookupAction: 'M’envoyer le lien par e-mail',
    lookupSending: 'Envoi…',
    lookupSent: 'Si cette référence et cette adresse correspondent à une demande, son lien est en route vers cette adresse. Vérifiez votre boîte de réception et vos courriers indésirables.',
    noLinkTitle: 'Suivre une demande',
    noLinkText: 'Chaque message que vous nous envoyez reçoit une référence, comme OB-7K2QXM, et un lien privé dans l’e-mail que nous vous renvoyons. Ouvrez ce lien pour voir où en est votre demande, lire chaque réponse et ajouter des détails.',
    tooMany: 'Cela fait beaucoup d’essais en peu de temps. Patientez quelques minutes, puis réessayez.',
    newRequest: 'Écrire un nouveau message',
  },

  feedback: {
    question: 'Ce guide vous a-t-il aidé ?',
    pageQuestion: 'Cette page vous a-t-elle aidé ?',
    yes: 'Oui',
    no: 'Non',
    thanksYes: 'Merci ! Nous sommes ravis qu’il vous ait aidé.',
    whyTitle: 'Désolés. Qu’est-ce qui n’a pas marché ?',
    reasons: {
      unclear: 'C’était difficile à suivre',
      missing: 'Ma question n’a pas trouvé de réponse',
      outdated: 'Cela ne correspond pas au jeu',
      'didnt-work': 'J’ai suivi les étapes, mais ça n’a pas marché',
      other: 'Autre chose',
    },
    commentLabel: 'Dites-nous en plus (facultatif)',
    commentHint: 'Nous lisons chaque réponse et nous en servons pour améliorer les guides. Aucune réponse ne vous sera envoyée d’ici : n’indiquez donc pas d’informations personnelles.',
    send: 'Envoyer',
    sending: 'Envoi…',
    thanksNo: 'Merci. Nous lisons chaque réponse et nous en servons pour corriger les guides.',
    escalate: 'Besoin d’un coup de main ? Une personne de l’équipe va vous aider.',
    contactAction: 'Contacter l’assistance',
    askAction: 'Demander à la communauté',
    failed: 'L’envoi a échoué. Veuillez réessayer.',
  },
};
