import type { SupportCopy } from '../model.ts';

export const ja: SupportCopy = {
  supportCrumb: 'サポート',
  hub: {
    title: 'あなたに合った方法で解決',
    lede: '数ステップで自分で直す、すでに把握している問題か確かめる、送ったメッセージの状況を確認する。いずれかを選んでください。',
    fixTitle: 'ステップごとに解決',
    fixText: '困っていることを選び、ひとつずつ試してください。どれもうまくいかなければ、そこからはチームが引き受けます。',
    issuesTitle: '既知の問題と修正',
    issuesText: '把握している不具合、それまでの対処法、そしてどのアップデートで直るかをまとめています。',
    trackTitle: 'お問い合わせの状況を確認',
    trackText: 'メッセージの対応状況を確認し、チームからの返信をすべて読み、詳細を追加できます。',
  },

  issues: {
    metaTitle: 'OutBrickの既知の不具合と修正状況：サポート',
    metaDescription: 'iPhone・iPad版OutBrickで把握している問題、修正されるまでの対処法、そして修正が含まれるアップデートをご案内します。',
    eyebrow: 'OutBrick サポート',
    title: '既知の問題と修正',
    lede: 'うまく動かないことがありますか？いま把握している不具合のすべてと、修正されるまでにできること、そして修正が含まれるアップデートをここにまとめています。このページは正直に、常に最新の状態に保っています。',
    reviewed: (date) => `最終確認：${date}`,
    openTitle: '対応中',
    resolvedTitle: '最近修正されたもの',
    noneOpen: 'いま把握している不具合はありません。うまく動かないことがあれば、ぜひお知らせください。',
    status: { investigating: '調査中', 'fix-coming': '修正を準備中', fixed: '修正済み' },
    affects: '影響を受ける方',
    whatHappens: '起きること',
    workaround: '修正されるまでは',
    fix: '修正',
    readMore: '詳しく読む',
    notListedTitle: '一覧にありませんか？',
    notListedText: 'その場合、まだ私たちが把握していない可能性があります。デバイス、iOSのバージョン、OutBrickのバージョン、レベルを添えて報告していただくと、すばやく原因を見つけられます。',
    reportAction: '不具合を報告',
    contactAction: '非公開で連絡する',
    stayTitle: '修正の配信を知る',
    stayText: 'すべてのリリースは、App Storeで公開されると同時にお知らせに投稿されます。カテゴリをウォッチするとメールが届きます。自動アップデートをオンにしておけば、修正が手間なく届きます。',
    stayAction: 'お知らせをウォッチ',
  },

  fix: {
    metaTitle: 'ステップごとに解決：OutBrick トラブル解決ガイド',
    metaDescription: 'OutBrickで困っていることを選び、ひとつずつ解決策を試せます：進行状況が消えた、購入、ライフ、サウンド、通知、ウィジェット、動画、VoiceOver。',
    eyebrow: 'OutBrick サポート',
    title: 'ステップごとに解決',
    lede: '困っていることを選ぶと、ひとつずつ順番にご案内します。ほとんどの問題は1〜2分で解決します。解決しなければ、そこからはチームの担当者が引き受けます。',
    chooseTitle: 'どうしましたか？',
    chooseHint: 'いちばん近いものを選んでください。',
    stepOf: (step, total) => `ステップ ${step}/${total}`,
    quickCheck: 'かんたんな確認',
    worked: '解決しました',
    next: 'まだ直りません',
    back: '戻る',
    another: 'ほかの問題を選ぶ',
    fixedTitle: '解決してよかったです。',
    fixedText: 'ステップを試していただき、ありがとうございました。次の盤面もお楽しみください。',
    stillTitle: 'まだ直りませんか？ここからはチームにおまかせください。',
    stillText: 'メッセージを送っていただければ、チームの担当者が調べます。試したことはメッセージに含まれるので、同じことをもう一度お願いすることはありません。',
    contactAction: 'サポートに連絡',
    askAction: 'コミュニティで質問',
    bugAction: '不具合を報告',
    knownIssue: 'これは既知の問題で、修正を準備しています。',
    allSteps: 'すべてのステップ',
    readGuide: 'ガイドをすべて読む',
  },

  request: {
    metaTitle: 'OutBrick サポートへのお問い合わせ',
    metaDescription: 'OutBrickサポートへのお問い合わせの状況を確認できます：対応状況、チームからのすべての返信、そして詳細を追加する方法。',
    eyebrow: 'OutBrick サポート',
    title: 'あなたのお問い合わせ',
    lede: 'メッセージの対応状況、チームからのすべての返信、そしてお伝えいただきたいことを書き添える場所です。',
    loading: 'お問い合わせを開いています…',
    invalid: 'このリンクではお問い合わせを開けません。リンクをすべてコピーしたか確かめるか、下から新しいリンクをリクエストしてください。',
    expired: 'このリンクは有効期限が切れています。下から新しいリンクをリクエストすると、1分ほどで届きます。',
    failed: 'いまはお問い合わせを開けませんでした。少し待ってからもう一度お試しください。',
    reference: '受付番号',
    topic: '内容',
    opened: '送信日',
    updated: '最終更新',
    statusTitle: {
      open: 'チームが対応中',
      replied: '返信しました',
      fix_pending: '修正を準備中',
      resolved: '解決済み',
      closed: '終了',
    },
    statusText: {
      open: 'チームの担当者がメッセージを受け取っており、メールで返信します。下からいつでも詳細を追加できます。',
      replied: 'メールで回答しました。解決しなかった場合は下でお知らせください。そのままチームに戻ります。',
      fix_pending: '原因を見つけて修正しました。修正を含むアップデートがApp Storeで公開されたら、すぐにメールでお知らせします。',
      resolved: 'このお問い合わせは解決済みです。問題が再び起きたら下に書いてください。もう一度対応します。',
      closed: 'このお問い合わせは終了しています。まだお手伝いが必要なら下に書いてください。再開されます。',
    },
    stages: { received: '受付', answered: '回答', fixing: '修正を準備中', solved: '解決' },
    historyTitle: '履歴',
    yourMessage: 'あなたのメッセージ',
    detailsTitle: 'お知らせいただいた詳細',
    detail: {
      level: 'レベル',
      'purchase-item': '購入',
      'purchase-date': '購入日',
      assistive: '支援技術',
      tried: '試したこと',
      guide: '参照したガイド',
      device: 'デバイス',
      ios: 'iOSのバージョン',
      app: 'OutBrickのバージョン',
    },
    event: {
      created: 'メッセージを送信しました',
      reply: (staff) => `チームの${staff}が返信しました`,
      fixedIn: (version) => `OutBrick ${version}で修正しました`,
      fixedShipped: (version) => `修正を含むOutBrick ${version}がApp Storeで公開されました`,
      resolved: '解決済みにしました',
      closed: '終了しました',
      reopened: '再開しました',
      solvedYes: '解決したとお知らせいただきました',
      solvedNo: 'まだ解決していないとお知らせいただきました',
      rated: (stars) => `サポートを5段階中${stars}と評価していただきました`,
      playerNote: 'あなたが追加した内容',
    },
    addTitle: '詳細を追加',
    addHint: 'レベル番号、試したこと、変わったことなど。パスワードやカード情報は書かないでください。スクリーンショットを送るには、私たちからのメールに添付して返信してください。',
    addLabel: 'あなたのメッセージ',
    addAction: 'チームに送信',
    addSending: '送信しています…',
    added: 'ありがとうございます。チームに届きました。',
    addReopens: '送信すると、お問い合わせが再開されます。',
    feedbackTitle: '解決しましたか？',
    feedbackText: 'タップひとつでお知らせください。「まだ」を選ぶと、そのままチームに戻ります。',
    solvedYes: 'はい、解決しました',
    solvedNo: 'まだです',
    rateLabel: 'サポートはいかがでしたか？',
    lookupTitle: 'リンクをなくしましたか？',
    lookupText: '受付番号と、メッセージを送ったメールアドレスを入力してください。お問い合わせへのリンクをメールでお送りします。',
    refLabel: '受付番号',
    refHint: 'OB-7K2QXMのような形式で、私たちからのメールの件名に書かれています。',
    emailLabel: 'メールアドレス',
    lookupAction: 'リンクをメールで受け取る',
    lookupSending: '送信しています…',
    lookupSent: '受付番号とメールアドレスがお問い合わせと一致すれば、そのアドレスにリンクを送りました。受信トレイと迷惑メールフォルダを確認してください。',
    noLinkTitle: 'お問い合わせの状況を確認',
    noLinkText: 'お送りいただいたメッセージには、OB-7K2QXMのような受付番号がつき、私たちからの返信メールに専用のリンクが記載されます。そのリンクを開くと、対応状況の確認、すべての返信の閲覧、詳細の追加ができます。',
    tooMany: '短い時間に何度も試されています。数分待ってからもう一度お試しください。',
    newRequest: '新しいメッセージを書く',
  },

  feedback: {
    question: 'このガイドは役に立ちましたか？',
    pageQuestion: 'このページは役に立ちましたか？',
    yes: 'はい',
    no: 'いいえ',
    thanksYes: 'ありがとうございます！お役に立ててうれしいです。',
    whyTitle: '申し訳ありません。どこがよくなかったですか？',
    reasons: {
      unclear: 'わかりにくかった',
      missing: '知りたいことが書かれていなかった',
      outdated: 'ゲームの内容と違っていた',
      'didnt-work': '書かれたとおりにしたが、うまくいかなかった',
      other: 'その他',
    },
    commentLabel: '詳しく教えてください（任意）',
    commentHint: 'いただいた回答はすべて読み、ガイドの改善に役立てます。ここから返信は届かないので、個人情報は書かないでください。',
    send: '送信',
    sending: '送信しています…',
    thanksNo: 'ありがとうございます。いただいた回答はすべて読み、ガイドの修正に役立てます。',
    escalate: 'まだお困りですか？チームの担当者がお手伝いします。',
    contactAction: 'サポートに連絡',
    askAction: 'コミュニティで質問',
    failed: '送信できませんでした。もう一度お試しください。',
  },
};
