import type { SupportCopy } from '../model.ts';

export const ptBR: SupportCopy = {
  supportCrumb: 'Suporte',
  hub: {
    title: 'Ajuda do seu jeito',
    lede: 'Resolva você mesmo em poucos passos, veja se já sabemos do problema ou acompanhe uma mensagem que você nos enviou.',
    fixTitle: 'Resolva passo a passo',
    fixText: 'Escolha o que está errado e tente uma coisa de cada vez. Se nada funcionar, a gente assume a partir daí.',
    issuesTitle: 'Problemas conhecidos e correções',
    issuesText: 'O que sabemos que está com defeito, o que fazer enquanto isso e qual atualização traz a correção.',
    trackTitle: 'Acompanhe sua solicitação',
    trackText: 'Veja em que pé está sua mensagem, leia todas as respostas da equipe e acrescente detalhes.',
    levelsTitle: 'Ajuda com um nível',
    levelsText: 'Empacou em um tabuleiro? Veja o que outros jogadores disseram sobre ele ou pergunte a eles.',
    involvedTitle: 'Ajude a construir o OutBrick',
    involvedText: 'Teste atualizações antes do lançamento, participe do painel de acessibilidade e receba notícias da equipe todo mês.',
    promise: 'Uma pessoa da equipe lê cada mensagem. Procuramos responder em até dois dias úteis.',
  },

  levels: {
    metaTitle: 'Ajuda com um nível do OutBrick',
    metaDescription: 'Empacou em um nível do OutBrick? Veja o que outros jogadores disseram sobre esse tabuleiro, pergunte à comunidade e confira dicas para tabuleiros difíceis.',
    eyebrow: 'Suporte do OutBrick',
    title: 'Ajuda com um nível',
    lede: 'Digite o número do nível em que você empacou para ver o que outros jogadores disseram sobre esse tabuleiro ou para perguntar a eles. O número aparece no topo do tabuleiro.',
    label: 'Número do nível',
    hint: 'De 1 a 2.000 e além.',
    action: 'Buscar ajuda',
    invalid: 'Digite o número de um nível, como 512.',
    resultsTitle: (level) => `Nível ${level} na comunidade`,
    none: (level) => `Ninguém perguntou sobre o nível ${level} ainda. Seja a primeira pessoa: os jogadores adoram um desafio.`,
    loading: 'Buscando conversas…',
    failed: 'Não conseguimos carregar a comunidade agora. Tente de novo daqui a pouco.',
    solved: 'Resolvida',
    replies: (n) => (n === 1 ? '1 resposta' : `${n} respostas`),
    askTitle: 'Pergunte sobre este nível',
    askText: 'Conte o que você já tentou e onde está empacando. Outros jogadores e a equipe respondem publicamente.',
    askAction: 'Perguntar à comunidade',
    askThreadTitle: (level) => `Nível ${level}: `,
    bugAction: 'Relatar um problema com este nível',
    tipsTitle: 'Antes de perguntar: dicas para tabuleiros difíceis',
    tips: [
      'Toda tentativa vem com uma **Dica**, um **Foguete** e um **OVNI** grátis: use a Dica primeiro, ela mostra uma jogada que ajuda.',
      'Leia os objetivos antes da primeira jogada: o tabuleiro termina assim que os objetivos são cumpridos, e as jogadas que sobram viram raios de linha.',
      '**O primeiro desfazer** de cada tabuleiro é grátis. Use-o para tentar outra troca.',
      'A partir da sexta tentativa em um tabuleiro, **uma ajudinha** dá três jogadas extras, uma vez por dia.',
      'Se nenhuma jogada for possível, o tabuleiro é embaralhado de graça, então você nunca fica realmente sem saída. Saiba mais em [Vidas, ficar sem jogadas e desfazer](help:lives-moves-and-undos).',
    ],
    spoilersTitle: 'Uma palavra sobre spoilers',
    spoilersText: 'Muitos jogadores gostam de desvendar um tabuleiro sozinhos. Ao responder, comece com uma pista e só dê a solução completa quando alguém pedir.',
  },

  involved: {
    metaTitle: 'Construa o OutBrick: testes beta e painel de acessibilidade',
    metaDescription: 'Teste as atualizações do OutBrick com o TestFlight antes do lançamento, participe do painel de acessibilidade de quem joga com VoiceOver, Controle por Voz e Controle Assistivo e receba notícias da equipe todo mês.',
    eyebrow: 'Comunidade do OutBrick',
    title: 'Ajude a construir o OutBrick',
    lede: 'O OutBrick fica melhor porque os jogadores nos contam o que funciona e o que não funciona. Veja três jeitos de participar.',
    beta: {
      title: 'Teste atualizações antes do lançamento',
      text: 'Entre no grupo beta e jogue as novas versões do OutBrick pelo app TestFlight da Apple, alguns dias antes de todo mundo.',
      points: [
        'Convidamos testadores em pequenos grupos antes de cada atualização; o convite chega por e-mail, enviado pelo TestFlight.',
        'Você precisa de um iPhone ou iPad com um iOS recente e do app gratuito TestFlight.',
        'Conte para a gente o que quebra ou parece errado, pelo próprio TestFlight ou na comunidade.',
        'Você pode sair do beta quando quiser, e seu progresso continua sendo seu.',
      ],
      action: 'Entrar no grupo beta',
    },
    panel: {
      title: 'Participe do painel de acessibilidade',
      text: 'Se você joga com VoiceOver, Controle por Voz, Controle Assistivo, teclado, Texto Maior ou Zoom, sua experiência molda cada tabuleiro que criamos.',
      points: [
        'Consultamos o painel sobre novos tabuleiros e recursos antes do lançamento e agimos com base no que ouvimos.',
        'Algumas perguntas rápidas ou uma versão de teste de vez em quando, nunca mais do que você quiser.',
        'Conte qual tecnologia assistiva você usa e como prefere que a gente entre em contato.',
      ],
      action: 'Participar do painel',
    },
    monthly: {
      title: 'Da equipe, todo mês',
      text: 'Uma vez por mês, publicamos em Novidades o que foi lançado, o que ouvimos de vocês e o que vem a seguir. Acompanhe a categoria para receber por e-mail ou assine a newsletter do OutBrick.',
      followAction: 'Acompanhar Novidades',
      newsAction: 'Assinar a newsletter do OutBrick',
    },
    honest: 'Participar é voluntário e não remunerado, e nunca muda nada no seu jogo. Saia quando quiser respondendo a qualquer um dos nossos e-mails.',
  },

  banner: {
    level: { info: 'Aviso', warning: 'Atenção', outage: 'Problema no serviço' },
    more: 'Saiba mais',
    dismiss: 'Fechar este aviso',
  },

  attach: {
    label: 'Capturas de tela',
    hint: 'Até três imagens. Removemos os dados de localização e da câmera antes de armazená-las, e só a equipe e você podem vê-las.',
    add: 'Adicionar uma captura de tela',
    remove: 'Remover',
    uploading: 'Enviando…',
    failed: 'Não foi possível anexar essa imagem. Tente um arquivo PNG ou JPEG.',
    tooBig: 'Essa imagem tem mais de 8 MB.',
    tooMany: 'Você pode anexar até três imagens.',
    alt: (n) => `Captura de tela ${n}`,
    title: 'Capturas de tela',
  },

  issues: {
    metaTitle: 'Problemas conhecidos e correções do OutBrick',
    metaDescription: 'Os problemas que conhecemos no OutBrick para iPhone e iPad, o que fazer até serem corrigidos e qual atualização traz a correção.',
    eyebrow: 'Suporte do OutBrick',
    title: 'Problemas conhecidos e correções',
    lede: 'Algo não está funcionando? Aqui está tudo o que sabemos que está com defeito agora, o que você pode fazer até a correção e qual atualização a traz. Mantemos esta página honesta e atualizada.',
    reviewed: (date) => `Última revisão em ${date}`,
    openTitle: 'Em andamento',
    resolvedTitle: 'Corrigidos recentemente',
    noneOpen: 'No momento, não sabemos de nenhum problema. Se algo não estiver funcionando para você, conte para a gente.',
    status: { investigating: 'Investigando', 'fix-coming': 'Correção a caminho', fixed: 'Corrigido' },
    affects: 'Quem é afetado',
    whatHappens: 'O que acontece',
    workaround: 'Até a correção',
    fix: 'A correção',
    readMore: 'Saiba mais',
    notListedTitle: 'Não está na lista?',
    notListedText: 'Então talvez ainda não saibamos do problema. Um relato com seu aparelho, a versão do iOS, a versão do OutBrick e o nível nos ajuda a encontrá-lo rápido.',
    reportAction: 'Relatar um bug',
    contactAction: 'Escreva para nós em particular',
    stayTitle: 'Saiba quando sai uma correção',
    stayText: 'Cada versão é publicada em Novidades assim que chega à App Store. Acompanhe a categoria para receber um e-mail e mantenha as atualizações automáticas ativadas para que as correções cheguem até você sem precisar pensar nisso.',
    stayAction: 'Acompanhar Novidades',
  },

  fix: {
    metaTitle: 'Resolva passo a passo: solução de problemas do OutBrick',
    metaDescription: 'Escolha o que está errado no OutBrick e tente uma solução de cada vez: progresso sumido, compras, vidas, som, notificações, widgets, vídeos e VoiceOver.',
    eyebrow: 'Suporte do OutBrick',
    title: 'Resolva passo a passo',
    lede: 'Escolha o que está errado e vamos guiar você uma coisa de cada vez. A maioria dos problemas se resolve em um ou dois minutos e, se o seu não se resolver, uma pessoa da equipe assume a partir daí.',
    chooseTitle: 'O que está errado?',
    chooseHint: 'Escolha a opção mais parecida.',
    stepOf: (step, total) => `Passo ${step} de ${total}`,
    quickCheck: 'Verificação rápida',
    worked: 'Isso resolveu',
    next: 'Ainda não funciona',
    back: 'Voltar',
    another: 'Escolher outro problema',
    fixedTitle: 'Que bom que deu certo.',
    fixedText: 'Obrigado por tentar os passos. Divirta-se no próximo tabuleiro.',
    stillTitle: 'Ainda não funciona? A gente assume a partir daqui.',
    stillText: 'Escreva para nós e uma pessoa da equipe vai analisar. Sua mensagem informa o que você já tentou, para ninguém pedir que você faça tudo de novo.',
    contactAction: 'Falar com o suporte',
    askAction: 'Perguntar à comunidade',
    bugAction: 'Relatar um bug',
    knownIssue: 'Este é um problema conhecido, e a correção está a caminho.',
    allSteps: 'Todos os passos',
    readGuide: 'Ler o guia completo',
  },

  request: {
    metaTitle: 'Sua solicitação ao suporte do OutBrick',
    metaDescription: 'Acompanhe sua solicitação ao suporte do OutBrick: em que pé ela está, todas as respostas da equipe e um jeito de acrescentar detalhes.',
    eyebrow: 'Suporte do OutBrick',
    title: 'Sua solicitação',
    lede: 'Em que pé está sua mensagem, todas as respostas da equipe e um espaço para acrescentar o que precisarmos saber.',
    loading: 'Abrindo sua solicitação…',
    invalid: 'Este link não abre uma solicitação. Confira se você copiou o link inteiro ou peça um novo link abaixo.',
    expired: 'Este link expirou. Peça um novo abaixo e ele chega em um minuto.',
    failed: 'Não conseguimos abrir sua solicitação agora. Tente de novo daqui a pouco.',
    reference: 'Referência',
    topic: 'Assunto',
    opened: 'Enviada',
    updated: 'Última atualização',
    statusTitle: {
      open: 'Com a equipe',
      replied: 'Respondemos',
      fix_pending: 'Uma correção está a caminho',
      resolved: 'Resolvida',
      closed: 'Encerrada',
    },
    statusText: {
      open: 'Uma pessoa da equipe está com sua mensagem e vai responder por e-mail. Você pode acrescentar detalhes abaixo a qualquer momento.',
      replied: 'Respondemos por e-mail. Se isso não resolveu, diga abaixo e a mensagem volta direto para a equipe.',
      fix_pending: 'Encontramos a causa e corrigimos o problema. Vamos enviar um e-mail assim que a atualização com a correção estiver na App Store.',
      resolved: 'Esta solicitação foi resolvida. Se o problema voltar, escreva abaixo e retomamos o caso.',
      closed: 'Esta solicitação foi encerrada. Se ainda precisar de ajuda, escreva abaixo e ela é reaberta.',
    },
    stages: { received: 'Recebida', answered: 'Respondida', fixing: 'Correção a caminho', solved: 'Resolvida' },
    historyTitle: 'Histórico',
    yourMessage: 'Sua mensagem',
    detailsTitle: 'Detalhes que você informou',
    detail: {
      level: 'Nível',
      'purchase-item': 'Compra',
      'purchase-date': 'Comprado em',
      assistive: 'Tecnologia assistiva',
      tried: 'Já tentou',
      guide: 'Do guia',
      device: 'Aparelho',
      ios: 'Versão do iOS',
      app: 'Versão do OutBrick',
    },
    event: {
      created: 'Você enviou sua mensagem',
      reply: (staff) => `${staff}, da equipe, respondeu`,
      fixedIn: (version) => `Corrigimos o problema no OutBrick ${version}`,
      fixedShipped: (version) => `O OutBrick ${version}, com a correção, chegou à App Store`,
      resolved: 'Marcada como resolvida',
      closed: 'Encerrada',
      reopened: 'Reaberta',
      solvedYes: 'Você nos disse que está resolvido',
      solvedNo: 'Você nos disse que ainda não está resolvido',
      rated: (stars) => `Você deu ${stars === 1 ? '1 estrela' : `${stars} estrelas`} de 5 para a nossa ajuda`,
      playerNote: 'Você acrescentou',
    },
    addTitle: 'Acrescentar detalhes',
    addHint: 'O número de um nível, o que você tentou, o que mudou. Não inclua senhas nem dados de cartão.',
    addLabel: 'Sua mensagem',
    addAction: 'Enviar para a equipe',
    addSending: 'Enviando…',
    added: 'Obrigado. A equipe recebeu sua atualização.',
    addReopens: 'Ao enviar, sua solicitação é reaberta.',
    feedbackTitle: 'Resolvemos?',
    feedbackText: 'Um toque já nos diz. Um “Ainda não” volta direto para a equipe.',
    solvedYes: 'Sim, resolvido',
    solvedNo: 'Ainda não',
    rateLabel: 'Como foi nossa ajuda?',
    lookupTitle: 'Perdeu o link?',
    lookupText: 'Digite sua referência e o endereço de e-mail que você usou para escrever, e enviaremos por e-mail o link da sua solicitação.',
    refLabel: 'Referência',
    refHint: 'Ela tem o formato OB-7K2QXM e aparece no assunto dos nossos e-mails.',
    emailLabel: 'Seu endereço de e-mail',
    lookupAction: 'Receber o link por e-mail',
    lookupSending: 'Enviando…',
    lookupSent: 'Se a referência e o endereço corresponderem a uma solicitação, o link dela está a caminho desse endereço. Confira sua caixa de entrada e a pasta de spam.',
    noLinkTitle: 'Acompanhe uma solicitação',
    noLinkText: 'Toda mensagem que você nos envia recebe uma referência, como OB-7K2QXM, e um link particular no e-mail que mandamos de volta. Abra esse link para ver em que pé está sua solicitação, ler todas as respostas e acrescentar detalhes.',
    tooMany: 'Foram muitas tentativas em pouco tempo. Espere alguns minutos e tente de novo.',
    newRequest: 'Escrever uma nova mensagem',
  },

  feedback: {
    question: 'Este guia foi útil?',
    pageQuestion: 'Esta página foi útil?',
    yes: 'Sim',
    no: 'Não',
    thanksYes: 'Obrigado! Que bom que ajudou.',
    whyTitle: 'Sentimos muito. O que deu errado?',
    reasons: {
      unclear: 'Foi difícil de entender',
      missing: 'Minha dúvida não foi respondida',
      outdated: 'Não corresponde ao jogo',
      'didnt-work': 'Segui as instruções, mas não funcionou',
      other: 'Outro motivo',
    },
    commentLabel: 'Conte mais (opcional)',
    commentHint: 'Lemos todas as respostas e as usamos para melhorar os guias. Não enviamos resposta por aqui, então não inclua dados pessoais.',
    send: 'Enviar',
    sending: 'Enviando…',
    thanksNo: 'Obrigado. Lemos todas as respostas e as usamos para corrigir os guias.',
    escalate: 'Ainda precisa de ajuda? Uma pessoa da equipe vai ajudar você.',
    contactAction: 'Falar com o suporte',
    askAction: 'Perguntar à comunidade',
    failed: 'Não foi possível enviar. Tente de novo.',
  },
};
